### ISSUE TITLE
Bug: Option to not subtract Ammo/PP does nothing (BR2)

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#102]
Even if unchecked, Powers and ranged weapons use ammunition.

**Comment by javierriveracastro** [comment]
Works for me. There must something more. What are you exactly doing?

**Comment by SalieriC** [comment]
I click on the weapon icon in the summary. That's basically it. Then the roll happens and a message shows that a shot was used from the weapon.

**Comment by javierriveracastro** [comment]
Ahhh... direct roll... now I see it.

**Comment by SalieriC** [comment]
Wait. I see  the problem now. It doesn't work when the roll and card show at the same time. Just showing the card and rolling from there does not...
Yeah, you were faster. :D

**Comment by javierriveracastro** [comment]
Solved
