### ISSUE TITLE
Option to use BR2 chat cards for the SWADE item cards.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#103]
SWADE features chat cards for items like weapons. These can have buttons for actions. An option to use the BR2 config (i.e. direct roll on single click) on these buttons would be great. This way users would have the option to pop their weapon out and have it ready even without the character sheet open, but could still use BR2.

**Comment by javierriveracastro** [comment]
I'm not sure about this... I'm on the edge of closing it as I feel it doesn't make a lot of sense. 

Damage is integrated in the better roll card so it makes some kind of mixed and clunk interface.

A macro can probably work better.

**Comment by javierriveracastro** [comment]
If you feel this still make sense feel free to reopen.
