### ISSUE TITLE
Apply Half Damage

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#107]
Hello Javier,

as mentioned: There are NPCs out there, that only take half damage by particular damage (like Bloats in Deadlands Noir or Skeletons). An easy way to apply that as well would be awesome.

Thank you!

**Comment by SalieriC** [comment]
There would be two problems:
1. It's a Special Ability (I have a way to check for that, but neither Javier nor you (probably) are going to like that as it requires to set up Special Abilities as Edges/Hindrances and even then my solution would check it by name which results in difficulties on languages other than english).
2. It only affects certain weapon types which would probably be a bitch to set up. 

I see an alternative - non-automated - way though: A way to set half damage in the roll. I.e. by having a `/2` modifier in the modifier section or by having a button in the chat card. I'd prefer the modifier though.

**Comment by Razortide** [comment]
Ah, this is what I meant, I was looking for a button to click, not auto applying :-)

**Comment by SalieriC** [comment]
@javierriveracastro If you can tell me where the BR2 mods are handled and placed, I could possibly do that by replicating the code that is already there. I'm just unable to find the relevant lines. XD

**Comment by javierriveracastro** [comment]
The damage partial (the HTML that shows damage and apply damage button) is here:

https://github.com/javierriveracastro/betteroll-swade/blob/version_2/betterrolls-swade2/templates/damage_partial.html

You will need to add a hook to that button in:

https://github.com/javierriveracastro/betteroll-swade/blob/3e879dfbc1596bbc72d976dcf2933d738127b65b/betterrolls-swade2/scripts/item_card.js#L196

And finally alter your well know and lovely apply_damage() function. You will probably need to pass it an extra paramether to make it know that it needs to apply half damage.

**Comment by SalieriC** [comment]
Uhm. We're clearly talking different ways to achieve the same here I guess. I thought about a `/2` damage modifier button in the common BR modifiers, and these are located in `options_form.html`.
![image](https://user-images.githubusercontent.com/1230041/108628776-00416b80-745d-11eb-9f98-329d577d4674.png)
I think that would make things a bit easier. But it's also quite cramped. Hm...

**Comment by Razortide** [comment]
Hello all, this is how it looks like in Betterrolls for DND:
![image](https://user-images.githubusercontent.com/35796457/113459485-ec066c00-9415-11eb-902d-412438627294.png)

As you can see you could roll a crit on the left side (n/a or Raise damage), and then applying full, half, double damage or heal.

This will be different for a wound based system like SW, but this is what I would like to see :-)

**Comment by SalieriC** [comment]
I would dislike that because a) as it would mean only users who want the automation can use it and b) it isn't immediately obvious what the result is.
I still think a `/2` modifier and/or a global action would be best for that.

**Comment by Razortide** [comment]
I am not sure I got your point
- "only users who want the automation can use it" -> This implies there are users that don't want the automation but still want to use it? Or did I get you wrong?
-  Arguable. As a GM I can apply half (or double) damage without giving away the mechanic behind it. Using a global action or modifier this responsibility is with the player and therefore I will need to tell him or her right away what is going on. Why do you think a /2 modifier or a "apply half damage" global action is more obvious then having a "apply half damage" button at the damage itself? I think a /2 modifier is less clear since it does not provides the context.

Take care
Marc

**Comment by SalieriC** [comment]
Ofc. As a matter of fact I myself refuse to use the automation features. I don't want automation in my games.
Also I like to be up front with my players. I don't tell them everything a creature has for obvious reasons, but I do tell them their modifiers and /2 is nothing different than +2 or -4. At least it isn't for me.

**Comment by Razortide** [comment]
Ah! Got it! You mean you may want to use the "Half Damage" but don't want to use an Auto-Apply, right?

**Comment by SalieriC** [comment]
Prertty much.

**Comment by javierriveracastro** [comment]
I'm not sure that this is something too common. It could make sense in D&D where half damage happens quite often, but putting more clutter in the UI for something like this in SW...

What about a control hidden in damage detail?

![imaxe](https://user-images.githubusercontent.com/8113700/116131621-e7f40400-a6cc-11eb-802e-e0a398d5af72.png)

![imaxe](https://user-images.githubusercontent.com/8113700/116131736-0e19a400-a6cd-11eb-984b-da70311516bc.png)

An icon for half damage would be in the circle place (the hand draw one).

**Comment by Razortide** [comment]
I like that very much. @SalieriC ?

**Comment by SalieriC** [comment]
It is uncommon until you actually need it, then you'll have to use it pretty much all the time unless you get a lucky hit. I dunno, I think it makes sense in the genral modifiers, for some campaigns at least. But nevermind, as long as there is a way to apply it... This solution should work.

**Comment by javierriveracastro** [comment]
Should be done.
