### ISSUE TITLE
GM: Re-roll with Bennies Button still showing after (GM-)Bennies hit 0.

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#108]
Hello Javier,

As a GM, if I have depleted all my Bennies (WC and GM alike) I still have one more opportunity to do a Benny roll - when the last Benny spent is a GM benny.

1. Test: Player: Since Player Bennies are bound to a character (I think) it's working fine
2. GM: WC 1 Benny, GM 1 Benny: Three Rolls Possible (it will spend the Wild Card benny, then the GM one) -> One too much
3. GM: WC 1 Benny, GM 0 Bennies: One Roll -> Works
4. GM : WC 0 Bennies, GM 1 Benny: Two Rolls -> One too much

Hope this helps!

**Comment by javierriveracastro** [comment]
It does. Thank you very much.

**Comment by javierriveracastro** [comment]
Should be solved in git. Please test it when a new version is released.
