### ISSUE TITLE
Documentation is obsolete

### ISSUE THREAD

**Issue by javierriveracastro** [javierriveracastro/betteroll-swade#109]
At least I need to remove it it I'm unable to keep it updated.

**Comment by Razortide** [comment]
I could help in updating it?

**Comment by javierriveracastro** [comment]
Yes please. I'll love it.
 You can either fork the project here (in github) and edit the README.MD. Or if you have some experience in git do it in your computer with a better editor.

**Comment by Razortide** [comment]
Haven't done that before, I will just ping you on Discord if I face issues? :D

**Comment by javierriveracastro** [comment]
Sure, as much as you want.

**Comment by javierriveracastro** [comment]
And don't forget to add yourself to the credits.

**Comment by Razortide** [comment]
Btw. You can assign it to me (or close it)

**Comment by javierriveracastro** [comment]
Assigned, you can close it when you feel it's done. Or mainly done.

**Comment by Razortide** [comment]
I have no permissions to do so unfortunately. :-)

**Comment by javierriveracastro** [comment]
You should have an email from github with an invite to collaborate.

**Comment by Razortide** [comment]
Thanks
