### ISSUE TITLE
Auto Apply Vulnerable when Wild Attacking

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#110]
Hello Javier,

I was wondering if it is possible to auto apply the Vulnerable status when a character is using the Wild Attack option?

**Comment by javierriveracastro** [comment]
This should be part of the global actions, but yes. Applying status should e part of it.

**Comment by Razortide** [comment]
Sorry, I didn't get it. What's global actions? :-)

**Comment by Razortide** [comment]
Found the other discussion. Thanks

**Comment by javierriveracastro** [comment]
Should be there in next version.
