### ISSUE TITLE
Show card and roll trait and damage did not work

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#112]
Hey, I just tried the above mentioned option and found that it is not working at least for me.

Setup: One PC actor targets an NPC actor. I use above mentioned option and click on:

a) a gun from SWADE Core (Colt Peacemaker)
b) a melee weapon (Switchblade)
c) a power (Bolt)

In all instances, the trait roll is done but not the damage roll.

**Comment by javierriveracastro** [comment]
Solved.

**Comment by Razortide** [comment]
It is still not working for me. I receive this error message:

Uncaught (in promise) TypeError: html.find is not a function
    at roll_dmg (item_card.js:657)
    at item_card.js:485
    at Array.forEach (<anonymous>)
    at roll_item (item_card.js:483)
    at async item_click_listener (item_card.js:153)
    at async HTMLDivElement.<anonymous> (item_card.js:168)
roll_dmg @ item_card.js:657
(anonym) @ item_card.js:485
roll_item @ item_card.js:483
async function (asynchron)
roll_item @ item_card.js:464
item_click_listener @ item_card.js:153
async function (asynchron)
item_click_listener @ item_card.js:151
(anonym) @ item_card.js:168
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

![image](https://user-images.githubusercontent.com/35796457/107890527-c7177180-6f19-11eb-87ec-59b34a5af038.png)

This only appears when I try to auto roll damage, card or card and roll work fine.

**Comment by javierriveracastro** [comment]
Are you using git?. Because solved means that it is solved in git, but I haven't release an update, so it should still be giving an error in released version.

**Comment by Razortide** [comment]
Got it :-) Solved means -> It is not yet released. Thanks :-)

**Comment by javierriveracastro** [comment]
I hope to make a release tomorrow.
