### ISSUE TITLE
Suggestion: "Get TN from Target" takes the Parry value also with ranged weapons

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#113]
I played around with the get TN settings as well and found that it has an impact on melee weapons but not on ranged weapons. I do see the reasoning, but the only use case I could come up with that is if I am fighting in Melee (either shooting or fighting), therefore it would make sense to apply the Parry to shooting as well. Bonus points for checking if the shooter is in melee range of the target.

But maybe I got the concept wrong and I just misunderstood.

**Comment by javierriveracastro** [comment]
Main problem is that shooting TN is near always 4 (except in melee) as distance is a modifier not a different TN. But I'll try to at least set it when both tokens are in melee

**Comment by Razortide** [comment]
I totally get this, but it's there another use case besides getting parry? I mean there are powers and edges that modify getting hit by ranged damage (also size and distance matters), but I doubt that was the intention?
Maybe just renaming it to 'get parry' and move on?

(although I would love to see all those things above getting factored in, but I am hoping that active effects will be able to cover it

**Comment by javierriveracastro** [comment]
This should be solved in next version.
