### ISSUE TITLE
Token name vs actors name

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#117]
Hey, I am not sure what to make of this, so I am just putting it out there:

![image](https://user-images.githubusercontent.com/35796457/108120611-d6292b80-70a1-11eb-8796-3167e3e57443.png)

As you can see, the actors name (at least I *think* "Mick Real" is the actors name will be used as the acting character, but when talking about damage and soaking, the token name ("Rick Mael" is used.

A use case I am thinking of is, that characters might share the same characteristics (townsfolk) while using different token names to tell them apart. Therefore I think using the token name everywhere might be good practice but on the other hand, I am not too experienced in actually using Foundry for gaming :-)

**Comment by javierriveracastro** [comment]
That's a difficult one. There are times when there is an actor and a sheet but no token and there are tokens without actor and sheets. Whenever possible I try to use token data before actor data, but this is no always possible.

That doesn't mean that this time it is not a bug. Added to the list.

**Comment by javierriveracastro** [comment]
This should be solved, at least in damage cards. Its quite possible that the problem persist in some other places, please open bugs for it.
