### ISSUE TITLE
Request: Respect the Hidden name feature of CUB

### ISSUE THREAD

**Issue by QckSilverDragon** [javierriveracastro/betteroll-swade#123]
Is is possible to hide the Token/Actor name when using Hidden Names from CUB mod.
I like using the hidden names to keep my players in the dark on what they are fighting before they see/recognize it.

**Comment by javierriveracastro** [comment]
I have no idea how CUB does this, or even if it is possible or how much work is involved.
But I'll take a look.

**Comment by SalieriC** [comment]
I would also very much like this.

**Comment by javierriveracastro** [comment]
AFAIK this is now working, probably thanks to some CUB wizardry.

If it doesn't, please confirm it with an example.

**Comment by RandyLyne** [comment]
Still doesnt seem to work. The top card is native SWADE card and the second is BetterRolls. This is from the players point of view.
![image](https://user-images.githubusercontent.com/77080531/118344416-81a41980-b4f3-11eb-9157-5faeceb6772d.png)

P.S. sorry for the delayed response.

**Comment by javierriveracastro** [comment]
Something more is going on... in my computer:

Game master:
![imaxe](https://user-images.githubusercontent.com/8113700/118354519-b5228a80-b56b-11eb-817e-b1c378217c37.png)
Player:
![imaxe](https://user-images.githubusercontent.com/8113700/118354544-ccfa0e80-b56b-11eb-9eb7-6737a056035d.png)

May there is some configuration in CUB or somewhere else.

Also, for some reason, NPC cards from core, in my setup are not shown to players.

**Comment by RandyLyne** [comment]
"Also, for some reason, NPC cards from core, in my setup are not shown to players."
There is a system setting now that lets you hide NPC rolls.
Can Better rolls honor this setting too?


Ive made sure my modules are up to date. I am running the stable version of everything.
![image](https://user-images.githubusercontent.com/77080531/118372369-ed7b9600-b576-11eb-9989-691a4e8dc5b3.png)

@javierriveracastro what do you have this setting set to?
![image](https://user-images.githubusercontent.com/77080531/118372497-83afbc00-b577-11eb-8a69-068c3fc72344.png)

**Comment by javierriveracastro** [comment]
Everybody, but it is also difficult that this is related to the current problem as it is internal to the better roll card. 

If I have to bet it is likely something about CUB configuration. How are you rolling?. From token or from an actor?

```
There is a system setting now that lets you hide NPC rolls.
Can Better rolls honor this setting too?
```

Sure, but that is a different issue.

**Comment by QckSilverDragon** [comment]
"How are you rolling?. From token or from an actor?"
I was rolling from actor.


Card 1: Swade card token
Card 2: BR2 card token
Card 3: BR2 card Actor
Card 4: Swade card Actor

![image](https://user-images.githubusercontent.com/4044050/118411216-08263b80-b659-11eb-9c81-48a518228ae4.png)

**Comment by javierriveracastro** [comment]
Now I understand it even less..

**Comment by javierriveracastro** [comment]
I've been making more test. As long as the token or the prototype token disposition is set (for some reason all the core rules actor have friendly disposition) to something not friendly it works.

So, please check if hiding it works after changing token (or prototype token) disposition.

**Comment by QckSilverDragon** [comment]
The NPC I was testing was set to hostile.
It just doesn't hide the name if I have the NPC Actor sheet open and not the [Token] sheet open.
Havent tested it with a wildcard NPC yet.

**Comment by QckSilverDragon** [comment]
Tried some more testing. It appears that skill rolls, regardless if [Token] or not, are hidden. Weapons are only hidden if using the [Token] sheet.

**Comment by javierriveracastro** [comment]
This is getting crazier for moments.

Right now, for me, rolling from the actor sidebar never hides the name, even when using system rolls. Rolling after double clicking the token does hide it.

I think that I understand how cup works. I have made some changes in how tokens are stored in the message that maybe (or mayben) not can help, but are more in line with that core does (storing the id, not the full token). I hope that it helps.

**Comment by javierriveracastro** [comment]
I will close this hoping that the last updated worked.

**Comment by SalieriC** [comment]
Seems broken now. It should look like [here](https://github.com/javierriveracastro/betteroll-swade/issues/123#issuecomment-841625421) but instead always shows the real name.

**Comment by javierriveracastro** [comment]
I will close this as CUB is not really SWADE compatible now.
