### ISSUE TITLE
Cant tell if modifier is for damage or skill.

### ISSUE THREAD

**Issue by QckSilverDragon** [javierriveracastro/betteroll-swade#124]
You cant tell in this image which modifiers are to shooting and which are to damage.
![image](https://user-images.githubusercontent.com/4044050/108302958-9da15480-716a-11eb-8090-909e81d21376.png)

In the default card you can tell.
![image](https://user-images.githubusercontent.com/4044050/108302994-aeea6100-716a-11eb-8733-998163172af6.png)

Is there something you can do about this?

**Comment by Razortide** [comment]
Hey @javierriveracastro,  also, the modifier will also be removed after the skill roll, like #106. Therefore, the damage won't be modified.
Would it be possible to factor in the range modifier for the skill roll as well? Currently it is just applying the +2 for Shotgun, but not the 0/-2/-4 for range.

**Comment by javierriveracastro** [comment]
Modifier removed should be addressed in next version. But double clicking it, so it shows in red, should prevent it to be removed by the skill roll (unfortunatly damage roll still removes in until next version).
Range modifiers are in the TODO list, so likely some day, but not soon.

And talking about this bug, it should be easy to add the icon (and proper margins) so I'd try to get this done as soon as possible.

**Comment by javierriveracastro** [comment]
This should be solved in next version.
