### ISSUE TITLE
Bug: {"windowName":"parent-1613778684683","windowType":"parent"} text glitch on basically every card

### ISSUE THREAD

**Issue by Yalnin** [javierriveracastro/betteroll-swade#129]
Hello,

with the new 2.1 update some "windowname" and "windowtype" text glitch came up that was not there before:

Tested on weapon cards, skill cards and attribute cards. Using FVTT 0.7.9 and SWADE 0.16.2

![image](https://user-images.githubusercontent.com/67702264/108575416-72f5fe00-731a-11eb-8913-78926b4759f5.png)

**Comment by javierriveracastro** [comment]
I can't reproduce it. It looks like some kind of debug information.

Which browser are you using?. Do you have some debug option enable? Any other module?

**Comment by javierriveracastro** [comment]
It seens to be shown before dice notation.

**Comment by javierriveracastro** [comment]
I think I have found something. I still don't know how you get it, but I will make a stealth update. Please update when you can and test it again. I hope that it solved it, but as I'm not seeing it I can't test it myself.

You will need to unistall and install again betterrolls to force the update (this is why I call it a stealth update, no auto-update, no announcement).

**Comment by Yalnin** [comment]
You got it nailed - stealth update solved it!
Thanks!
