### ISSUE TITLE
Hide Skill type actions on direct rolls

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#130]
There is little reason to have skill type modifiers on direct rolls as you likely set the modifier before rolling and you can't alter the current roll anyway. If you really want to save the action for later there would still be the option to show the card only before rolling but direct rolls would be much cleaner, instead of this madness:
![image](https://user-images.githubusercontent.com/1230041/108610700-13f6be80-73d8-11eb-903a-5d0ef62d62f9.png)
Edit: This should _not_ disable damage modifiers however unless the direct+damage roll option was used.

**Comment by javierriveracastro** [comment]
This card look old, it should be much better now.

But anyway yes, no need to show actions in direct rolls. I was thinking of making this par tabs. One tab for item description, one for skill description and one for actions. Start with either all collapsed or showing just actions.

**Comment by javierriveracastro** [comment]
This should be also be solver a couple of versions ago.
