### ISSUE TITLE
Hide reroll options on a crit fail (optional)

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#131]
Hide the reroll buttons whenever a critical failure comes up. This is a core rule now so should be the default behaviour. But since there is a setting rule to reroll crit fails the option to turn them on should be given.

**Comment by javierriveracastro** [comment]
Not really a priority, but yes, it should be done that way.

**Comment by javierriveracastro** [comment]
Should be done in dev.
