### ISSUE TITLE
Power Points pool management issues when spellcasting

### ISSUE THREAD

**Issue by cdj0902** [javierriveracastro/betteroll-swade#132]
Power points should be taken from whatever category or Power Points the spell is cast from. BR2 seems to only support taking power points only from the "General" Power Points pool

Example:
![image](https://user-images.githubusercontent.com/77641521/108758765-1b6db300-7511-11eb-9906-30014078059d.png)
![image](https://user-images.githubusercontent.com/77641521/108758862-36d8be00-7511-11eb-84ad-703f1b88cc9c.png)
![image](https://user-images.githubusercontent.com/77641521/108758969-5ec82180-7511-11eb-8a28-3b36fc07f660.png)

In the above example Bolt should be using Power Points from the "Magic" PP pool, but it does not.

2ndly, the chat card seems to need a way to add/subtract Power Points manually for a cast spell. Currently there is no way to increase/decrease the Power Points spend on chat cards. This would be needed when applying spell modifiers etc.

**Comment by javierriveracastro** [comment]
That should be done someday, for sure. You should be able to manually manage your "general" power points hitting the "Manual PP Management" button, but again only works for general.

**Comment by javierriveracastro** [comment]
This should be solved in next version.
