### ISSUE TITLE
Active Effects support

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#133]
Sometimes you just have penalties or bonuses during an entire situation (i.e. Phobia (Spiders) in the presence of Spiders). Now, the BR Modifiers are a decent way to track that but also not ideal. For example: You have a -1 from your phobia but get another situational -1. You've already set up the -1 in BR Modifiers to stick. Now you need to deselect the -1, select the -2 and after the roll activate the -1 again.
Active Effects support yould make this more comfortable by setting up some character specific bonus and malus AEs. 
It would also be great to have for Extras to quickly enable or disable their commanders command bonusses.
An additional feat would be that the name of the AE could also be used to explain the penalty or bonus in the BR chat card.

**Comment by Razortide** [comment]
Also, Boost/Lower Trait would be greatly enhanced

**Comment by SalieriC** [comment]
Overwriting die types? I hadn't considered this to be at all possible. If this is feasable, then that would be incredible.

**Comment by javierriveracastro** [comment]
I don't get it. AFAIK active effects support is already built-in in the system. Do you mean Active Effects fir skills? Toolkit already does and it is compatible.

**Comment by SalieriC** [comment]
Toolkit is pretty whacky and doesn't work properly. System support for AEs is lackluster. My idea isn't about directly affecting Skills, Attributes, etc. I though about directly affecting modifiers taken by BR2. For example you set up an AE with a +1 modifier for all BR2 damage rolls. Then all damage rolls get a +1 but the modifiers options in the sidebar are unaffected. This would give the user more flexibility when it comes to (semi-)permanent (situational) modifiers because you don't need to swap it constantly in the sidebar whenever you get other modifiers while the (semi-)permanent ones persist.

**Comment by javierriveracastro** [comment]
I believe that most of the things talked here can be now be achieved through global actions.

If I add an option to create and action when an actor is affected by an effect... could this solve the rest of the issues?

**Comment by javierriveracastro** [comment]
I have added an option so that an action is only available when the actor is under some Active Effect. This should solve all this use cases.
