### ISSUE TITLE
BR2 Chat Card for NPC Edges, Hindrances and Special Effects

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#134]
Could use right click for this, due to the fact that they have no icons and left click is reserved for opening the items sheet.

**Comment by javierriveracastro** [comment]
Right click is not really discoverable. But I agree that someway should be provided to open it.

**Comment by javierriveracastro** [comment]
I have take the contrary approach. Editing with right click, show card with left click. Bad design, but at least consistent with skills.
