### ISSUE TITLE
 damage bonus d10

### ISSUE THREAD

**Issue by montver** [javierriveracastro/betteroll-swade#140]
How could it be changed when it hits with a raise, for example if it deals 1d10 as a damage bonus instead of the usual d6. For games as  deadlands hell on earth is essential and I imagine for deadlands classic too.

**Comment by javierriveracastro** [comment]
Flo wants to add this to system, let's wait a bit to see if he does.

**Comment by javierriveracastro** [comment]
This should be doable now (I mean next version or current git) using global actions.
