### ISSUE TITLE
French support

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#141]
Hi there.

I read in the documentation that the skill names are automatically recognized for English and Spanish.

Here are the French translations: 

- Fighting → Combat
- Athletics → Athlétisme
- Shooting → Tir

If there any other skill you need the name of?

An alternative would be to provide input fields in settings where the GM can set the skill names by himself.

**Comment by javierriveracastro** [comment]
All those translations should be already supported. Skill names should be also recognized in French and German.

But.... there is plenty of work for a complete French translation, do you want to take care of it?

I can set up a fr.json for you to edit if you have the time.

**Comment by CyrilRonseaux** [comment]
Hi Javier. Yup I saw later that it did work perfectly in my French instance :( sorry.

Hmm, French translation, sure I can certainly help! I'm not a developer, I know how json, yaml, or xml works. I'm very newbie with git or github, I have no development tools on my computer (I think I have Atom somewhere). So I will definitely need some help before I can make it work :D 

But, yeah, sure! let's do it.

**Comment by javierriveracastro** [comment]
If everything goes well you won't need any of those... Let me try to convince JuanV to set a weblate for French.

**Comment by javierriveracastro** [comment]
Ready, see if you can work with this:
https://trans.etranslator.eu/projects/better-rolls-swade-2/en-json/

**Comment by javierriveracastro** [comment]
Change the language maintainer from me to yourself. 

I don't know if you can create an user (you don't need to), if not and you want, just ask me (or JuanV directly in discord)

**Comment by CyrilRonseaux** [comment]
Thank you. Done.
Under my real name Cyril Ronseaux.
Will take some time to finish it. (family guy :D)
