### ISSUE TITLE
Double shaken does not wound

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#144]
Hey Javier,
while testing the German language, I found that if a shaken Wild Card actor with three wounds receives another shaken, Better Rolls recognizes the event but no wound or incap will be applied:
![image](https://user-images.githubusercontent.com/35796457/110763135-d7d5b180-8251-11eb-821d-1f65488b2d0b.png)

Best regards,
Marc

**Comment by javierriveracastro** [comment]
Ummm... if the token is in combat it should be incapacitated. Incapacitation outside combat is not possible in the system right now.

What is a clear bug is that the "Show incapacitation card" button is not shown and it must. It will probably appear after a soak roll, but the logic for the showing it initially is quite weak.

**Comment by javierriveracastro** [comment]
Ok, should be solved.
