### ISSUE TITLE
Wild Attack not showing (French)

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#146]
I have a staff (baton), @str+d4 damage, linked to the "Combat" skill.
When I roll for attack, it does propose Called Shot and The Drop as global actions, but not Wild Attack.
What did I miss?

![image](https://user-images.githubusercontent.com/38113746/110941920-53f6f480-8339-11eb-9d79-e243bf12066c.png)
Clicking on Baton from the Inventory with a Parry 10 target selected: 
![image](https://user-images.githubusercontent.com/38113746/110941993-725cf000-8339-11eb-9d3d-0c1d3b45bdb4.png)
Weapon card displayed in chat:
![image](https://user-images.githubusercontent.com/38113746/110942063-8bfe3780-8339-11eb-9696-78bd7684836b.png)
Parry is correctly picked, but Wild Attack wasn't proposed:
![image](https://user-images.githubusercontent.com/38113746/110942127-a6d0ac00-8339-11eb-80cf-04b3a168d2c1.png)

**Comment by javierriveracastro** [comment]
Wild attack (and global actions) uses the json file that you are translating, so as soon as it is merged it should (I hope) start working. Hardy and some of the new automation rely also on it.

**Comment by javierriveracastro** [comment]
Solved in next version.
