### ISSUE TITLE
Missing translation entries in manual PP management

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#147]
In this screen:
![image](https://user-images.githubusercontent.com/38113746/111038078-68191f80-8427-11eb-8c1b-5422012d2328.png)

I can't find the "Power Point Management" (title), the "Amount of Power Points" (input label) and the "Soul Drain" (button) in json for translation.

Could you have a look at it? thank you.

**Comment by javierriveracastro** [comment]
Strings added.

**Comment by CyrilRonseaux** [comment]
Hi @javierriveracastro.

I don't find the new translations you added in weblate.
In game with the last module version, I see: 
![image](https://user-images.githubusercontent.com/38113746/111785158-8914c100-88bc-11eb-8fe7-9032c6d0cefd.png)

It's pretty good. 
Only Soul Drain and Amounts of Power Points are invalid.

Also, the "Depenser PP par défaut" is not the right translation. it's the translation for "Subtract Power points by default" (key=BRSW.PPManagement).

**Comment by javierriveracastro** [comment]
I have asked JuanV to pull last changes, new strings should be available in weblate in a couple of indeterminate time units.

**Comment by javierriveracastro** [comment]
Wow, looks like there where seconds... The title thing seens to be an error:

https://trans.etranslator.eu/translate/better-rolls-swade-2/en-json/fr/?offset=1&q=BRSW.PPManagement&sort_by=-priority%2Cposition&checksum=

I can't correct it.
