### ISSUE TITLE
Rolling damage vs multiple targets

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#148]
When casting a power (but I think it would work the same with Sweep) is it possible to roll damage for each selected target?

Example:
![image](https://user-images.githubusercontent.com/38113746/111038351-b7ac1b00-8428-11eb-9194-2672fed79f80.png)

The grey guy (selected) is casting Burst with two targets active (as a player I used shift+double-rightclick to multi-target them). I then click the "damage" button. Only kayla (the yellow girl) rolls and takes damage. The white bearded man doesn't.

I have a workaround, I can remove Kayla from selection, and hit the damage button again.
![image](https://user-images.githubusercontent.com/38113746/111038423-1376a400-8429-11eb-8af9-c1f2432a9225.png)

Yet it would be nice if I could roll them all at once. 👍

**Comment by javierriveracastro** [comment]
That makes a lot of sense...

**Comment by javierriveracastro** [comment]
There is a problem, if there are post-damage macros... ¿should they run once per target or just once?

**Comment by Razortide** [comment]
I think damage is handled per target right?
One thing that came to mind was also to be able to drag and drop the damage on a target (like it is possible with weapons to target them).

**Comment by javierriveracastro** [comment]
Jvir did some work on drag on drop damage, but it looks like he dropped it. I can ask him for it. But this issue is now done. Macros are run multiple times and dice son nice is confusing, but as it is optional (you need to target two tokens) I believe it is good.
