### ISSUE TITLE
[Suggestion] Change of the Apply Damage icon?

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#152]
I find it confusing that the Apply Damage icon looks like the Raise icon.
Could go with a blood drop or so?
![image](https://user-images.githubusercontent.com/38113746/111469836-7321c780-8727-11eb-8820-6224a5201318.png)

**Comment by javierriveracastro** [comment]
It is a font awesome icon. You can check here the ones that are available in foundry:

https://fontawesome.com/icons?d=gallery&p=2&m=free

if you can find one more clear I'll love to add it. The other option is using a svg file, but that could be more complex (I need to check to code to be sure).

**Comment by Razortide** [comment]
Bahai, Heartbeat, Skull?

**Comment by CyrilRonseaux** [comment]
I was thinking "tint"
![image](https://user-images.githubusercontent.com/38113746/111515145-bd6c6e00-8752-11eb-8ae3-8f15150b73b4.png)

But I like bahai the best. Heartbeat is good too. Skull sounds a bit final :D

**Comment by SalieriC** [comment]
amazon-pay as in "you'll pay for that!" XD
I think tint is the best option here as it would be consistent with the damage result icons. Bahai, Heartbeat and Skull do not strike my fancy.

**Comment by CyrilRonseaux** [comment]
I just realized the tint icon is already used for actual wounds.
![image](https://user-images.githubusercontent.com/38113746/111779305-44862700-88b6-11eb-9c02-869868fc1f4a.png)

Maybe some some generic icon, like angle-double-down
![image](https://user-images.githubusercontent.com/38113746/111779473-78f9e300-88b6-11eb-9448-8de42b86bc86.png)

or sign-in-alt
![image](https://user-images.githubusercontent.com/38113746/111779571-9333c100-88b6-11eb-95cd-0ea1d8004891.png)

**Comment by SalieriC** [comment]
That's what I was saying... I honestly think a single checkmark would be the best option here, as it signalises "apply" the most.

**Comment by javierriveracastro** [comment]
This has not been exactly helpful... :). Now either a roll a dice or make a setting for the apply damage icon XDDDD

Seriously, I tend to agree with SalieriC that a checkmark is the best known "apply" icon, but it usually used with something else. Maybe both the tint and a check is more clear.

**Comment by CyrilRonseaux** [comment]
Single check mark ok for me **as long as** it's an icon which doesn't not mean "success" or "raise" already (or "shaken" or "wound"). Something which is dedicated to "do it" and has no other meaning in the module.

**Comment by javierriveracastro** [comment]
That's my try:

![imaxe](https://user-images.githubusercontent.com/8113700/111868806-5cc07980-897c-11eb-822d-a40179b183b5.png)

Feel free to reopen the bug if you have a better idea.

**Comment by SalieriC** [comment]
Can I persuade you to allign the results? This picture is making me uncomfortable. XD

**Comment by javierriveracastro** [comment]
Sure, but please open a different bug.

You know I hate CSS bugs, I'll find something nasty on Spices in retaliation.

**Comment by CyrilRonseaux** [comment]
This solution is clear, I like it! thank you very much!
