### ISSUE TITLE
[Improvement] Run Better Roll 2 cards from the Quick Access panel

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#153]
In the Quick Access panel of my character sheet, if I click a weapon name, it unfolds standard options, noone of which will go through Better Roll 2 cards.
![image](https://user-images.githubusercontent.com/38113746/111470055-b67c3600-8727-11eb-9ba8-81a9aa305b06.png)

I wish I had a config option to set the weapon name to "display better roll card" (or display and roll).
I know you can click on the thumbnail of the weapon, but it's so small and the weapon name is so large and tempting :D

Also, to be noted, clicking the "chat bubble" at the right seems to do nothing.

(using Better Roll 2, in French)

**Comment by javierriveracastro** [comment]
Yes. I agree. The problem is that I don't know if most people will like to lost that system functionality. Also I'm not sure that adding more config options is a good option.

I'd like to hear more people opinion about this issue.

**Comment by Razortide** [comment]
I would like to have that option :)

**Comment by SalieriC** [comment]
I don't mind options but I'd just use the same behaviour as for other rules using the hotkeys setup.

**Comment by CyrilRonseaux** [comment]
Yeah, I agree, let's just make it that icon and name and quick access and whatelse all go through the same Better Roll option. If you want the default behaviour you can use Alt+click or ctrl+click settings.

**Comment by javierriveracastro** [comment]
Done.
