### ISSUE TITLE
[Improvement] Clicking weapon damage rolls Better Roll Damage card

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#154]
In the character inventory, if I click a weapon name or picture, I get the BR2 card as configured and as expected.
However, when I click the damage, I get the standard popin. 
![image](https://user-images.githubusercontent.com/38113746/111470813-88e3bc80-8728-11eb-9c42-4cbb8b01c380.png)

I wish I could have a setting to link the weapon damage label to roll BR2 weapon card and roll damage (using target's toughness if a target is selected).

**Comment by javierriveracastro** [comment]
That could be done. Directly show damage or show the full card?

**Comment by CyrilRonseaux** [comment]
I would say that if I click the "@Str+d6" I mean to roll damage without rolling to hit. (maybe I rolled to hit with my fighting skill by "mistake", or I'm hitting an immobile wall :D , I don't know). At least sounds more "logical" to say it rolls damage.

**Comment by SalieriC** [comment]
Sometimes a damage roll without attacking is needed (i.e. when using a weapon from a vehicle) so a +1 for damage only BR2 card from me.

**Comment by javierriveracastro** [comment]
Ok, let's call this a bug.

**Comment by javierriveracastro** [comment]
Done.
