### ISSUE TITLE
[minor] Some options are not translated

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#157]
In module options, under global actions, the actions are listed in English.
![image](https://user-images.githubusercontent.com/38113746/111816158-cc7f2780-88dc-11eb-8c66-ee142804220c.png)

When they appear in the roll cards they are correctly translated.

**Comment by CyrilRonseaux** [comment]
I also found a Shaken not translated on the Incapacity card
![image](https://user-images.githubusercontent.com/38113746/111846487-38768580-8907-11eb-81c7-7aa9151f7a03.png)

**Comment by javierriveracastro** [comment]
Shaken should be easy to fix, have to look for global action names.

**Comment by javierriveracastro** [comment]
Should be solved.
