### ISSUE TITLE
[minor] Missing translation string - Damage dice theme

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#158]
The damage dice theme option can't be translated, I can't find it in the translation weblate.

![image](https://user-images.githubusercontent.com/38113746/111816683-67780180-88dd-11eb-8e15-8278ed969ef6.png)

**Comment by CyrilRonseaux** [comment]
The module title might also be untranslatable: 
![image](https://user-images.githubusercontent.com/38113746/111817011-c3428a80-88dd-11eb-82ad-f0e600214f9a.png)

I saw "Better Rolls for Savage Worlds" as translation entry, but I couldn't find the "Better Rolls 2 for Savage Worlds".

**Comment by CyrilRonseaux** [comment]
Some other missing entries, in the "add modifier" box:
![image](https://user-images.githubusercontent.com/38113746/111817332-2e8c5c80-88de-11eb-828e-533d74fd7928.png)

I also could not find the strings for spending PP when casting a power:
![image](https://user-images.githubusercontent.com/38113746/111817520-61365500-88de-11eb-8151-0a9aa8572bf7.png)

Not enough PP isn't translated either.
Reaching back to one's maximum is translated however.
![image](https://user-images.githubusercontent.com/38113746/111836992-81bed900-88f7-11eb-9dc6-6ad4488a3be5.png)

**Comment by javierriveracastro** [comment]
Extension name is untranslatable, I'll look into the rest.

**Comment by javierriveracastro** [comment]
OK and Cancel buttons in the "Add modifier" form are added by Foundry. They will probably be translated with a base Foundry language pack (the same that this 7s ago).

**Comment by javierriveracastro** [comment]
All the other should have translations strings by now.

**Comment by CyrilRonseaux** [comment]
Translations ready in Weblate!
thank you very much, again and again :D
