### ISSUE TITLE
[minor] Attribute names not translated in attribute card

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#159]
When rolling an attribute:
![image](https://user-images.githubusercontent.com/38113746/111817680-96db3e00-88de-11eb-83e1-91c130c191a6.png)

The attribute name (in red) in the card title is not translated.
Also attribute names in the footer are not translated.

**Comment by javierriveracastro** [comment]
That could also bee dificult.

**Comment by javierriveracastro** [comment]
This should be solved in next version. Note that you need the translation module for your language unless it is german (that is keep in system by Florad himself).
