### ISSUE TITLE
Allow free rerolls on Damage

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#160]
I know no core Edge or abilities does it, but one of my add-ons  (Fighters & Warlords) give Edges which grant free rerolls for damage rolls in some situations. And there might be similar edges or abilities or powers in other settings.

Could we add a "free reroll" button to the damage card? (weapons and powers)
![image](https://user-images.githubusercontent.com/38113746/111837226-d82c1780-88f7-11eb-9674-d3b6be1d0884.png)

**Comment by SalieriC** [comment]
I'd say that's a good catch. I can also think of at least one power that enables one to do so.

**Comment by CyrilRonseaux** [comment]
I also think of Common Bond which let's you give one Benny to another player. Of course you can spend your Benny, but the GM must grant it to the other player, and that player must then spend it. With a free reroll a bit everywhere, your ally can spend a benny and you just "free reroll", saving a few clicks for the gm :D

**Comment by SalieriC** [comment]
You are absolutely right on that although players are in fact able to do that on their end. They do have the power to increase their benny count. ^^

**Comment by javierriveracastro** [comment]
Well, you can just click again on the dice. It will be the same as a free reroll.

Adding just another icon will just add clutter, IMHO. But the positive thins is that it will no work at all...

**Comment by SalieriC** [comment]
That's actually true. And the much better option in my opinion.

**Comment by javierriveracastro** [comment]
I will close it a won't fix.
