### ISSUE TITLE
Translation key displayed instead of label

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#161]
In French, the title of the Injury card shows the translation key instead of label:
![image](https://user-images.githubusercontent.com/38113746/111846577-6bb91480-8907-11eb-8a74-967537cce70f.png)

Same in English
![image](https://user-images.githubusercontent.com/38113746/111846661-91461e00-8907-11eb-9b01-b07d1416553f.png)

**Comment by javierriveracastro** [comment]
This should be solved.
