### ISSUE TITLE
Bug: No click button on skill cards on the official character sheet (GER)

### ISSUE THREAD

**Issue by Yalnin** [javierriveracastro/betteroll-swade#163]
Hi,

I am using 0.7.9 FVTT and the actual patch of BR2 2.23, and in German language.

Using the official SWADE actor sheet, leftklicking on the skill name now shows a chat card without options section and klick button:

![image](https://user-images.githubusercontent.com/67702264/112315785-bf7e8180-8caa-11eb-9a16-265a630e9e40.png)

Switching to the community actor sheet leftklicking the skill shows a chat card with klick button:

![image](https://user-images.githubusercontent.com/67702264/112315921-e76de500-8caa-11eb-827d-c4423a03ac01.png)

NPC sheet (which is only available in community version) works also fine.

**Comment by javierriveracastro** [comment]
Oh, I'll try to make a fast fix this afternoon. I mean before my ETU game at 16:30. That's motivation...

**Comment by Razortide** [comment]
Is this related to German? Umlauts maybe?

**Comment by Yalnin** [comment]
Not sure. Look at my example, "Fahren" does not use Umlauts. Switched to English - same behavior. It only happens with skills, and only on the official char sheet. Attributes and weapons show fine.

**Comment by javierriveracastro** [comment]
This should be addressed by today's update, please check it. And no, it was just a regression joined with sloppy testing. It happened in all languages.
