### ISSUE TITLE
BR2: Global Action for disabling/adding Wild Die

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#164]
Sprawlrunners has the option to get a Skill from Cyberware which does not roll a Wild Die. Also one might want to quickly roll a Group Roll for Extras so removing and adding a Wild Die on demand seems to be a sensible option for Global Actions.

**Comment by javierriveracastro** [comment]
That's a great idea. Expanding on it why not let it also change the Wild Die?

**Comment by SalieriC** [comment]
That's already supported by the System. But if you think it's a good idea and can find a simple way to do it, then go ahead.

**Comment by javierriveracastro** [comment]
Not as an action.

**Comment by javierriveracastro** [comment]
This should be working with a global actions now.
