### ISSUE TITLE
Add +2 to rolls when Elan/No Mercy is found on character

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#166]
When rerolling, BR2 should add +2 to the roll if the character has the Elan Edge and +2 damage if damage is rerolled and the character has No Mercy.
Should be easy with a search for owned items of type edge by name and can be localised as well I guess.

**Comment by javierriveracastro** [comment]
Sure, if it could be done with global actions the best.

**Comment by SalieriC** [comment]
I was thinking to have it backed into the reroll itself. As long as it doesn't require the click of another button it's fine I guess.

**Comment by CyrilRonseaux** [comment]
Careful with the translations. Please don't look for "Edge with name Elan".

Maybe, it should be treated the way Level Headed is treated, with a checkbox on the character sheet.
(The Edge Active Effects would check that box automatically)

Or at least have a setting where I can pick the Edge name. Also note that some custom settings could (in theory) have the edge renamed or offer the functionality as part of another edge (yet, I know no setting that does such a thing).

As a minor side note, my SWAG Add-On Fighters & Warlords, improved No Mercy to have it applied to any damage reroll, not just reroll from Bennies. But I don't see a way to implement that, cause you could use the reroll on the card to damage a second target, or because the GM was nice with you, or ... Some things just can't be fully automated :D  I can still add a +2 modifier to the roll before hitting "reroll". The modifier would apply to both the old and the new roll.

(and continue the good work! I love this module)

**Comment by SalieriC** [comment]
I see no problem to do it similar to hardy: https://github.com/javierriveracastro/betteroll-swade/blob/a49a4fea7265bde1ffa4e357830d6e4f1840193f/betterrolls-swade2/lang/en.json#L111
I'm not aware of any cases where it is replaced or renamed. It could however be done by creating a setting in which you enter the name(s) seperated by `,` or `;` or `|` or whatever seperator and then using `.split(|)`. But there are already quite a few options so I'd go for the way hardy handles it until we actually find a case where other settings change it.

**Comment by javierriveracastro** [comment]
This should be done.It is working in English and Spanish, other languages should work as soon as they are translated.

**Comment by CyrilRonseaux** [comment]
French translation is now available in Weblate.

**Comment by SalieriC** [comment]
Doesn't seem to be the case in 2.30 or am I doing something wrong?
![image](https://user-images.githubusercontent.com/1230041/120065874-e32bc280-c073-11eb-93a8-df021a23b9c2.png)

Edit: I see on rolls for weapons it is working, just not on skill rolls unless I'm missing something.

**Comment by javierriveracastro** [comment]
Yes, skill doesn't support actions, global or otherwise.

Making skill support actions will be nice, but probably a lot of work.

And a different, much bigger issue. Closing it again.

**Comment by CyrilRonseaux** [comment]
What do you mean? Elan works in BR2 but just for... Attribute rolls? Weapons attacks rolls?

**Comment by javierriveracastro** [comment]
Item rolls. Actions is SWADE are only supported on items. Skills or atributtes doesn't have actions.

I should probably add actions to skills and attributtes rolls, but this is a big change that will add lots of issues. Let's get the items working as good as possible before adding new features that will inevitable came with more issues.

**Comment by SalieriC** [comment]
I don't know if Global Actions are really the way to go here. I'd include it in the code directly by searching for the edge and applying the bonus if found. The way it currently works is inconsistent and thus confusing. Don't get me wrong, I appreciate the work. It's just not a good call doing it as a global action imo.
I could take a look at it doing it in the code directly if you wish. It's something I did a lot on SWIM. BR2 is somewhat different but maybe I can work something out.

**Comment by javierriveracastro** [comment]
Doing it directly in code has a couple of problems:

- It just doesn't scale. You can't test for each possible edge in each roll..
- It's not easy to enable/disable it. You will need to add one configuration setting for each edge, now global actions config are just checks derived from the global actions.
- It is not configurable. You can't add your howbrew edged to the code.
- You get a much, much harder to mantain code, and you need to know how every dam edge hard coded work to make sense of it.

And having some edge working one way and other the other way will just be crazy from a maintainability point of view.

To make it short, hardcoding edges is the Dark Side, it's faster, it's easier, but you will be serving it in the long haul.

**Comment by javierriveracastro** [comment]
> The way it currently works is inconsistent and thus confusing.

 But this is true, the answer is making global actions work in skills and attributes, making it consistent.

**Comment by CyrilRonseaux** [comment]
Somehow I wish there would be more hidden stats in core SWADE. Like "penalty to ranged attacks against you", "bonus when rerolling Trait", "gangup reduction", "resistance to powers", "resistance to smarts tests", ...
it still has issues (there will always be edges in settings the don't fit in those stats, e.g. in my Fighters & Warlords I made No Mercy work on all damage rerolls not just rerolls from bennies) but it could allow for quite some automations.
