### ISSUE TITLE
Error message when editing TN

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#167]
Say I roll a skill, the default TN is 4, and I want to change that TN, I click the "edit TN" button, input my new TN, and save.
Yet, I do get an error message.

![image](https://user-images.githubusercontent.com/38113746/113330063-a024cb80-931e-11eb-9667-d79ec463a3d1.png)

BR2 SW version 2.24
Foundry 0.7.9
French translations installed (Foundry, SWADE and BR2). I haven't tested in English.

Note that this also happens with the Fighting skill, and with the "edit all TN" button just above the "edit that TN".

**Comment by javierriveracastro** [comment]
That's the point in the translations. Try to remove it editing the fr.json file. I believe it is a foundry bug, not a Better Rolls one.

If it works, please change the translation if weblate for something sensible. I can just remove the point, but I don't know if it will make sense in French.

**Comment by CyrilRonseaux** [comment]
The point is for when you shortens the word. You would write "coop." if you mean "cooperative" for exemple. TN is for Target Number which is has been translated in the official core book as Difficulty, and so TN would become "Diff."

But if I translate "TN" into full word (Difficulty), there are other places where it could be too long.
I'll have to check a bit further. 

(it's insane that a special character in the **label** of an input field does crashes saving that input field, very weird, we are not changing the ID or html name)

**Comment by CyrilRonseaux** [comment]
Fixed in Weblate.
