### ISSUE TITLE
Shooting should use cover modifier from shields

### ISSUE THREAD

**Issue by mountogdengc** [javierriveracastro/betteroll-swade#168]
I don't see what attribute the cover modifier is on this page https://gitlab.com/peginc/swade/-/wikis/active-effects, but if possible, it should be calculated into shooting rolls (unless in melee, when/if you get that added)

**Comment by javierriveracastro** [comment]
That should be optional, as some settings can ignore shield cover, but yes, added to the list.

**Comment by javierriveracastro** [comment]
After some thoughs, the current cover modifiers can be used or this. I will close it as won't fix. If you believe that I should not, feel free to add some comment here.
