### ISSUE TITLE
World global actions error "invalid JSON"

### ISSUE THREAD

**Issue by Yalnin** [javierriveracastro/betteroll-swade#170]
Hi Javier,

using FVTT 0.7.9 and SWADE 0.17.2, I get this error message when typing/traying to save anything in the world global actions:

![image](https://user-images.githubusercontent.com/67702264/114060098-50ea1800-9895-11eb-8701-eabd23a071d4.png)

Did not find info about what syntax is expected in the text field, so maybe it is my mistake. The error occurs in German and English language settings alike.

**Comment by javierriveracastro** [comment]
There is stub with some documentation [link](https://github.com/javierriveracastro/betteroll-swade/blob/version_2/GLOBAL_ACTIONS.md).

As it is said it expects a json item. Closing it as it is not really a bug, unless the bug is about lacking documentation.

**Comment by javierriveracastro** [comment]
Anyway, tell me what you are trying to achieve and I'll try to give you a valid json.

**Comment by Yalnin** [comment]
Thanks, I had not seen the documentation, it helped a lot. I was actually trying to reproduce "Wild Attack" since the official one does not work with my German skillset yet, and I was able to make it work like this:

`{"id":"Wild Attack","name":"Wild Attack","button_name":"Wild Attack","skillMod":"+2","dmgMod":"+2","dmgOverride":"","selector_type":"skill","selector_value":"kämpfen"}`

Very cool and powerful tool! Beyond that, I could imagine two enhancements, if possible:
- Some optional field(s) to trigger additional (or less?) ammo consumption, beyond of that triggered by the FR of the weapon (example: this would enable to create global effects like "double shot" or "3-burst-shot")
- Some optional field(s) to set one or more status to the actor/npc that selects this global effect (example: would allow a global effect like "wild attack" to activate the "distracted" status to the attacker who used it, making it complete.

**Comment by javierriveracastro** [comment]
Default wild attack It should work in german, AFAIK. If it doesn't it is a bug.

And it can trigger status on the rollin token, just add:

```self_add_status: "Vulnerable"```
