### ISSUE TITLE
Damage (@str+d8) appear twice in damage cards

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#172]
![image](https://user-images.githubusercontent.com/38113746/114269134-5cf4e780-9a05-11eb-88dc-32860203d464.png)

I think the first line is the +d8 and the second line is the str attribute but 
- both have the same label
- the second does not have the dice type background
- the second does not list each rolled dice (e.g. in the screenshot below, str is d10, it shows 18 directly)
![image](https://user-images.githubusercontent.com/38113746/114269198-c7a62300-9a05-11eb-9911-56d09d9430dc.png)

(note : despite the weapon name and note, the game is set in English)

**Comment by javierriveracastro** [comment]
Sorry I missed this issue.

Can you show me the character sheet? It looks like it is unable to read its Strenght value.

**Comment by CyrilRonseaux** [comment]
Hi @javierriveracastro,
this is the Character Sheet:
![image](https://user-images.githubusercontent.com/38113746/118690467-60e80680-b808-11eb-9cc8-54938fb77bab.png)

I used @str (lowercase) for the strength part. I'm playing in French, so the attribute is actually "Force" (and is d10).
![image](https://user-images.githubusercontent.com/38113746/118690666-91c83b80-b808-11eb-9a30-f996258004b5.png)

The roll is correct. The first line is a d4 (which ended up rolling a 3). The second line is an exploding d10 (10 then 8).
It's really only a matter of the label.
I would expect the first line to say "d4x" and the second line to say "@str" or something like that.
The fact that both says "str+d4x" is confusing. that's all. no big deal.
It looks like 2.27 did already fix the missing dice background and listing each individual die.

Here is another example, with Str d10 and a @str+d8x weapon; (in BR2SW version 2.27)
![image](https://user-images.githubusercontent.com/38113746/118691094-03a08500-b809-11eb-8ebc-2a244764c946.png)

And here, a Str d6 with a str+d4 claw:
![image](https://user-images.githubusercontent.com/38113746/118691306-3a769b00-b809-11eb-821a-6acf57ac440a.png)

And here a 2d6 bow (no str):
![image](https://user-images.githubusercontent.com/38113746/118691509-70b41a80-b809-11eb-8766-eaa932891d5b.png)

**Comment by javierriveracastro** [comment]
Ah ok, I agree that the label is confusing, I'll give it a think, and if I see a simple solution I'll implement it. If it is more complex I'd probably move it down the issue list.

**Comment by javierriveracastro** [comment]
Is this clearer?

![imaxe](https://user-images.githubusercontent.com/8113700/123306238-544e8080-d521-11eb-81b6-65d7228253e6.png)

![imaxe](https://user-images.githubusercontent.com/8113700/123306286-63353300-d521-11eb-9781-e2e34b75a0e6.png)

**Comment by javierriveracastro** [comment]
With proper spacing, I mean.

**Comment by CyrilRonseaux** [comment]
Good for me !

I had in mind that "@str+d8" would give labels "@str" (or "Strength") and "+d8".

But, what you propose is clear, even in situation where str die is the same as damage die, you would see: "d6" and "d6" as labels, but that's ok, since both could be swapped around. 

What I wanted to avoid is a label saying "@str+d8" making your think that str AND d8 got rolls when it only rolled str OR d8.
