### ISSUE TITLE
Conflicts with the community sheet

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#173]
- [ ] 1) BR2 overwrites the left click behaviour of unfolding an item in the Quick Access. This is intentional but removes somewhat important core features. Suggested solution: Unfold by right click and/or a module setting to disable this behaviour.

- [x] 2) Clicking on the icon on the skill in the PC sheet sends the item to the chat but rolls are not possible. Suggested Solution: Same behaviour as for clicking the text (respecting the user settings).

- [x] 3) **Breaking:** Clicking an Edge/Hindrance/Special Ability creates a chat card (without description) instead of opening the description on the right side of the PC sheet. This is incredibly invasive and breaks the sheet. I won't suggest but be so impertinent to demand a solution here: Bring back the *original* behaviour on this and use the eye symbol for the chat card here (which currently doesn't show the description as well.

**Comment by javierriveracastro** [comment]
Point 1:) Won't fix. Mixing default behaviour and better rolls confuses the hell out of my players, and you can always revert to the default behaviour using the modifier key (even make it default for non key click).

Point 2: Solved.

Point 3: Solved, it now behaves like official sheet, clicking in the name shows the description, click on eye to send it to chat (without descripcion that makes no sense, so it needs an improvement,  but not with bug priority).

**Comment by SalieriC** [comment]
1) Sorry, meant unfold by right click as discussed on Discord earlier.

**Comment by javierriveracastro** [comment]
Oh yes, I forgot that. I'm ok with it.

**Comment by SalieriC** [comment]
I just realised that right click conflicts with the open feature, which is expecially important for constistency in NPC sheets. :-S
Hm, I don't see any other way of still having the unfold then... I still think it is an important feature though, especially when you are like me and put links in the items notes, which then are clickable from the unfolded menu...

**Comment by javierriveracastro** [comment]
You can still use whatever you select in the config menu as syste behaviour (i.e. CTRL+click, ALT+click, etc...)

**Comment by SalieriC** [comment]
It must suffice I guess.

**Comment by javierriveracastro** [comment]
I'm open to other ideas, maybe an icon to expand or something. But it should confuse my players...

Or someway to get the description back in cards.

**Comment by SalieriC** [comment]
The idea is to have the basic info there... A button could work. I guess, this might be something we can tackle on Spices & Flavours when we create our own sheet better than we can here(?).

**Comment by SalieriC** [comment]
Closing this now in favour of #220. I have reconsidered this and think it works great as it is right now although one of my players yesterday was confused by that behaviour, most players are fine with it.
