### ISSUE TITLE
Clicking chat bubble on character sheet items has no effect

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#174]
In Quick Access, if I click the "chat bubble" of a weapon, nothing happens.
![image](https://user-images.githubusercontent.com/38113746/114286531-e33e1780-9a5f-11eb-8db7-3c401055adba.png)

Javascript error message says:
![image](https://user-images.githubusercontent.com/38113746/114286545-fea92280-9a5f-11eb-9408-3ca1078ce7bc.png)

It also happens from the Edge/Hindrance tab or the power tab.
![image](https://user-images.githubusercontent.com/38113746/114286560-2304ff00-9a60-11eb-8241-a084f549c130.png)

**Comment by javierriveracastro** [comment]
Solved, shouldn't happen in next version.
