### ISSUE TITLE
Clicking the arcane skill button of a power should use Better Roll Card

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#175]
In the Powers tab, when clicking the button for the arcane skill, it does open the standard skill dialog instead of using Better Rolls.

In this screenshot, my arcane skill is name "La Voie" (The Way, Shaintar's Adepts).
![image](https://user-images.githubusercontent.com/38113746/114286597-82fba580-9a60-11eb-813a-545f755d460c.png)

**Comment by javierriveracastro** [comment]
This should be solved.
