### ISSUE TITLE
Power Points aren't removed from the Arcane Backgrounda

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#176]
When I cast a power (from the Quick Access), skill is rolled correctly, but when Power Points should be taken off, it claims I have NaN, and then I'm out of Power Points. I can recharge and discharge, but in fact it is not changing the Power Points associated with the Arcane Background.

Here, my power Main Fantôme (ghost hand) is from Adept Arcane Background and I have set the current and max PP to 10.
![image](https://user-images.githubusercontent.com/38113746/114286655-061cfb80-9a61-11eb-9ac5-3770fade8e28.png)

I have casted the power a few time (to test), and see how it tells me I have only 2 remaining.
![image](https://user-images.githubusercontent.com/38113746/114286675-319fe600-9a61-11eb-97cf-84e7e157df9a.png)

But the power points on my AB haven't moved at all:
![image](https://user-images.githubusercontent.com/38113746/114286688-49776a00-9a61-11eb-89e5-c836c47faa37.png)

**Comment by CyrilRonseaux** [comment]
I tried to Benny Recharge, and look, now I'm back to "NaN"
![image](https://user-images.githubusercontent.com/38113746/114286709-7fb4e980-9a61-11eb-891a-a1909da10433.png)

**Comment by Nnayl** [comment]
Same issue here.
Power points dropped from global pool, not from arcane pool.

**Comment by javierriveracastro** [comment]
This should be solved in the next release.
