### ISSUE TITLE
Blind GM Rolls doesn´t work

### ISSUE THREAD

**Issue by StormDarkwood** [javierriveracastro/betteroll-swade#177]
When my players send me a blind gm roll they can see the roll if i am using Better Rolls 2.

![blind gm rolls](https://user-images.githubusercontent.com/75157840/114556993-8615b200-9c69-11eb-957c-dbb7076bb7b3.jpg)

**Comment by javierriveracastro** [comment]
I can't reproduce this bug. Are you sure that your players don't have dm assistant priviledges?

**Comment by StormDarkwood** [comment]
No. Ningunos de mis jugadores tiene privilegios superiores a jugador. Lo
miro en cuanto pueda y si sigue habiendo error grabó un video para que lo
puedas ver.

Gracias por mirarlo

**Comment by javierriveracastro** [comment]
Si vas a grabar un video, si puede ser, hazlo con la consola visible, porfa,

**Comment by StormDarkwood** [comment]
Hola Javier.... no te he respondido antes pues no he tenido tiempo de
ponerme a probar. Lo estoy haciendo ahora mismo y parece que va todo bien.
Lo estoy probando con BR2 activado en solitario por lo que si me vuelve a
suceder ya se que es cuestión de otro módulo.
Gracias por tu tiempo

**Comment by javierriveracastro** [comment]
Cierro el bug entonces. Si vuelve a pasar, vuelve a abrirlo.
