### ISSUE TITLE
Bubble icon does not send item description to chat

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#179]
Foundry 0.7.9, Chrome, System SW 0.17.2, BR2 for SW 2.25. Configured in French.

Clicking the bubble icon next to items in Quick Access, Edges, Hindrances, Special Abilities, or Powers Tabs does nothing:
![image](https://user-images.githubusercontent.com/38113746/115147177-0a957580-a05a-11eb-86a5-f2556b643b30.png)

Javascript error:
![image](https://user-images.githubusercontent.com/38113746/115147188-197c2800-a05a-11eb-9198-7aaf10dfc519.png)

**Comment by javierriveracastro** [comment]
This also should be solved as a sideeffect of solving another but. Now that icon always sends system chat.
