### ISSUE TITLE
First wound on double shaken is factored in Soak roll

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#180]
Hello Javier,

maybe I am doing something wrong but I just found this:
![image](https://user-images.githubusercontent.com/35796457/115840052-91ac6a00-a41b-11eb-8050-87bf737359f7.png)

Setup:
1. Target is already Shaken (but not wounded)
2. Target receives enough damage to be shaken a second time (thus receiving a wound)
3. Soaking the wound

Expectation: Wound will be shown in the wound modificators with -1, but Remove wound modifier will show 1

Result: Remove wound modifier shows 0, -1 gets factored into the roll.

**Comment by Razortide** [comment]
I checked for a roll that is a straight wound (raise on toughness) and there it worked just fine

**Comment by javierriveracastro** [comment]
I'll try to solve this before the hopefully close next release.

**Comment by javierriveracastro** [comment]
That should be solved.
