### ISSUE TITLE
Better rolls for the wealth die from swade system 0.18.0

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#181]
Since 0.18 there is a new possible roll on the inventory tab for the Wealth rule (have to enable it up first in the system config)
Failure vs TN4, modifiers and detection of raise are nice for wealth rolls. It's considered a trait roll (wild die apply).

**Comment by javierriveracastro** [comment]
I'll try to add it to the release after the next.

**Comment by SalieriC** [comment]
Moved it to #222 for some cleaning up of the issue list.
