### ISSUE TITLE
Bring "More Options" Section on cards back or make it optional setup choice

### ISSUE THREAD

**Issue by Yalnin** [javierriveracastro/betteroll-swade#183]
Hi Javier,

I was actually writing a bug report when I found in the changelog that the "more options" section of the cards were intentionally removed on v2.26 of BR2.

Although I do not know the reason, my group plays with full rules so that fights include many modifiers which we can not be handled all with global actions, so we add them up and insert them directly into the "more options" section manually. The preset modifier range down in the modifier section of the chat window is no alternative, since it has gaps (no -3, -5, +3. modifier, etc.)

If you do not want to bring back the "more options" section on the cards, maybe you can make it optional in the settings. Or complete the gaps in modifier range down in the chat window?

Thanks for considering.

**Comment by javierriveracastro** [comment]
You can click more that one modifier down the chat window. So press -2 and -1 to get a -3, etc...

I believe that it is still faster then entering a number, but I will look into get back "more options" as an option.

**Comment by SalieriC** [comment]
`Rolls:` can be expanded to enter individual modifiers. Is that sufficient? Can we close this ticket then @Yalnin?
![image](https://user-images.githubusercontent.com/1230041/120100968-f017e700-c143-11eb-8ddb-34fc1955447e.png)

**Comment by Yalnin** [comment]
Yep that's fine. Close it please.
