### ISSUE TITLE
Enhancement: Add an Ammunition Modifier JSON Expression for Global Actions

### ISSUE THREAD

**Issue by Yalnin** [javierriveracastro/betteroll-swade#184]
Hi Javier,

a JSON expresson to manipulate ammo consumtion in global actions would be great.

Being at it - maybe a complete list of the existing expressions to manipulate global actions would be great, since the list in the global action reference doc is not complete.

Thank you!

**Comment by JillyTaboga** [comment]
I have interest in that too, for CdT and ammo control for example.

**Comment by SalieriC** [comment]
> a JSON expresson to manipulate ammo consumtion in global actions would be great.

Does the module really needs to handle that? You can set up the shots used in the actions & effects tab in each weapon individually, is that not sufficient for your purposes @Yalnin & @JillyTaboga ?

Edit: If the expression is needed anyway, this should edit the new `used_shots` as introduced in #214.

**Comment by Yalnin** [comment]
Would be great to have.

One of the most popular edges used in my group is "double shot". Increases damage and shooting-test by one, plus weapon's ammo consumtion +1 too. Same with the M16's 3-shot burst: shooting-test+2, damage+2, and +3 ammo consumtion. Perfect candidates for global actions if you could manage the additional ammo consumtion too.

Those two are constantly used, as long as it is not solved by global effect you have to not forget to manually adapt the ammo consumption manually.

**Comment by SalieriC** [comment]
> Those two are constantly used,

I'd argue that this makes it a perfect candidate for the Actions & Effects for the weapons which have the Burst option. Double Tap is another story given that it is an edge but I'm really not sure if this isn't better handled by what the system has to offer. But since we have `used_shots` now, it's probably reasonably easy to set up as it could directly edit this variable. What do you think @javierriveracastro?

**Comment by Yalnin** [comment]
Obviously you do not understand the edge "double shot". It is useable with any weapon capable of firing two shots without have to reload in between. This applies to basically every existing modern firing weapon, be it revolver, semi-automatic or automatic.

**Comment by SalieriC** [comment]
Well, if you go over to hostilities: Obviously you do not know that it is called "Double Tap". -.-
I know the Edge perfectly fine, which is exactly why I wrote:
> Double Tap is another story given that it is an edge [...]

I'd like to ask you to hold back on offensive comments like that.

**Comment by javierriveracastro** [comment]
This is a place to try to have work done not for personal discussion. Please, both of you, edit your messages to something more "neutral". Think that you are not addressing one another, but the community as a whole.

**Comment by javierriveracastro** [comment]
Done
