### ISSUE TITLE
Global action configuration requires lower case.

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#188]
Just found:
```JSON
{
	"id": "TRICKSHOT",
	"name": "Trick shot",
	"button_name": "Trick shot",
	"skillMod": "+2",
	"dmgMod": "-2",
	"selector_type": "skill",
	"selector_value": "Shooting"
}
```
is not working. You need to replace "Shooting" with "shooting" and it will work.

Also, the mod is accepting -2, but not +2. It will accept "+2" and "-2" nonetheless. For the sake of harmonization I would suggest to use quotes for both cases in the samples.

**Comment by javierriveracastro** [comment]
The uppercase thing can be easily solved, the other one it's likely unsolvable as "skillMod": +2 is not valid json and the built-in javascript parse will not accept tit.

**Comment by Razortide** [comment]
Regarding +2: Yeah, I know. My point was to just generally use quotation marks in the JSON samples to have the same format for all values.

It is more a thing how to communicate the examples given, not about to change something.

**Comment by javierriveracastro** [comment]
Solved in trunk.
