### ISSUE TITLE
Shift or ALT + Click on "Quick Access" will expand item instead of the defined Better Rolls 2 configuration

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#189]
Hello Javier,

just found. Shift or ALT + Click on items in Quick access will expand the item instead of showing the defined Better Rolls 2 card. CTRL is still working though.

The configurations still works in the Gear section.

**Comment by javierriveracastro** [comment]
Could it be a browser problem? Does it happen in all of them?

**Comment by Razortide** [comment]
Just tested with Edge. Will check this evening.

**Comment by Razortide** [comment]
I was able to reproduce it with Chrome as well. To clarify: I click on the text. Clicking on the icon does not expand but does not work either.

**Comment by javierriveracastro** [comment]
I still can't reproduce it. Are you sure you don't have Shift+click and Alt+click configured to use system rolls in settings?.

Have tried the builtin browser, Chrome and Firefox. There must be some different configuration somewhere.

**Comment by SalieriC** [comment]
Can we close that @Razortide or does the issue persist? I can't reproduce it either.

**Comment by Razortide** [comment]
We can close
