### ISSUE TITLE
Let spells roll using attributes instead skills

### ISSUE THREAD

**Issue by javierriveracastro** [javierriveracastro/betteroll-swade#194]

**Comment by SalieriC** [comment]
The system now supports Smarts and Spirit. I think expanding it to all Attributes would be beneficial. What do you think?
In any case BR2 doesn't support any of the Attributes, so I'll mark it as a bug.

**Comment by javierriveracastro** [comment]
I was trying to solve this today. The main problem is (again) translation. Specially as now my players are mixing Spanish and English in the same game. I mean some people has swade and Foundry in Spanish but others in English. Funny group.

I'm probably going to make it work only if the attributes is the item card are in the same language than the sheet. Unless I get some idea fast.

**Comment by javierriveracastro** [comment]
Done.
