### ISSUE TITLE
Calculate Height in the Range Penalty

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#196]
Hi. This is the best SWADE module for sure.

Can you add to the Range Penalty calculation the Height ?

I got a macro that you could use to add the distance/Height penalty.

Better Rolls 2 now
![image](https://user-images.githubusercontent.com/4999783/117596041-c822fe00-b118-11eb-8fb6-3f202b04fffa.png)

Macro <https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Qualquer/DistanciaEntreTokens.js>
![image](https://user-images.githubusercontent.com/4999783/117596138-120be400-b119-11eb-9624-350076397d38.png)

**Comment by javierriveracastro** [comment]
This only makes sense, added to the queue.

**Comment by javierriveracastro** [comment]
Thanks for the macro, added to git version.
