### ISSUE TITLE
There is a system setting now that lets you hide NPC rolls. Can BR2 follow it?

### ISSUE THREAD

**Issue by QckSilverDragon** [javierriveracastro/betteroll-swade#197]
```
There is a system setting now that lets you hide NPC rolls.
Can Better rolls honor this setting too?
```

Sure, but that is a different issue.

_Originally posted by @javierriveracastro in https://github.com/javierriveracastro/betteroll-swade/issues/123#issuecomment-841805715_

**Comment by SalieriC** [comment]
I do think this is invalid. The System setting does not say rolls but chat cards. Further discussion over at #209.
