### ISSUE TITLE
Suggestion: Group Effects with the same name

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#198]
Hey Javier,

just a thought that crossed my mind: We do have actions (like Wild Attack) that affect damage and trait rolls (among other things).

![2021-05-18_10h24_18](https://user-images.githubusercontent.com/35796457/118617801-43dd1480-b7c3-11eb-94a5-f452f70e899e.jpg)

E.g. Instead of having Buckshot - RANGE AND Shooting (Buckshot) you would have three Buckshot Damage Actions and three Buckshot Trait Actions in the config, but in the BR2 card it will show only three items "Buckshot - Short/Medium/Long" with both icons and will apply to both.

What do you think?

**Comment by javierriveracastro** [comment]
This actions came from the core rules, that makes it difficult.

Maybe an option to disable actions from the weapon card or a global action that does it. And global actions for shotguns.

**Comment by SalieriC** [comment]
Dammit, Javier was faster than me. Gonna leave my reply here anyway...

I think this would be great, but I also think this would be somewhat difficult to do. The thing is, that Wild Attack and Called Shot and such are defined by the rules and set up as global actions. The other things depend on the weapon and may be different for each play group depending on setting and other unpredictable circumstances.
As the actions do not share the same name, they can't be easily merged together by the module. A fuzzy search would be needed but that is bound to lead to errors.

**Comment by Razortide** [comment]
Or! Or! I can just configure it in Better Rolls and kill it for the player weapons. Got your point. Thank you!

**Comment by Razortide** [comment]
Hm, could you enable an item name selector that works the same as the Actor name for global actions?

**Comment by javierriveracastro** [comment]
Done (the item name selector).

**Comment by SalieriC** [comment]
If it is done, can we close that now @javierriveracastro?

**Comment by javierriveracastro** [comment]
Not really, it still needs some way of disabling the weapon actions.

**Comment by javierriveracastro** [comment]
And now you can disable weapon actions.
