### ISSUE TITLE
Add permissions to "apply damage" rolls

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#200]
Hello Javier,
when a player tries to apply damage to another token/actor the following error message is displayed:
![image](https://user-images.githubusercontent.com/35796457/118799656-44e37400-b89f-11eb-8457-f1f3c6618b7a.png)

I have seen, that SWADE Tools has a permission check first to avoid that kind of issue. Maybe you could also restrict those actions to (Assistant) GMs?

**Comment by javierriveracastro** [comment]
Applying damage has been restricted to master in git version.
