### ISSUE TITLE
More Global Actions!

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#202]
Hi!

Can you add more standard global actions? They can start off by default.

- [x] Called Shots HAND 
- [x] Light/Medium/Heavy/Near Total Cover
- [ ] Target is defending
- [x] Ganging up selector
- [x] ILLUMINATI ON PENALTIES
- [ ] Multi-Actions
- [ ] Touch Attack
- [ ] Two Weapons
- [ ] Unarmed Defender

I'm trying to to some. But, I'm having trouble.
Is there a way to the cover shows to Fighting and Shooting? Do I need to create 2 entries?
```json
{
  "id": "LightCover",
  "name": "Light Cover",
  "button_name": "Light Cover",
  "skillMod": "-2",
  "selector_type": "skill",
  "selector_value": "Fighting"
}
```

**Comment by javierriveracastro** [comment]
Use item_type weapon.

**Comment by SalieriC** [comment]
I think most of these are best handled by the modifiers in the chat. Target is defending is best solved using AEs I think. Should be easy enough to set one up.

**Comment by javierriveracastro** [comment]
Here I agree with SalieiriC, an action that is just a modifier will add a lot of clutter to the chat card and can be easily solved using the modifier window, or dice tray or whatever.

Anyway, all actions are optional, and maybe in some settings they make sense because they are often used.

**Comment by brunocalado** [comment]
You're both right.

I don't really want these for the automation. They're for helping me remember some rules in the heat of the battle.

There is a way to add then without making a mess in the chat. Create a new selector like `"optional": "true"` and send all of these to a small button that will expand all of it on click.

```json
{
  "id": "LightCover",
  "name": "Light Cover",
  "button_name": "Light Cover",
  "skillMod": "-2",
  "selector_type": "skill",
  "selector_value": "Fighting"
  "optional": "true"
}
```

**Comment by brunocalado** [comment]
I think add this to the WIKI can be useful for others
```json
// Cover & Obstacles
−2 Light Cover: A quarter of the target is obscured.
−4 Medium Cover: Half the target is obscured, or target is prone.
−6 Heavy Cover: Three-quarters of the target is obscured.
−8 Near Total Cover: The target is barely visible.

{
  "id": "LightCover",
  "name": "Light Cover",
  "button_name": "Light Cover",
  "skillMod": "-2",
  "selector_type": "item_type", 
  "selector_value": "weapon"
}
{
  "id": "MediumCover",
  "name": "Medium Cover",
  "button_name": "Medium Cover",
  "skillMod": "-4",
  "selector_type": "item_type", 
  "selector_value": "weapon"
}
{
  "id": "HeavyCover",
  "name": "Heavy Cover",
  "button_name": "Heavy Cover",
  "skillMod": "-6",
  "selector_type": "item_type", 
  "selector_value": "weapon"
}
{
  "id": "NearCover",
  "name": "Near Cover",
  "button_name": "Near Cover",
  "skillMod": "-8",
  "selector_type": "item_type", 
  "selector_value": "weapon"
}
```

I'm working on Penalty	Lighting
-2	Dim: Twilight, light fog, night with a full moon.
-4	Dark: Typical night conditions with some ambient light from stars, a clouded or partial moon, emergency lights in an office building, a few flickering torches in a large space, etc. Targets aren’t visible outside of 10″.
-6	Pitch Darkness: Complete and total darkness (or the target is hidden or invisible). Powers that require sight may not be possible.

Any tip to handle attacks, Notice and powers???

Thank you

**Comment by javierriveracastro** [comment]
Power should work like weapons, just use a different selector or just "power" as a value.
I need to add and or complex selector.

Skills don't (yet) support actions, so not easy for notice.

**Comment by brunocalado** [comment]
I'm trying to build this now. What I am doing wrong?

Thank you.

```json
{
  "id": "OneEye",
  "name": "One Eye",
  "button_name": "One Eye",
  "skillMod": "-2",
  "selector_type": "actor_has_edge",
  "selector_value":"One Eye"  
}
```

**Comment by javierriveracastro** [comment]
One Eye is not a an edge.

I should create an "actor_has_hindrance" selector for it to work.

**Comment by SalieriC** [comment]
World Global actions could benefit from a way to target multiple or all skills. Especially when it comes to the Skill Specialisations setting rule.

**Comment by javierriveracastro** [comment]
Ok, progress on this bug, I have added an "or_selector", it should let you reduce the number of needed actions for lots of actions.

I have also marked the gang up as it has it own issue.

Next step 'actor_has_hindrance' selector.

**Comment by javierriveracastro** [comment]
'actor_has_hindrance' done.

Now the list. Target is defending needs to update the parry... it will probably need another rule that let's an action modify the tn.

**Comment by javierriveracastro** [comment]
I have added ilumination penalties. I'm not really sure of the others. I'll close this bug as right now discussion is a bit confusing. If you feel like some other actions ca be added, please open an issue for each (one for multi-action for example) so that they can be discussed orderly.
