### ISSUE TITLE
Gang Up

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#204]
Hi. 

Can try to add Gang Up rule to better2? Thank you.

![image](https://user-images.githubusercontent.com/4999783/119509407-01798180-bd47-11eb-8854-7d0717acc53d.png)

Macro: <https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Savage%20Worlds/GangUp.js>

**Comment by javierriveracastro** [comment]
Sure, it will take a while, but I'll try.

**Comment by brunocalado** [comment]
There is a problem with this macro. I'll work on it soon.

**Comment by brunocalado** [comment]
I updated the macro. I should be working well now.

**Comment by brunocalado** [comment]
I'm updating this macro in the module swademacros. It's working with 8x.

https://github.com/brunocalado/swademacros

**Comment by CyrilRonseaux** [comment]
FYI. I have tested it just now: Bruno's macro works as expected by PEG.

See PEG official rule : https://www.pegforum.com/forum/savage-worlds/official-answers-on-core-rules/51683-about-gang-up

To cancel one point of gangup, the ally of the defender must be adjacent to both the attacker and the defender. So there's exactly at most 2 spots where that ally can stand (while there are 6 for enemies to gangup from), unless attacker is striking from Reach, in which case there are 3 spots (adjacent to attacker and its target).

**Comment by brunocalado** [comment]
> FYI. I have tested it just now: Bruno's macro works as expected by PEG.
> 
> See PEG official rule : https://www.pegforum.com/forum/savage-worlds/official-answers-on-core-rules/51683-about-gang-up
> 
> To cancel one point of gangup, the ally of the defender must be adjacent to both the attacker and the defender. So there's exactly at most 2 spots where that ally can stand (while there are 6 for enemies to gangup from), unless attacker is striking from Reach, in which case there are 3 spots (adjacent to attacker and its target).

Thank you for verify this. It'll be great to see this code inside br2. :)

**Comment by javierriveracastro** [comment]
Some day, some day...

**Comment by javierriveracastro** [comment]
The day has come XDDDD

Macro added, thank you very much.
