### ISSUE TITLE
Attribute Rolls do not use the label but the attribute name instead

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#205]
When I try rolling an attribute from the character sheet with the German translation enabled, it still shows the card title as "agility":
![image](https://user-images.githubusercontent.com/35796457/119511557-d573f580-bd72-11eb-93fd-e804f098c4bf.png)
Expectation would be to see the language label.

**Comment by javierriveracastro** [comment]
This is a duplicate of [#159](https://github.com/javierriveracastro/betteroll-swade/issues/159)
