### ISSUE TITLE
Applying damage to 0/0 Wound opponents

### ISSUE THREAD

**Issue by Alis-72** [javierriveracastro/betteroll-swade#207]
When creature with 0 wounds gets wounded it wont get incapacitated (and gets no wounds)
All non-wildcard creatures in premium SWADE and Deadlands have 0 wounds listed on sheet and thus all have to manually 'handled' when they get that 1 wound.

Would be optimal if mooks would also get down on wounds automaticly when they receive one (or more)

**Comment by SalieriC** [comment]
*On click as usual please, automatically is bad. ^^'

**Comment by javierriveracastro** [comment]
Unless you are talking about something else it seems to be working for me:


https://user-images.githubusercontent.com/8113700/120204414-106da180-c229-11eb-9908-663d2b86e0aa.mp4

The NPC needs to be in a combat, AFAIK incapacitation only works in combatants (tokens in a battle).

Unless you are talking about something else, like the incapacitation effect.

**Comment by Alis-72** [comment]
My bad, didnt have test char in combat tracker. Closing this obsolete ticket.
Sorry for confusion.
