### ISSUE TITLE
Respect the systems chat card setting.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#209]
The system has a setting that could be used by BR2 as well:
![image](https://user-images.githubusercontent.com/1230041/119847777-8f9e6500-bf0b-11eb-9c8e-be5aeb840c90.png)
If enabled all chat cards from BR2 _except those which initiate a roll_ should be whispered to the GM. This way items which do not initiate a roll can't be accidentally shown to players (which happens to me a lot).
Those items which initiate a roll should respect the setting in the chat as usual.

**Comment by javierriveracastro** [comment]
That's a great idea, in our last deadland game the dm send to chat by error on the "invulnerable" trait of an enemy. That was a terrible spoiler :(.

**Comment by SalieriC** [comment]
In #197 it seemed s/o thought this would be about rolls but from reading the setting and experimenting with system rolls it only applies to the actual chat cards which are separate from rolls in the system. I'd say do as I suggested and possibly hide the description of the item which was rolled from for non-gm accounts? Or maybe just hiding non-rolls by sending them as message. I'm torn on this. Some special ability weapon descriptions I don't want to show to players, most stuff I do want to show them. Any thoughts?

**Comment by javierriveracastro** [comment]
This is getting harder. All chat cards (but incapacitation) are of type roll. And that makes sense, specially if you are using tabbed chat or another module that uses char card categorization.

There is clearly a problem here, but I don't know how to approach it.

**Comment by javierriveracastro** [comment]
As no one has helped and I don't know how to do this I'm closing it. 

Whoever reads this, feel free to reopen if you find some way of tackling this issue.
