### ISSUE TITLE
Add functionality to handle Boost / Lower Trait

### ISSUE THREAD

**Issue by zk-sn** [javierriveracastro/betteroll-swade#210]
Our group has a caster with Boost/Lower Trait and handling it is a bit unwieldy.  We're currently having the character whose trait is boosted (or lowered) go into their sheet and actually increase or decrease the trait dice.  Would be nice if in the "Modifiers for Better Rolls 2" section above the chat bar there was a row for +2, +1, 0, -1, -2 die sizes that would handle that automatically.

**Comment by javierriveracastro** [comment]
That could be done, but isn't this the exact usage case for active effects?

**Comment by zk-sn** [comment]
Possibly, but I see a couple of problems with that:
- I figured out how to modify die size for attributes via active effects by modifying data.attributes.agility.die.sides but I couldn't figure out how to do the same for skills, unless there's a way to use a script in the attribute key
- Modifying a die size via an active effect doesn't seem to handle increasing die size past d12 or below d4

If you know how to work around those problems, using active effects would be the perfect solution!

**Comment by javierriveracastro** [comment]
You can use Swade Toolkit (a module) to change skill dies. No way of solving the other problem AFAIK.

**Comment by zk-sn** [comment]
I'll check out Swade Toolkit, thanks!

**Comment by CyrilRonseaux** [comment]
I would also do it with Active Effects. Especially since it's not a modified for a single or a few rolls, but for all rolls for a duration. Swade Toolkit (which works perfectly with BR2) is the way to go, until AE on "Items" is implemented in Foundry core.

**Comment by zk-sn** [comment]
Swade Toolkit's skill dice bonus doesn't handle going over d12 or under d4 quite right, but I'll open that up as an issue over there.  I'll close this issue, thanks for the quick response!

**Comment by SalieriC** [comment]
Don't get your hopes up @zk-sn. The author has been gone for a long time now. Take a look at https://github.com/SalieriC/SWADE-Toolkit-Hotfix
I fixed some annoying issues but I couldn't fix going over d12/under d4 yet. But it's something.
Hope @javierriveracastro doesn't mind me advertising it here. I'm very sorry if you do, don't mean to be rude, just want to help out.

**Comment by zk-sn** [comment]
Awesome, thanks @SalieriC.  I'll take a look!
