### ISSUE TITLE
Damage card looks funny in German with AP

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#213]
Hey Javier, as discussed, the official translation is a bit long and forces linebreaks in German.
![image](https://user-images.githubusercontent.com/35796457/119898941-c2178480-bf42-11eb-898f-2b46e98cb43f.png)

**Comment by Razortide** [comment]
Since there is a tooltip configured, maybe you can overwrite it with an own abbreviation?

**Comment by javierriveracastro** [comment]
Yes, I can make two trasnlation string, one for the label other for the toolptip, make it the same in concise languages and different in german.

**Comment by javierriveracastro** [comment]
i have added it and make it AP for german, probably not the best translation.

![imaxe](https://user-images.githubusercontent.com/8113700/126362720-402210c1-d94d-4f78-9e26-9bd10022a37c.png)
