### ISSUE TITLE
Pass amount of shots and power points down for macro use in global actions.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#214]
Currently there is no reasonable way to get the actual number of shots or power points from the BR2 chat message in the light of global actions. They can only be guessed which is subject to errors.

**Comment by SalieriC** [comment]
As discussed, passing the rolled skill could also be beneficial.

**Comment by javierriveracastro** [comment]
Done, now let me test it to do a release.

**Comment by SalieriC** [comment]
By default `used_shots` is zero. So it will by default use the max RoF to initiate the roll but doesn't set the appropriate number of shots. Calculating this by BR2 is not exactly mandatory but probably easier.
Also when using an action which has "Shots Used" set up on the weapon, BR2 still passes `shots_used` as zero.
Sorry to be such a nuisance. ^^'

**Comment by javierriveracastro** [comment]
It works for me. I tested an action, default rof and clicking modifier.

Is "subtract ammo" marked?. What it doesn't do if doing shot calculation when it isn't need (i.e. when it doesn't need to subtract ammo).

Maybe using another default but 0 could make sense.

**Comment by SalieriC** [comment]
>Is "subtract ammo" marked?

Well, no. I'm trying to build an alternative to that. :rofl: 
I guess having it only do what's necessary is reasonable performance wise but not so much when it comes to supporting third-party creators... :-S

**Comment by javierriveracastro** [comment]
Ok, that makes sense. But how do I know I must calculate shots? Do it for every item? 

Maybe doing the calculation in the run_macro function...

**Comment by SalieriC** [comment]
A switch to toggle on the calculation in the global action .json maybe?

**Comment by javierriveracastro** [comment]
Now the calculation will be triggered when one of this is true:

1. The subtract ammo button is selected
2. There is an action with a macro selected and the item has a shot stats different than 0.

Hope that it is enough.

**Comment by SalieriC** [comment]
You never know with SalieriC-Bugs...
`used_shots` is still not updated. The BR2 ammo management uses the correct amount of shots from an action but it doesn't matter whether or not it is activated, `used_shots` is still always zero. I need it to get updated with the amount of shots specified in the action when the BR2 subtract ammo button is **not** activated to address a bug in my code.

**Comment by javierriveracastro** [comment]
The "BUG" part should be solved. I'll keep it for the "ENHACENMENT" part (pass power points).

**Comment by javierriveracastro** [comment]
used_pp is now passed in render_data.
