### ISSUE TITLE
Macro Global Actions are not shown on direct roll item cards.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#215]
And possibly others.
Also the Actions are not collapsed by default if a global action is set up and enabled by default. Not sure whether this is intentional or not.

**Comment by javierriveracastro** [comment]
The main issue should be solved.

Also actions are only collapsed by default on direct rolls. I mean if you don't use a direct roll, it is because you want to set an action, no?

**Comment by SalieriC** [comment]
Makes sense. Thanks. =)
