### ISSUE TITLE
Using a BR2 item card macro disables global actions with `"defaultChecked":"on"`

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#219]
Happens for Direct Rolls as well as Chat Card.

Additional context: It seems to be enabled but gets disabled shortly after the card is created.

**Comment by javierriveracastro** [comment]
It seems to work for me with a simple macro. Does it happen always or just with some specific macro?. If it happens with only some macros, can you post one here?, does it do something with the message object?.

**Comment by SalieriC** [comment]
Happens with more than one macro. I sent you a video as DM in discord for reference.

**Comment by javierriveracastro** [comment]
Confirmed. Happens specially when using a macro from the bar.

**Comment by javierriveracastro** [comment]
This should be solved. Or at least it looks like. Remember: never say solved to a SalieriC bug.

**Comment by SalieriC** [comment]
No, this seems to be fixed indeed. :D
