### ISSUE TITLE
Right click on Quick Access items on the PC sheet does nothing

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#220]
For the sake of consistency it should open the item as it does on NPC sheets.
Doesn't work on the Community sheet as well as the official sheet.

**Comment by javierriveracastro** [comment]
While I agree this is not a bug. A bug is something that doesn't work, this is a very reasonable enhacement and clearly an UX issue.

**Comment by javierriveracastro** [comment]
Should be done, hope that I didn't hidden some unknown right click function.
