### ISSUE TITLE
Expanding Global Actions to Skill rolls.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#221]
As discussed in #166, expanding Global Actions to skill rolls would be of great benefit for many purposes. This is true for #166 as well as #164 and possibly other which we don't know about yet.

**Comment by CyrilRonseaux** [comment]
I'm all for that kind of feature.
See my proposal to SWADE core : https://gitlab.com/peginc/swade/-/issues/270

Ideally, it could be added to Attributes too. (Iron Jaws, Combat Reflexes, Brave...)

**Comment by javierriveracastro** [comment]
Should done, it probably needs testing, but it is done.
