### ISSUE TITLE
BR2 does not use the weapons modifiers if it is a die type.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#225]
Entries of a number work but die type modifiers like `+d4x` or `+1d4x` do not. This is true for all item modifiers, the universal ones as well as the action specific ones. Using `+1d4x` leads to a modifier of `1` instead.

**Comment by javierriveracastro** [comment]
I'm not sure that this is doable with the current way that modifiers work, it really expect them to be a number.

I'll look into it anyway.

**Comment by javierriveracastro** [comment]
This is half solved. Next version will support dice expression in trait modifiers.

I'll try to add dice damage modifiers (likely the most useful) when this version is released.

**Comment by javierriveracastro** [comment]
And now it should be solved for damage too.
