### ISSUE TITLE
Add "modifiers" block to roll cards where appropriate

### ISSUE THREAD

**Issue by richardgaywood** [javierriveracastro/betteroll-swade#227]
See mock below.

Reasons for suggesting this change:

1. Semantically clearer to apply modifiers specifically for "25% cover" rather than remembering that is -2
2. The player can initiate the roll card, then the GM can click the modifier buttons as needed before the player rolls; feels more streamlined than the GM verbally telling the player and then the player having to click the button
3. Mutually exclusive modifiers can be grouped (eg. dim/dark/pitch black) and when one is selected the others can be de-selected
4. Opens the door, down the road, to automatic detection of modifiers that apply to the modifiers (eg. an Aim button that understands how to cancel up to four points of penalties but only from certain sources; or a Dodge modifier that would appear in the list, pre-selected to apply, when the target has the Dodge Edge)
5. Acts as a reminder to the GM for common situational modifiers to apply
6. Acts as a reminder to GM for which situational modifiers BR2 cannot apply automatically - eg. the _absence_ of range here is a reminder/hint that range is taken care of by the framework and does not need to be considered.
7. Makes it really clear, before the dice are rolled, what modifiers will apply to this roll

Sample (crude) mock:
![25B87C32-3F66-4C05-9104-80E15606B63F](https://user-images.githubusercontent.com/9166480/120318663-035bbb80-c2d8-11eb-92e6-1b7ae5b47cb4.png)

**Comment by Razortide** [comment]
Maybe a "global action" could have an optional "category" value?

**Comment by javierriveracastro** [comment]
I was thinking more about a "group", and likely adding a "Card" group for the actions defined in the card.

There are also internalization issues with system level global actions, but they should be solvable.

It can also be really helpful to configure br, as it should allow people to enable or disable a group of actions with a simple click.

In general it is a fantastic idea, but I don't get why there is an Action an a Modifer section. All are actions to me.

Anyway, right now 0.8.6 compatibility is the priority, enhancements will have to wait.

**Comment by richardgaywood** [comment]
> In general it is a fantastic idea, but I don't get why there is an Action an a Modifer section. All are actions to me.

Well, first of all, in the wider context of SWADE itself: you have the action the PC does, and you have the modifiers that apply to the action. So there's a distinction between the two in the game itself.

But I think there's also a language difference. An "action" section that says "wild attack" or "called shot" is a menu from which I pick one exclusive choice. The fact it is a list of possible "actions" tells me I am only doing one of them; my character has a turn, they take an action, the action is one of these things. Whereas for modifiers, clearly, more than one can apply (and they can all apply to any action.)

(I concede this gets a little messy with RoF, because one might do a called shot at RoF1 or RoF3 or burstfire. So RoF isn't really an action either, it's a modifier.)

Not splitting it into two sections is a perfectly valid choice, but then I'd suggest a different name for it than "actions", to convey it's a wider category than that name implies. 

> Anyway, right now 0.8.6 compatibility is the priority, enhancements will have to wait.

Of course, no arguments there :D That's clearly the most important thing right now!

**Comment by CyrilRonseaux** [comment]
Wild Attacks and Called Shot are not actions. Wild Attack is more of a state, and Called Shot is clearly a situational modifier. Frenzy is an action (a multi-dice melee attack action). Sweep is an action.
I'm ok with having all handled under BR2 actions. Could also be "options" or "variations".

**Comment by javierriveracastro** [comment]
This should be done unless I miss something,
