### ISSUE TITLE
Don't autoroll damage: Doesn't work for players.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#23]
It works just fine for the GM. Players on the other hand roll attack and get no buttons for rolling damage at all on melee weapons or all of them at once using ranged weapons:
![image](https://user-images.githubusercontent.com/1230041/88025853-3b7d6400-cb35-11ea-941a-90606a5c7063.png)

**Comment by javierriveracastro** [comment]
I believe that I have found the problem. Does Brass Knuckles have a ROF of 0?.

**Comment by javierriveracastro** [comment]
Anyway, now (the trunk version) doesn't break on ROF 0 or non integer. It just defaults to 1.

**Comment by javierriveracastro** [comment]
I'm assuming it was the ROF 0 bug and closing the issue.
