### ISSUE TITLE
Modifier label is ignored when manually adding modifiers

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#230]
On a roll card, after the dice have been rolled, if you use that black + to add a modifier on the fly, a dialog asks for a label and a modifier. Then the modifier is added to the roll.

Issue is the label that was set is totally ignored. The modifier is correctly added but its label is always "manually added".

![image](https://user-images.githubusercontent.com/38113746/120870420-31bbee00-c599-11eb-9be6-9a42bce132b7.png)

Foundry 0.7.10, SWADE 0.18.4, BR2 2.31
Used in French language in the screenshot.
But also reproduced in English with only BR2 module active.

![image](https://user-images.githubusercontent.com/38113746/120870773-14d3ea80-c59a-11eb-9719-2e3517fb61a7.png)
![image](https://user-images.githubusercontent.com/38113746/120870780-1ac9cb80-c59a-11eb-9952-eac62ddf8bb8.png)

Very minor issue. The label isn't that much useful.

**Comment by javierriveracastro** [comment]
Should be alse easy to solve.

**Comment by javierriveracastro** [comment]
And now it should be solved in git.
