### ISSUE TITLE
Status Effect icons not updating

### ISSUE THREAD

**Issue by techogre** [javierriveracastro/betteroll-swade#232]
Not sure if this is the module that would handle this or the character sheet. Please ignore if this is not your clown or circus. :)

Running server version 0.8.6 with only the following modules installed:

* Better Rolls 2 for Savage Worlds (version 2.34)
* Compendium Folders (version 2.3.1)
* libWrapper (version 1.6.2.0)
* Savage Worlds Adventure Edition Core Rules (version 1.0.4)
* Settings Extender (version 1.1.6+0.8.5)

Issue: When an actor gets the Shaken condition from damage and I click the Apply Damage button, the Status Effect icon for shaken is not selected. The same happens with Distracted, Vulnerable, etc. However, the check box for Shaken (and the others) does get checked and the usual Shaken effects seem to work.

Is the Status Effect icon linked to the status checkboxes? Do I need any additional modules?

Thanks!

**Comment by javierriveracastro** [comment]
As comented in Discord, this was never a BR feature. You were likely using it with SWADE Toolkit, that AFAIK is not supported in 0.8.x.

If Toolkit is not updated, I'll think about including this feature in BR, but for now let's hope that someone else takes the work.

**Comment by SalieriC** [comment]
As a workaround, @techogre, try using Combat Utility Belt. Here is a guide to set it up: https://github.com/SalieriC/SWADE-Immersive-Macros/blob/main/documentation/CUB%20Setup.md
