### ISSUE TITLE
Items (items/powers) in inventory no longer working

### ISSUE THREAD

**Issue by techogre** [javierriveracastro/betteroll-swade#233]
### Environment Details

Foundry VTT Version: 0.8.6
Operating System: Ubuntu 20.04 on a Raspberry Pi 3 B+
How Are You Using Foundry: Nodes.js service
Modules Enabled?:
- Better Rolls 2 for Savage Worlds (version 2.34)
- Compendium Folders (version 2.3.1)
- Dice So Nice (version 3.4.2)
- libWrapper (version 1.6.2.0)
- Savage Worlds Adventure Edition Core Rules (version 1.0.4)
- Settings Extender (version 1.1.6+0.8.6)
- Token Action HUD (version 1.0.30)

### Issue Description

When an actor is selected and one of the items under Inventory is selected, I get the following error in console:

2swade-br2sw.js:57 
Uncaught (in promise) TypeError: game.brsw.create_item_card_fromid is not a function
    at RollHandlerBR2SWSwade._rollItem (swade-br2sw.js:57)
    at RollHandlerBR2SWSwade.doHandleActionEvent (swade-br2sw.js:28)
    at RollHandlerBR2SWSwade.handleActionEvent (rollHandler.js:47)
    at handleClick (tokenactionhud.js:100)
    at HTMLDivElement.<anonymous> (tokenactionhud.js:107)
    at HTMLDivElement.dispatch (jquery.min.js:2)
    at HTMLDivElement.v.handle (jquery.min.js:2)

### Relevant logs and/or screenshots

n/a

### Possible Solution and/or Root Cause

n/a

/label ~bug

**Comment by javierriveracastro** [comment]
The truth this is the first time that I'm aware TokenActionHud supports BR. I'll try to look into it, but not sure that this is a br issues.

**Comment by zk-sn** [comment]
@javierriveracastro This was an issue with Token Action HUD and should now be fixed

https://github.com/espositos/fvtt-tokenactionhud/issues/272

@techogre Can you update Token Action HUD and confirm if it's working now?

**Comment by javierriveracastro** [comment]
I will close this as people on Discord reported that it is working.
