### ISSUE TITLE
Collapse by default the modifier window not working

### ISSUE THREAD

**Issue by QckSilverDragon** [javierriveracastro/betteroll-swade#235]
I have this option enabled and its not working. It did work with 0.7.9 but since i upgraded to 0.8.6 it doesn't seem to start collapsed.

I dont see any errors in the console.

![image](https://user-images.githubusercontent.com/4044050/121278785-f0795600-c898-11eb-8def-50657ddd1058.png)

**Comment by javierriveracastro** [comment]
There are two errors on the console, likely not relevant, but...

**Comment by javierriveracastro** [comment]
This is now working for me in 0.,8.6
