### ISSUE TITLE
Global Actions Importer/Exporter

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#236]
Hi.

Can create a better way to lots of global actions? This could be easy to share.

Suggestions:

1. Create a importer button that will read one file and add all actions in there.

**Comment by javierriveracastro** [comment]
That's a great idea. It will let people create "settings pack" with global actions.

**Comment by javierriveracastro** [comment]
This should be done.

**Comment by grendel111111** [comment]
I can make the Json with the exporter but it won't import into a new world. Is there another step you need to take other than import, ad select the file?

**Comment by javierriveracastro** [comment]
Nope. Can you post your json here?

**Comment by grendel111111** [comment]
[{"id":"MARKSMAN2","name":"Marksman2","button_name":"Marksman","skillMod":"+1","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Marksman"},{"selector_type":"skill","selector_value":"Athletics"}],"group":"BRSW.Edges"},{"id":"MARKSMAN","name":"Marksman","button_name":"Marksman","skillMod":"+1","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Marksman"},{"selector_type":"skill","selector_value":"Shooting"}],"group":"BRSW.Edges"},{"id":"Ugly","name":"Ugly","button_name":"Ugly","skillMod":"-1","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"Ugly"},{"selector_type":"skill","selector_value":"Persuasion"}],"defaultChecked":"on","group":"Hindrance"},{"id":"Tongue Tied4","name":"Tongue Tied4","button_name":"Outsider","skillMod":"-1","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"Tongue Tied"},{"selector_type":"skill","selector_value":"Taunt"}],"defaultChecked":"on","group":"Hindrance"},{"id":"Tongue Tied3","name":"Tongue Tied3","button_name":"Outsider","skillMod":"-1","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"Tongue Tied"},{"selector_type":"skill","selector_value":"Performance"}],"defaultChecked":"on","group":"Hindrance"},{"id":"Tongue Tied2","name":"Tongue Tied2","button_name":"Outsider","skillMod":"-1","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"Tongue Tied"},{"selector_type":"skill","selector_value":"Intimidation"}],"defaultChecked":"on","group":"Hindrance"},{"id":"Tongue Tied1","name":"Tongue Tied1","button_name":"Outsider","skillMod":"-1","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"Tongue Tied"},{"selector_type":"skill","selector_value":"Persuasion"}],"defaultChecked":"on","group":"Hindrance"},{"id":"Outsider","name":"Outsider","button_name":"Outsider","skillMod":"-2","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"Outsider"},{"selector_type":"skill","selector_value":"Persuasion"}],"defaultChecked":"on","group":"Hindrance"},{"id":"One Eye","name":"One Eye","button_name":"Skill uses vision at 5 inches or more","skillMod":"-2","selector_type":"actor_has_hindrance","selector_value":"One Eye","defaultChecked":"on","group":"Hindrance"},{"id":"One Arm3","name":"One Arm3","button_name":"Weapon uses two hands","skillMod":"-4","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"One Arm"},{"selector_type":"skill","selector_value":"Fighting"}],"defaultChecked":"on","group":"Hindrance"},{"id":"One Arm2","name":"One Arm2","button_name":"Weapon uses two hands","skillMod":"-4","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"One Arm"},{"selector_type":"skill","selector_value":"Shooting"}],"defaultChecked":"on","group":"Hindrance"},{"id":"One Arm","name":"One Arm","button_name":"Skill uses two hands","skillMod":"-4","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"One Arm"},{"selector_type":"skill","selector_value":"Athletics"}],"defaultChecked":"on","group":"Hindrance"},{"id":"Mild Mannered","name":"Mild Mannered","button_name":"Mild Mannered","skillMod":"-2","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"Mild Mannered"},{"selector_type":"skill","selector_value":"Intimidation"}],"defaultChecked":"on","group":"Hindrance"},{"id":"Mean","name":"Mean","button_name":"Mean","skillMod":"-1","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"Mean"},{"selector_type":"skill","selector_value":"Persuasion"}],"defaultChecked":"on","group":"Hindrance"},{"id":"Hard of Hearing","name":"Hard of Hearing","button_name":"Listening check","skillMod":"-4","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"Hard of Hearing"},{"selector_type":"skill","selector_value":"Notice"}],"defaultChecked":"on","group":"Hindrance"},{"id":"Clumsy2","name":"Clumsy2","button_name":"Clumsy","skillMod":"-2","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"Clumsy"},{"selector_type":"skill","selector_value":"Stealth"}],"defaultChecked":"on","group":"Hindrance"},{"id":"Clumsy1","name":"Clumsy","button_name":"Clumsy","skillMod":"-2","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"Clumsy"},{"selector_type":"skill","selector_value":"Athletics"}],"defaultChecked":"on","group":"Hindrance"},{"id":"Clueless2","name":"Clueless2","button_name":"Clueless","skillMod":"-1","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"Clueless"},{"selector_type":"skill","selector_value":"Notice"}],"defaultChecked":"on","group":"Hindrance"},{"id":"Clueless1","name":"Clueless","button_name":"Clueless","skillMod":"-1","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"Clueless"},{"selector_type":"skill","selector_value":"Common Knowledge"}],"defaultChecked":"on","group":"Hindrance"},{"id":"Can't Swim","name":"Can't Swim","button_name":"Can't Swim","skillMod":"-2","and_selector":[{"selector_type":"actor_has_hindrance","selector_value":"Can't Swim"},{"selector_type":"skill","selector_value":"Athletics"}],"defaultChecked":"on","group":"Hindrance"},{"id":"Bad Eyes","name":"Bad Eyes","button_name":"Bad eyes","skillMod":"-1","selector_type":"actor_has_hindrance","selector_value":"Bad Eyes","defaultChecked":"on","group":"Hindrance"},{"id":"BLIND","name":"Blind","button_name":"Blind","skillMod":"-6","selector_type":"actor_has_hindrance","selector_value":"Blind","defaultChecked":"on","group":"Hindrance"},{"id":"Healer2","name":"Healer","button_name":"Healer","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Healer"},{"selector_type":"item_name","selector_value":"Healing"}],"defaultChecked":"on","group":"BRSW.Edges"},{"id":"Healer1","name":"Healer1","button_name":"Healer","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Healer"},{"selector_type":"skill","selector_value":"Healing"}],"defaultChecked":"on","group":"BRSW.Edges"},{"id":"Danger Sense2","name":"Danger Sense2","button_name":"No notice roll allowed","skillMod":"-2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Danger Sense"},{"selector_type":"skill","selector_value":"Notice"}],"group":"BRSW.Edges"},{"id":"Danger Sense1","name":"Danger Sense1","button_name":"Roll for surprise","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Danger Sense"},{"selector_type":"skill","selector_value":"Notice"}],"group":"BRSW.Edges"},{"id":"Champion","name":"Champion","button_name":"Target is evil(good)","dmgMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Champion"},{"selector_type":"item_type","selector_value":"weapon"}],"group":"BRSW.Edges"},{"id":"Streetwise3","name":"Streetwise3","button_name":"Network with criminal elements","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Streetwise"},{"selector_type":"skill","selector_value":"Intimidation"}],"group":"BRSW.Edges"},{"id":"Streetwise2","name":"Streetwise2","button_name":"Network with criminal elements","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Streetwise"},{"selector_type":"skill","selector_value":"Persuasion"}],"group":"BRSW.Edges"},{"id":"Streetwise1","name":"Streetwise1","button_name":"Underworld Knowledge","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Streetwise"},{"selector_type":"skill","selector_value":"Common Knowledge"}],"group":"BRSW.Edges"},{"id":"Menacing","name":"Menacing","button_name":"Menacing","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Menacing"},{"selector_type":"skill","selector_value":"Intimidation"}],"defaultChecked":"on","group":"BRSW.Edges"},{"id":"Woodsman2","name":"Woodsman2","button_name":"In the wild","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Woodsman"},{"selector_type":"skill","selector_value":"Stealth"}],"group":"BRSW.Edges"},{"id":"Woodsman1","name":"Woodsman1","button_name":"In the wild","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Woodsman"},{"selector_type":"skill","selector_value":"Survival"}],"group":"BRSW.Edges"},{"id":"Thief2","name":"Thief2","button_name":"Thief","skillMod":"+1","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Thief"},{"selector_type":"skill","selector_value":"Thievery"}],"defaultChecked":"on","group":"BRSW.Edges"},{"id":"Thief1","name":"Thief1","button_name":"Urban climb","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Thief"},{"selector_type":"skill","selector_value":"Athletics"}],"group":"BRSW.Edges"},{"id":"MRFIXIT","name":"Mr Fix It","button_name":"Mr Fix It","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Mr Fix It"},{"selector_type":"skill","selector_value":"Repair"}],"defaultChecked":"on","group":"BRSW.Edges"},{"id":"Investigator2","name":"Investigator2","button_name":"Investigator","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Fame"},{"selector_type":"skill","selector_value":"Research"}],"group":"BRSW.Edges"},{"id":"Investigator1","name":"Investigator1","button_name":"Investigator","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Fame"},{"selector_type":"skill","selector_value":"Notice"}],"group":"BRSW.Edges"},{"id":"Assassin","name":"Assassin","button_name":"Assassin (Target is V or D)","dmgMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Assassin"},{"selector_type":"item_type","selector_value":"weapon"}],"group":"BRSW.Edges"},{"id":"Improved Sweep","name":"Improved Sweep","button_name":"Improved Sweep","skillMod":"-2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Improved Sweep"},{"selector_type":"skill","selector_value":"Fighting"}],"group":"BRSW.Edges"},{"id":"Sweep","name":"Sweep","button_name":"Sweep","skillMod":"-2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Sweep"},{"selector_type":"skill","selector_value":"Fighting"}],"group":"BRSW.Edges"},{"id":"Martial Warrior","name":"MartialWarrior","button_name":"Martial Warrior","skillMod":"+2","dmgMod":"+1d6x","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Martial Artist"},{"selector_type":"item_name","selector_value":"unarmed"}],"defaultChecked":"on","group":"BRSW.Edges"},{"id":"Martial Artist","name":"MartialArtist","button_name":"Martial Artist","skillMod":"+1","dmgMod":"+1d4x","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Martial Artist"},{"selector_type":"item_name","selector_value":"unarmed"}],"defaultChecked":"on","group":"BRSW.Edges"},{"id":"Giant Killer","name":"GiantKiller","button_name":"Giant Killer","dmgMod":"+1d6x","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Giant Killer"},{"selector_type":"skill","selector_value":"fighting"}],"group":"BRSW.Edges"},{"id":"Free runner","name":"Free runner","button_name":"Free runner","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Famous"},{"selector_type":"skill","selector_value":"Athletics"}],"group":"BRSW.Edges"},{"id":"Famous","name":"Famous","button_name":"Famous","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Famous"},{"selector_type":"skill","selector_value":"Persuasion"}],"group":"BRSW.Edges"},{"id":"Fame","name":"Fame","button_name":"Fame","skillMod":"+1","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Fame"},{"selector_type":"skill","selector_value":"Persuasion"}],"group":"BRSW.Edges"},{"id":"Brave","name":"Brave","button_name":"Aristocrat","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Brave"},{"selector_type":"attribute","selector_value":"Spirit"}],"group":"BRSW.Edges"},{"id":"Aristocrat2","name":"Aristocrat2","button_name":"Aristocrat","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Aristocrat"},{"selector_type":"skill","selector_value":"Common Knowledge"}],"group":"BRSW.Edges"},{"id":"Aristocrat1","name":"Aristocrat1","button_name":"Aristocrat","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Aristocrat"},{"selector_type":"skill","selector_value":"Persuasion"}],"group":"BRSW.Edges"},{"id":"Very Attractive2","name":"Very Attractive2","button_name":"Very Attractive","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Attractive"},{"selector_type":"skill","selector_value":"Persuasion"}],"group":"BRSW.Edges"},{"id":"Very Attractive1","name":"Very Attractive1","button_name":"Very Attractive","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Very Attractive"},{"selector_type":"skill","selector_value":"Performance"}],"group":"BRSW.Edges"},{"id":"ALERTNESS","name":"Alertness","button_name":"Alertness","skillMod":"+2","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Alertness"},{"selector_type":"skill","selector_value":"Notice"}],"defaultChecked":"on","group":"BRSW.Edges"},{"id":"3 actions","name":"3 actions","button_name":"3 actions","skillMod":"-4","selector_type":"all","group":"Multi-action"},{"id":"2 actions","name":"2 actions","button_name":"2 actions","skillMod":"-2","selector_type":"all","group":"Multi-action"},{"id":"ran","name":"Ran","button_name":"Ran","skillMod":"-2","selector_type":"all","group":"Multi-action"},{"id":"Attractive2","name":"Attractive2","button_name":"Attractive","skillMod":"+1","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Attractive"},{"selector_type":"skill","selector_value":"Persuasion"}],"group":"BRSW.Edges"},{"id":"Attractive1","name":"Attractive1","button_name":"Attractive","skillMod":"+1","and_selector":[{"selector_type":"actor_has_edge","selector_value":"Attractive"},{"selector_type":"skill","selector_value":"Performance"}],"group":"BRSW.Edges"},{"id":"Targetprone2","name":"target prone2","button_name":"target prone","skillMod":"-4","or_selector":[{"selector_type":"skill","selector_value":"Shooting"},{"selector_type":"skill","selector_value":"Athletics"}],"group":"BRSW.SituationalModifiers"},{"id":"Targetprone1","name":"target prone","button_name":"target prone","skillMod":"+2","selector_type":"skill","selector_value":"Fighting","group":"BRSW.SituationalModifiers"},{"id":"NONLETHALDAMAGE","name":"Nonlethal Damage","button_name":"Nonlethal Damage","skillMod":"-1","selector_type":"skill","selector_value":"Fighting","group":"BRSW.AttackOption"},{"id":"UNSTABLEPLATFORM","name":"Unstable Platform","button_name":"Unstable Platform","skillMod":"-2","or_selector":[{"selector_type":"skill","selector_value":"Shooting"},{"selector_type":"skill","selector_value":"Athletics"}],"group":"BRSW.SituationalModifiers"},{"id":"Aim","name":"Aim","button_name":"Aim","skillMod":"+2","selector_type":"skill","selector_value":"Shooting","group":"BRSW.AttackOption"},{"id":"Two Weapons","name":"Two Weapons","button_name":"Two Weapons vs. single weapon","skillMod":"+1","selector_type":"skill","selector_value":"Fighting","group":"BRSW.SituationalModifiers"},{"id":"OFFHANDATTACKS","name":"Off-Hand Attacks","button_name":"Off-Hand Attacks","skillMod":"-2","selector_type":"item_type","selector_value":"weapon","group":"BRSW.AttackOption"},{"id":"TOUCHATTACK","name":"Touch Attack","button_name":"Touch Attack","skillMod":"+2","dmgOverride":"0","selector_type":"skill","selector_value":"Fighting","group":"BRSW.AttackOption"},{"id":"UNARMEDDEFENDER","name":"Unarmed Defender","button_name":"Unarmed Defender","skillMod":"+2","selector_type":"skill","selector_value":"Fighting","group":"BRSW.SituationalModifiers"}]

**Comment by grendel111111** [comment]
Sorry it won't attach as a file.

**Comment by javierriveracastro** [comment]
It is ok. I'll try it.

**Comment by grendel111111** [comment]
Has anyone had any luck with the json importer? I still haven't been able to get it to work.

**Comment by javierriveracastro** [comment]
The importer should work again (in git version).
