### ISSUE TITLE
Ammo spent - Card is not translatable

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#237]
Hello Javier,

unfortunately, the content of the "Ammo spent" card is not available in Weblate: 
![image](https://user-images.githubusercontent.com/35796457/121488348-4b16cd00-c9d3-11eb-8138-885618493734.png)

If you add it, we can translate it :-)

**Comment by javierriveracastro** [comment]
This should be now (well in a couple of minutes) available in weblate.
