### ISSUE TITLE
Feature: Template on mouse courser if range is "SBT", "MBT", "LBT" or "Cone"

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#238]
_This would be a qol improvement but maybe not worth the effort. Feel free to close it as usual._

The idea is: When using a chat card for a weapon that has a range of `SBT`, `MBT`, `LBT` or `Cone`, automatically activate that template on the mouse cursor to be placed after the skill roll is made. This would need localisation I guess but would be a great qol improvement I think as it would alleviate the user from selecting the template in the left control bar.
Could potentially also be made as a world global action template to allow the user to disable it or enable it on certain weapons that do not have said range (i.e. grenades which have the throwing range there), filtered by name or part of the name.

**Comment by javierriveracastro** [comment]
Automatically placing a template would be a little obtrusive to me. But adding a button to place a template in the card is certanly a good idea. It could also be added to global actions.

**Comment by SalieriC** [comment]
My idea was not to place it down but stick it for placement on the mouse. Similar to what it is like when you click the control on the left. But a button would work as well I suppose.

**Comment by javierriveracastro** [comment]
It is one more step, but a little less intrusive.

**Comment by brunocalado** [comment]
Create a template is hard. I was trying using this pf2 macro:
[Criador de Template Feet.txt](https://github.com/javierriveracastro/betteroll-swade/files/6659449/Criador.de.Template.Feet.txt)

But, I failed.

**Comment by javierriveracastro** [comment]
Never tried.

**Comment by CyrilRonseaux** [comment]
Great idea. 
From attacks and powers please.

Next step would be to have color/texture on the template to match some keyword on the weapon or power from where we clicked :D

**Comment by SalieriC** [comment]
That sounds even more complicated. :D With a file path to the texture in question on the item it would be quite easy but this is possibly out of scope for BR2 but if BR2 would offer a way to hook into it I could do this on SWIM. Damn, that gets me excited. XD

**Comment by CyrilRonseaux** [comment]
Oh, and btw, Power Modifiers do mess up with Templates. Some powers are "single target" and become "Template", some like havoc offers two templates choices from scratch (cone and mbt) and a third one with PM (LBT).  _and epic/mega/amplifiers from SWPF, Rifts, or my Fantasy Addons add new PM with extra template options_. PAIN :D

**Comment by javierriveracastro** [comment]
This should be mostly done. I said mostly because non-ascii characters in description are not recognized and this will make finding templates in desciption in non-english languages messy.

BTW, did I said it looks for templates both in description and range and supports multiple templates?.
