### ISSUE TITLE
Italian translation: Parry is not used for fighting checks

### ISSUE THREAD

**Issue by zk-sn** [javierriveracastro/betteroll-swade#239]
When using BR2SW with SWADE Italian Translation, the Fighting skill is "Combattere" but when that is set as the "Parry Base Skill", BR2SW item cards don't use that as the target number - they just use default 4.

I looked into this and found that "combattere" is not included in the const FIGHTING_SKILLS in skill_card.js, so the check "is_skill_fighting" doesn't detect that it's fighting and doesn't use parry.

**Comment by zk-sn** [comment]
Pull request #240 created to address this issue

**Comment by javierriveracastro** [comment]
Nice pull request.
