### ISSUE TITLE
Pass final result to global actions

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#241]
Macros executed by world global actions currently have no way of getting the final result. The can get if the roll is a critical failure and the results of the individual dice but not the final result (`success`, `failure`, `raise`, and `x raises`).
Having this would be of great benefit for me.

**Comment by javierriveracastro** [comment]
It passes the tn and the dice results. But yes, it could be made more convenient.

**Comment by SalieriC** [comment]
Additionally, it would help immensely to also add targets to the BR2 messages flags.

**Comment by javierriveracastro** [comment]
This should be solved (by sheer chance), as the br_card object stores both targets, and results and is passed to macro.s
