### ISSUE TITLE
Add module setting for default rate of fire

### ISSUE THREAD

**Issue by zk-sn** [javierriveracastro/betteroll-swade#242]
Currently, when a weapon is rolled it automatically makes the roll with the max rate of fire of the weapon.  It would be nice to have a module setting that would allow you to change that to default to a single shot instead of the max rate of fire.

**Comment by SalieriC** [comment]
This has been discussed on #137. Please feel free to reopen it if you have can "add some other rationale to it."
As it is now, you can use either the weapons actions or the number of trait dice option to reduce the RoF which works fine imo. I'll close this ticket as won't fix however for being a duplicate.

**Comment by javierriveracastro** [comment]
The main difference is that this one has a merge request attached ;).

I'll look into it and likely merge it.

**Comment by javierriveracastro** [comment]
This was done in last version.
