### ISSUE TITLE
Wild Attack not showing on melee weapons in French

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#246]
Forget it. it just works. I'm just blind :D

**Comment by javierriveracastro** [comment]
Argggghhhh!!! Too slow!!!. I was going to assign it to the Franch translation maintainer (that is you).

It uses "BRSW.SkillName-figthing" key to identify the skill name.

**Comment by CyrilRonseaux** [comment]
:D 

When I read the bug again to make sure it was clear enough, I saw the screenshot and "Attaque totale" was clearly in!
So I made a few other tests and found out the character where I initiale had the issue was one where I did a typo in the skill name :(

shame on me.
