### ISSUE TITLE
Rerolls for non-wildcards drop ROF by 1 per reroll

### ISSUE THREAD

**Issue by zk-sn** [javierriveracastro/betteroll-swade#247]
If a non-wildcard makes a roll with more than 1 trait dice, such as a high-ROF weapon, a reroll of that roll will drop one of the trait die per reroll.  

https://user-images.githubusercontent.com/83551610/123122857-37b82880-d3fb-11eb-879f-bcf5b1873980.mp4

This is because the ROF calculation for the reroll functionality is set to subtract one die from what was rolled, assuming that one of the dice rolled was a wild die.  
```
cards_common.js:674
rof = render_data.trait_roll.rolls.length - 1;
```
That line should check if the actor is a wildcard, and only subtract 1 from the number of dice if so.  I will submit a merge request for this issue.

**Comment by javierriveracastro** [comment]
Thanks
