### ISSUE TITLE
Change Wounds colors for colorblind

### ISSUE THREAD

**Issue by Gorvaine** [javierriveracastro/betteroll-swade#254]
I give a sample of well differentiated colors.

From:
https://i.imgur.com/zZgYZx1.jpeg

To:
https://i.imgur.com/17kTIw8.jpeg

**Comment by javierriveracastro** [comment]
Gracias.

**Comment by javierriveracastro** [comment]
Right now colors change with the amount of wounds. I don't know if you will be able to differentiate the colors, but...:

![imaxe](https://user-images.githubusercontent.com/8113700/123811147-46b74300-d8f3-11eb-9d77-5b22c0c1353c.png)

Maybe it would be better just to use a transparent fill for the wounds (optional, of course)

**Comment by javierriveracastro** [comment]
This should be done
