### ISSUE TITLE
The Skill description of the main trait for a weapon is displayed instead of the one for the used skill

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#255]
When rolling on a weapon, the description of the weapons trait is always displayed, even if the Skill for the selected action difers from the main Skill, the heading however displays the correct Skill name.
![image](https://user-images.githubusercontent.com/1230041/124174983-4a8ec500-daad-11eb-88db-c729fe0b78f2.png)

**Comment by javierriveracastro** [comment]
Should be solved.
