### ISSUE TITLE
Global action macro execution doesn't seem to work with item type

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#256]
As mentioned in Discord, executing a macro with selector_type item and _value power doesn't seem to work. This .json will *not* work:

```
{
    "id": "whatever.id",
    "name": "whatever.name",
    "button_name": "whatever.button.name",
    "runSkillMacro": "whatever.macro",
    "selector_type": "item",
    "selector_value": "power",
    "defaultChecked": "on"
}
```

While this *does* work:
```
{
    "id": "whatever.id",
    "name": "whatever.name",
    "button_name": "whatever.button.name",
    "runSkillMacro": "whatever.macro",
    "selector_type": "skill",
    "selector_value": "spellcasting",
    "defaultChecked": "on"
}
```

This is a little inconvenient as it would mean you have to set up an individual global action for each skill you want to cover. It would be by far easier to be able to target all items of a certain type in many situations. It also seems to be a bug as it *should* work with all combinations.

**Comment by javierriveracastro** [comment]
You should use "item_type" for this to work.
This works fo me:
`{"id":"whatever.id","name":"SalieriCPower","button_name":"whatever.button.name","runSkillMacro":"whatever.macro","selector_type":"item_type","selector_value":"power","defaultChecked":"on"}
                `
