### ISSUE TITLE
Add other roll types to roll card.

### ISSUE THREAD

**Issue by sroakjp** [javierriveracastro/betteroll-swade#257]
Would it be possible to add options for the other roll types, such as Self Roll, GM Roll, and Blind GM Roll, to the roll cards?
We can make the roll private by right clicking, but I see no easy way to do the others other than by changing the default roll type, which is cumbersome.

**Comment by javierriveracastro** [comment]
Technically yes, but I feel that adding an UI element for this will make the card more complex for something that can be easy done with the default roll drag. It will also add some element duplication (two close UI elements doing the same thing).

TL/DR: It could be done, but I need a good UI idea.

**Comment by sroakjp** [comment]
Here is an idea, but no idea if it is feasible or not. Right now you can right-click on the card and show an option to make the roll private. What if, instead right click presented a drop down with each of the other options shown?

**Comment by javierriveracastro** [comment]
Will clean this as this is probably too dificult to do.
