### ISSUE TITLE
Shotgun Damage (1-3d6) is broken

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#258]
Due to the exception of Str 1 rolls the 1-3d6 damage rolls of Shotguns are non-functional atm (they roll 1 and subtract 3d6). Should instead get the range to the target and determine the damage based on it and the shotguns range bracket (1d6 on long, 2d6 on medium and 3d6 on short range) or default to 3d6 if no target is present.

**Comment by javierriveracastro** [comment]
1-3d6 is (in git version) rolled as 3d6. But official module shotguns have no damage not 1-3d6.

The range idea is nice, but harder to implement. I'll leave this issue open until them.

**Comment by javierriveracastro** [comment]
The bug aspect is solved, so changing it to enhacement.

**Comment by flynnkd** [comment]
Target/damage icons don't show properly for range groups. Buckshot-short has no icon - on mine at least.

**Comment by flynnkd** [comment]
![Shotguns damage](https://user-images.githubusercontent.com/74580085/164949127-cfef3dc6-1278-4ff2-956f-e5379a8bd354.png)
Shotgun-shot damage is using the target symbol, should be damage symbol, and not showing at all sometimes.

**Comment by javierriveracastro** [comment]
This should be solved except for when damage actions show target icon. This is an inconsistency in core data and should probably be solved there.
