### ISSUE TITLE
Expand Roll results automatically with setting

### ISSUE THREAD

**Issue by holgaph** [javierriveracastro/betteroll-swade#259]
It would be very helpful to have an option similar to "Expand Results", for dice rolls.

I have attached a file with the changes that should enable this functionality. Hopefully this can be incorporated. Thanks.
[BetterRolls2SWADE_v2.37_Modification-for-Roll-Expansion.txt](https://github.com/javierriveracastro/betteroll-swade/files/6804858/BetterRolls2SWADE_v2.37_Modification-for-Roll-Expansion.txt)

**Comment by javierriveracastro** [comment]
That's close to a patch. I'll use it for sure.

**Comment by javierriveracastro** [comment]
Works nicelly. It is already in git and will be in next version. Thanks a lot.
