### ISSUE TITLE
Joker is not adding +2 to rolls

### ISSUE THREAD

**Issue by deanopalooza** [javierriveracastro/betteroll-swade#263]
Tried on a fresh world no other modules other than SWADE, etc. etc.   Default system rolls are adding joker +2, but BRS2 won't register joker at all.   However, if you switch the true and false of code pasted below from cards_common, it will apply the joker to all combatants whether they have a joker or not, or whether or not a joker is even drawn.  It appears as though everything between joker = false and joker = true isn't testing for Joker condition properly.  Wondering out loud if this is related to issue #251 description of data structure changes?

(sorry if this is unclear, not well versed in JS)

/**
 * Returns true if a token has drawn a joker.
 * @param token_id
 * @return {boolean}
 */
export function has_joker(token_id) {
    let joker = false
    game.combat?.combatants.forEach(combatant => {
        if (combatant.tokenId === token_id) {
            const swade_value = combatant.flags?.swade?.cardValue || 0;
            if (swade_value >= 95) {
                joker = true
            }
        }
    });
    return joker;
}

**Comment by javierriveracastro** [comment]
That makes sense. But why was this working sometime?

**Comment by deanopalooza** [comment]
I'm sorry I can't offer more insights.   "Sometimes" for me has been never, so I can't look the differences.

Console does flag a bunch of "deprecated" messages and a couple of "asynchronous" if that helps.

![br2_joker](https://user-images.githubusercontent.com/87743097/126483528-b80690cd-5634-4d42-a0da-73a12381c49d.PNG)

**Comment by javierriveracastro** [comment]
No, those warnings are kinda normal, thank you any way. I'll try to take a look at it this afternoon.

**Comment by javierriveracastro** [comment]
This should be solved. But I'm not sure it is related to the sometimes joker is applied, sometimes not problem.
