### ISSUE TITLE
defaultChecked is not working well

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#266]
Hi.

If you set  **"defaultChecked":"off",** it'll start on.
![image](https://user-images.githubusercontent.com/4999783/126527844-2044e641-e9b9-4fc7-b9d9-7d40b1954a86.png)

```json
{
   "id":"GIANTKILLER",
   "name":"Giant Killer",
   "button_name":"Giant Killer",
   "defaultChecked":"off",
   "dmgMod":"+1d6x",
   "and_selector":[
      {
         "selector_type":"actor_has_edge",
         "selector_value":"Giant Killer"
      },
      {
         "selector_type":"item_type",
         "selector_value":"weapon"
      }
   ],
   "group": "Edges"
}
```

**Comment by javierriveracastro** [comment]
Yes. Any value of defaultChecked will make it start on. As the documentation say: 

> defaultChecked: If this key exist the action button will start pinned (marked in red)

**Comment by SalieriC** [comment]
I'll not reopen this although I'm tempted. This is somewhat counterintuitive and thus bad design as it confuses the user. This is because it can be set to on, off or razupaltuff, it'll always just be on. But I get that it might be more work than reward to _fix_ it.

**Comment by javierriveracastro** [comment]
It should be easy to check that the value is "on". But it can give the impression to users that "defaultChecked" is needed. As it is now it is clearly optional. But...
