### ISSUE TITLE
Feature: Have Damage rolls modified by minimum strength

### ISSUE THREAD

**Issue by TheLaslo** [javierriveracastro/betteroll-swade#277]
Swade rules have some weapons have a Min Strength requirement, if a PC doesn't have the strength then they don't gain the full benefit of the weapon.  i.e.  a Long Sword has a Min Strength of d8, if a PC only has a d6 in Strength then they roll 2d6 damage instead of 1d6 + 1d8.

**Comment by javierriveracastro** [comment]
Dividing:

- [x] Damage should be affected by minimun strengh
- [x] Ranged weapon attacks should also be affected.
- [x] Armor should affect all skill checks?
