### ISSUE TITLE
Skill rolls for extras

### ISSUE THREAD

**Issue by javierriveracastro** [javierriveracastro/betteroll-swade#28]
How?.

There is no skill images, nor an easy way to add them.
Create a new sheet?
Modify default rolls?

**Comment by SalieriC** [comment]
Middle mouse button to trigger the better roll maybe? Overriding the standard system behaviour would lead me to uninstalling the module.

**Comment by javierriveracastro** [comment]
I'm not keen to modify standard behavior too. This is why a I didn't do nothing with this ticket. If I ever do it will optional and defaulted to no.

But middle click or alt click are not discoverable and so they are also not good design.

BTW: If I do middle button my mac players will kill me. Although I believe that one of them has bought a mouse just for Foundry ;P

**Comment by javierriveracastro** [comment]
Done. I finally used some css tricks to add a small image before the skills and force then to one skill per line.

It's probably to dirty and going to came back to me in the future...
