### ISSUE TITLE
Group Names Stack

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#280]
Hi!

Could you make identical group names come together?

![image](https://user-images.githubusercontent.com/4999783/127687672-fba3708d-55e4-4dc5-85bc-6bf614dd19c6.png)

**Comment by javierriveracastro** [comment]
Use "BRSW.SituationalModifiers" for your custom group. System groups use translatable names, to enable, well translations.

It should probably need to be documented somewhere.

**Comment by brunocalado** [comment]
worked

But, I couldn't make this one:

**Called Shot**
```json
{
  "id": "CALLEDSHOTHAND",
  "name": "Called shot: Hand",
  "button_name": "Called shot: Hand",
  "skillMod": "-4",
  "dmgMod": "+4",
  "selector_type": "skill",
  "selector_value": "Shooting" , 
  "group": "BRSW.AttackOptions"  
}
```

![image](https://user-images.githubusercontent.com/4999783/128053405-62c33c66-7f95-4677-af2a-260ea25d0813.png)

**Comment by javierriveracastro** [comment]
BRSW.AttackOption it's probably my fault, it should be options.
