### ISSUE TITLE
Dead people should not provide gangup bonus

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#286]
In this fight, the tree-carrying ape (mister "Bras Droit") is attacking the Groot guy while having one of his minions adjacent to the Groot guy. However, the minion is dead (as shown in the tracker and as a status marker on the target). Dead characters can't grant Gangup bonus.

![image](https://user-images.githubusercontent.com/38113746/128188749-dc1bbf18-4d33-45d6-a29f-03926c85cb13.png)

**Comment by javierriveracastro** [comment]
Zombies beg to differ, but yes, it is a bug.

**Comment by javierriveracastro** [comment]
Should be solved.
