### ISSUE TITLE
Melee/thrown weapons should not benefic from gangup when used thrown

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#287]
I have a throwing axe. By default, it's melee using the "Fighting" skill. It has one action to replaces the skill with the Athletics skill.

When I attack from ranged using the "throwing" action, it still adds Gangup bonuses.
![image](https://user-images.githubusercontent.com/38113746/128190166-a410d75f-81bc-43b0-ba63-f3890884c7e4.png)

Here is the throwing axe settings:
![image](https://user-images.githubusercontent.com/38113746/128190249-6b174090-4b88-4a24-bc61-7b9a5ab42856.png)

And here is the throwing axe action:
![image](https://user-images.githubusercontent.com/38113746/128190444-04d88fa9-c6de-447f-9aa4-02616022ee96.png)

I have the feeling that gangup is always added if the main skill used for a weapon is the one set as "Skill used for Parry calculation" in SWADE system. And that ranged is considered only whenever it's not that skill. Sounds fair. However, in that case, the action is switching skills around, the gangup-adding-rule should take that into account.

Versions:
Foundry 0.8.8
SWADE 0.20.4
BR2SW 2.40 (also had it on 2.39)

**Comment by CyrilRonseaux** [comment]
Just in case, I tested to put the throwing skill as main skill and put the fighting skill on the action, gangup bonus is never added (which confirms that only the main skill is changed and the action skill is ignored)

**Comment by javierriveracastro** [comment]
This should be also be solved.
