### ISSUE TITLE
Wild Attack not showing up when renaming Fighting skill

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#288]
It looks like whether the "Wild Attack" action appear or not is directly linked to the Fighting skill (and how it's translated).

I made a oneshot in a prehistoric setting and to give the mood to the players I renamed the skills to something more "stupid" or "slang". Combat (French for Fighting) became "Castagner" (could be "punching").

I set up the SWADE system to use that "Castagner" skill instead of Fighting/Combat for Parry calculation and it works fine.
When I attack with a weapon set to use the "Castagner" skill, it doesn't show the Wild Attack ("attaque totale") option.

![image](https://user-images.githubusercontent.com/38113746/128192150-476b5836-b1bf-46ad-afb9-165feda7819c.png)

As you can see "Castagner" is d10, so the skill is configured correctly on the weapon.
But "attaque totale" does not show up.

However, the weapon is considered melee and gangup bonus does show up: 
![image](https://user-images.githubusercontent.com/38113746/128192351-9401077d-24b6-478f-9fb2-a0fb464cf4f3.png)

While I understand that renaming SWADE skills is an edge case, BR2 isn't homogeneous here.

If it's possible to link the "wild attack showing up" to the "weapon is used with the skill that is used for Parry" (like gangup does) it would also allow non-officially translated languages to work (as of today, "Combat" shows "Attaque totale" because I translated in Weblate and it's in the "code"').

(not a priority though, as a workaround I can recreate the action myself, it would probably not set up the Vulnerable state, but it's far from "not usable").

**Comment by javierriveracastro** [comment]
Wild attack is done using global actions, and they are much more limited than real code. With the current implementation it is not possible to do what you want. Basically wild attack is just this action:

```    
{id: "WTK", name: "Wild Attack", button_name: "BRSW.WildAttack",
        skillMod: 2, dmgMod: 2, dmgOverride: "",
        selector_type: "skill", selector_value: "fighting",
        self_add_status: "Vulnerable", group: "BRSW.AttackOption"},
```
As a workaround you can add your own action, I'll leave this issue open for a while, just in case I think about something else.

**Comment by CyrilRonseaux** [comment]
Hmm. Could add a selector "is melee attack" which checks for "the skill is the same as the one used for Parry calculation"?

Adding my own action will certainly work. Oh! I didn't know actions could add statuses. excellent!

**Comment by Razortide** [comment]
self_add_status does not work for me.

I simply replaced the fighting skill name:
{
   "id":"RA",
   "name":"Wild Attack",
   "button_name":"BRSW.WildAttack",
   "skillMod":2,
   "dmgMod":2,
   "dmgOverride":"",
   "selector_type":"skill",
   "selector_value":"Kämpfen",
   "self_add_status":"Vulnerable",
   "group":"BRSW.AttackOption"
}

**Comment by Razortide** [comment]
It works! Thank you!

**Comment by javierriveracastro** [comment]
I have finally reached the conclusion that adding a custom selector for this is probably a bad idea. It's only useful in some strange cases, that as Razortide said, can be addressed with custom actions.

Custom actions seem a better solution that adding to the code size.
