### ISSUE TITLE
Wounds penalty reduction makes Soaking rolls incorrect

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#289]
I have a character with Nerves of Steel and so I have configured that character to ignore one Wound penalty.

![image](https://user-images.githubusercontent.com/38113746/128193661-1aead6d7-a5a4-4d23-a94f-b8fd933b9dd1.png)

When any character is Wounded and has to Soak, the Wounds are applied to the character and a chat card is sent to propose a Soak roll. Since the Soak roll is supposed to happen before the Wounds are applied, BR2 adds a "reverse" bonus that should negate the Wound penalties that shouldn't be there yet.

Here in this example, I damage someone without Nerves of Steel, he receives 1 Wound, so has a -1 to that Vigor Soak roll, and the "remove Wound modifier" shows a +1. Which is perfect.

![image](https://user-images.githubusercontent.com/38113746/128193958-db9d6f8a-d076-4149-9296-8606d68e2c5f.png)

Now with Nerves of steel, the Wound penalty is smaller (in the screenshot below it's -2 instead of -3 from 3 Wounds) but the "remove Wound modifier" adds too much back (it's adding +3 instead of +2).

![image](https://user-images.githubusercontent.com/38113746/128195626-b93abd00-1f49-43e2-a38b-9819ed3bb2fd.png)

**Comment by javierriveracastro** [comment]
Should be solved.
