### ISSUE TITLE
Attack should be using "Unskilled" if actor does not possess the weapon's skill

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#290]
I created an actor that does not have the Fighting skill at all.
He is using a weapon set to use the Fighting skill.
When I roll the weapon to chat (from the quick access), it only shows the damage buttons. It should roll as if my skill is d4-2.

![image](https://user-images.githubusercontent.com/38113746/128197677-2648dab0-b044-49aa-afd7-243ea535b801.png)

Same behaviour with powers whose skill is not known by the actor (which usually happen when you failed to set your character correctly :D )

![image](https://user-images.githubusercontent.com/38113746/128197922-7ad096b3-935d-4c51-8be8-eff2bc1b0e78.png)

**Comment by javierriveracastro** [comment]
This is kinda solved. The actor needs to have an "untrained" skill or something similar (it tries quite a lot of possibilities and also a localized one). But it should now detect it better.
