### ISSUE TITLE
Enhancement: clicking the "talk-bubble" icon should use BR2 chat cards

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#291]
I find it confusing that my players can click something in their character sheet that roll the default SWADE system behaviour.
There is a configuration that let me roll the default behaviour with ctrl+click (or alt or shift).

I would prefer if, by default, everything is sent as BR2 cards.

So I'm suggesting that clicking the talk-bubble icons follow the same BR2 settings and behaviour than clicking the item label.

By "talk-bubble icon" I mean those: 

![image](https://user-images.githubusercontent.com/38113746/128199970-1a689b9b-febf-4324-ba95-d01e45da398a.png)

From the Quick Access, on a weapon, **observed** = I get BR2 when clicking on the label and default system on the talk-bubble. **wished** = both behave the same.

![image](https://user-images.githubusercontent.com/38113746/128200156-cf8329fd-9012-482f-8c5b-4968eaa24d37.png)

Same for powers from Quick Access:

![image](https://user-images.githubusercontent.com/38113746/128200276-7569dd6f-e9bf-4e0b-9e3d-652a0acbe1e5.png)

Same for armor from Quick Access: (to be honest that one isn't important, armors shouldn't even appear in Quick Access, they are useful there, but that's an issue for the system)

![image](https://user-images.githubusercontent.com/38113746/128200517-8f56e916-cd51-4c1c-ae53-8455a32479a8.png)

For Edges, Hindrances, and Abilities in the Edge & Hindrance tab, the current behaviour is reasonable. You usually don't want to send the edge description to chat. Label click unfolds silently in your character sheet, bubble sends to chat. **behaviour is fine, don't change it**

![image](https://user-images.githubusercontent.com/38113746/128200912-39ddd109-2339-4958-9871-6f24a0852ab5.png)

Weapons in the inventory tab has no "bubble". Clicking the label does correctly send to the chat as BR cards.

Powers in the Power tab, follows the "edge/hindrance" pattern, that is, clicking the power does silently unfold it in the character sheet (so that you can read your power peacefully). In that description panel, there is a "cast power" button, which correctly sends as a BR2 card. However, the talk-bubble uses the "system default" panel. Wish it would send BR2 panel.

![image](https://user-images.githubusercontent.com/38113746/128201489-da5b4d3b-5199-48f9-817e-29479a0cac81.png)

An alternative would be to link all "talk-bubble icons" to the same behavior as if clicking ALT+label. So users could even more customize how they wish their bubble click to behave and could still have the opportunity to make them behave different than clicking the label.

It's only a suggestion for enhancement. Nothing's blocked or broken. No urge either.

**Comment by javierriveracastro** [comment]
This should be done in git.
