### ISSUE TITLE
Adding to macrobar from the Inventory tab does not perform a BR2 card

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#292]
When drag&dropping a weapon from the Quick Access onto the macro bar is does correctly display the BR2 chat card and I can even use shift/alt/ctrl to control how much should be rolled by default. That's perfect.

![image](https://user-images.githubusercontent.com/38113746/128203375-92d0df2d-ad04-450d-9a56-9e9402958933.png)

However, if I try the same by sliding from the Inventory panel, **observed** = I get the default system behaviour. **expected** = BR2 chat card with detection of shift/alt/ctrl.

![image](https://user-images.githubusercontent.com/38113746/128203483-27fbcf3d-e156-46b0-af4b-baca684b0dd6.png)

**Comment by javierriveracastro** [comment]
Done.
