### ISSUE TITLE
Missing translation: Recharging PP using Soul Drain

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#293]
When using "manage PP" option on a power, and using "soul drain" to take Fatigue and recharge PP, it works fine, and a message is sent to chat:
![image](https://user-images.githubusercontent.com/38113746/128210546-249f8c4a-a525-4e85-8108-1c84b382d0a3.png)

However, that message isn't translated to French. Yet the French text is in Weblate.
Translation entry is missing (in weblate), I can't translate it :D

**Comment by SalieriC** [comment]
I hate every language other than English. Even my native language.
Ah well, fine, I'll take care of it.

**Comment by SalieriC** [comment]
done in git.
