### ISSUE TITLE
Enhancement: ability to add/remove to damage after damage has been rolled

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#294]
Right now, once damage is rolled, all I can do is add +1d6 (or change the toughness by picking from target).
![image](https://user-images.githubusercontent.com/38113746/128211546-16770a79-8950-4029-a799-483d2eb2e602.png)

If I realized I forgot to click "wild attack" or "the drop" or I forgot I had the Assassin Edge or similar edge that adds to damage, I can't add it afterwards.

Would it be possible to add a lovely (+) button, just like we have for the skill roll?

![image](https://user-images.githubusercontent.com/38113746/128211831-47084674-7f7a-4412-a708-c53fc6c6b761.png)

It would recalculate the outcome (shaken, number of wounds, etc.). Of course, there would be no use for changing damage once the "apply wounds" has been performed.

**Comment by javierriveracastro** [comment]
This is done in git.
