### ISSUE TITLE
Display for multi-location armor could be improved

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#296]
When sending an armor to chat, the location that armor covers is shown in the footer of the card.

When dealing with multi-location armors, all locations are packed without separator. A coma, pipe, or space could do the trick.

![image](https://user-images.githubusercontent.com/38113746/128215006-51758264-c84a-411b-8f04-7df7a83888e0.png)

**Comment by javierriveracastro** [comment]
Done.
