### ISSUE TITLE
Armor location should be translated

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#297]
When sending some armor to chat, the location is not translated.

![image](https://user-images.githubusercontent.com/38113746/128215147-4e4f0dc5-1140-42e7-8f38-37ba3bb9cc09.png)

They are translated on the default SWADE system's card, using the SWADE French module.

![image](https://user-images.githubusercontent.com/38113746/128215373-97148bee-100f-47d2-bd2f-450f10883782.png)

I don't know whether you can use the translation key from SWADE system, or if you need to add some specific to BR2.
If you need to add, I'll add the translations in weblate for French, no worry.

**Comment by javierriveracastro** [comment]
Also solved.
