### ISSUE TITLE
Add support for Bound status

### ISSUE THREAD

**Issue by CyrilRonseaux** [javierriveracastro/betteroll-swade#298]
**1/ Bound is Distracted**
When using a skill or attack or using a power while being Bound, you should be considered Distracted and so get -2 to your roll.
(while Bound means you can take no physical action, and so won't probably be able to attack, you could still roll Strength or Athletics to break free, or roll Spirit against fear or a skill such as Persuasion and maybe cast a power if your AB allows it, e.g. psionics in some settings)

If I ever check Bound & Entangled, or Bound & Distracted, I would only suffer -2 once (just like it works today with Entangled and Distracted).

![image](https://user-images.githubusercontent.com/38113746/128222773-4775881f-4879-4b6b-a386-0609735e08f6.png)

**2/ Bound is Vulnerable**

If a target is Bound, it is considered Vulnerable and so I should get a +2 to affect her.

![image](https://user-images.githubusercontent.com/38113746/128223024-428f6dc4-b4f6-4bda-99fd-e625e1f2f6a9.png)

**Comment by javierriveracastro** [comment]
The status bonus came from system. I have submited a patch to it to solve this. If they don't accept it (likely), I'd look into a better-rolls solution.

**Comment by bloy** [comment]
The system way to handle this means toggling Bound or Entangled as well as Distracted or Vulnerable to get the effects of those statuses. I think that SWADE tools attempts to automate this, but there might be edge cases that it over-automates.

**Comment by javierriveracastro** [comment]
No, if you click entangled the system will apply de -2 from distracted even when distracted is not set.

This is the merge request: https://gitlab.com/peginc/swade/-/merge_requests/186

**Comment by bloy** [comment]
huh. I will need to experiment with no modules loaded. I guess I'd always marked distracted and vulnerable as part of selecting bound. My bad.

**Comment by javierriveracastro** [comment]
You need then for bound. It is entangled what is currently supported, but not bound.

**Comment by javierriveracastro** [comment]
Flo accepted the merge request, this should happen in next system update.
