### ISSUE TITLE
Blind GM roll doesn't work.

### ISSUE THREAD

**Issue by MarkPearce** [javierriveracastro/betteroll-swade#300]
When a player chooses a Blind GM roll, the GM is shown the relevant skill card with a ROLL button. Then the GM must roll for a result.

This should instead automatically trigger a die roll on the GM client on the players behalf and show the result. (as it works without mod)

**Comment by javierriveracastro** [comment]
But then, the DM would not be able to click on mods. And blind rolls respect the key combo settings. By default CTRL+click should make a direct blind roll.

**Comment by MarkPearce** [comment]
preserving a sense of player agency is the key issue for me.  if the GM needs to add modifiers they can do so after the roll, by clicking add modifier. or changing the TN

**Comment by MarkPearce** [comment]
Almost closed.  You're right.  The direct blind roll does work.  and shows ??? on the card. BUT the Dice so nice animation of the dice still appear in the players view so they can look at those. (even with ghost dice checked, the player sees full render)

**Comment by javierriveracastro** [comment]
Should be solved now.
