### ISSUE TITLE
gang-up bonus should not include the 1st token. 

### ISSUE THREAD

**Issue by MarkPearce** [javierriveracastro/betteroll-swade#302]
The gang up bonus should not include the 1st token, ie. its always one higher than it should be.

currently in a 1-1 fight a character receives a +1 gang-up bonus. (it should be 0)

in a 2-1 the gang-up is currently +2 (should be +1)

etc...

**Comment by javierriveracastro** [comment]
It doesn't happen to me. Are you sure that 1) you are using last version 2) You have dispositions set.

If not, please try to make it reproducible. Try to record a video, or give instructions to reproduce it.

**Comment by MarkPearce** [comment]
weird I rebuilt the scene now can't reproduce... apologies for the false report,

**Comment by javierriveracastro** [comment]
It is probably not false, but something more was going on. It is a pitty that it can be found.
