### ISSUE TITLE
Tirada del daño

### ISSUE THREAD

**Issue by StormDarkwood** [javierriveracastro/betteroll-swade#303]
Se podría hacer que la tirada del daño apareciera después de confirmar que se golpea al objetivo?
Me pasa que mis jugadopres suelen tirar el daño antes de saber si dan pues ven los dados y es a lo primero que le dan.

Y por pedir... se podría hacer que saliera el daño simple o con el dado extra dependiendo de si se golpea con o sin aumento?

**Comment by javierriveracastro** [comment]
Es que a veces quieres tirar daño sin tirar a dar...

Pero supongo que se puede estudiar de forma opcional.

Sobre el daño, si usas la combinacion de teclas para que lo tire todo ya lo lanza con o sin aumento según toque.

**Comment by javierriveracastro** [comment]
Al final es bastante complicado de hacer y creo que aporta mucho, lo voy a cerrar excepto que alguien haga alguna sugerencia de como implementarlo fácilmente o me de una razón que me convenza para tomarme el curre.
