### ISSUE TITLE
Elan and No Mercy final result.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#304]
If you use a bennie to reroll with one of these edges they add +2 to the final result of the roll. Currently they only add to the reroll, but as far as I know you can choose either the original roll or the reroll and still benefit from the +2. Is there any way to adjust the first roll to include the +2 if you use a reroll, so you can see quickly if taking the first roll is a better option?

**Comment by SalieriC** [comment]
That is not true, both only apply to rerolls, as their description specifically states. You can use modifiers in the chat or [Global Actions](https://github.com/javierriveracastro/betteroll-swade/blob/version_2/docs/global_actions.md) to support such house rules.

**Comment by grendel111111** [comment]
Thank you I hadn't realized the wording had changed since Delux.
