### ISSUE TITLE
Attack rolls ignore attacker's size

### ISSUE THREAD

**Issue by purrie** [javierriveracastro/betteroll-swade#306]
Characters that have size different than 0 don't take their size into consideration for calculating size bonus or penalty for attack rolls. Only target's size is considered. The bonus or penalty should be relative to characters size rather than to size 0.

**Comment by javierriveracastro** [comment]
It does take the attacker size into account for sure. Can you put an example where this is happening?

**Comment by purrie** [comment]
![Size bug 1](https://user-images.githubusercontent.com/16594625/128670314-4d8740c1-f2de-4056-84ad-dda5e23dbe1f.png)
![Size bug 2](https://user-images.githubusercontent.com/16594625/128670316-dd40b86e-ebe1-48ac-89ae-5485bad64627.png)
![Size bug 3](https://user-images.githubusercontent.com/16594625/128670319-cf428bcd-6c68-4fcd-9011-13c104d8c572.png)
![Size bug 4](https://user-images.githubusercontent.com/16594625/128670321-16c36c06-426f-41fa-a89e-77a71aae34a1.png)
As you can see, in 3 of those examples, size bonus or penalty is completely ignored while in fourth, the turret(size-2) attacking a character(size-1) is given a wrong bonus.

**Comment by javierriveracastro** [comment]
Sorry, but to me all the examples are correct. In all examples the expected bonus is 0 (they are all the same scale). The turret attacking a -1 character +2 bonus also looks right to me.

You should probably read again the rules on size and scale, and look at table in page 179 of the rulebook. If you still don't agree with me, we should move this a place for rules discussion or ask for a comment from PEG.

I'm closing this as the module is working according to specification (if the specification is wrong then it is another problem).
