### ISSUE TITLE
Size and Scale rules

### ISSUE THREAD

**Issue by purrie** [javierriveracastro/betteroll-swade#307]
In relation to https://github.com/javierriveracastro/betteroll-swade/issues/306
![size bug 5](https://user-images.githubusercontent.com/16594625/128676891-f1579638-70df-447c-b665-55b65446f35f.png)
Am I blind or something? The rules clearly state that the penalty or bonus is relative between characters' sizes. The table on page 179 just shows size table for available sizes and bonus or penalty to toughness they give. The rules on that page, and in that chapter in general don't make any direct mention to size and scale rules when it comes to attack bonus or penalty. The actual rules are on page 106 which point to that table for reference to what sizes there are in the game. If there is any other rule that I'm missing, please point me to it because I've scanned the rulebook back to back before deciding to write about the issue here and found nothing else.

**Comment by javierriveracastro** [comment]
Scale is not the same as size. A size 1 and a size 0 character are both normal scale.

A -2 size turret is small scale, so it gets a +2 when shooting a -1 (normal scale) character.

Check the Size table for the scale-sizes equivalence. 

You can continue to comment in the closed issue, please don't spam new duplicates issues.

**Comment by purrie** [comment]
I didn't know that you can comment on closed issues, I saw the comment button grayed out and assumed. Sorry about that. 

I see what you mean now. The example creatures suggested it work as I thought it did, since the math still checked out if you assume size, yet I didn't realize until now that there are no -6 size creatures. (I'm coming fresh from GURPS where there's no such distinction and I guess the assumption carried over) Sorry and thank you for pointing that out, and for your great work in general.
