### ISSUE TITLE
Add support for minor and major hindrances with the same name.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#308]
Currently you can only attach a hindrance with the name even if it can be at 2 levels, eg. Bad Eyes. Maybe a selector for hindrance is major?

**Comment by javierriveracastro** [comment]
actor_has_major_hindrance and target_has_major_hindrance added.

**Comment by grendel111111** [comment]
Just checking, the has hindrance will still fire when major hindrance goes too?

**Comment by javierriveracastro** [comment]
Oh sh... of course it does... it needs some and_selector or maybe I need to make an actor_has_minor_hindrance selector...

**Comment by grendel111111** [comment]
It's easy enough to do. You add a not if actor has major hindrance to the normal hindrance.

**Comment by javierriveracastro** [comment]
Yes, but it is somewhat stupid needing the and, an actor_has_minor_hindrance should be less work and will result in clearer actions.
