### ISSUE TITLE
Try to use a different color dice in dice so nice for the wild die

### ISSUE THREAD

**Issue by javierriveracastro** [javierriveracastro/betteroll-swade#31]

**Comment by javierriveracastro** [comment]
Looks to me that Dice so Nice doesn't support it yet.

**Comment by kristianserrano** [comment]
Supposedly this might be possible in Foundry v0.7

**Comment by javierriveracastro** [comment]
It will need both Foundry 0.7 and the new alpha version of Dice so Nice. And of course we need that base SWADE system supports 0.7. So this is going to take some time.

**Comment by javierriveracastro** [comment]
More than two months later.... done!!!
