### ISSUE TITLE
Create target selectors

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#311]
Can you add target selectors?

```
target_has_edge: The same, this time it will look for an edge that contains that string.
target_has_hindrance: Like the last two, but for hindrances.
```

**Wing Chun: Wing Chun focuses on fast blocks and flexibility against attacks, like bamboo before a storm. This gives the warrior +1 Parry and subtracts 2 from any melee damage she takes while using this style.**
You could detect Wing Chun and remove 2 from melee.

**Comment by javierriveracastro** [comment]
Added to the list.

**Comment by Razortide** [comment]
Yes please! That would be amazing!

**Comment by javierriveracastro** [comment]
Should be done in git
