### ISSUE TITLE
Distance don't work well if you change grid scale

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#312]
Hi.

The distance work well in you set the grid like this
![image](https://user-images.githubusercontent.com/4999783/130299603-236ec9d9-39a6-47ea-89f7-5c51442f3ca2.png)

But, if you change to a different number, it don't work well:
![image](https://user-images.githubusercontent.com/4999783/130299635-710ae1f9-8d82-4c80-92ef-ea4a9f9dd553.png)

![image](https://user-images.githubusercontent.com/4999783/130299533-8de3888c-9208-4ed4-852f-d918fbf12a48.png)

**Comment by javierriveracastro** [comment]
That's expected behavior. Better rolls counts "squares" not units. The main reason is making all this 5 feet per square maps available for d&d usable.

Maybe I can add a check or something to setttings

**Comment by brunocalado** [comment]
> That's expected behavior. Better rolls counts "squares" not units. The main reason is making all this 5 feet per square maps available for d&d usable.
> 
> Maybe I can add a check or something to setttings

I created a macro to change 5 feet maps to 1'' in. 

Some maps can be 2'' or more. So, you can use the range mecanics. The maps usually are so small for 1'' that you can't have a battle where range matters

**Comment by javierriveracastro** [comment]
The problem changing 5 feet maps to 1 is that lightning is usually messed.

Also most people just don't realize that they are using 5 feets per square maps and that Savage World ranges are in inches.

So, while I agree that an option for power users can be useful, I still believe that default behavior just works for most users.

**Comment by brunocalado** [comment]
My macro patches the light

**Comment by brunocalado** [comment]
![image](https://user-images.githubusercontent.com/4999783/130466048-0fb9e9f1-a475-4f46-a947-10df419fc8d2.png)

**Comment by javierriveracastro** [comment]
That's really nice.

**Comment by javierriveracastro** [comment]
Ok, I take a middle way approach.

Now when grid scale is a multiple of five it will treat it as 1 inch per 5 feet square. It it is not it will treat each unit as 1 inch. That way (I hope) we can both keep our cake.
