### ISSUE TITLE
Reduce Better2 Screen Space 1

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#314]
Hi.

Is it possible to replace the text in the modifiers for a image or maybe a smaller text? Translated can get messy....
![image](https://user-images.githubusercontent.com/4999783/130624273-89bbb24b-519a-42af-9a78-628fd7b3f0dc.png)

Example:
![image](https://user-images.githubusercontent.com/4999783/130625021-3daf3ecd-554f-4a1d-9440-4f1e2d005081.png)

**Comment by brunocalado** [comment]
The best option is an image. It'll align everything.

**Comment by brunocalado** [comment]
Examples
Trait: https://game-icons.net/1x1/delapouite/round-star.html
Dice Icon: https://game-icons.net/1x1/lorc/cubes.html
Damage Icon: https://game-icons.net/1x1/lorc/bleeding-heart.html

**Comment by SalieriC** [comment]
I don't think an image would be a good option here. Makes it harder for newcomers to get what they mean and even veterans could be confused. Maybe shorter translations are key here. Surely they can be made shorter?

**Comment by brunocalado** [comment]
> I don't think an image would be a good option here. Makes it harder for newcomers to get what they mean and even veterans could be confused. Maybe shorter translations are key here. Surely they can be made shorter?

Making translation shorter would fall in problem you mention for newcomers.

From my experience, you can write a huge text, the players still ask: "how do I use this button".

Use an image would make the layout better. You can add a tool tip with a long description.

**Comment by brunocalado** [comment]
Any news?

**Comment by javierriveracastro** [comment]
Nothing done, but I'm thinking about moving it (the full window) to the bottom of the combat tracker or next to the macro hotbar.

Regaining chat space seems a sensible thing to do, given than cards are groing

**Comment by javierriveracastro** [comment]
Ok, that combat tracker idea was a really awful one.

Either move it out of the right bar (but then it will take map space, and that is premium), the image thing (maybe optional), or I don't know what to do.

**Comment by javierriveracastro** [comment]
I thing I found a compromise. I have enabled HTML in the translations strings in that box, so you can now do this:

![imaxe](https://user-images.githubusercontent.com/8113700/143900820-298cc387-0976-4c63-bf76-db2fa9546f75.png)

Using with this translation string:

```json
    "BRSW.Wounds": "Ferimentos",
    "BRSW.ChatFormTittle": "Modificadores para o Better Rolls",
    "BRSW.TraitModifier": "<i class='fas fa-star' title='Modificador de rolagem de caracteristica'></i>",
    "BRSW.ManualAmmo": "Recarregar/Munição Manual",
    "BRSW.OldRoll": "Rolagens antigas",
```

You use an img tag, or anything that you wish if you prefer

**Comment by javierriveracastro** [comment]
If this is enough I will close this and commit the change to the code (but not to translations).

**Comment by brunocalado** [comment]
Good solution.

**Comment by brunocalado** [comment]
Thank you
