### ISSUE TITLE
Global Actions are not translated

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#316]
Hey Javier,

I just found that translations are not applied everywhere: The preconfigured global actions are translated on the button, but on the table they are not. Would it be possible to apply the translation there as well?

![image](https://user-images.githubusercontent.com/35796457/131145000-1da26fd6-55de-4763-9019-bcfcb54a704c.png)

**Comment by javierriveracastro** [comment]
This should be, finally, solved in git.
