### ISSUE TITLE
Compact mode, default optional modifiers to closed

### ISSUE THREAD

**Issue by MarkPearce** [javierriveracastro/betteroll-swade#321]
Feature request: default the situational modifiers to "collapsed" (or provide a setting toggle for that option) 

I've been looking through the scripts trying to see where the collapsible flag is set on the skill cards. I'd edit my local version if I can figure out where thats set... any hints?

![smallerDefault](https://user-images.githubusercontent.com/6976378/134785685-f0516c35-d1d9-455e-b40c-d97e169371c5.jpg)

**Comment by javierriveracastro** [comment]
Yes, right now you can't make then collapsed by default. They will be collapsed if you make an auto-roll (either skill or damage).

It is set in the creation of the card, when the card is created from the character sheet, in line 179 of item_card.js:

```js
    const collapse_actions = action.includes('trait') || action.includes('damage');
    // Show card
    let message = await create_item_card(target, item_id, collapse_actions);
```

It checks if the "action" or click type includes trait or damage and collapses the card if it does.

**Comment by javierriveracastro** [comment]
Done in git. Now there is a new setting to collapse cards by default.

BTW, this is a great idea, I'm going to test it in a game ASAP.
