### ISSUE TITLE
Don't have edge/hinderance

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#324]
IN BR2 You can use actor_has_edge to add a button if the actor has an edge. 
Is it possible to make an option like actor_doesnt_edge as a selector?
So if you have 2 global effects:
1. and selector, actor has fame, actor doesn't have famous. (+1 persuasion)
2. and selector, actor has famous. (+2 persuasion)
( this will mean the fame button won't appear if the character has fame and famous.)
useful for attractive, martial artist/warrior, sweep/improved sweep, and different levels of hinderance

**Comment by javierriveracastro** [comment]
It would be much more flexible to make a negation selector, similar to and and or...

**Comment by javierriveracastro** [comment]
The not_selector is done in git and should appear in next version.
