### ISSUE TITLE
Gatling Shotgun does not reload

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#325]
Hey Javier, funny issue:

When I fire a Gatling Shotgun, it fires as expected. If I click then the reload button and enter any amount, it confirms that is has been reloaded, but it's not. The log does not show any issues except the output in the attachment which looks ok to me. Any ideas?
[foundry.-1633381584712.log](https://github.com/javierriveracastro/betteroll-swade/files/7281313/foundry.-1633381584712.log)

**Comment by javierriveracastro** [comment]
No idea, and not eniugh info :(. Where is it Gatilng Shotgun from?. Core rules, some module, custom?

**Comment by Razortide** [comment]
It is coming from the Deadlands module it is not working out of the box.

**Comment by javierriveracastro** [comment]
I don't own that (not planning to buy it at that price), can you make a json export of the item?. I hope that it is a part small of the module that it can't be considered copyright infringement.

**Comment by Razortide** [comment]
[gatling-shotgun.txt](https://github.com/javierriveracastro/betteroll-swade/files/7284493/gatling-shotgun.txt)
As always, thank you for your guidance!

**Comment by javierriveracastro** [comment]
It is working for me. Do you have "Shotgun shells" with quantity 0?.

If that happens it will not reload, not broke with any error, and give you that message.

And this is a bug, it should inform players of why it hasn't reloaded the weapon.

**Comment by Razortide** [comment]
Nice stuff! Yes, that has been the issue!

**Comment by SalieriC** [comment]
Will check it out to add a notification when out of ammunition.

**Comment by SalieriC** [comment]
Should be fixed in Git now. I've added a new localisation string for it that notifies of missing ammo.
