### ISSUE TITLE
Under Minimum Strength gives bonus, not penalty

### ISSUE THREAD

**Issue by michaeldougherty76** [javierriveracastro/betteroll-swade#331]
Hey,
Unless i'm reading/interpreting the screen wrong, it looks like the Under Minimum Strength build-in modifier gives a bonus, not a penalty:
![image](https://user-images.githubusercontent.com/47453887/138560066-60c1740b-e939-491e-9f9b-82b60fae3686.png)

**Comment by javierriveracastro** [comment]
Errr.... that's true.

Solved in git, next version will carry the fix.
