### ISSUE TITLE
Adding stead hands to unstable platform

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#334]
You could add the edge Steady hands to the unsteady platform by using a not_selector.
{"id":"UNSTABLEPLATFORM",
"name":"Unstable Platform",
"button_name":"Unstable Platform",
"skillMod":"-2",
"and_selector":[{
"or_selector":[
{"selector_type":"skill","selector_value":"Shooting"},
{"selector_type":"skill","selector_value":"Athletics"}]},
{"not_selector":[
{"selector_type":"actor_has_edge",
"selector_value":"Steady Hands"}]}],
"group":"BRSW.SituationalModifiers"}

**Comment by javierriveracastro** [comment]
Sure, and BTW can I add (not today) all the actions that you have shared on the discord channel?

**Comment by grendel111111** [comment]
Yes no problem. The addition of nesting and the not option has been fantastic. Thank you.

**Comment by javierriveracastro** [comment]
Done (this bug, not added all the 47 pages of actions).
