### ISSUE TITLE
Joker question.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#335]
Is there a way to select for a character having a joker? I have tried "selector_type":"actor_has_effect","selector_value":"has_joker", among other things with no luck? Is it a detectable effect?

**Comment by javierriveracastro** [comment]
No AFAIK, but it should be doable.

**Comment by grendel111111** [comment]
Thanks. One more, can you modify damage by multiplying rather than add/subtract?

**Comment by javierriveracastro** [comment]
Sure, but open another issue, and remember that at the current speed it will take something like two months.

**Comment by grendel111111** [comment]
Ok Thanks. Speed is not an issue.

**Comment by javierriveracastro** [comment]
actor_has_joker selector added
