### ISSUE TITLE
modify damage by multiplying or dividing.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#336]
There are a few edges that multiply damage (Not a common occurrence so not a high priority). The option would be helpful for Deadshot, Mighty Blow, vulnerabilities and Grenades.

**Comment by javierriveracastro** [comment]
Done.

**Comment by grendel111111** [comment]
Not sure if I am doing wrong, but I can't get multiplyDamMod to work. It says unknown key:
![image](https://user-images.githubusercontent.com/80164119/192141881-676824db-1b9c-4b4f-b7e3-01dc22f5820f.png)

**Comment by javierriveracastro** [comment]
Could it be that you are on an old version?.

**Comment by grendel111111** [comment]
Sorry you are right. Forge hasn't updated to latest version.
