### ISSUE TITLE
Minimum Strength.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#340]
Minimum Strength. is currently made up of the armor and the weapon you are using and both create a modifier "BRSW.NotEnoughStrength". This is fine if you only have 1 effect created. If both the armor and weapon are under minimum strength it gets created twice so second effect will over ride the first. The result is that only the weapon strength minimum will be applied.
![image](https://user-images.githubusercontent.com/80164119/140524111-995d4423-be63-4c88-8f02-d34cfda79e88.png)
So even though -3 should be applied here only -1 (the second time the modifier is created) takes effect. 

Also (and I don't know if this is possible) the minimum strength is calculated from the characters Strength attribute. If instead it was done from data.attributes.strength.encumbranceSteps then when you change it for the edges of Brawny and Soldier it will calculate into the effect.

**Comment by javierriveracastro** [comment]
I'd try to solve both.

**Comment by javierriveracastro** [comment]
Should be done in git.
