### ISSUE TITLE
Add a power point modifier.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#341]
Adding a power point modifier would allow making buttons that add power points and do another action (run a macro that makes the character glow/ add damage etc.)

**Comment by javierriveracastro** [comment]
The macro thing should be doable now, see "runSkillMacro" or "runDamageMacro". SWIM from SalieriC makes intensive use of it.

**Comment by SalieriC** [comment]
Correct. With Sequencer for example it also shouldn't be a problem to apply vfx using a macro.
But I think this is more about altering PP. *I* would suggest using the "Shots" as a total PP number, then it would be a breeze to set up all the power modifiers as actions which use different PP.

**Comment by javierriveracastro** [comment]
But shots is already used to change the number of dice thrown. I'd probably need to add another modifier.

**Comment by SalieriC** [comment]
I must've been unclear. I meant this:
![image](https://user-images.githubusercontent.com/1230041/140773372-3c4c437a-b863-4ee8-a9ea-d52d3f0fd25f.png)

**Comment by javierriveracastro** [comment]
Ahhhhhh!!!!. Great idea, not the most easy to use, but really useful.

**Comment by javierriveracastro** [comment]
I have implemented SalieriC idea. Now shotsUsed, either in the action tab or in a global action also affects PP expended (if the object is a powe).

This should probably be well documented somewhere.

**Comment by SalieriC** [comment]
I can document it.

**Comment by SalieriC** [comment]
Now documented here: https://github.com/javierriveracastro/betteroll-swade/blob/version_2/docs/card_types.md#modifiers-altering-power-points-to-be-spent

**Comment by steveculshaw** [comment]
> Now documented here: https://github.com/javierriveracastro/betteroll-swade/blob/version_2/docs/card_types.md#modifiers-altering-power-points-to-be-spent

That link seems to be broken :-(

**Comment by javierriveracastro** [comment]
Yes, documentation has been moved to a wiki:

https://github.com/javierriveracastro/betteroll-swade/wiki
