### ISSUE TITLE
Arcane Device Support for BR2

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#343]
When [Arcane Devices](https://gitlab.com/peginc/swade/-/issues/134) are released to the SWADE system there is likely some work to do to support them fully by BR2. At the very least, Power Points need to be deducted from the item instead of the actor.

**Comment by javierriveracastro** [comment]
Well, I have no idea about how to do this.

Right now, the best I can think of is showing the powers somewhere in the card, clicking then will then open another card (the power card somehow linked to the arcane device skill and arcane device power points).

**Comment by SalieriC** [comment]
This is sensible I suppose. Rolling from an arcane device itself could also be done similar to the way it is done on NPC sheets (by clicking on the power itself, which does nothing in the system as of yet).

**Comment by javierriveracastro** [comment]
As it doesn't knew nothing about the caster (not even the skill name) it will be very limited, but at least it could be something.

**Comment by SalieriC** [comment]
The actor should be stored in `data.parent` of the item the power is in. The Skill is another story, but that's not defined by the system anyway.

**Comment by loofou** [comment]
Until the Arcane Device support is added to BR2, can we have a workaround/fix to call the native card of the item? Right now, when I set the native card in the settings to any key combination (like Ctrl+Click), it simply expands the item or does nothing. I have to test it again in detail, but I think it expands the items in the sheet in the PC sheet, but does nothing in the NPC sheet. If I disable BR2, then the native card is shown on a click.

**Comment by javierriveracastro** [comment]
I will need to test this. If ti does indeed happens it is a bug.

**Comment by javierriveracastro** [comment]
Ummm... it works like system to me. Clicking on the item expands it, clickling on the eye or message icon sends the card to the chat. Unless I'm missing something.

**Comment by grendel111111** [comment]
I think what loofou is referring to is when you click on the icon on an Item it will send a skill card to the chat so you can roll based on the skill set in the action and effects tab. The same item on an NPC gives an icon in the chat which opens the item instead of setting up a roll card.
![image](https://user-images.githubusercontent.com/80164119/152012912-44ed534f-f6b7-4540-a622-41dfb52d031b.png)

**Comment by loofou** [comment]
Yeah this is kind of what I meant. I think I also misinterpreted the eye icon and some features. Seems an npc can't use an Arcane Device at all even with the system card. The Arcane Device card simply never appears. Instead it asks for a skill and just provides the "Shooting / Damage / Throw" dialog instead. I also think there was some changes there to the latest v9 version of the SWADE system, so I think I'm confusing some features right now and I'm sorry for that. I'm pretty sure there was a chatcard at some point, but I can't manage to get it to appear even with BR2 disabled in the latest SWADE system version...

Still it would be great if Arcane Devices would be possible to use in any way at all for PCs and NPCs. If a work-around exists, please let me know.

**Comment by SalieriC** [comment]
Moved it to #222 for some cleaning up of the issue list.
