### ISSUE TITLE
BR2 doesn't get the proper custom dice for damage rolls.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#344]
It uses completely black dice instead:
![image](https://user-images.githubusercontent.com/1230041/141849537-86bc4a56-e74a-4889-9f18-e2e5b9b96216.png)

**Comment by javierriveracastro** [comment]
Works for me. Any error in the console?

**Comment by SalieriC** [comment]
None.

**Comment by javierriveracastro** [comment]
Have you tried to change the theme?. Maybe it is a problem with one in particular.

**Comment by SalieriC** [comment]
I have the same issue on other worlds as well. Also, the setting seems to affect all worlds but it should only affect the current world, shouldn't it?

**Comment by javierriveracastro** [comment]
The setting is per player. That means that it is stored in the browser (ask Artropos), and it will affect all worlds run from this browser.

And now that I think about it try clearing browser cookies and site data.

**Comment by javierriveracastro** [comment]
I will close it unless someone else confirms its.

**Comment by SalieriC** [comment]
Yeah, I don't know as well. I've tried in another browser and with cookies and site data cleared but it persists. I am using customWildDie for now. Maybe I'll find more information later.
