### ISSUE TITLE
Target has ability or effect.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#349]
The new target has options are great but a lot of the monsters have their abilities as special abilities. Also being able to do target has effect means we could base off things like prone or glowing to adjust to hit.

**Comment by javierriveracastro** [comment]
Both should be easy to add, but it is also a good point to try to refactor the action processing function.

**Comment by javierriveracastro** [comment]
At the end I left the refactoring for a better day. Done.
