### ISSUE TITLE
Hardy Revisited.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#350]
With the official modules coming out all having hardy as a special ability, and we can now refer to abilities in actors, could we change the hardy reference in the damage card line 112 to ability. It would mean we would need to change the edge to an ability, but other wise we will have to change the ability to edge every time a new adventure or source book is released.

**Comment by javierriveracastro** [comment]
Why choose, it is easy enough to support both. Already done in git

**Comment by grendel111111** [comment]
Thank you.
