### ISSUE TITLE
Automation Switch

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#352]
Hi.

Can you add settings to turn off some automation?

Disable Gang Up calculation. 

I saw the gang up calculation mess up lots of times. I would prefer to turn this off.

**Comment by javierriveracastro** [comment]
Sure, but it will be quite interesting seeing some examples of when it does mess up to improve it. 

But this would be totally not related to the switch.

**Comment by javierriveracastro** [comment]
Done, but I still would like to see when and how it does mess up gang up.

**Comment by SalieriC** [comment]
Ganging up is a tricky thing, which I have said on many occasions, for example [here](https://github.com/SalieriC/SWADE-Immersive-Macros/issues/22#issuecomment-849723289).
There are many variables to consider, here are just a few:

- Did the token make an attack already?
- Does the token wield a melee weapon?
- Is the token Prone, Entangled, Stunned, etc.?
- How are friendly tokens and foes positioned?

I doubt that BR2 can factor all the variables in, although I'd love it to do as I hate calculating the gang up bonus.

**Comment by brunocalado** [comment]
> Ganging up is a tricky thing, which I have said on many occasions, for example [here](https://github.com/SalieriC/SWADE-Immersive-Macros/issues/22#issuecomment-849723289). There are many variables to consider, here are just a few:
> 
> * Did the token make an attack already?
> * Does the token wield a melee weapon?
> * Is the token Prone, Entangled, Stunned, etc.?
> * How are friendly tokens and foes positioned?
> 
> I doubt that BR2 can factor all the variables in, although I'd love it to do as I hate calculating the gang up bonus.

Fantasy Grounds can do gang up. It's a matter of time to find out how to solve all the problems.

- Did the token make an attack already? **This don't really matter. You can ignore this case. Just delete the bonus.**
- Does the token wield a melee weapon? **Just ignore**
- Is the token Prone, Entangled, Stunned, etc.? **The first macro could do that. It's a very simple problem.**
- How are friendly tokens and foes positioned? **The first macro could do that.**

The gang up calculation is very useful without need to look for every single case. It should just handle the main case.

**Comment by SalieriC** [comment]
And yet you fail to answer Javiers question.

**Comment by brunocalado** [comment]
> And yet you fail to answer Javiers question.

I finished my game. When I start the next game I'll answer and provide a demonstration. It failed position detection.

**Comment by javierriveracastro** [comment]
Ummm.... By RAW it doesn't matter if the foes have already attacked, are wielding melee weapons, nor if they are prone or entangled. They just need to be there and not be stunned.

Position detection is difficult in foundry, specially if you are playing gridless. But is likely solvable.

Now, I fear that most people is not playing using RAW for gang up, but making their own rulings, as the official rules are confusing and somewhat stupid (does really a prone disarmed foe help?), so the ability to disable them is really useful.

**Comment by javierriveracastro** [comment]
And BTW, Fantasy Ground just doesn't calculate gang up on gridless maps.
