### ISSUE TITLE
 collapse cards in Token Action HUD?

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#355]
collapse cards by default is working great. but it doesn't work if it an action is sent from Token Action HUD. Is that something that would need to be done in HUD or the BR2?

**Comment by javierriveracastro** [comment]
Most likely HUD, but I have no idea of how does it work.

**Comment by javierriveracastro** [comment]
This is likely solved. I mean likely because I didn't test it with action HUD, but the public methods that it uses now respect the collapsed_card settings.

But for attributes, that right now don't know about that setting, but this is another problem.
