### ISSUE TITLE
Using ROF to increase the trait dice rolled on non weapon skills..

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#356]
I'm not sure if my action is written correctly, but when I use ROF to increase the number of shots in a gun there is no problem and the trait dice roll correctly. (this might be that ROF is also tied to ammo, but that is just a guess)

This should give 2 trait dice and a wild die but it doesn't:
{"id":"Work the room",
"name":"Work the room",
"button_name":"Work the Room",
"rof":"2",
"and_selector":[
{"selector_type":"actor_has_edge",
"selector_value":"Work The Room"},
{"or_selector":[
{"selector_type":"skill","selector_value":"Performance"},
{"selector_type":"skill","selector_value":"Persuasion"}]}],
"group":"BRSW.Edges"}

**Comment by javierriveracastro** [comment]
You are right, rof is only checked on item rolls. I'd take a look at it.

**Comment by javierriveracastro** [comment]
Done.
