### ISSUE TITLE
Shots Used should be additional not absolute

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#357]
As of now the option `Shots Used` is the absolute number of power points, preventing the user from using multiple modifiers set up as actions on the power. It would be better to use them as modifiers to the pp cost set up on the power I think. Trouble is that the field is a number not a string so it can't be easily done using `+` or `-` but we gotta deal with what we have and this is probably the best option.

**Comment by SalieriC** [comment]
I've pushed something to add pp instead of overwriting them but it currently doesn't add used shots if multiple actions are selected. I'm running out of time so this has to wait. As of yet I didn't found how this can be done anyway.

**Comment by grendel111111** [comment]
I also was hoping for the PP modifier. My temp solution was to make PP over ride buttons. When you use a power it put 10 buttons in the  chat that over ride the PP cost (So if you used bolt (1) added glow (1) and extra range (1) you select the 3PP button. 
![image](https://user-images.githubusercontent.com/80164119/144575699-ecc100c7-70cc-431a-b657-00fc1022b62f.png)
I'll use this till it changes to a PP modifier.

**Comment by javierriveracastro** [comment]
That's a neat idea, but an awful implementation. 

This will break all user created global actions that currently use Shots_used. 

I believe that the right way of doing this is to make a new option, something like "pp_modifier" or "shots_used_modifier".

**Comment by grendel111111** [comment]
I agree. It was the only way I could work around  using it as a flat number.

**Comment by grendel111111** [comment]
> That's a neat idea, but an awful implementation.
> 
> This will break all user created global actions that currently use Shots_used.
> 
> I believe that the right way of doing this is to make a new option, something like "pp_modifier" or "shots_used_modifier".

Sorry I'm a little confused. Why it is awful implementation? What did I miss? As far as I know there are no powers that currently interact with shots used which is why PP were attached to it.

**Comment by javierriveracastro** [comment]
Sorry, not yours, the implementation idea of SalieriC. It was awful because it would break all the global actions using "shots_used" that any user out there is using (including yours),

But the idea to have various actions that add together to the PP spent is quite good and should be done someway.

**Comment by SalieriC** [comment]
Just to be clear: I'm talking item actions (provided by the system) here, not global actions (provided by BR2). I may have broken something with global actions without realising it, but then that can be fixed.

**Comment by javierriveracastro** [comment]
Betterrolls uses when possible the same code for item and global actions. Keep code simple and all of that. So if an option is both an item action and a global action they work the same, modifying one will modify the other.

And changing this is probably going to be lot of work.

**Comment by javierriveracastro** [comment]
I've been thinking about this. Is adding something to the action name too cryptic?

I mean something like if the action name includes "(additive shots)" in its name, then shots will be treated as an addition instead of a override number.

It's quite easy to program, but very ugly to use, but I can't think of a better way without changing the item sheet.

**Comment by SalieriC** [comment]
I still think additive should be the default behaviour for `if (item.type === "power")`. It's very rare at best that a power modifier overwrites the standard power points. I can't think of a use case for this _at all_.
But if you really want this and this is the best we get, then go for it. It would cause a little clutter but meh.

**Comment by javierriveracastro** [comment]
Again I agree that it is a better solution, but I don't want to break existing actions. The other option is adding another toggle in settings, but they are complicated enough as they are now.

**Comment by SalieriC** [comment]
IMO the better option, also in terms of the future, would be to treat global actions and shots used on the item sheet differently, even if that's a bit more complicated and would require a rewrite of a part of that. Untying those would be wise _IMO_.
And while I'm usually on your side, especially in terms of not breaking something, on this one I disagree. This is for the greater good. If you want to go for the solution you've just proposed, I'd call for something simpler and shorter as a switch. Another way would be an Additional Stat as a switch, but that's not prettier than the text added thing. 
If we were to change the sheet, it would be as simple as making the Shots Used field a String (instead of a number, so that `+` and `-` could be used).
I can't add anything else to this discussion, you'll have to decide what to do. My vote is on rewrite or breaking change. I'm ready to help you whatever you decide to do though.

**Comment by grendel111111** [comment]
Rather than "(additive shots)" would "(PP)" be less intrusive?

**Comment by SalieriC** [comment]
Somewhat. But that needs some thought, because we wouldn't want it to target any other words like `Suppressive Fire` for example, just because there's a pp in the name.

**Comment by grendel111111** [comment]
Sorry I assumed the brackets around the pp would isolate it from appearing in other words.

**Comment by javierriveracastro** [comment]
Yes, that's the intent behind the brackets.

**Comment by SalieriC** [comment]
By @Joshmvii7

> I'd like to be able to use shotsUsed to automate via global world actions the additional cost of power modifications. Right now shostsUsed: 1 makes the cost of the item 1, and the functionality I need is to have it add 1 to the cost of the Power or other item instead. This way I could use the same global action to add say the armor piercing power modification to a power that costs 1 and make it cost 2, or on a power that costs 2 base it would cost 3.

**Comment by javierriveracastro** [comment]
After a year I have done something with this. Item actions work as they did, no simple and elegant solution.

World actions now check how the value is writen. If it is a plain number "6", it works as before. It is starts by + or -, i.e. "+5" it will add 5 points to the power cost. Of course "-5" will subtract then.

I know this was not exactly what was required, but I'm closing it as no good solution has been found.

If someone disagrees please write here. For new ideas open new issues.

**Comment by SalieriC** [comment]
What about item actions? Does it work the same way there?

**Comment by javierriveracastro** [comment]
No, they can't, they are a number not a string, so there is no way to differentiate +5 from 5.

**Comment by SalieriC** [comment]
Then maybe change it to always treat them as `+x`? I know it's inconsistent but a dramatic improvement in usability.

**Comment by javierriveracastro** [comment]
As you said it is inconsistent, as actions will work in a different way in core or tools or whatever and in better rolls.

I really believe this is a bad idea prone to cause endless confusion with users.

**Comment by javierriveracastro** [comment]
But I also get that it is useful for spell modifiers.

**Comment by SalieriC** [comment]
Yeah, It'd be really bad for weapons but exceptionally useful for powers.
