### ISSUE TITLE
Add Text Option.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#358]
Currently if I want to add a note to the results I need to run a macro from the global action. This results in a bunch of macros sitting in the macro folder just to put up information.
To be clear I am not sure if this is possible. 

If we could get an option like:
"text" : "Support: Success = +1 to targets roll. Raise = +2 to targets roll. Crit Fail = -2 to targets roll." 

That puts the test after the rolls are finished it would be a way to add quick reminders to the rules for beginning players/GM's.
This is similar to how the support macro from macros for SWADE works, but with out the specific numbers.
![image](https://user-images.githubusercontent.com/80164119/144694282-1e9b53f1-aa1e-4524-8811-ff12c94905da.png)

**Comment by grendel111111** [comment]
I'm trying to add a text block under a skill roll so using a macro. If I use a chat macro it doesn't seem to run. Does the runskillmacro need to be a script macro?

**Comment by javierriveracastro** [comment]
Yes, it should probably be marked clearly in the docs. It only works with script macros.

**Comment by grendel111111** [comment]
I might have missed that. Thanks.

**Comment by javierriveracastro** [comment]
I mean, that documentation should be modified to reflect that.

**Comment by grendel111111** [comment]
Just checking, there isn't an option to run a macro on only one result (like only if result is success or raise).

**Comment by javierriveracastro** [comment]
No, nor an easy way to check for success. I mean you have the full roll object, so you can test if the roll was a success or a failure, but I'd like to add some easy way to check it.

**Comment by grendel111111** [comment]
How do you access the roll text in a macro?

**Comment by javierriveracastro** [comment]
They pass a variable named message with all the data, console.log(message) for details, as it's quite complete.

You also get actor, item, speaker, token, character and targets as parameters in macros ran from actions.

**Comment by javierriveracastro** [comment]
This is kind of done, check #380

**Comment by grendel111111** [comment]
This is great, but I am having trouble figuring out the code to make it match the "You are shaken" text. I'm assuming there are HTML codes to change text and background color, and centered?

**Comment by javierriveracastro** [comment]
You can do a lot of formatting using HTML, but you can't change the position (at least not easily).

Inline styles are probably what you are looking for,

**Comment by grendel111111** [comment]
In this action:
```{"id":"6Reliable",
"name":"Reliable",
"button_name":"Reliable (on support rolls)",
"extra_text":"<p>Free re-roll on support rolls.</p> ",
"and_selector":[
{"selector_type":"actor_has_edge",
"selector_value":"Reliable"},
{"or_selector":[
{"selector_type":"item_type",
"selector_value":"skill"},
{"selector_type":"item_type",
"selector_value":"attribute"}]},
{"not_selector":[
{"selector_type":"item_type",
"selector_value":"weapon"}]}],
"defaultChecked":"on",
"group":"You have a free re-roll from:"}```

it works to place a text box. If I use inline and change line number 4 from:
"extra_text":"Free re-roll on support rolls. ",
to:
"extra_text":"<p style="color:red;"> Free re-roll on support rolls. </p>",
I get an invalid Json. Is this not how to do inline formatting?

**Comment by javierriveracastro** [comment]
It is, but you're use of the quotes inside quotes is confusing javascript. Either us `'color: red;'` (note the single quotes) or use `\"color: red;\"`.

The \ means that the next character is literal and should not be treated as special. It's called escaping strings if you want to google it.

But I feel the first one (single qoute) is easier and more readable.

**Comment by grendel111111** [comment]
Thank you!
