### ISSUE TITLE
Extras roll a Wild Die

### ISSUE THREAD

**Issue by dmpunks** [javierriveracastro/betteroll-swade#36]
Steps to reproduce:
1. On the NPC sheet, click on one of the Extra's weapon icons

Actual result: Extra's skill with weapon is rolled along with a wild die.
Expected result: only the Skill die is rolled (like it does when the dice are rolled by clicking the actual skill)

**Comment by javierriveracastro** [comment]
It's a feature, not a bug. 

If you pay attention you will see the wild die is always discarded (grayed). It can be used for fumble detection or group rolls.

Truth is that you behavior was the original one and I changed it to roll the second dice :). Maybe it could be made optional.

**Comment by dmpunks** [comment]
Oooh. If you put it that way, that is nice to have. Thanks for the explanation!
