### ISSUE TITLE
Something broke in the new update.  Wounds.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#360]
When the new update went through something broke in the damage application process. 
![16387674060644357670689628622895](https://user-images.githubusercontent.com/80164119/144790663-ddc7eee6-27b1-473a-bd5b-1e585ec6e98c.jpg)
This is before attack. After the attack and damage is rolled
![1638767530895937208930729633006](https://user-images.githubusercontent.com/80164119/144790836-ad9c6e2b-91a9-4e24-9f3e-86813086f9e0.jpg)
Then damage is applied and wounds disappears. Instead of adding 2 wounds.
![1638767582402864403414819689100](https://user-images.githubusercontent.com/80164119/144790915-389bc3bf-5131-4389-9357-6cf761d5b6e9.jpg)

**Comment by javierriveracastro** [comment]
ARGGGHHHHHHH!!!!!

Update released.
