### ISSUE TITLE
Better Rolls is seeing melee weapons as having ammunition

### ISSUE THREAD

**Issue by gravagehulk** [javierriveracastro/betteroll-swade#361]
This just started recently and I haven't changed anything. This applies to creatures from the bestiary compendium (for example an Orc's Falchion from Pathfinder Bestiary) as well as PC weapons. 

![image](https://user-images.githubusercontent.com/69117052/144872205-8e357411-4fe9-4cf9-a55e-4f0b956648ee.png)

**Comment by javierriveracastro** [comment]
Have this items "Doesn't need Reload action" checked?

**Comment by gravagehulk** [comment]
Affirmative:

![image](https://user-images.githubusercontent.com/69117052/144890053-92e01ec8-b0e6-43f5-99b6-3eac09329f3d.png)

**Comment by Razortide** [comment]
Found the same issue. Remove the checkmark and it works :)

**Comment by gravagehulk** [comment]
I’m not sure that’s a solution. We’re talking about removing a check mark for hundreds of weapons and npcs in compendiums (which are locked) for the entire world. That is the default configuration for monsters in the Pathfinder and SWADE bestiaries.

**Comment by SalieriC** [comment]
Sounds like a faulty configuration then.
Anyway, I can try to get a failsafe in there in case no ammo is listed or something else. Does the ammo under "Actions & Effects" list something though? Or is it empty?

**Comment by gravagehulk** [comment]
No ammo listed, no.

**Comment by SalieriC** [comment]
Okay, so maybe it would help to check for `item.data.data.ammo` if `item.data.data.autoReload` is true here: https://github.com/javierriveracastro/betteroll-swade/blob/fcbbe23074cdb5ac58f87129156ee7ba2a9eec45/betterrolls-swade2/scripts/item_card.js#L93
But I'm unsure if this would break something else, so @javierriveracastro should take a look at it as well first.

**Comment by gravagehulk** [comment]
Thanks. For what it’s worth, this is something that changed recently.  This is a new world with a fresh install and only SWADE and Pathfinder for SWADE enabled, meaning it would affect pretty much everyone. I didn’t tweak the config at all.

**Comment by SalieriC** [comment]
It's certainly two things:
1. A rather strange way to set up an item and
2. an issue that needs to be addressed in some way.

I mean, I could write a simple macro reasonably quickly to change it, but if SWPF is set up like this, then maybe you're the first but certainly not the last one to encounter it. Let's wait what Javiers thoughts are about my idea.

**Comment by grendel111111** [comment]
He isn't the first to have this problem. Someone over on Discord had the same thing: https://discordapp.com/channels/170995199584108546/715780900322803753/915777838521663499 
I think it is the people who are making the savage pathfinder that are misunderstanding the "do not reload" button and checking it when it should be off.

**Comment by gravagehulk** [comment]
I was about to update you guys. Okay, I did some more testing. Here's the deal. This is a configuration issue with the weapons in the Pathfinder Items compendium specifically. When I drag any melee weapon over, the "doesn't need reload action" is checked by default. This does not happen with the standard SWADE items compendium.

![image](https://user-images.githubusercontent.com/69117052/145222365-4bc91d5a-adbe-4adf-941d-916194049546.png)

**Comment by javierriveracastro** [comment]
Can someone post a bow from the pathfinder module?

Does it have shots?

**Comment by grendel111111** [comment]
![image](https://user-images.githubusercontent.com/80164119/145406685-7d30584c-07c0-4b2b-8ab5-2c78b634b8e4.png)

Here you go
so 0/0 shots

**Comment by grendel111111** [comment]
![Uploading image.png…]()
Close combat weapons

**Comment by grendel111111** [comment]
![image](https://user-images.githubusercontent.com/80164119/145407056-0743efdd-af0f-4ee3-8e19-2cd09c120f6d.png)
Close combat weapons

**Comment by javierriveracastro** [comment]
Does the bow has something in ammo (in actions & effects tab)?. I hope it does.

**Comment by grendel111111** [comment]
No, they don't.
![image](https://user-images.githubusercontent.com/80164119/145412847-eb7ab602-3910-41bf-95e6-ee9f90dfb550.png)

**Comment by SalieriC** [comment]
Well that sucks.

**Comment by gravagehulk** [comment]
Yeah, this is pretty clearly an issue with the compendium. I'm sorry I blamed the module. You guys do great work. I'm not really sure how to report it to the devs of Pathfinder SWADE, either.

**Comment by javierriveracastro** [comment]
A lot. Now we are basically down to use "trait" to know when an item should use or not ammo. And that also sucks in another settings where melee items can have charges/shots.

**Comment by grendel111111** [comment]
I think they need to fix the compendium, They aren't being consistent with how the system and the SWADE compendiums are set up.

**Comment by SalieriC** [comment]
There is no good solution for us here, just two evils. Maybe the compendiums and bestiary will be patched. Maybe they don't, there is nothing we can do there, only things we can do here. It's not a big deal regarding the bestiary though. With the solution I proposed it is *fixed* by not enabling ammo management on NPCs which is a thing many GMs I used to know don't like anyway. For PCs it would need manual fixing...

**Comment by gravagehulk** [comment]
For what it's worth, I do not have NPCs use ammunition from their inventory enabled. It's just an annoying error that pops up on every attack with a melee weapon. As a workaround, I'll just use melee weapons from the SWADE compendium whenever possible and/or modify the ones I import from Pathfinder each time.

![image](https://user-images.githubusercontent.com/69117052/145415615-4e01b08f-4650-4a2f-8646-5e4c807309ce.png)

**Comment by grendel111111** [comment]
I sent an error report about the compendiums to the Savage Pathfinder github email.

**Comment by javierriveracastro** [comment]
I finally went for SalieriC suggestion. Ammo managent will only kick when there is a maximun shot or both something in ammo and "Doesn't need reload action' is checked.

Pathfinder users will just need to change the bow-like items.

I will close this issue, note that you can still comment if you want.
