### ISSUE TITLE
World global action philosophy. 

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#362]
I have a question for users of BR2 and I'm not sure where else I can ask it. When setting up a global action at the moment all edges, hindrances, etc go together in one group. This makes a lot of sense especially for attacks, but as I am making action for other things another option is appearing. In athletics there are lots of edges that only effect one kind of action (only swimming, only climbing, only stealth). Does it make sense to still put all the edges together, or make a single row for ”climbing” with thief (urban climb),  claws, free runner, etc.? I suspect it would come down to preference but I'd like some feedback.

**Comment by javierriveracastro** [comment]
And what would you do with effects that affect various things, like thief?. Open a row for climbing and another for stealth?. And if there is a effect that is used for two different things with the same skill (like maybe trip and push)?

**Comment by grendel111111** [comment]
That's what am I'm trying to go through. If it is in the edges category does it need an explainer of which things it applies to. There are some edges that give different modifiers depending on what you are doing with it anyway, like theif.

**Comment by grendel111111** [comment]
Healing skill has different rules for healing an injury vs identifying poisons and diseases.

**Comment by javierriveracastro** [comment]
I see, you are trying to use the grouping headers as a kind of rules pointer. Not sure that it makes sense, but it could.

**Comment by grendel111111** [comment]
Without some kind of guidance beginning players may select theif for any agility roll. Putting it in the buttons can end up with long buttons. Now with collapsing headings you just don't open the climbing set unless that is what you doing. I'm am thinking of keeping it generic and modify it just for my games.

**Comment by javierriveracastro** [comment]
But it will get crazy to people who wants all the options open.

**Comment by grendel111111** [comment]
The healing skill is odd because when healing wounds you start at -2 which is removed if you use a healing kit. You could do a healing wounds button which does the -2 and you don't select it if you are using a healing kit. Or healing is a button with -2 and use first aid kit button gives +2. Preference?

**Comment by SalieriC** [comment]
I set up Active Effects for Skills in these cases. That works okay-ish. But it would all be easier if this feature request would be addressed: https://gitlab.com/peginc/swade/-/issues/270

**Comment by grendel111111** [comment]
If you choose to set BR2 up that way you can with selectors for each action. 

> I set up Active Effects for Skills in these cases. That works okay-ish. But it would all be easier if this feature request would be addressed: https://gitlab.com/peginc/swade/-/issues/270

If you choose to set BR2 up that way you can with selectors for each action. The selectors on BR2 are very powerful now. If you select for weapons when only attacks are affected and add "not_select" for weapon, for things like climb you can narrow down the number of options.  
Healing looks like this:
![image](https://user-images.githubusercontent.com/80164119/145678658-0c412f08-1a5c-47d5-9d66-f7e0e9afa150.png)

**Comment by javierriveracastro** [comment]
Has this yield any conclusion or something actionable?

If not I'm likely to close it.

**Comment by SalieriC** [comment]
Apparently not. I'm closing it then.
