### ISSUE TITLE
BR2 modifiers aren't applied if chat is popped out

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#364]
If using [PopOut!](https://foundryvtt.com/packages/popout/) to open the chat in a new window, BR2 modifiers selected in the chat aren't applied. This is likely not a bug but a compatibility issue. No idea if possible to fix though.

**Comment by javierriveracastro** [comment]
I don't know. PopOut is some kind of mysterious magic, I have no idea of how it does work.

**Comment by Wigginns** [comment]
PopOut has decent documentation for integration and compatibility https://github.com/League-of-Foundry-Developers/fvtt-module-popout#compatibility

But I also don't think it's unreasonable to just say "BR2 does not support PopOut"

**Comment by SalieriC** [comment]
Absolutely. With the amount of modules out there, it's just not feasible to support all of them.
But quite a while ago it was discussed to put the modifiers somewhere else, now that this here is a thing, maybe it is time to reconsider this idea. Maybe as an optional setting per player.

**Comment by javierriveracastro** [comment]
The main problem is that $() is used quite a lot in br, likely around 20 times. And changing it to use foundry documents is not always easy, not maybe even possible. This is the kind of thing that is easy if you do it from the start, but this is a big refactor now.

And I already have a couple of big refactors that I want to do first. So this is likely a wont'fix.

If someone is interested in doing it, I'll lovely merge the request and help them as much as I can, but I'm not doing it myself in a reasonable amount of time.
