### ISSUE TITLE
Allow Item rolls for items of types other than weapon if a Trait is given

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#366]
Every item in the system can be set up with a trait and item actions. The system however does not make use of it as there is no way to use these actions yet. Better Rolls however can do *better* by allowing rolls from items of type gear, shield or even edge/hindrance just as well as it does with weapons. Possibilities would be endless: Rolling Healing from first aid kits, repair from tool kits, shield bashing directly from a shield, rolls from edges that allow you to do certain things with the appropriate modifier, etc.

**Comment by javierriveracastro** [comment]
This was as easy as moving two lines :).
