### ISSUE TITLE
Changing the target number. (Before rolling)

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#367]
Currently there are several options to change the target number after a roll has been made, and normally you make changes by adding or subtracting from the dice rolls. But there are a few instances where the true roll is important. Mostly to do with resisting tests against you. For example if someone tries to push you, you resist with your strength, and the target number is the roll the tester made. 
If you pass the test stops there. But if not it feeds back to the tester who compares it to their roll to see if they got a success or a raise. if you did it by modifying the dice roll to see if the defender resisted the dice rolls at the end  are not the number you need to feed back to the tester. If you could give the target number at the start, then you would have the correct result to feed back to the tester.

eg. A pushes B. A rolls 6 and tells B to roll 6 or higher to stop the push. (Currently you need to subtract 2 from the roll or roll the dice and then change the target number). If B fails the check, they need to tell A the result (which if you subtracted 2 from the roll will gave an incorrect value for A to compare their results to)

Sorry Not easy to explain.

**Comment by javierriveracastro** [comment]
You can set TNs in the modifier window just above the chat.

But I'm open to other ways of changing tn like global actions or whatever.

**Comment by grendel111111** [comment]
Do you mean here?
![image](https://user-images.githubusercontent.com/80164119/147250887-73fcfe48-139b-4926-ba22-cb827e48666f.png)
I can't see where to add the TN.

**Comment by grendel111111** [comment]
What I was thinking of would be a global action code like:
"tnOveride":"6"
This would change the target number for that roll to 6. When they roll they know if the succeeded and the test is over, or they need to tell the testing player the value they rolled so they can see if they got a raise.

**Comment by javierriveracastro** [comment]
Yes. I have probably removed it. It was not really used anyway.

That global action could be really useful, but anyway there should be some better way of doing contested rolls.

**Comment by grendel111111** [comment]
I was trying to do a non automated way of doing contested rolls, using dialog macros.
![image](https://user-images.githubusercontent.com/80164119/147257182-ead18d3f-6779-4d68-93ff-79755c55ce05.png)
![image](https://user-images.githubusercontent.com/80164119/147257406-28015c2d-ee96-473d-844f-ab7271950e13.png)
I'd like to put an option so they can select the TN the tester tells them like this:
![image](https://user-images.githubusercontent.com/80164119/147257605-78b8d75d-e5ba-4af3-b256-6f8544d9fac2.png)

**Comment by javierriveracastro** [comment]
That's done, I mean the tnOverride thing not the contested roll.

**Comment by grendel111111** [comment]
Thank you.

**Comment by javierriveracastro** [comment]
I'd close this issue, but we likely need another one for opposed rolls.

**Comment by grendel111111** [comment]
I realise this has been closed for a while, and I suspect this will not be possible, but I am going to ask anyway. If I put a target number at the end of an effect (BanishTN7) I can use it to change teh targte number by calling it.  If effect TN7 then Target number is 7. However it means you need 1 world action for each target number and as roll can get very high it needs a lot of world actions. Is it possible to do a general TN:X will add X to the roll?

**Comment by javierriveracastro** [comment]
I'll reopen it wih two new actions:

1) Change the TN

2) Use the last roll result as the TN.

As always no promises on time frames.

**Comment by javierriveracastro** [comment]
Number 1 is done. Number 2 is probably never going to happen so I'm closing this.

There is probably going to be a way of selecting a roll result as a TN in the redesign.
