### ISSUE TITLE
Token doesn't seem to be able to roll against a targeted token.

### ISSUE THREAD

**Issue by JasonSK22** [javierriveracastro/betteroll-swade#368]
Token will roll skill when not targeting another token.  As soon as a token is targeted the roll pops the attached error.
![BR2 - Target error](https://user-images.githubusercontent.com/28511333/147309093-c0948d90-3655-48c2-95d2-f5e01e4f39c5.jpg)

**Comment by grendel111111** [comment]
Have you upgraded to 0.9? I'm not getting that error on 0.8 system.

**Comment by JasonSK22** [comment]
Yes, I should have been clear what version I am on.  

Foundry 9.238
SWADE  0.22.1
BR2 2.55

**Comment by JasonSK22** [comment]
I can't seem to duplicate this issue in my test  world.  I started out with no modules and worked up to my game world active modules and the targeting works fine with all the modules active.  

I deactivated everything but BR2 in my active game world and the error pops up.  Any suggestions on trouble shooting?

**Comment by javierriveracastro** [comment]
Not really, this is clearly a bug. Somewhat the scale calculation (that should be a number) is detected as NaN and the module tries to treat it as a die expression (well, as a string). 

The most likely reason is that the size of one of the actors (token or "roller") is NaN. Anyway, this should be solved in code with some kind of graceful failure (most likely just ignore scale).

**Comment by JasonSK22** [comment]
Yah, it was the size.  anything over 20 fails to roll when targeting another token.

**Comment by javierriveracastro** [comment]
Kinda solved. It doesn't break, but I'm not really sure what should one do with sizes bigger than 20. For now any size above it are treated as gargantuan for scale.

**Comment by JasonSK22** [comment]
Thank you.  Super rare to have a creature over size 20.  Savage Rifts is over the top.
