### ISSUE TITLE
Modify AP

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#369]
At the  bottom of weapons when you use a weapon  it lists the AP. But there doesn't seem to be a way to modify the AP on attacks. Also there are 3 powers that deal damage that would benefit from having an AP value (set to 0 when created). A modAp would be helpful for these.

**Comment by SalieriC** [comment]
Powers not having an AP field was always weird but is a core problem. I think this would be a great addition to BR2.
As for weapons, the AP can be modified using AEs, I think that's the more convenient option there.

**Comment by javierriveracastro** [comment]
Done in git.
