### ISSUE TITLE
Support for Melee/Thrown Weapons

### ISSUE THREAD

**Issue by dmpunks** [javierriveracastro/betteroll-swade#37]
When attacking with a Thrown Weapon that can also be used in Melee (like a Javelin), Athletics is automatically used.

This prevents using the weapon as a melee attack.

Suggestion: Clicking a weapon should allow the user to choose between all the modes it can be used as (i.e. Fighting or Shooting or Athletics, etc)

**Comment by javierriveracastro** [comment]
As a workaround you can make two weapons for each kind of attack. Just put range 0 and no weight on the melee one.
I'm used to do most choices that way, for example one sword for normal attack and another one for wild attack. Same thig with multi-rof weapons.

Opening a window to ask is akin to the core way or the Combat Flow macro (but the macro is much more powerful than all this module), is somewhat against the philosophy of betterrolls and just duplicating effort.

**Comment by dmpunks** [comment]
Yup, that's a good workaround. 

There might be no need to open an actual window. Maybe it could be on the chat card?

**Comment by javierriveracastro** [comment]
¿In the card?. ¿How?. 

Maybe I can show two rolls, one for athetics and another for figthing...

**Comment by javierriveracastro** [comment]
Depends on #52

**Comment by javierriveracastro** [comment]
The use of the skill in the "Actions and Effects" tab should resolve this.
