### ISSUE TITLE
Hide ammo usage and PP remaining

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#371]
The panels under the main window with PP and Ammo used are shown to all players. Can it be changed to show to just the GM and the players who is attacking/ using the power?

**Comment by Wigginns** [comment]
This setting is meant to control this but doesn't appear to work presently.
![image](https://user-images.githubusercontent.com/3180645/147625061-c0ec745d-fbaf-49d1-b6d8-9b44dd08a3ae.png)

**Comment by Wigginns** [comment]
I'm taking a stab at fixing this by turning these optional cards into whispers to the gm when the setting is set

**Comment by javierriveracastro** [comment]
This works for me...

**Comment by Wigginns** [comment]
On Foundry V9 build 238 I am seeing it display the remaining value to everyone no matter which option is selected. 

I am logged in as AJ with the remaining card option set to "Master only" and see the ammo expended message from both David and AJ

![image](https://user-images.githubusercontent.com/3180645/147644979-638c8631-93c7-400b-91fe-b0ce85479471.png)

**Comment by javierriveracastro** [comment]
Uffff... shouldn't try to do updates on a hurry. I was assuming that the color means that it was a master only thing. You are right we should probably need to also set the whisper.

**Comment by Wigginns** [comment]
If it's not any trouble, I'd love to take a stab at modifying the output cards to use whispers instead. I have it working right now, just cleaning it up a bit and making it respect the option the user selects

**Comment by Wigginns** [comment]
https://github.com/javierriveracastro/betteroll-swade/pull/374
