### ISSUE TITLE
There is an extra "s" that is a typo and breaks the application of damage.

### ISSUE THREAD

**Issue by Wigginns** [javierriveracastro/betteroll-swade#372]
https://github.com/javierriveracastro/betteroll-swade/blob/949b473e15c75325c86fdc1dd427285c0983eaa0/betterrolls-swade2/scripts/damage_card.js#L153

Users can delete the "s" and functionality returns.

**Comment by SalieriC** [comment]
Thanks, I've fixed it.

**Comment by javierriveracastro** [comment]
Thanks.
