### ISSUE TITLE
Ammo not updating

### ISSUE THREAD

**Issue by sroakjp** [javierriveracastro/betteroll-swade#376]
Characters who have a ranged weapon with ammunition assigned from their inventory are not expending ammo from the inventory item. 

The following error message is shown in the console:

Uncaught (in promise) TypeError: actor.updateOwnedItem is not a function
[Detected 1 package: betterrolls-swade2]
    at reload_weapon (assets.forge-vtt.com/bazaar/modules/betterrolls-swade2/2.57/scripts/item_card.js:761)
    at roll_item (assets.forge-vtt.com/bazaar/modules/betterrolls-swade2/2.57/scripts/item_card.js:704)
    at async HTMLButtonElement.<anonymous> (assets.forge-vtt.com/bazaar/modules/betterrolls-swade2/2.57/scripts/item_card.js:243)

**Comment by sroakjp** [comment]
Words are failing me in describing the expected behavior in a succinct manor.

This feature appeared to work properly before updating foundry to version 9, and whatever the corresponding version of Better Rolls 2 was.

When working I was able to assign ammo from the character's inventory to the weapon (such as assigning Bolts to a hand crossbow) and as shots were made the number of Bolts in the inventory reduced accordingly. I believe this is the intended behavior. What I'm seeing now is that I can manually update the ammo counter on the Details tab. When I do that the ammo will tick down as shots are expended, but the ammo item in the inventory isn't changed. If I don't update the ammo counter on the Details tab then after each shot the ammo message in the chat window says 0 shots remain and the ammo item in the inventory is again, not changing.

**Comment by sroakjp** [comment]
I'm not Java enough programmer to know for sure but it looks like the currently outstanding pull request might address the error message I'm seeing in the console, which may resolve this issue.

**Comment by SalieriC** [comment]
So worries, the error message explains it all. The `actor.updateOwnedItem()` function was deprecated in v9, that's why it stopped working. Now it's `actor.updateEmbeddedDocuments()`. And yes, the PR looks like fixing it.

**Comment by sroakjp** [comment]
I'll go ahead and close the issue then.

**Comment by sroakjp** [comment]
For completeness:
Closed by PR #374

**Comment by SalieriC** [comment]
I've pinned this for the sheer amount of questions that are asked about this. We can unpin it once the new version that fixed it is released.

**Comment by Razortide** [comment]
I've found that the issue is not fixed for me. There is no ammo deduction with the latest version (Foundry 9.242, SWADE 0.22.5, BR2 2.58). There is no message or deduction regardless of the configuration.

UPDATE: Issue appears if I do the trait roll and damage automatically. It works as expected if I just show chat card THEN click the trait roll button.

**Comment by javierriveracastro** [comment]
And this should also be done.
