### ISSUE TITLE
Improvement: Way to Reorder world global actions

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#381]
I'm not sure if this is possible. Currently the order is determined by which action is at the top of the world action list. The only way to reorder the list is to delete and repost the action. If you could move an action up or down the list you could reorder them without having to cat and paste or re enter the data.

**Comment by javierriveracastro** [comment]
Do you mean on settings or on the card?

On the card maybe adding an 'order' field to the actions can do it.

**Comment by grendel111111** [comment]
I was thinking in the setting, when you are entering the actions, but that was because the card is made based on which action it gets to first.

**Comment by javierriveracastro** [comment]
This is probably more difficult... Maybe order them by id?

**Comment by grendel111111** [comment]
It was an idea and doesn't impact the usefulness. I wouldn't worry about it.

**Comment by javierriveracastro** [comment]
Global actions are now sorted by id, both in settings and in the card.
