### ISSUE TITLE
Damage will also be automatically rolled even if it is not configured.

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#383]
Hey Javier, as discussed, I am facing a low prio issue:

I have configured my default action to "Show Chat card and roll trait". If I use a weapon action it will always auto roll the damage with it.

If I use the "just show chat card" option, and roll the trait roll it works as expected.

**Comment by javierriveracastro** [comment]
Something more must be going on. I can't reproduce it.

How do you a "weapon action"?. AFAIK there is no way to roll directly and action in br (like it is in core system).

**Comment by Razortide** [comment]
I drag a gun to another actor. I will try later if I can target and click if the issue persists.

**Comment by javierriveracastro** [comment]
Ok, I have not tested dragging, just clicking.

**Comment by Razortide** [comment]
Yep, that was it.

Dragging = Auto Roll Damage
Clicking = Just Skill roll

Same is true for #376 by the way: Clicking reduces ammo, Dragging does not.

**Comment by javierriveracastro** [comment]
This should be solved in git.
