### ISSUE TITLE
Dodge edge automation

### ISSUE THREAD

**Issue by gravagehulk** [javierriveracastro/betteroll-swade#384]
Similar to the way this module calculates the range and applies applicable modifiers to the roll, could it conceivably detect that the target has the "dodge" edge and apply the -2 to hit?

**Comment by grendel111111** [comment]
You can try this:

{"id":"Target has dodge",
"name":"The target has dodge",
"button_name":"has Dodge and is at range",
"skillMod":"-2",
"and_selector":[
{"selector_type":"item_type",
"selector_value":"weapon"},
{"selector_type":"target_has_edge",
"selector_value":"Dodge"},
{"or_selector":[
{"selector_type":"skill",
"selector_value":"Shooting"},
{"selector_type":"skill",
"selector_value":"Athletics"}]}],
"defaultChecked":"on",
"group":"The target"}
(Will do dodge for weapons).

and this will do dodge for powers:

{"id":"Target has dodge 2",
"name":"The target has dodge",
"button_name":"has Dodge and is at range",
"skillMod":"-2",
"and_selector":[
{"selector_type":"target_has_edge",
"selector_value":"Dodge"},
{"selector_type":"item_type",
"selector_value":"power"}],
"defaultChecked":"on", 
"group":"The target"}

**Comment by javierriveracastro** [comment]
I'm closing this as there is no answer to grendel1111 workaround.

**Comment by gravagehulk** [comment]
If that was directed at me, I didn't understand it. I thought it was a suggestion for how it could be implemented in Betterrolls. 

I have no idea what I'm supposed to do with the code he posted. I'm not a developer.

**Comment by javierriveracastro** [comment]
Yes, these are global actions that support dodge. Not the most elegant possible solution, but if they work, then development time can be probably be used in some other place and that actions can be added to the built-in ones.

The main problem with this approach is that you need to target your enemy before showing the card, otherwise the global action would not work.

See this link for more info on global actions and what they can do:
https://github.com/javierriveracastro/betteroll-swade/blob/version_2/docs/global_actions.md

**Comment by gravagehulk** [comment]
Okay, I didn't even realize that these were being proposed as global actions I should add. My mistake. Thank you.

**Comment by grendel111111** [comment]
> Okay, I didn't even realize that these were being proposed as global actions I should add. My mistake. Thank you.

Sorry you put these 2 codes into a world global actions. Then when you attack someone with the edge Dodge it will subtract 2 from your attack roll. The second one will subtract 2 from powers that target the character with dodge.
![image](https://user-images.githubusercontent.com/80164119/150441217-f2ea2a4f-4086-4fe4-bd8c-6a55cb87056e.png)
![image](https://user-images.githubusercontent.com/80164119/150441455-7d617d36-55b3-454c-8ac8-c739c875625d.png)
![image](https://user-images.githubusercontent.com/80164119/150441837-6c7d597f-efad-4207-bf4c-77ca14a7687b.png)

**Comment by gravagehulk** [comment]
Thanks, man!. Sorry I didn't understand initially. I have never actually set up any custom actions, so I wasn't even thinking about that.

**Comment by javierriveracastro** [comment]
I will add then to the bultiin-actions

**Comment by javierriveracastro** [comment]
Added in git
