### ISSUE TITLE
When using Token Action HUD with Auto-Roll, no MP/Ammo will be reduced

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#385]
Hey Javier, I just found another interesting issue with the Token Action HUD and BR2:

If I configure BR2 to Autoroll the Skill roll (Spellcasting, Faith, Shooting...) and click on a Weapon or Power in the Token Action HUD the action works, but no ammo or MP will be reduced. However, if I just display the chat card and click on the Roll button there, everything works just fine.

Might also be related to #376 and #383. In this case the damage is not auto-rolled.

**Comment by javierriveracastro** [comment]
Can you check if this is still happening with git version?

I don't know a lot of Token HUD, but I believe that solving #376 will also solve this one.

If not, I'm planning on a release tomorrow, so just update and check afterwards.

**Comment by Razortide** [comment]
Hello @javierriveracastro,

I updated all my modules today and tried it - the ammo is still not deducted. Same is true for spells.

**Comment by javierriveracastro** [comment]
I have made a pull request in Token Action Hub, that I hope solves this.

**Comment by Razortide** [comment]
With the latest BR2 update everything works like it should. Thank you!
