### ISSUE TITLE
Two Macros are created when dragging items to the hotbar

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#386]
When dragging any item (Skill, Weapon, etc.) to the hotbar, two macros are created: The default `game.swade.rollItemMacro();` one and the one from BR2.
BR2 should instead overwrite that core functionality completely in order to avoid clutter. Since BR2 macros support the hotkeys used on the sheet as well, there really is no need to create standard macros anyway.

**Comment by javierriveracastro** [comment]
I don't know ho to tackle this. Both system and betterrolls hook to "hotbarDrop".

As br is a module it hooks happens after system's. So swade creates its macro and assigns it to the hotba slotr.
Afterwards br2 creates its own macro and assigns it to the same hotbar slot. That way system one dissapears from the slot but it is still created.

If I can for sure find the name of the system macro and delete it, but as names are quite generic I can delete something that is used in another slot.

Any ideas?

**Comment by SalieriC** [comment]
There is a lot of stuff in the console when dragging an item to the hotbar with `CONFIG.debug.hooks = true;`. I can't check right now but maybe there is something to watch out for and get the ID of the macro that has just been created. Then deleting by ID would be rather safe.

**Comment by javierriveracastro** [comment]
No that I can see. I can delete any macro stating with "game.swade." int the createMacro hook but it sounds dangerous radical. Specially for just avoiding clutter. 

And I can't find anywhere else that I can use.

**Comment by SalieriC** [comment]
In this case, we'll just live with it. =)
