### ISSUE TITLE
Preconfigured Modifiers, Edges, Hindrances do not work with German language settings

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#387]
Hello Javier,

I just noticed, that the pre-configured global actions are now very complete. The issue is, that they won't work with the german Edge names so far (so, if an actor has the edge "Schneller Angriff" (Frenzy), it won't show up in the modifiers.

It would be great if this would also work to spare me the effort to create all of those global actions by hand.

Best regards,
Marc

**Comment by javierriveracastro** [comment]
It should work if the system is set to german. Frenzy should check for: "BRSW.EdgeName-Frenzy" that is set to "Schneller Angriff"

I will try to check it this afternoon.

**Comment by javierriveracastro** [comment]
Found, it was devilish.... it was failing becasue of this translation string ``"BRSW.SkillName-fighting": "Kämpfen"`` , the original one was ``"BRSW.SkillName-fighting": "fighting"``, and the capital K was killing it.

I have made the check insensible to capitals, so it will be solved in next update without needing to change the translation.

**Comment by Razortide** [comment]
Sorry, we Germans like to capitalize a LOT :-)

**Comment by Razortide** [comment]
Hello Javier, I just checked and here is what I've found:

Wild Attack and Aim: Head works
Surprise Attack, Unstable Platform, Unarmed Defender, Touch Attack, Nonlethal Damage do not show up.

Talents: Elan, No Mercy, Frenzy, Alertness,  "Repairguy", 
Marksman, Aristocrat, Attractive, V. Attractive, Fame, Famous, "Climbing or foot chases", Martial Artist, Martial Warrior does not work. (Except Marksman they are also not yet translated).

Alertness factors in size category right now if there is a bonus when the size category difference is big enough?

Multi-Action: "Running" shows up twice

All Thumbs: No button visible - it will be deduced every time, even with a Tomahawk :-)
Bad Eyes, Blind: Does not work: I guess, the rest is also not easily testable, therefore I stopped there.

Best regards,
Marc

**Comment by grendel111111** [comment]
Running occurs twice because of the steady hands edge. Normally running results in -2 to actions. If you have steady hands there is only a -1 penalty.  The first run will not show if you have the steady hands edge, and the second one will only show if you do have the steady hands edge.  I found the error in Martial Artist, Martial Warrior, one set of the quote marks "" goes to the left and right instead of straight down. This causes it to give an error.

**Comment by javierriveracastro** [comment]
Ok, a couple of them (those resulting from a capitalized figthing in the rules has been solved).

![imaxe](https://user-images.githubusercontent.com/8113700/150555646-ff29c631-86a4-4265-bb46-dd37ad8a9759.png)

Non translated ones can't work, nor can I do nothing about them with my totally lack of command of german.

**Comment by javierriveracastro** [comment]
And I also solved a bug that was not detecting come skill translations (shooting and athletics), this solves Marksman and likely some others.

Finally solved another bug that made all translated hindrances not work.

Now, I'm really thinking that you are the first to try this with translations enabled, close to nothing was working XDDD.

I will close the bug, as right now I don't know what works and what not. Feel free to open it if you find more errors either using git version, or after next release.
