### ISSUE TITLE
Replace "Fumble" by "Critical Failure" or "Snake Eyes" in the english version.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#39]
In the original english version a one on both, the Trait and Wild Die is called Critical Failure or (in previous versions and more flavourful): Snake Eyes.
_Also a single exclamation mark should be enough: http://wiki.lspace.org/mediawiki/index.php/Multiple_exclamation_marks_ ^^'

**Comment by kristianserrano** [comment]
Since this is for SWADE, I vote for "Critical Failure!" as the label for consistency.

**Comment by javierriveracastro** [comment]
Done. Used Critical Failure.
