### ISSUE TITLE
Use the new status introduced by system version 1

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#393]
Can an option be made to trigger the SWADE core bleeding out instead of the CUB AE?

**Comment by javierriveracastro** [comment]
I have to look at the new status, but for now, better rolls doesn't do nothing related to bleeding out.

I will make this bug more generic.

**Comment by grendel111111** [comment]
It triggers bleeding_out in the incapacitation sequence.

**Comment by javierriveracastro** [comment]
Not AFAIK it just adds the defeated condition (and active effects for injuries). Anything else is likely done by CUB.

I can be wrong, for sure, the code is much bigger than my memory but I'm quite confident. I'll check it after work, but anyway a bug to update all conditions is probably a better idea.

**Comment by grendel111111** [comment]
You're right. Sorry. I made cub do it.

**Comment by javierriveracastro** [comment]
This should be finally done. Hopefully.
