### ISSUE TITLE
Cannot read properties of null (reading 'addChild') in SWADE 1.0.2 on world load

### ISSUE THREAD

**Issue by Zamrod** [javierriveracastro/betteroll-swade#394]
BR2 2.61
Foundry v9.249
Microsoft Edge

On World load with a bunch of chat messages in the history I get a bunch of the following error in the console log:
```
foundry.js:22128 
        
       Uncaught TypeError: Cannot read properties of null (reading 'addChild')
[Detected 1 package: betterrolls-swade2]
    at TokenLayer.createObject (foundry.js:22128:18)
    at TokenDocument.get object [as object] (foundry.js:9756:31)
    at TokenLayer.get (foundry.js:22207:49)
    at cards_common.js:220:42
```

**Comment by javierriveracastro** [comment]
It is trying to access the token layer before it is ready. 

Not sure how to solve it within the current model.

**Comment by javierriveracastro** [comment]
Blocked by #417

**Comment by SalieriC** [comment]
Is this still relevant or can we close it?

**Comment by javierriveracastro** [comment]
Still relevant, still in the roadmap.

**Comment by javierriveracastro** [comment]
I think this have solved itself with the last Foundry versions.
