### ISSUE TITLE
Incapacitation turned on and off on receiving wounds

### ISSUE THREAD

**Issue by Tommycore** [javierriveracastro/betteroll-swade#396]
Unfortunately I have not been able to reliably reproduce the behaviour, but sometimes when applying wounds via chatcard, the incapacitated and shaken status effect are applied and incapacitated is directly removed, leaving only shaken. The character remains incapacitated on the combat tracker though.

Foundry version 9.249
Swade 1.0.2
Active modules:
- BR2 2.62
- German Swade CRB 1.2.4
- libwrapper 1.12.2.0
- Settings Extender 1.2.0
- Compendium Folder 2.4.1

**Comment by javierriveracastro** [comment]
BR doesn't manage (yet) incapacitation (I know you are not the first one opening a bug like this). Are you using CUB to do it?. Then it is not really compatible with SWADE 1.0+.

**Comment by javierriveracastro** [comment]
Anyway I have changed it right now to use system incapacitation state, so this bug is likely indirectly resolved.
