### ISSUE TITLE
Wild Attack has stopped adding Vulnerable

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#397]
When you use wild attack it has stopped adding Vulnerable to you character.
It uses (self_add_status: "vulnerable"), but I'm guessing that changed when it moved to 1.0.

**Comment by javierriveracastro** [comment]
Ummm... I have tested it specifically and was working for me. I'll look for it again this afternoon.

**Comment by grendel111111** [comment]
I turned off CUB but the change didn't save. So it was still on. sorry. With cub gone it works fine.

**Comment by javierriveracastro** [comment]
See this for some of the cub functions: https://github.com/SalieriC/SUCC

**Comment by grendel111111** [comment]
That's great I was just trying to figure out how to update my macros. I will wait for this.
