### ISSUE TITLE
Global actions seem to be on the user scope

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#399]

**Comment by javierriveracastro** [comment]
Hummm... they should be of "world" scope. Or at least it looks like that to me.

Are you sure?

**Comment by SalieriC** [comment]
Yeah, when I disable something like Martial Artist or Clumsy or whatever on my end, it still seems to apply to rolls made from other players. I could double check again ofc but I'm pretty sure since we have toggled off some things together (each on their end) two sessions ago.

**Comment by javierriveracastro** [comment]
Oh.... that. You are right, solved but not in today release.
