### ISSUE TITLE
Better roll with SWADE roll window

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#40]
I know this is against the original idea of Better rolls but as I really like the modules chat message I'd highly appreciate it. There are three ways this could be done that I can think of:

1. Replace the regular roll (clicking on the skills name) with the Better rolls roll that uses the roll window to modify the roll.
2. Introduce an option that opens the roll window, replacing the usual Better rolls behaviour.
3. Have another button/combination (i.e. middle mouse button or shift-click) to roll with the roll window.

The first would interfere with the system, the second wouldn't offer a way to have both at the same time, the third option is kind of a middle ground but inconveinient if you have no middle mouse button (Mac users) or if you rarely use the keyboard. I really like the way Better rolls does the chat message and I'd love to have the option to do modifiers before rolling but as I said: I realise this is against the original intention of the module, thus I'd understand if this request is denied.

**Comment by javierriveracastro** [comment]
If I do it, it will be number 3. I don't like to alter default behavior.

I'll look into it. If it is easy (there is a way to use the default box) I'll add it. If I need to create a new window and all of that... I will think about it, it somewhat can interact well with the result row (just prepopulate its values).

**Comment by javierriveracastro** [comment]
Clicked the wrong button.

**Comment by SalieriC** [comment]
Maybe a mix of 1 and 3 would also be possible, now that I think about it. It could have an option to swap it. So if the user prefers the roll window he could check the option and all rolls are made using the window unless the key combination is used or vice versa.
Anyway, thanks for looking into it. =)

**Comment by javierriveracastro** [comment]
The window in the systems roll is showed within the constructor of their own Roll class. That means that reusing it is hard. Or at least I can't see anyway to reuse any code but the template.

And them, just for the template, I prefer to make my own than to risk breakages. I'll look into it after I manage to get the result roll to something like finished (as all modifiers are likely to end there in trait rolls).

**Comment by javierriveracastro** [comment]
Depends on #52

**Comment by javierriveracastro** [comment]
Preliminary version done. 
The windows can be called with the right click menu or by alt-clicking any element enabled by betterrolls.
It doesn't show the formula (could be revised in a future version), not the type of message dropdown as I find it should use the option selected above the chat for consistency.
