### ISSUE TITLE
Soak rolls with Iron Jaw edges.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#400]
The Iron Jaw edge adds 2 to soak rolls, but I can't find a way to modify the soak roll that is made automatically by BR2 when a character takes a wound. 1) is there a way to modify it,  and if not 2) can a +2 be added to the roll inside the automatic sequence if the roller has the Iron Jaw edge?

**Comment by javierriveracastro** [comment]
Added.
