### ISSUE TITLE
Dice Tray Module Modifier box does not clear when BR2 roll is executed

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#402]
Hey Javier,

not sure if this is for you or not. When using the Dice Tray module and entering something in the modifier box, it won't clear after the BR2 roll. Is there something you can do about it or do you have a hint for me I can take to the Dice tray author?

**Comment by javierriveracastro** [comment]
I can change it. Likely only I can. But is clearing it the expected behavior? Will most people expect it?. Is it the most useful?

I'm not really sure about it.

**Comment by Razortide** [comment]
That is an interesting question. On my gaming table it has been a persistent cause of confusion. In Fantasy Grounds the modifiert got reset after rolling.
UI wise I would argue that resetting the dice tray would be good and using the BR modifications for persistent modifiers?

**Comment by javierriveracastro** [comment]
Done.
