### ISSUE TITLE
Translation issues (German)

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#403]
Hello Javier,

a few issues I have noticed in the Global actions selection:

- BRSW.EdgeName-Investigator is not translatable
- BRSW.Ran is displayed twice
- BRSW.TargetHasDodge is displayed twice

**Comment by grendel111111** [comment]
There are several effects that need more than 1 global action to make them perform correctly. In the case of run, if you have the steady hands edge it changes the run modifier. If you have the edge run will be replaced with an alternative run that has the changed mods. The player will only ever have 1 run button and it will add the correct effect. Target has dodge occurs for athletics for thrown weapons and for shooting. There is no way to merge the 2 into 1 script and the player will only ever have 1 showing.

**Comment by Razortide** [comment]
Ah, makes sense. Thank you.
I only have the one issue then. :-)

**Comment by javierriveracastro** [comment]
And investigator should be now translatable.
