### ISSUE TITLE
Powers like deflection need more than 1 AE to trigger different BR2 scripts.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#405]
This is more a note than anything else. Some powers like deflection need 2 different scripts to run. For deflection there is deflection (-2) and deflection (-4). Currently I am using a system where I create  2 different active effects (deflection and deflection+). As the core system and the SUCC both are using a single icon/effect for both events I have to keep making new AE for the enhanced versions. I don't know if there is some way to put something in the active effect to tell the BR2 script that they are different other than the names. I suspect the best way will be to wait for SUCC to stabilize and give the option of adding additional conditions.

**Comment by javierriveracastro** [comment]
There are lot's of ways that I can think of.

1. Adding a new possible value to "skill_mod" so that it can read a path.
2. Adding another active effect for dodge like the one for gang-up
3. If skill_mod is present but empty try to a number of smart things to derive some value.

**Comment by javierriveracastro** [comment]
I can't find deflection neither in system nor in SUCC. There is a defending effect that changes parry, but it is not the same.

There is also a protection effect that changes toughness or armor.

How are you expecting deflection to work?

**Comment by grendel111111** [comment]
Sorry it was when I create a deflection power in a macro:
```	let Deflection = {
		icon: 'https://assets.forge-vtt.com/bazaar/systems/swade/assets/assets/icons/armor.svg',
		label: 'deflection',
		id: 'deflection',
		duration: {seconds: 30, rounds:5},
	   flags: {
			swade: {
			  "expiration": 3,
			}
		  },  
	}; ```
I need to make 2 different deflection AE (So deflection and deflection+) I was wondering if there was another way to signify the difference .

**Comment by javierriveracastro** [comment]
The only way that I can think of is creating some kind of new AE key. Something like `brsw-ac.gangup-reduction`, but this will be always applied, not treated like an action.

**Comment by grendel111111** [comment]
I don't think it is worth doing.
