### ISSUE TITLE
New selector_type "item_has_effect"

### ISSUE THREAD

**Issue by basic-element** [javierriveracastro/betteroll-swade#407]
It would be nice to have a new selector_type called "item_has_effect" similiar to "actor_has_effect". This way, we can add an active effect to an item/weapon and have it trigger/enable the global action.

**Comment by javierriveracastro** [comment]
Ummmm.... AFAIK Active Effects from items are transferred to the actor as soon as they are equipped. Also items can't have effects that affect themselves, they modify actors.

What are you trying to achieve here?.

**Comment by grendel111111** [comment]
I think the idea he is going for is this: We were talking about weapons in rifts that have the disintegrate property which changes the wild die. To add that to a weapon you can do it by naming each weapon in it's own action, or you could add a tag to the weapon or ability  in the name (Dis) When ever that tag is in the name it will run the action. (I do this for magic resistance, so all spells and magic items I put a (magic) tag in their name. basic-element  suggested it crowded the name and wondered if it could be an active effect. I have realised that if it is an active effect it will transfer to the character and every action by the character will trigger with the effect. But if we could put the trigger words in the description of the item it wouldn't crowd the name and only trigger on that weapon or item. So like this:
![image](https://user-images.githubusercontent.com/80164119/156572639-cfc51a35-f7b3-41e7-a68a-71773da49c63.png)

So a "item_has_description" tag.

**Comment by javierriveracastro** [comment]
That last one "item_description_includes" ;), has a lot of potential and should be easy to implement.

**Comment by javierriveracastro** [comment]
Added
