### ISSUE TITLE
Let GMs see player selection on Cards

### ISSUE THREAD

**Issue by loofou** [javierriveracastro/betteroll-swade#409]
When lots of modifiers are required to be set on a card (for example to shoot at someone in light cover in dim light while doing a called shot), sometimes players forget to select one of the options. Right now I, as the GM, have to ask the players "did you select Dim Light?" etc, hoping they will do it and not seeing if they did until after the roll. If they forgot something or clicked wrong, we have to remove the card and try again, which takes unnecessary time.

It would be great if the GM (or anyone for that matter) could see live what the players have selected on the card, while they are selecting it. 
Bonus for also showing the generic modifiers from the toolbar near the chat field at the bottom somewhere.
Another bonus would be to have the GM change the selection the player made or help them set up the right things on the card. This is especially useful to teach the system to new players. 

All of this can be made optional of course.

**Comment by javierriveracastro** [comment]
That's on the roadmap, but it will require some changes to the basic design, so don't expect it soon.

**Comment by loofou** [comment]
That's good to know, thank you!

**Comment by javierriveracastro** [comment]
Blocked by #417

**Comment by steveculshaw** [comment]
Is this still an issue?

As GM, I think in seeing the players choices before they roll.
Isn't that the case?

**Comment by javierriveracastro** [comment]
This should be solved. Closing it.
