### ISSUE TITLE
Change Cursor and add border when hovering over the icon

### ISSUE THREAD

**Issue by kristianserrano** [javierriveracastro/betteroll-swade#41]
For new players, it's not obvious that clicking the icon does something different than clicking the text. The icon looks just like its an icon rather than a button. Changing the cursor and adding a border on hover could help somewhat.

**Comment by SalieriC** [comment]
I think changing the cursour is sufficient.

**Comment by kristianserrano** [comment]
Alternatively, you could use [CSS filters](https://developer.mozilla.org/en-US/docs/Web/CSS/filter) to make subtle changes in the icons saturation, contrast, or brightness for example. This way it doesn't mess up @SalieriC 's themes. 😉

**Comment by javierriveracastro** [comment]
I have finally used the same shadow effect that the base system uses for consistency. Hope it plays well with Salieri personalization.
