### ISSUE TITLE
Change rolls from chat card based to dialogue based

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#411]
Hi.

This is the best automation module! Thank you!

I want to suggest a next step.

Replace the chat card for a integrated solution inside the system dialog box.
![image](https://user-images.githubusercontent.com/4999783/157433777-63a5b6cf-3db3-40bf-8661-00d50fd95565.png)

The system roll dialog box is very well done. Add the better rolls feature to it would make it amazing.

Thank you for everything.

**Comment by SalieriC** [comment]
I don't get why that would be "the next step". The chat card solution wasn't meant as a temporary solution, it just is the superior version in some ways. For example shareability: Everyone sees the card. This makes it infinitely easier to troubleshoot players, especially new ones. "I don't find the Wild Attack option." - "Oh it's right there at the bottom under Attack options."

> The system roll dialog box is very well done.

So are the chat cards.

**Comment by brunocalado** [comment]
> I don't get why that would be "the next step". The chat card solution wasn't meant as a temporary solution, it just is the superior version in some ways. For example shareability: Everyone sees the card. This makes it infinitely easier to troubleshoot players, especially new ones. "I don't find the Wild Attack option." - "Oh it's right there at the bottom under Attack options."
> 
> > The system roll dialog box is very well done.
> 
> So are the chat cards.

The chat cards are very good. But, after add everything they took all the chat. The dialog is much clean. Everything show up on the roll where you can check if anything was wrong.

**Comment by SalieriC** [comment]
> The chat cards are very good. But, after add everything they took all the chat.

That's an issue about redesigning the chat cards more than anything else. The chat cards really are what makes the module what it is. The chat cards in BR1 where much smaller but more restrictive. In BR2 they slowly became bigger and bigger because of the sheer amount of features added. "The next step" would be to redesign the chat cards, not to completely get rid of them as they are part of the modules identity.

**Comment by brunocalado** [comment]
> > The chat cards are very good. But, after add everything they took all the chat.
> 
> That's an issue about redesigning the chat cards more than anything else. The chat cards really are what makes the module what it is. The chat cards in BR1 where much smaller but more restrictive. In BR2 they slowly became bigger and bigger because of the sheer amount of features added. "The next step" would be to redesign the chat cards, not to completely get rid of them as they are part of the modules identity.

That would be nice too. But, The chat card still have dozens of buttons. I still think follow along with the system would be a better call.

**Comment by Razortide** [comment]
I am opposing the idea of any popup at all. The main idea behind that is, that in my games there are only so many rolls that require the application of a modifier. Let's say 20%. For those 20% where I might need to add a modifier I don't want to be bogged down by a popup for the other 80%. Effectively it doubles the effort I need to make for a roll from one click to two clicks (or click and enter).

**Comment by brunocalado** [comment]
> I am opposing the idea of any popup at all. The main idea behind that is, that in my games there are only so many rolls that require the application of a modifier. Let's say 20%. For those 20% where I might need to add a modifier I don't want to be bogged down by a popup for the other 80%. Effectively it doubles the effort I need to make for a roll from one click to two clicks (or click and enter).

The core system is working like that. You can always use a shotcut for a quick roll.

The idea is just improve the system dialog with better rolls options.

**Comment by Razortide** [comment]
I know that the core system works like that. That doesn't make it a good solution in my book. If you can show me how to apply shortcuts, I am very happy to hear it 👍 We can take this discussion to discord though.

**Comment by brunocalado** [comment]
> I know that the core system works like that. That doesn't make it a good solution in my book. If you can show me how to apply shortcuts, I am very happy to hear it 👍 We can take this discussion to discord though.

PF2, DND etc have the Control/Alt/Shift you can press before click on the roll button. This already work on br2, press shift and you get the system dialog.

Ok. We can go to discord.

**Comment by javierriveracastro** [comment]
There is already a very good automation module based on dialogs (SWADE Tools), moving there, IMHO, will make the community poorer and just remove options.

That said, card redesign should probably be a priority feature.
