### ISSUE TITLE
Player unable to roll soak when receiving damage.

### ISSUE THREAD

**Issue by sroakjp** [javierriveracastro/betteroll-swade#413]
Hit a player in combat tonight and applied damage. I can see the option to soak but the player cannot.

**Comment by Wigginns** [comment]
Does the player have bennies? They need to have bennies to soak. If I recall correct you also need to make sure that character is assigned to that player via the players menu in the bottom left.

![image](https://user-images.githubusercontent.com/3180645/158028529-293f39ce-b85e-4dce-b685-22f1aa930517.png)

![image](https://user-images.githubusercontent.com/3180645/158028535-406ff2f3-8f88-4bea-bfe1-9c599c09def9.png)

**Comment by sroakjp** [comment]
That was the issue.
