### ISSUE TITLE
Range calculation seems to be off on large tokens

### ISSUE THREAD

**Issue by gravagehulk** [javierriveracastro/betteroll-swade#414]
I don't know if this is Better Rolls 2 or the SWADE core system. As you can see in the screenshot below, the range calculation seems to calculate to the BACK of large tokens, not the front. I have tested this on several large tokens and a few huge. On the huge tokens, it adds a couple extra squares because it calculates to the rear of those tokens as well. For what it's worth, SWADE Tools seems to have this issue as well, though it calculates a different (lesser) range. The first range increment of the pistol in use is 5 squares.

<img width="1186" alt="Better Rolls Range" src="https://user-images.githubusercontent.com/69117052/157886197-56039726-ab27-49f1-b206-cfcb3f282463.png">

**Comment by SalieriC** [comment]
It's BR2 and I think I've noticed this as well.

**Comment by javierriveracastro** [comment]
Rigth now distance is calculated from the top left side of the token (before you ask this is what canvas.grid.measureDistance does by default). I have changed it to measure from token centers.

I can't find no rules on how you should measure distance in SW, and at least measuring from center seems more consistent. But I'm open to any other option.

**Comment by gravagehulk** [comment]
This is great! Thank you. I agree that it should be from the center of the token. This will be a huge help.

**Comment by SalieriC** [comment]
There are no rules in SWADE (or SaWo in general for that matter) regarding bigger tokens. I'd go for the square which is closest to the attacker on old tabletop but center should be just as good I suppose.
