### ISSUE TITLE
Feature Request: Allow players to roll soak for wild card allies under their control.

### ISSUE THREAD

**Issue by sroakjp** [javierriveracastro/betteroll-swade#416]
As is players can only roll soak rolls for the PC assigned to their player. Thus if they are in control of any NPC wildcards besides their own PC they cannot roll soak for those characters. It would be nice to allow players to roll soak for any character they are in control of.

**Comment by javierriveracastro** [comment]
This should be done. Only the first player (by order of login) who is owner of the actor will get the ability to roll for it. It is not convenient, but with the current card security model only one user (and all the GMs) can roll a card.
