### ISSUE TITLE
Rephrase Shaken wording

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#419]
Hello @javierriveracastro.

as discussed, In the German translation there is no such thing as "Recover from being Shaken" but the wording is rather bound to a specific character.

"XYZ gibt einen Benny aus und ist nicht mehr Angeschlagen" > "XYZ spends a Benny and is not Shaken anymore"

If I am unable to take a subject into the sentence it will sound very clunky in German, therefore I wondered if you could add the character name. This would allow me to create a more natural output.

Thank you!

**Comment by SalieriC** [comment]
I'm currently working on the unshake script and will take that into account @Razortide and @javierriveracastro. Please wait a day or two as I'm doing something more elaborate. But since I speak German, I may be able to come up with something that works in both languages. ^^'

**Comment by Razortide** [comment]
Damn! You guys are fast!
@SalieriC: I already added my suggestions to Weblate. It is following the German translations but it does not sound very natural to me (e.g.: Erholung vom Angeschlagen-Sein durch Ausgabe eines Bennys.)

EDIT: I think I found a working solution.

**Comment by SalieriC** [comment]
Your edit confuses me @Razortide. Do you still need the actors name in the text?

**Comment by Razortide** [comment]
Hm, I would love to hear your opinion @SalieriC . I went with:

"Erfolgreiche Willenskraftprobe: Der Charakter ist nicht mehr Angeschlagen." and "Benny ausgegeben: Der Charakter ist nicht mehr Angeschlagen."

I still think this is a bit clunky and would prefer to have another solution. What do you think?

**Comment by SalieriC** [comment]
@Razortide: I mean... It's German, what else can we expect? You could phrase it in first person or integrate the first part into the sentence, but even with the actors name, it doesn't sound great:
> Der Charakter erholt sich von Angeschlagen mit einer erfolgreichen Willenskraftprobe.
> Der Charakter ist, nach einer erfolgreichen Willenskraftprobe, nicht mehr Angeschlagen.
> X erholt sich von Angeschlagen mit einer erfolgreichen Willenskraftprobe.
> X ist, nach einer erfolgreichen Willenskraftprobe, nicht mehr Angeschlagen.
> Du erholst dich von Angeschlagen mit einer erfolgreichen Willenskraftprobe.
> Du bist, nach einer erfolgreichen Willenskraftprobe, nicht mehr Angeschlagen.

None of these sound really good. ("erholt sich von Angeschlagen" was the common wording before Ulisses took over, don't know what wording they use/prefer.) I'd probably go with one of these without any particular preference:
> Erfolgreiche Willenskraftprobe: Der Charakter ist nicht mehr Angeschlagen.
> Der Charakter erholt sich von Angeschlagen mit einer erfolgreichen Willenskraftprobe.
> Der Charakter ist, nach einer erfolgreichen Willenskraftprobe, nicht mehr Angeschlagen.

I'm just glad I use the English version right now. XD

**Comment by Razortide** [comment]
So, I found two version that sound like good phrasing:

A) Razortide erholt sich mit einer erfolgreichen Willenskraftprobe und ist nicht mehr Angeschlagen
B) Der Charakter gibt einen Benny aus und erholt sich. Er ist nicht mehr Angeschlagen.

I would love to get rid of "der Charakter" in favor of the actual name, but that should work. I leave it to you guys if you want to pursue it further or close the issue.

**Comment by SalieriC** [comment]
@javierriveracastro: It's a design question now, do you want to include the characters name or would you prefer not to?

**Comment by javierriveracastro** [comment]
Including the name seems sane and little work. It will also look better in English, IMHO.

**Comment by javierriveracastro** [comment]
Done. Let's see it weblate can merge it.
