### ISSUE TITLE
Modify the behavior of clicking on text to use Better Rolls

### ISSUE THREAD

**Issue by kristianserrano** [javierriveracastro/betteroll-swade#42]
Ideally, clicking on the text of a Trait or weapon should trigger Better Rolls rather than having to depend on the icon. In fact, because of the visual presentation of the icons, it's not obvious to new players that they are clickable or yield different outputs (see issue #41 ).

I'd even argue that if you could modify the text click behavior, you don't need the icons at all, eliminating confusion about what to click while also cleaning up the UI.

**Comment by javierriveracastro** [comment]
As I said in discord, overriding default functions is prone to errors and breakages on system updates. I'll rather not do it. Closing the issue.
