### ISSUE TITLE
Consider using backtick instead of apostrophe in BR2 macros

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#420]
BR2 macros currently use apostrophe (`'`) as a delimiter. The apostrophe however is a common character in names as well. Using the backtick (``` ` ```) would thus prevent problems with names including an apostrophe. The backtick should be less likely to appear in names.

**Comment by javierriveracastro** [comment]
Do you mean in macros created by drag and drop?

**Comment by SalieriC** [comment]
Exactly.

**Comment by javierriveracastro** [comment]
There are little names used in macros, I only found then in attribute names and when calling system rolls in objects but done. I keep quotes around ids as it is clearer and ids should be just numbers and letters.
