### ISSUE TITLE
Automatically apply modifiers for entangled and bound statuses

### ISSUE THREAD

**Issue by basic-element** [javierriveracastro/betteroll-swade#421]
Currently, the distracted and vulnerable statuses work. When a distracted actor rolls, BR2 applies -2 labeled as status. Also if the target is vulnerable, BR2 gives a +2 and labels as vulnerable.  If a character is distracted or bound rolls, BR2 should also automatically apply -2 and should also be labeled as status since they are implicitly distracted. If the target is bound, BR2 should give a +2 and label the target either as vulnerable or bound. Labeling as vulnerable makes sense since that is also implied when being bound, but either label is fine.

**Comment by SalieriC** [comment]
I'd argue that it would be better to just add the proper status effects along with Distracted and Bound as it is the expected behaviour. The rules explicitly state that Vulnerable and/or Distracted are applied with these.

**Comment by basic-element** [comment]
The problem with adding the distracted and vulnerable statuses is that by default, these effects automatically expire after the end of the actors next turn. Entangle and Bound effects have no expiration. They must break free. Some it is very cumbersome to keep adding distracted and vulnerable after it automatically expires.

**Comment by SalieriC** [comment]
Sounds like a core problem to me. Bound and Entangled should probably force activate their respective status effects.

**Comment by javierriveracastro** [comment]
I agree with SalieriC, this is better solved in core. I'll try to reach them.

**Comment by javierriveracastro** [comment]
SUCC should also be able to solve this when modified status are done.

**Comment by javierriveracastro** [comment]
I have proposed this to be added to system in the league discord with a small code sample. I'll close this issue. If it is not solved in system then feel free to open it again.
