### ISSUE TITLE
Automatically apply modifiers for entangled and bound statuses part 2

### ISSUE THREAD

**Issue by basic-element** [javierriveracastro/betteroll-swade#423]
Sorry for opening up another issue, but I couldn't update the original since you closed it. I just wanted to mention that for consistency purposes, if the decision is to have entangle and bound create the implied statuses of distracted and vulnerable automatically, then I believe Stun should behave the same way. Currently BR2 recognizes Stun and automatically applies a +2 and labels it as vulnerable even though the vulnerable status is not applied. This was what I was proposing for bound. So to keep it consistent, BR2 should NOT assume Stun means they are vulnerable and apply the +2 and the core system should also automatically apply the distracted and vulnerable statuses (distracted expires automatically after the end of their next turn). Thanks.

**Comment by javierriveracastro** [comment]
That makes sense. Let's wait until I have an answer from Flo.

**Comment by javierriveracastro** [comment]
Ok, this issue is going to be tackled on system. So I'm closing it here.
