### ISSUE TITLE
Confused about doing something wrong on wild attack.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#425]
(Sorry for the title: I can't figure out the right wording)
I am modifying wild attack and have found something not working as I would expect. The idea is to have 2 wild attacks 1) the normal wild attack but will only show when the person is not berserk. (That works fine).
```{"id":"5WTKa",
"name":"Wild Attack",
"button_name":"BRSW.WildAttack",
"skillMod":"2",
"dmgMod":"2",
"and_selector":[
{"selector_type":"skill",
"selector_value":"fighting"},
{"selector_type":"item_type",
"selector_value":"weapon"},
{"not_selector":[
{"selector_type":"actor_has_effect",
"selector_value":"Berserk"}]}],
"self_add_status":"Vulnerable",
"group":"BRSW.AttackOption"}
```
and 2) the same wild attack only appears when the actor is berserk. The difference is that it is always on.
```{"id":"5WTKb",
"name":"Wild Attack,Berserk",
"button_name":"BRSW.WildAttack",
"skillMod":"2",
"dmgMod":"2",
"and_selector":[
{"selector_type":"skill",
"selector_value":"fighting"},
{"selector_type":"item_type",
"selector_value":"weapon"},
{"selector_type":"actor_has_effect",
"selector_value":"Berserk"}],
"defaultChecked":"on",
"self_add_status":"Vulnerable",
"group":"BRSW.AttackOption"}
```
This also works as intended, but the (self_add_status : Vulnerable) stops working. I can't figure out what I am doing that is blocking the self_add_status. Any ideas?

**Comment by javierriveracastro** [comment]
Capitalization? I'd have to try it.

**Comment by javierriveracastro** [comment]
Yes, condition names are case sensitive, it works if I use ""self_add_status":"vulnerable". I'm not sure that I should change this in br, as this is a Foundry core thing.

**Comment by grendel111111** [comment]
Thanks. It did fix it, For some reason in the first one it doesn't need to be lower case and still works. That is what got me confused. I don't think it needs to change in BR.
