### ISSUE TITLE
Add Armor Piercing option for damage mod/override in Global Actions

### ISSUE THREAD

**Issue by basic-element** [javierriveracastro/betteroll-swade#427]
This stems from the fact core system has no field for AP on powers (and this is a core system power modifier option). Ideally it will be added as a field for powers. But, I was thinking it would still be useful for Global Actions to have an option to change AP value since we could have other situations where an edge or some other situation could change AP. We have damage modifiers, so why not add AP modifiers?

**Comment by javierriveracastro** [comment]
Done
