### ISSUE TITLE
Wild die and extras can be confussing

### ISSUE THREAD

**Issue by kristianserrano** [javierriveracastro/betteroll-swade#43]
If the Wild Card checkbox is unchecked, Better Rolls still rolls a Wild Die for Trait rolls. It should be checking to see if the checkbox is checked before including a Wild Die.

**Comment by SalieriC** [comment]
It should not and I believe this is an intentional feature in case you need a group roll, which cannot be done using Better rolls otherwise since there is no roll window.

**Comment by kristianserrano** [comment]
If you need Group Rolls, then mark it as a Wild Card.

**Comment by SalieriC** [comment]
If you don't need the group roll, then don't look at the Wild Die.

**Comment by kristianserrano** [comment]
Fair enough.

**Comment by javierriveracastro** [comment]
Anyway, this is clearly confusing new users. I will mark the discarded dice more clearly. If I still get this issue afterwards I'll seek for another solution, like making it optional or showing the second dice only when clicking the result.

**Comment by javierriveracastro** [comment]
12 days without news... I'll close this. Hope that it is really fixed and things are clear now.
