### ISSUE TITLE
Adding Hooks

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#430]
I'd like to have the following hooks to allow SWIM to add its immersion features to be used with BR2 more easily:

- [x] After applying damage (`message`)
- [x] After applying Shaken/damage (`message`)
- [x] After Soaking (`message`)
- [x] After applying Incapacitated / Bleeding Out (`message`)
- [x] After removing Stunned (`message`)
- [x] On placing a template from an item roll (`message`, `templateType`, `location`)
- [x] On applying combat injury AE (`message`, `combatInjuryAE`, combat=true, permanent=false)
- [x] On applying (semi-)permanent injury AE (`message`, `injuryAE`, combat=false, permanent<sub>boolean</sub>)

Mind the "after". If `message` would include a concise property that gives the exact degree of success and failure that would be the best possible solution and then "after" could be replaced with "on" or "when". But if I can't get that in the message, I need "after".

**Comment by javierriveracastro** [comment]
Ok, let's start with the damage one, and see if it is useful to you.

**Comment by javierriveracastro** [comment]
There are two places for the first hook, just after this line:

https://github.com/javierriveracastro/betteroll-swade/blob/31c305c28a8f029c5533d928202b9ebe120d0b4a/betterrolls-swade2/scripts/damage_card.js#L160

This will be called after damage and status are applied, when first clicked and after each soak roll. It doesn't have access to the message, but it does have access to lots of useful data.

Or just after this:
https://github.com/javierriveracastro/betteroll-swade/blob/31c305c28a8f029c5533d928202b9ebe120d0b4a/betterrolls-swade2/scripts/damage_card.js#L46

This have access to the message, but will only be called when the damage card is shown and not when soak rolls change the damages. It does have access to the message, but it have much less interesting info.

Which one do you prefer?

**Comment by SalieriC** [comment]
Is it either or? I mean, it's not like we have to pay for each line of code, is it? ^^'
I'd prefer to have both, as stated above. I guess
> After applying Shaken

could/should be replaced with

> after applying damage

So yeah, both of the variants you suggest are very interesting to me.

**Comment by javierriveracastro** [comment]
We do pay for each line of code. Both in performance and code complexity. But it is a low enough price. I'll add both hooks.

**Comment by javierriveracastro** [comment]
Added two hooks:

`    Hooks.call("BRSW-AfterShowDamageCard", actor, wounds, message);`

and 

`    Hooks.call("BRSW-AfterApplyDamage", token, final_wounds, final_shaken,
        incapacitated, initial_wounds, initial_shaken, soaked);`

**Comment by javierriveracastro** [comment]
The second one will also be called after soaking. I believe it addresses all first four options.

**Comment by SalieriC** [comment]
That's awesome.
I found one more thing I need though: Injuries.
Could you include the AE from combat injuries as well as a new hook with the AE when (semi-)permanent injuries from incapacitation are applied please? To support healing these using SWIM I need a fool-proof way of getting and adjusting them. actor update hooks are not reliable enough.

**Comment by javierriveracastro** [comment]
The template thing. I can do a hook exactly when placing as core is in control then. The last thing that br do with the template is creating the "preview", i.e. the thing that the player can move and place. So the hooks can be just before the preview or just after the preview is created.

But I have no control of when the users places the preview and when it is converted in a proper template.

**Comment by javierriveracastro** [comment]
Also what is the different between one injury and the other?.

**Comment by SalieriC** [comment]
> But I have no control of when the users places the preview and when it is converted in a proper template.

May that be enough to change the template? Like adding stuff before it is placed, which stick after placing it? If so, that would be great.

> Also what is the different between one injury and the other?.

Well, they are different in SWIM as SWIM offers functionality to remove wounds depending on their source, for you it might not matter depending on how you've set up a script. I just need the following when an injury is created:
- is it a combat injury (from the gritty damage setting rule)?
- is it a semi-permanent injury (from incapacitation roll being a success or raise)?
- is it a permanent injury (from incapacitation roll being a failure)?

**Comment by javierriveracastro** [comment]
Added a hook before letting the player place the template:

`Hooks.call("BRSW-BeforePreviewingTemplate", template, ev)`

template holds the Foundry template and ev the click event that created the template.

**Comment by javierriveracastro** [comment]
The two hooks remaining are not possible right now. There is no stun removal card and effects are only applied in the current hook. So I will close this issue, if I'm wrong feel free to reopen it.

**Comment by SalieriC** [comment]
Reopening as discussed on Discord. For the Reference:

By the system , there are in fact three different kinds of injuries:
- Combat Injuries (applied from getting wounded with the Gritty Damage setting rule),
- Temporary Injuries from becoming Incapacitated and
- Permanent injuries from becoming Inc.
- 
It is not possible to determine the type by a running combat as you can get all three types during a combat and out of combat. The only way to determine the type of injury is when it is applied:

- Is it applied from getting wounded but not becoming Inc and Gritty Damage is active? -> Combat Injury.
- Is it applied from Inc but the Vigor roll was >=4? -> Temporary Injury.
- Is it applied from Inc and the Vigor Roll was <4 (but not a crit fail)? -> Permanent Injury.

There is no way for any module to know the type of injury other than BR2.

Unstun hook is just a far future reference so I don't forget if you would introduce a feature to roll for it (happy to provide code snippets to that as usual but that's another issue). =)

**Comment by javierriveracastro** [comment]
Unstun done

**Comment by javierriveracastro** [comment]
And this should be finally completed.
