### ISSUE TITLE
Unshake spirit roll doesn't use some statuses 

### ISSUE THREAD

**Issue by basic-element** [javierriveracastro/betteroll-swade#431]
When clicking on the "The character is shaken" link in the chat card and then rolling spirit on the new chat card, it does not use the negative modifiers for distracted and wounds. Not sure what else it is ignoring.

**Comment by javierriveracastro** [comment]
It does for me. I'm quite sure as my Spirit d4 character was out of bennies and spend stun locked half combat this Friday :)

Or at least it does wounds, not sure about distracted.

Yes it does both. Something else is going on here. Can you give me more info?

**Comment by basic-element** [comment]
Looks like it's a problem with NPCS with unlinked actors. Try dragging an NPC token that is unlinked and try it again. That one doesn't work for me.

**Comment by javierriveracastro** [comment]
Done.
