### ISSUE TITLE
All Thumbs is active by Default

### ISSUE THREAD

**Issue by TheBiggerBadderBear** [javierriveracastro/betteroll-swade#433]
The Hindrance 'All Thumbs' is active on all rolls (trait, skill, attacks) by default. 

Whilst we realise we can disable it in Global Actions, we'd prefer it to be off by default, though still show on the Better Rolls card, and activated as the player/gm determine.

Thank you!

![allthumbs](https://user-images.githubusercontent.com/76487459/164216716-4720b90d-1b80-4c0b-b9a9-d0da993a48a2.jpg)

**Comment by javierriveracastro** [comment]
That was discussed a while ago. It is very setting dependent, sometimes all thumbs applies most of time, in fantasy close to never.

Unluckily there is no easy way to solve it right now. You can disable it from the actions button in the setting and add you own world action that is not checked by default.
