### ISSUE TITLE
Targeting enemy with powers is using parry as TN

### ISSUE THREAD

**Issue by basic-element** [javierriveracastro/betteroll-swade#436]
Not sure what happened but I updated to the latest version and now when I target a character and roll a power, it is using a TN of parry instead of a standard 4.

**Comment by SalieriC** [comment]
This should only happen when adjacent and then also only use the Parry of the adjacent token (the highest if there are more than one). It does happen in range though, I can reproduce. Needs fixing.

**Comment by javierriveracastro** [comment]
I bet it is related to the modification of the range calculation to use center of tokens. It didn't show on test combats, so it if it is related to this it is likely happening just at some ranges.

**Comment by SalieriC** [comment]
Yeah, on a range of 159 grid squares I still get Parry as the target number as well as on shorter range of two or three grid squares. I could test this for more exorbitant ranges but...
