### ISSUE TITLE
Incapacitation (Sorry just a question)

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#437]
Is it possible to trigger the BR2 incapacitation card from outside BR2? I am making a poison macro and if they are incapacitated I want it to start the BR2 card and run from there.  But it would also be useful if a character became incapacitated from exhaustion or another cause.

**Comment by javierriveracastro** [comment]
No, it was not. Added an option to be able to do it to git.

```game.brsw.create_incapacitation_card(token_id)```
