### ISSUE TITLE
Thrown weapons are rolling as unskilled.

### ISSUE THREAD

**Issue by Freewolf2000** [javierriveracastro/betteroll-swade#44]
For characters or NPCs when rolling from the icon in the inventory, it is rolling the weapon as unskilled rather than with Athletics. Seems it is always looking for the Shooting skills for any ranged weapon. Rather than Shooting or Athletics depending.

**Comment by SalieriC** [comment]
See #37.

**Comment by javierriveracastro** [comment]
It should use shooting unless @str is in the damage formula for the weapon. Then it will look for Athletics. If you post weapon details I can look for a solution.

**Comment by javierriveracastro** [comment]
With no more info and markint closign this as a dupplicate of #37 .
