### ISSUE TITLE
Bonus die is rolled along with a d6 if set other to a d6 on a weapon.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#442]
If a weapons bonus die is set up to be other than d6 on a weapon, it will be rolled alongside a d6 on a raise damage roll. The Bonus die should instead overwrite the d6.

**Comment by javierriveracastro** [comment]
Umm, I can't reproduce it. Can you give more details.

**Comment by SalieriC** [comment]
I logged in to test once again and now I can't reproduce it either. How strange. 🤔
