### ISSUE TITLE
Global Action selector for `faction`

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#443]
As discussed on Discord, a selector for faction using the way BR2 determines whether or not to roll powers against parry would be a useful addition for certain things like _arcane protection_. It could look like this:

```json
        {
            "selector_type": "faction",
            "selector_value": "other"
        }
```
and token and target are the same (i.e. both player owned or same disposition, whatever BR2 uses), do **not** apply the global action. Or do apply if only one is player owned (or other disposition) but the other not.
Respectively if
```json
        {
            "selector_type": "faction",
            "selector_value": "same"
        }
```
*do* apply the global action if both are player owned (or same disposition). And so on.

**Comment by javierriveracastro** [comment]
Done
