### ISSUE TITLE
Allow World Action Selectors to access Item "additional stats"

### ISSUE THREAD

**Issue by TheLaslo** [javierriveracastro/betteroll-swade#444]
In the SWADE Configuration you can define additional stats on actors and items.  As an enhancement it would be helpful to use those fields as selectors for World Actions.

**Comment by javierriveracastro** [comment]
This is done, should be in next version.

**Comment by TheLaslo** [comment]
Thanks Javier, I appreciate how quickly you add features.
I wanted to point out that items can have additional stats as well.
The item stats was what prompted me to ask for this feature.

**Comment by javierriveracastro** [comment]
Done in items too.
