### ISSUE TITLE
Joker bonus applied if action held and acted after/before joker turn

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#445]
This is a pretty niche bug and I only saw it during testing:
If token a is on hold and is set to act immediately or after as long as a combatant with a joker has its turn, then a will get the joker bonus as well, probably because BRSW only looks at the suit or card value in the flags(?). The system does not have this problem.

To reproduce:
1. Set up a combat with at least two combatants.
2. Set any of the combatants to hold.
3. Skip rounds until a joker comes up or assign a joker to any non-holding combatant.
4. move current turn to the combatant with the joker.
5. Click on either act now or act after current combatant..
6. Make any roll with the combatant which was on hold earlier.

**Comment by javierriveracastro** [comment]
Solved. I hope. I hate joker mysteries.
