### ISSUE TITLE
Use re-targeting by drag & drop damage rolls

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#446]
Hello Javier,

as mentioned by penllawen here: https://discord.com/channels/170995199584108546/715780900322803753/974270982695043152

it would be very cool if, after rolling the skill dice you could drag & drop the damage or raise damage button on a token that will receive that damage (therefore, the target will change).

**Comment by javierriveracastro** [comment]
I was more thinking about draggin the dice, but yes, damage buttons will also work.

**Comment by Razortide** [comment]
Which dice? :D

**Comment by javierriveracastro** [comment]
The result dice, the same you can click to change its value.

**Comment by Razortide** [comment]
I was totally oblivious that this would work! :)
In that case it would need to recognize if a raise is in order.

**Comment by javierriveracastro** [comment]
Yes

**Comment by javierriveracastro** [comment]
Done, using buttons.
