### ISSUE TITLE
BR2 breaks Link from Quick Access Active Effect to source

### ISSUE THREAD

**Issue by Razortide** [javierriveracastro/betteroll-swade#449]
Hello Javier,
with the latest SWADE update, the whole Quick Access have been revamped. You can now add Active Effects to the Quick Access and they even have a link to their source (e.g. an edge). With vanilla SWADE you can click on the AE entry text in the Quick Access and the source will open (so if you click on the Brave Active Effect, it would open the Brave edge item).

When BR2 is activated the following error is thrown:
![image](https://user-images.githubusercontent.com/35796457/170221031-76311a9b-63bf-44c7-8b65-8f586f5d57df.png)

It would be great if it would be possible to preserve the opening of the source item.

**Comment by SalieriC** [comment]
While at it, it should be considered to make right click on the AE open the AE itself. This is BRSW behaviour for any other thing except AEs which is a consistency problem.

**Comment by javierriveracastro** [comment]
This should be solved.
