### ISSUE TITLE
Custom Layout for Modifiers

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#451]
Hi.

Is it possible to add to options a place to edit the chat modifiers?

So, you can make then like this:

https://user-images.githubusercontent.com/4999783/170740549-cfd6dc6b-5832-4ad3-a07d-0a251f375fb5.mp4

You can <i class="fas fa-dice" title="Trait roll modifier:"></i> on the lang folder, but change it in the options would be easy.

Tks

**Comment by javierriveracastro** [comment]
I'm not really sure this could be done in a way that works nicelly with translations, but I'll add it to the backlog.

**Comment by brunocalado** [comment]
> I'm not really sure this could be done in a way that works nicelly with translations, but I'll add it to the backlog.

Some modules create a space in module settings to replace strings. This replace the need for translation. Because you can do it.

**Comment by javierriveracastro** [comment]
This is harder than it looks. When the sidebar is rendered, settings are not yet available, so they can't be read there.

The only way that i see is to change this afterwards (when ready).

**Comment by javierriveracastro** [comment]
Done.

**Comment by brunocalado** [comment]
Hi. I can only add text? Is it not possible to add an icon?
![image](https://user-images.githubusercontent.com/4999783/172223063-e5cc10ed-8df1-4039-9557-e6530b430c0a.png)

**Comment by brunocalado** [comment]
Estou tentando usar isso:
`<i class='fas fa-star' title='Modificador de rolagem de característica'></i>`

**Comment by javierriveracastro** [comment]
Oh, it is inserted as text not html.

**Comment by javierriveracastro** [comment]
And now it should support it.

**Comment by brunocalado** [comment]
br2: 2.73 

Is this correct?
![image](https://user-images.githubusercontent.com/4999783/172745913-a0660ebc-392d-449e-9417-fddc03ddba5a.png)

**Comment by brunocalado** [comment]
![image](https://user-images.githubusercontent.com/4999783/172745996-5883b744-bf97-4804-aab2-25444f609bf9.png)

**Comment by javierriveracastro** [comment]
The window thing no, It should not change that. The bug is solved in git, I have not yet released it. If you are in a hurry I can try to make a release tomorrow.

**Comment by brunocalado** [comment]
> The window thing no, It should not change that. The bug is solved in git, I have not yet released it. If you are in a hurry I can try to make a release tomorrow.

Take your time. I thought I was ready.
