### ISSUE TITLE
Roll fails if another token is selected

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#454]
Players who open their actor sheet trying to roll from it while having another token selected causes an error and the roll won't be made.
![image](https://user-images.githubusercontent.com/1230041/171963623-7efb52ae-94c9-4efe-a234-8131605b82de.png)

**Comment by javierriveracastro** [comment]
In git I hope. Probably something introduced by the non-eucluidean meassurement

**Comment by javierriveracastro** [comment]
I can't reproduce it. Something else is going on. Can you give me more details? What skill are you trying to roll? Is anything targeted?

**Comment by javierriveracastro** [comment]
It looks like measure distance has been called without origin token... Maybe he opened the sheet with 'c' and there is no token on the canvas but he is targeting something?

**Comment by javierriveracastro** [comment]
Should be solved.
