### ISSUE TITLE
Document `target_has_effect` in world global actions documentation.

### ISSUE THREAD

**Issue by jja006** [javierriveracastro/betteroll-swade#458]
target_has_effect for world global actions would be useful when rolling spellcasting against targets who are under the effect of the Arcane Protection core SWADE power, for example. Arcane Protection in particular has been a tough effect for us to automate or track in Foundry otherwise.

This could work similarly to actor_has_effect which already exists, as well as target_has_edge, for example.

I'm thinking we could then make a world global action like the following (untested/just a guess, I'm new to this module).

{
  "id": "vs arcane protection",
  "name": "vs arcane protection",
  "button_name": "vs arcane protection",
  "skillMod": "-2",
  "and_selector":[
    {
      "selector_type":"target_has_effect",
      "selector_value":"Arcane Protection"
    },
    {
       "selector_type":"skill",
       "selector_value":"Spellcasting"
    }
  ],
  "group": "BRSW.TargetBuffs"
}

...I'm not sure yet how you would account for the success vs. raise of Arcane Protection, but at worst it could be two different global actions, identified accordingly.

Also, there might be a (much?) easier way to do this. I realize it's not fully automating arcane protection, but at least it would make the rolls a little easier vs adding/tracking an additional completely manual modifier.

**Comment by SalieriC** [comment]
`target_has_effect` already exists, works similar to `actor_has_effect`. Just needs documentation.

**Comment by jja006** [comment]
woot! thank you very much. Hopefully, I'm on the right track here then.

**Comment by jja006** [comment]
ack sorry, just realized you changed the issue to the req. for doc. reopening accordingly, my apologies.

**Comment by SalieriC** [comment]
All good, I'm done already. I've documented it here: https://github.com/javierriveracastro/betteroll-swade/blob/version_2/docs/global_actions.md

You can check SWIM for examples: https://github.com/SalieriC/SWADE-Immersive-Macros/blob/main/documentation/Better%20Rolls%202%20integration.md#automating-deflection
