### ISSUE TITLE
Injury Table

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#459]
Hi.

Is it possible to add an option to choose a table for injury?

So, this button would roll the selected table and show the result.
![image](https://user-images.githubusercontent.com/4999783/172899044-4b0d736a-da06-4d4f-8b3b-fdee584076ed.png)

This is nice for the oficial modules; But, is also great for homebrew.
![image](https://user-images.githubusercontent.com/4999783/172899222-02904706-905a-4f81-a4d8-b01028ca5464.png)

Tks

**Comment by javierriveracastro** [comment]
The problem is that this is not a simple table. It includes the states caused by the wounds.

**Comment by brunocalado** [comment]
> The problem is that this is not a simple table. It includes the states caused by the wounds.

I didn't understand.

**Comment by grendel111111** [comment]
If you send it to an injury table the table will say you take 1 wound, or you are shaken and stunned. The BR2 injury table works more like a macro. It tells you what has happened, but also places those effects on the character. So it will apply stunned and shaken so you don't have to.

**Comment by javierriveracastro** [comment]
Not wounds but effects. If you are battered it will lower the strenght or whatever

**Comment by brunocalado** [comment]
> If you send it to an injury table the table will say you take 1 wound, or you are shaken and stunned. The BR2 injury table works more like a macro. It tells you what has happened, but also places those effects on the character. So it will apply stunned and shaken so you don't have to.

How do this then? After the player roll the INJURY TABLE on the br2 button, I have to check the book table to know what really happened. Am I mising something?
![image](https://user-images.githubusercontent.com/4999783/173232423-91d47a05-6fd5-493d-887b-c1e64a981117.png)

**Comment by javierriveracastro** [comment]
It should add an Active Effect that automatically reduces the correct attribute. It doesn't add the Hindrances, but it does show an effect to help remember them. I should probably auto-favorite it now so it shows on the firs page.

That doesn't make a custom table impossible, but it should be something more complex than a simple Foundry rolltable.

**Comment by SalieriC** [comment]
A roll table is what I use in SWIM. It's a pain and prone to error as I have to look for keywords in the tables text. BR2 is much smarter in that regard. And if it's really only for reference, why not just add a single paragraph below the result shortly explaining what it means?

**Comment by javierriveracastro** [comment]
I don't want to get into problems with PEG (again) by referencing its text. So the table idea is a nice one. That way you can put anything there. But we need to find a way to link it to the correct AE.

The main problem is when you use gritty damage, if not the table is rarely used and the lack of AEs a minor problem. But with gritty damage it is really convenient to have the effects auto-apply.

**Comment by SalieriC** [comment]
Just mail Shane. I think he'd be okay with it. Also, if you paraphrase it, it shouldn't be a problem, copyright-wise. The sentence is copyrighted, not what it means.

**Comment by javierriveracastro** [comment]
This is not the place to start a rant, but it is not just about copyright.

**Comment by SalieriC** [comment]
Ofc.

**Comment by javierriveracastro** [comment]
I have added an option to use system the injury table instead of the builtin one. As this is changeable it also solves this bugs.

Note that those tables lack automation right now.
