### ISSUE TITLE
Singular Raise vs. Plural Raises when appropriate

### ISSUE THREAD

**Issue by kristianserrano** [javierriveracastro/betteroll-swade#46]
After [line 95 of betterrollsswade.js](https://github.com/javierriveracastro/betteroll-swade/blob/master/betterrolls-swade/scripts/betterrollswade.js#L95), add a check to determine if `${Math.floor(result)` is equal to 1 or greater than 1 to determine if the output should be `Raise` or `Raises` respectively.

I also recommend one exclamation point for cleaner readability.

**Comment by javierriveracastro** [comment]
Done.
