### ISSUE TITLE
Ammunition reload not working

### ISSUE THREAD

**Issue by CarWashMeNot** [javierriveracastro/betteroll-swade#461]
_I just posted this in the discordchannel FoundryVTT and was advised to open an issue here._

I am having a problem with automated reloading of weapons. As you can see in the picture, my mercenary has a laserweapon with the fitting ammunition in his inventory. When I select the weapon in the chat and click on "reload ammunition", I get an error that I do not have enough ammuniton in my inventory. 
It used to work exactly like this some weeks ago. Anybody seeing what I do wrong?
![issue](https://up.picr.de/43822284ml.jpg)

I double checked if the ammunition is set up right and triple checked if a have enough ammo in my inventory. 
It was assumed in the discord that the problem might be a trailing space somewhere.

**Comment by javierriveracastro** [comment]
In next version br2 will not break for extra spaces in munition. I don't know if it will solve your problem if it was caused by something else.
