### ISSUE TITLE
BR2 Settings- initial install configuration problem

### ISSUE THREAD

**Issue by TheLaslo** [javierriveracastro/betteroll-swade#462]
When starting with a new world and activating BR2 it appears that the configuration for the module doesn't exist until a setting is modified or anecdotally an actor's token is placed on a scene.

To reproduce:
 start with a new world
 activate the module
create a new Player Character
click on an attribute 
The system default dialog box opens instead of creating a BR2 card.

**Comment by javierriveracastro** [comment]
This should be solved.
