### ISSUE TITLE
Request - option to have effects ON (red state)

### ISSUE THREAD

**Issue by flynnkd** [javierriveracastro/betteroll-swade#464]
Specifically the Unstable Platforms should be set ON as it only shows when it applies. An option in the configure of the effects to have them ON  would be nice also. Great module.

**Comment by javierriveracastro** [comment]
Sorry I don't understand what you are trying to say here.

World actions can now be configured to be selected by default (on red).

Unstable Platform itself can't be automated. There is no way that the module can know if you are riding a horse or some pure "roleplay" situation makes it necessary. And most of the time it doesn't apply, so having it enabled by default would mean that you have to unmark most of the time that you want to roll.

**Comment by flynnkd** [comment]
Ahh, my fault, got myself confused.  I created a Mounted condition in CUB
and then a check in BR2 for 'if Mounted' and forgot they aren't linked. It
was just co-incidence that it sort of showed during my testing and I
misinterpreted it.

While I am here tho, is there a way to limit skills, eg based on Riding
being lower and acting as a limiter?


Kevin Flynn
Mob: 0412380188
www.flynnkd.com
Facebook: https://www.facebook.com/mappingcards
Discord: flynnkd#7958
“liberalism is the worst form of government, except for all the others.”

**Comment by javierriveracastro** [comment]
Nope not yet. This is a quite interesting feature request, please open another issue asking for it.
