### ISSUE TITLE
Global Actions: Skill selector does not respect item skill

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#465]
I have noticed that the skill selector applies to the skill chosen by BR2, not the one provided by the item. This can be a problem in some cases, i.e. when the actor does not have the skill that is set on the item. In this case the action will not shown on the chat card because BR2 chooses untrained instead, thus not finding the global action.
I see two possible solutions: Either BR2 can look for both, the skill it chooses and the one determined by the item or adding a new selector that respects only the skill determined by the item.
The first solution would cover all existing actions but could possibly break something users were dealing with before. The second solution would not really cover the problem itself, just provide a way to bypass it.

**Comment by javierriveracastro** [comment]
This is tricky. BR2 `skill`modifier affects the skill being rolled, not the one of the item. It should work this way to allow edges that modify untrained, to work with skills when rolled directly and just for consistence.

Adding another selector could work, but as you stated it will be confusing. Can you tell me what are you trying to achieve? Which edge or hindrance are you trying to implement? Maybe there is a better way.

**Comment by SalieriC** [comment]
I was trying to add a text specific to and dependent on the skill specified on the item. Could be done by doing a text search in description but very tough and would break in some cases, thus not really feasible. 
Well, if that really is the case I'd go for the second option and document it properly, making it very clear that skill is the skill chosen by BR2.

**Comment by SalieriC** [comment]
I'll close this for now. I've added a bit of code that warns users if the skill is set to none (localised) which should suffice for now. In the future it might be worth taking a look at it again and how conditional text on global actions could be improved.
