### ISSUE TITLE
Request: Trait limiters and mods.

### ISSUE THREAD

**Issue by flynnkd** [javierriveracastro/betteroll-swade#468]
Riding skill acts as a limiter to  a number of other skills, an option to implement a limiter would be nice.
Also, a way to modify a trait dice, up or down, as provided by (eg) the Boost spell (might be there actually but too busy to check at present sorry).

**Comment by javierriveracastro** [comment]
You can use active effects to modify a trait. The system itself does that no need of modules. SWIM (a very nice module based on macros) makes this easy and convenient.
