### ISSUE TITLE
Feature Request: "Add Trait Die"

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#47]
Frenzy, weapons with RoF>1 and certain other edges and powers allow to roll more than one trait die. I think the module would greatly benefit from a way to roll multiple trait dice. For Example by adding a button in the result of a skill check to add one or more additional trait di(c)e to the roll that was made.

**Comment by javierriveracastro** [comment]
It already does it. Or it should. Try it in a weapon with a rof higher than 1.

**Comment by SalieriC** [comment]
That is neat thank you. But a way to have that for powers would be nice as well...

**Comment by javierriveracastro** [comment]
Depends on #52

**Comment by javierriveracastro** [comment]
Done, at least for rolling 1, 2, 3 or 5 dice. Other numbers should wait for the "complex roll window".
