### ISSUE TITLE
Trait modifiers on items like `+1+1` are not interpreted correctly

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#471]
In the case above BR2 just adds +1. Ideally it should check for each plus and minus and apply the modifiers appropriately. Either by adding them up or applying them separately. The system roll handles that just fine. This is especially important in case of Active Effects (since the modifier fields on items are strings, AEs can't just add one but need to add +1 instead.

**Comment by javierriveracastro** [comment]
That's highly inconsistent with trait modifiers and likely a system bug.

Anyway, I now evaluate item modifiers as "mini-rolls", so now this should work, as anything that can be written in a roll expression.
