### ISSUE TITLE
Wiki pages / documentation

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#472]
I have created a [wiki](https://github.com/javierriveracastro/betteroll-swade/wiki) for Better Rolls using the existing documentation pages. This gives a little more flexibility and is much more user friendly to navigate. The documentation thus becomes obsolete. Shall we remove it and link to the wiki from now on @javierriveracastro?

**Comment by javierriveracastro** [comment]
I'm not sure. The wiki is a github thing. If we are want or need to move to another place we will loose it.

But updating the documentation in two places is too much work and guarantee to be wrong in both places.

So yes, delete it, keep a short README (it is still the first page of the project) and add a link.

**Comment by SalieriC** [comment]
Done. Worst case we copy everything from the wiki over. It is markdown anyway, so not a big deal.
