### ISSUE TITLE
Shift actions activation on chat cards from none/white/red to none/red.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#473]
Currently actions on chat cards can have three states: disabled, active for next roll (white) and active for all rolls of that card (red). This has a very good application in the generic modifiers but for actions on cards it now doesn't make a lot of sense anymore. Usually a card represents one action and modifiers should always apply to that action. Also it gets confusing with modifiers like Wild Attack for example which the user expects to apply to trait and damage roll. Clicking twice thus is just counter-intuitive by now.

The modifiers on cards should be shifted from their current activation mode to a simpler, (hopefully) more intuitive activation mode where it either isn't (none) or is (red) active for the entire card.

**Comment by javierriveracastro** [comment]
I have changed so that the first click red selects it. I have retained the white option, but as a third click. So users will get the most used behaviour with just one click.

I don't know if it wise, but removing features makes me feel like a gnome developer.

I you really feel that removing white is best, feel free to reopen.

**Comment by SalieriC** [comment]
I just think it isn't really needed anymore. I for once never had a player using the white option on cards and never felt the need to use it myself but I suppose it won't hurt.

**Comment by SalieriC** [comment]
I'm going to reopen this issue as I think the generic modifiers above the chat message input should work the other way around (none -> white -> red). It makes for a minor inconsistency but I really don't think those generic modifiers should apply to all future rolls (only to the next roll for a single click). Feel free to close again if you disagree or can't stomach the inconsistency @javierriveracastro. =)

**Comment by javierriveracastro** [comment]
Done
