### ISSUE TITLE
Persistent BR2 Chat Message

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#475]
Hi!

I don't know if this is possible, but let explain the situation.

We create a br2 chat message. But, sometimes we use the chat before solve that message (nonsense, sharing rules, chatting). When this happen I have to scroll up to the current roll. 

Sometimes we just want to check a roll and run through the chat (br2 cards and regular chat use) is a little confunsing.

So, I want to know if is there a way to make the current br2 chat persistent. It always will move to the end of the chat. If this is crazy, is it possible to create a chat tab for br2?

Tks

**Comment by javierriveracastro** [comment]
Can't you just pop-out the message? Core foundry thing AFAIK.

**Comment by SalieriC** [comment]
> Can't you just pop-out the message? Core foundry thing AFAIK.

Foundry chat messages do not support that feature.

**Comment by javierriveracastro** [comment]
They did. Maybe they changed something.

**Comment by SalieriC** [comment]
I've been unable to use that for a very long time now. I thought you deliberately disabled it.

**Comment by javierriveracastro** [comment]
Nope, they also disabled in system rolls. I have to look into it, but you probably need to set something to make then popable.

**Comment by brunocalado** [comment]
I got a new idea.

**Comment by SalieriC** [comment]
> Nope, they also disabled in system rolls. I have to look into it, but you probably need to set something to make then popable.

It's `flags.core.canPopout`.
I think we should add it again to BRSW cards. At times this can make everything a little easier.

**Comment by javierriveracastro** [comment]
Done.
