### ISSUE TITLE
Weapon actions not applying damage

### ISSUE THREAD

**Issue by DreamingPhantasm** [javierriveracastro/betteroll-swade#476]
Hi!

I'm finding that weapon actions aren't applying damage. As an example, Double Tap's trait action does provide +1 to shoot and does take 2 shots instead of 1, but Double Tap's damage action does not add +1 to damage. As well, it doesn't matter what you select for shotguns - they will always do 3d6 damage. Having made weapons from scratch that should have no associated damage value and damage actions that are _not_ 3d6, the same thing happens - 3d6.

Edit:

This actually seems to be the case for global actions as well. Called Shots towards the head do not add +4 damage. It may also be the case for anything that affects damage - AP overrides don't take effect either.

**Comment by DreamingPhantasm** [comment]
And I've identified the culprit: this was caused by the selected actions clearing after rolling to hit. When I would go to roll damage, it would then pull the actions I had selected: absolutely none, because they'd just been cleared.

So! Is there a way to have a single click mark them as red, so they stay between the hit roll and the damage roll?

**Comment by SalieriC** [comment]
That is planned already, see #473. At some point the selection for only the next roll will replaced by all rolls for the card in question. White will only be available for the generic modifiers then. I'll close this ticket then. Thank you for letting us know though. =)
