### ISSUE TITLE
Use big death marker instead of small top left icon

### ISSUE THREAD

**Issue by PainfulByte** [javierriveracastro/betteroll-swade#479]
SWIM has a macro to mark a token as dead, the result is the topmost token here. BetterRolls2 for SWADE Combat automation marks the second token as dead, but with a small top left icon.

![image](https://user-images.githubusercontent.com/19226443/188498489-de56282a-e7fc-4e22-8678-cf39ce5885ac.png)

Could it be possible to use the big death marker functionality if SWIM is present instead of the small top left icon?

**Comment by SalieriC** [comment]
Thank you for your request. This is already done in Git, BR2 will use SUCC as dependency as a result. I'm thus closing this. Not sure when it will be released though.
Also thanks for using SWIM. =)
