### ISSUE TITLE
Automatically add Trademark Weapon bonus to attack roll

### ISSUE THREAD

**Issue by sanpats** [javierriveracastro/betteroll-swade#486]
Better Roll doesn't take into account of Trademark Weapon property in a weapon:
![image](https://user-images.githubusercontent.com/22677493/192085001-9e8ec27d-aee6-4d0f-8147-c9c2d1b3bee0.png)
"Regular" should give +1 to attack roll.
"Improved" should give +2.
![image](https://user-images.githubusercontent.com/22677493/192085074-8fce18b8-16a9-42c0-95b8-6c49fc04b944.png)

**Comment by javierriveracastro** [comment]
Done.

**Comment by sanpats** [comment]
For Foundry v9 or v10 or both?

**Comment by javierriveracastro** [comment]
Only v10, no more updates to v9. Sorry but it is really difficult to keep compatibility with both.
