### ISSUE TITLE
Feature request: allows shotsUsed to add cost on top of the item's base cost instead of overriding.

### ISSUE THREAD

**Issue by Joshmvii7** [javierriveracastro/betteroll-swade#488]
I'd like to be able to use shotsUsed to automate via global world actions the additional cost of power modifications. Right now shostsUsed: 1 makes the cost of the item 1, and the functionality I need is to have it add 1 to the cost of the Power or other item instead. This way I could use the same global action to add say the armor piercing power modification to a power that costs 1 and make it cost 2, or on a power that costs 2 base it would cost 3.

Thanks!

**Comment by SalieriC** [comment]
Closed as duplicate of #357.
Thank you for your time though. =)
