### ISSUE TITLE
Players can't see the Roll button (v10)

### ISSUE THREAD

**Issue by techogre** [javierriveracastro/betteroll-swade#489]
Foundry version 10.286
Savage Worlds Adventure Edition 2.0.3
Better Rolls For Savage Worlds 2.76
Compendium Folders 2.3.5
libWrapper 1.12.10.0
Savage Worlds Adventure Edition Core Rules 1.0.7

I (the GM) can see the Roll button when players roll a weapon or skill, but the players cannot see it.
Update: They see the button for a moment, then it disapears.

**Comment by javierriveracastro** [comment]
Sorry but BR2 is not yet updated to work with v10 (nor are core rules). Thank you for your report anyway.

**Comment by javierriveracastro** [comment]
This have been solved in git. If you want to help trying BR2 with v10, you can install a beta version from this manifest:

https://raw.githubusercontent.com/javierriveracastro/betteroll-swade/v10_test/betterrolls-swade2/module.json

You will also likely need the v10 compatible SUCC

https://raw.githubusercontent.com/SalieriC/SUCC/v10_test/succ/module.json

**Comment by techogre** [comment]
Thank you!

v10 version of Better Rolls and SUCC installed. I did a quick test and it seems to work.

I will test it a little harder with a few players later and try to break it. :)

**Comment by techogre** [comment]
Did a little more testing and it seems to be working fine. It has survived contact with the players.

**Comment by javierriveracastro** [comment]
Thank you.
