### ISSUE TITLE
Link to the HTML version broken

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#490]
The link to the HTML version seems to be broken .. [https://javierriveracastro.github.io/betteroll-swade/](url)

![image](https://user-images.githubusercontent.com/64320/193654932-782416ce-3e0f-4d13-8fa6-52a5cfcfbc87.png)

**Comment by javierriveracastro** [comment]
Yes, only the wiki remains, that should be removed from there.

**Comment by javierriveracastro** [comment]
Done.
