### ISSUE TITLE
Missing from Foundry v10 installable modules list

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#491]
The module seems to be missing from the Foundry Install Modules listing???

![image](https://user-images.githubusercontent.com/64320/193674869-96240a51-6cc9-463a-b283-e4d611ebe4a3.png)

**Comment by javierriveracastro** [comment]
If you are using v10, then yes. It is not yet officially compatible with it.

There is a beta version that you can install manually:

https://raw.githubusercontent.com/javierriveracastro/betteroll-swade/v10_test/betterrolls-swade2/module.json

You will also likely need the v10 compatible SUCC

https://raw.githubusercontent.com/SalieriC/SUCC/v10_test/succ/module.json

Please, make it clear if this is happening in v9 (a bug) or in v10 (expected).

**Comment by steveculshaw** [comment]
Thanks for the response

This was happening in **v10** instance of FVTT.

_I'm puzzled why the existing 2.76 version for v9 wasn't showing. 
Other v9 modules show up in the filter packages, e.g., SWADE Core Rules_

I'll try out the v10 beta's of BR2 and SUCC ... **will I also need a beta for SWIM? **

**Comment by javierriveracastro** [comment]
That is probably because they don't specify a maximun version on their manifest.

I don't think that there is a beta for SWIM, AFAIK SalieriC is quite busy right now and he will need more time to port it

**Comment by steveculshaw** [comment]
@javierriveracastro Ah ha ... thanks for explaining
