### ISSUE TITLE
Vulnerable status effect expires in the same round

### ISSUE THREAD

**Issue by basic-element** [javierriveracastro/betteroll-swade#493]
Updated to V10 and now when I do a wild attack, it adds the vulnerable status, but right after my turn is over it gets removed. It should stay until the end of the next turn. I looked at the Active Effect and looks like it is missing the effect start turn value.

**Comment by javierriveracastro** [comment]
That's likely a SUCC bug, but I will take a look at it.

**Comment by javierriveracastro** [comment]
I can't reproduce it, it's working fine for me. Maybe there is something else going on your end.

Can you give me the SWADE, BR2 and SUCC version?. Is there any other module installed?

**Comment by basic-element** [comment]
SWADE - 2.0.5
BR2 - 3.2
SUCC - 0.2.0

Try testing it with multiple characters, both PC and NPCs and do it for a few rounds (wild attack) and go to next turn. Some PCs, it's working fine, others are not. Trying to figure out why myself.

**Comment by basic-element** [comment]
Okay, I think I narrowed it down. If the token is linked to the actor it works fine. If the token is NOT linked to actor it is NOT working fine. Can you confirm on your end?

**Comment by javierriveracastro** [comment]
No, it still works for me with non linked tokens.

Can you attach an screen recording, maybe we are talking about different things.

**Comment by basic-element** [comment]
That's weird. so there was a foundry v10 system update available and I updated and now the issue is gone. But I do see another issue and wanted to know if you are experiencing it. If you wild attack on the first round, and  you wild attack again on the second round, the vulnerable status should reset and last till the end of the third round, but for me the status is still removed at the end of the action of the second round. The duration does not get reset/renewed.

**Comment by javierriveracastro** [comment]
That's happening to other people too, but I can't reproduce it.

https://github.com/javierriveracastro/betteroll-swade/issues/493

**Comment by javierriveracastro** [comment]
This should be solved when SUCC gets an update.

If you want to check it, use the SUCC git version.
