### ISSUE TITLE
Dragging icon to target not working in Foundry v10

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#495]
**Dragging icon to Macro Bar not working**

Foundry: 10.287
Savage Worlds Adventure Edition: 2.0.5
Savage Worlds Adventure Edition: 2.0.0
BR2: 3.2
SUCC: 0.2.0
SWIM: 0.18.5

Reading through the notes on [Drag & Drop](https://github.com/javierriveracastro/betteroll-swade/wiki/More-Functionalities) and trying out the drag & drop as it sounds really useful!

Set-up a player character sheet with long sword, and a monster set as target.

Click on the long sword ...
- the melee card is displayed _(and works as expected)_

Drag the long sword from a player character sheet onto the target on the scene ...
- nothing happens

Drag the long sword onto the macro bar
- macro generated titled "Display Sword, Long"
- script with code ... `Hotbar.toggleDocumentSheet("Scene.QqUF88wNkhSmdSAC.Token.XGRoS7gDNMG63gmO.Item.tcRH5BAFatbSjqJL")`

**Comment by javierriveracastro** [comment]
This should be solved in git.

**Comment by steveculshaw** [comment]
@javierriveracastro 
Sorry, I'm not clear on this ... do I have to do some in "git" to fix the issue in my Foundry set-up?

**Comment by javierriveracastro** [comment]
That means that it is solved in the code that is here. It will added to the next release.

If you want to test it you will need to download the betterrolls2 folder from the code tab above and overwrite your current module install.

**Comment by steveculshaw** [comment]
Ah ha ... Thanks for explaining
