### ISSUE TITLE
Group Rolls on Extra cards

### ISSUE THREAD

**Issue by EntreriCansinos** [javierriveracastro/betteroll-swade#497]
Would it be possible to add a Global Action for group rolls (wild die) on Extra cards?
Thank you so munch, your work is amazing and very useful.

**Comment by superseva** [comment]
This would be great to have it implemented

**Comment by SalieriC** [comment]
It was a thing in version 1 where BRSW just rolled an additional d6 for every NPC but never interpreted the result of it. Nowadays I think BRSW can do better I think. Probably _just_ by adding  another modifier `if (actor.type === "npc")` and then changing the formula if active.

**Comment by javierriveracastro** [comment]
I have already added a "is_wilcard" selector, the next action is to add a "force_wild_die" and the action should work. Note than in the system (I mean Foundry system, not rules) an actor of type pc can be a non wild card.

**Comment by javierriveracastro** [comment]
Should be done-
