### ISSUE TITLE
Remember the target from the to hit roll if there is no token targeted when rolling damage.

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#498]
**No button to apply a Shaken reroll result in v10**

Foundry: 10.287
Savage Worlds Adventure Edition: 2.0.5
Savage Worlds Adventure Edition: 2.0.0
BR2: 3.2
SUCC: 0.2.0
SWIM: 0.18.5

During playtesting we saw this effect, and it seemed like a bug _(although it may just be we're still learning BR2)_

Player decides to reroll their damage roll of 11 and got a worse result of 5 ... _see screen shot_

OK, they would likely want to go with the original result and wound the monster, but the second result of a Shake doesn't have any button with which to apply it to the monster.

_Does BR2 automatically assume that Wound is better than Shake and not bother with a button?_

![image](https://user-images.githubusercontent.com/64320/194833634-29295fb7-28f3-4671-9c96-654f8237c167.png)

**Comment by javierriveracastro** [comment]
It looks that for some reason the second roll has no target (see it says "Default" instead of "Monster 2").

The most likely reason is that he untarget or unselect the objetive while rerolling.

I'm not sure if this is an issue or not. What should br2 do when there is no target selected?. Default to the last one?. I have to think a little more about this.

I'll be grateful for any input.

**Comment by steveculshaw** [comment]
@javierriveracastro 
Thanks for the response and clarification ... _I'm starting to understand things_ :-)

For me, I'd say it was down to _"player error"_, so it's a "learning experience" that will remind them to watch what they're doing.
 
That said, it'd be really nice if BR2 remembered the target, and applied the damage versus that target ... 
  - but this is a really "nice to have" enhancement, and I'm sure there are plenty of other _"low hanging fruit"_ to go for :-)

**Comment by javierriveracastro** [comment]
Done
