### ISSUE TITLE
Can select both Two Actions and Three Actions in new style action modal dialog

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#500]
**Can select both Two Actions and Three Actions in v10**

Foundry: 11.390
BR2: 3.51

You can select both "Two actions" and "Three actions" in the cards "Multi-action" section.

It would be better if it was a toggle, i.e., clicking one, unchecked the other, and vice versa

<img width="252" alt="image" src="https://github.com/javierriveracastro/betteroll-swade/assets/64320/3f489642-e229-4020-ada3-28116273186f">

@javierriveracastro Just realised, this is a specific case of the more generic issue #643 that I recently logged about "radio buttons"

**Comment by javierriveracastro** [comment]
Sure, but the way that actions work this is not possible right now.

But it is an interesting option, it will probably be solved, but as it needs quite a lot of work it will have low priorty.

Plenty of bugs and low-hanging fruit to collect right now.

**Comment by steveculshaw** [comment]
@javierriveracastro Thanks for responding. 
I suppose if the player really wants the challenge of taking a -6 on their roll, that's their choice 😀

Go for those low fruits 👌 

Many thanks for a great module that makes playing Swade in Foundry a lot easier

**Comment by javierriveracastro** [comment]
This is solved by single option modifiers groups.
