### ISSUE TITLE
"Reload/Manual ammo" depreciates Ammo from Inventory BUT doesn't add to weapon

### ISSUE THREAD

**Issue by aedgaruk** [javierriveracastro/betteroll-swade#501]
Hi,

As the title states, the Ammo is depreciated but the amount is not added to the Weapon ...

![image](https://user-images.githubusercontent.com/111492074/195410399-3be368be-53ee-4702-9726-a2bf697c29a5.png)

Cheers
Andy

**Comment by javierriveracastro** [comment]
Done.

**Comment by aedgaruk** [comment]
Retested (v3.3) and works perfectly ... even reloads to max. capacity of weapon if you put too much in the "# of shots" box and depreciates the number reloaded not the value instructed.

Excellent work, Sir!

Cheers
Andy
