### ISSUE TITLE
Error: BasePackage#data deprecated in favor of referencing schema fields directly on the BasePackage instance

### ISSUE THREAD

**Issue by aedgaruk** [javierriveracastro/betteroll-swade#502]
Hi,

When Apply Damage (next to the red blood drop) to the Target is committed, 4 variations of the same error are thrown:

![image](https://user-images.githubusercontent.com/111492074/195895500-b5c5f1ae-8f30-4945-8cab-4f820d147123.png)

... attached is all 4, expanded and added as a cut'n'paste if it helps.

The action seems to work as expected but obviously there'll be issues by v12 as suggested by the output.

[BR2 - 1703 Error when Adding Damage to Target.docx](https://github.com/javierriveracastro/betteroll-swade/files/9788295/BR2.-.1703.Error.when.Adding.Damage.to.Target.docx)

Cheers
Andy

**Comment by javierriveracastro** [comment]
That's looks like a SUCC warning, not BR2. Anyway it should be already resolved there (but not released).
