### ISSUE TITLE
Items using attributes to trigger don't get rolled

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#504]
Burce on the SWADE foundry discord wanted to ask this. He wants to use an attribute for an item instead of a skill. If the trait setting is an attribute, it will not roll when you use the item.
Should the trait location work for both skills and attributes.
![image](https://user-images.githubusercontent.com/80164119/196038378-8559c6c0-11f2-46b8-9af2-dd2f4142f17d.png)

**Comment by javierriveracastro** [comment]
That should be solved.
