### ISSUE TITLE
Shaken not being removed when "Undo damage" used

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#505]
**Shaken not being removed when "Undo damage" used**

The goblin was hit, and the damage was enough for a Shake & Wound status, hence Incapacitated.
![image](https://user-images.githubusercontent.com/64320/196050083-3f76c5b9-475e-475a-ba55-44c6c925882f.png)

I tried the "Undo damage" option. 
It reckoned it had removed both the Shaken and the Incapacitated, but the Shaken was not removed?
![image](https://user-images.githubusercontent.com/64320/196049903-0e2e1a04-1831-48b9-944a-53bc8effbb00.png)

**Comment by javierriveracastro** [comment]
This should solved. It needs a new version of SUCC so it could be a while until the fix is released, as SalieriC is right now quite busy.
