### ISSUE TITLE
Subtract Power Points is a tri-state toggle

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#506]
**Subtract Power Points is a tri-state toggle**

The power card "Subtract Power Points" seems to be a tri-state choice, rather than a simple toggle?
Two of the states subtract power points, and the third doesn't
This seems confusing?

![image](https://user-images.githubusercontent.com/64320/196050516-73dac715-28bf-45b5-8411-6d35cd15a9e2.png)

![image](https://user-images.githubusercontent.com/64320/196050520-895f775f-e40d-4bdb-ad77-33c13345c468.png)

![image](https://user-images.githubusercontent.com/64320/196050525-123bbcb0-ae9a-4c72-a756-6294d9b17150.png)

**Comment by javierriveracastro** [comment]
Mostly everything is a three status toggle.

I'm not sure that it makes more or less sense here than in other places.

**Comment by steveculshaw** [comment]
It's just very weird that you have **two** options to automatically handle the Power Point subtraction, when it's a yes/no state as to the automatic subtraction?

**Comment by Wigginns** [comment]
What is the third state supposed to do?

**Comment by javierriveracastro** [comment]
It last just for one roll and then it unselects itself.

So it will just be added the skill roll and not to damage. It is mostly not needed now and it will probably been removed some day.

**Comment by Wigginns** [comment]
Oh interesting! I think that's actually pretty useful for stuff like Frenzy but I had no idea what it's function was. Thanks for clarifying 👍

**Comment by SalieriC** [comment]
Told you about it here @javierriveracastro: https://github.com/javierriveracastro/betteroll-swade/issues/473
;-)
I just don't think the white toggle makes sense for the chat cards (anymore).

**Comment by steveculshaw** [comment]
Seconded 👌

**Comment by javierriveracastro** [comment]
Solved in the redesign
