### ISSUE TITLE
Ability to change the die type of bonus damage based on the number of raises on an attack roll

### ISSUE THREAD

**Issue by JosephA1997** [javierriveracastro/betteroll-swade#508]
I've seen many people use this house rule where your bonus damage die increases past one raise (1d8 for 2 raises; 1d10 for 3 raises; 1d12 for 4 raises). I've looked into the global actions section of the wiki and can't seem to figure out if there is a way to do this already.

**Comment by javierriveracastro** [comment]
No, this is not currently supported.

**Comment by javierriveracastro** [comment]
I've thinking about this and I'm probably going to close it as wontfix.

The main problem is that there are the raise die is modified by some official and published third party abilities.

How this will work with a house rule that is not published is very difficult to asses (if you have d10 raise damage die and you get three raises, what happens?).

Of course, I'm open to pull requests or just general ideas about this, but for now I'll close it.

**Comment by JosephA1997** [comment]
That's understandable, thank you for looking into it.
