### ISSUE TITLE
Error warning about ChatMessage#data object no longer used

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#509]
Foundry: 10.288
Savage Worlds Adventure Edition: 2.0.6
Savage Worlds Adventure Edition Core Rules: 2.0.0
BR2: 3.3
SUCC: 0.2.0

When I just click on a weapon, there is no warning in the debug console.

But if I use the ALT + Click and CTRL + Click options, I'm getting the following warning ...

`You are accessing the ChatMessage#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly`

![image](https://user-images.githubusercontent.com/64320/196726060-a85d8eac-cc1c-47a4-8842-8d4f77e3f5d3.png)

**Comment by javierriveracastro** [comment]
Done.
