### ISSUE TITLE
Ranged attacks at greater than Extreme range still work

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#510]
Foundry: 10.288
Savage Worlds Adventure Edition: 2.0.6
Savage Worlds Adventure Edition Core Rules: 2.0.0
BR2: 3.3
SUCC: 0.2.0
SWIM: 0.18.5

In SWADE rules p.93, it's got ... "Extreme Range is up to 4× a weapon’s Long Range"

But if I attack at greater than this, I still get a chance of a hit, albeit it at a -8

Shouldn't the attack be flagged as an automatic miss ?

**Comment by javierriveracastro** [comment]
Not sure about that.

Maybe using an absurd low modifier, that way it can be easily deleted in a special case.

**Comment by steveculshaw** [comment]
@javierriveracastro 
Sorry, unclear on your comment re. "an absurd low modifier"

Is that something I need to set up in BR2 ?

**Comment by javierriveracastro** [comment]
Something like -999. So it will always fail, but it can be removed by a click of a settings or home rule allow far shots.

The other option is putting some kind of warning on the card.

Anything but auto failing as, to me, the dm should be able to override it.

**Comment by steveculshaw** [comment]
@javierriveracastro 
Is this something you have to do in the "code", or is it a setting I'd have to change?

**Comment by javierriveracastro** [comment]
Sorry, it is something that should be done in code. I was just trying to discuss how it should work.

**Comment by steveculshaw** [comment]
Ah, got ya 👍 

Yeah, an extreme value sounds like a good option

**Comment by javierriveracastro** [comment]
This has been already solved, likely with some other issue. Closing for clean-up
