### ISSUE TITLE
Damage D6s are double acing

### ISSUE THREAD

**Issue by SwordofSpirit** [javierriveracastro/betteroll-swade#516]
When rolling D6 + D6 damage (Strength + Weapon), if one of the dice rolls a 6, **two** additional dice are being rolled. I haven't experienced this issue on a potential extra raise die--just on the Str+Weapon damage dice.

I'm running Foundry V10.288, SWADE 2.0.6, and Better Rolls 2 3.4. I've isolated the issue to Better Rolls by disabling everything else (and tested both dependencies without Better Rolls to rule them out).

![Double Acing Bug](https://user-images.githubusercontent.com/87603251/198536363-e98d9275-51f8-4305-bb0b-0945f9187ca6.png)

**Comment by javierriveracastro** [comment]
Can't reproduce it. How is the weapon damage set up?. Can you provide a json export  of it?

Do you have some custom world action active that can affect this?

**Comment by SwordofSpirit** [comment]
There is nothing special going on in the world; it's just the free core module that we made some characters and items with. (We're new, and user error is entirely possible, but I'm not sure what it would be that we are doing wrong.)

[fvtt-Item-weapon-(d6-str-+-d6-weapon).zip](https://github.com/javierriveracastro/betteroll-swade/files/9895368/fvtt-Item-weapon-.d6-str-%2B-d6-weapon.zip)

**Comment by javierriveracastro** [comment]
Ahhhh... you put d6+d6 in damage. That is unusual, it is usually something like @str+d6 or 2d6. That explains why nobody else is seeing it, and of course I tested with `@str+d6`and a d6 strength character.

**Comment by SwordofSpirit** [comment]
Thanks! That was the issue! There is no sample gear with the core rules, so we basically had to guess on how to format it. Now it's fixed.

**Comment by javierriveracastro** [comment]
No, this is a workaround but I must fix the initial problem.

**Comment by javierriveracastro** [comment]
Solved.
