### ISSUE TITLE
Shaken with Linked Actors

### ISSUE THREAD

**Issue by Cosmic-Lattee** [javierriveracastro/betteroll-swade#517]
Hello!

So there is a strange issue where unlinked tokens roll spirit automatically, but when they are linked it no longer works.

![Shaken](https://user-images.githubusercontent.com/24766235/198751462-cf8b943a-92f4-4ead-b4dd-0f8508434ac9.gif)

Looking at the console it looks like when the token is linked it begins passing a null value that prevents the shaken menu from appearing.

Tested with no other modules (besides those required for better rolls) on Foundry build 288 on SWADE 2.0.6 with Better Rolls 3.4

![image](https://user-images.githubusercontent.com/24766235/198751542-66353c6f-bd34-4433-911d-a51fa470db16.png)

![image](https://user-images.githubusercontent.com/24766235/198751553-4711b897-eff7-4f02-9205-658ac84357a8.png)

**Comment by javierriveracastro** [comment]
Solved, I will try to make a release as soon as I can do some testing.
