### ISSUE TITLE
Global Actions API

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#518]
Great new feature!!!

I'm trying to set some ga with it. 

But, it's not working. Can you help?

![image](https://user-images.githubusercontent.com/4999783/199061896-807d652b-431a-495b-b4f2-1abf01663ec3.png)

```js
Hooks.once('init', () => {
  const BETTER_ROLLS_SWPF = [
    {
      id: "DESPERATE_ATTACK-2", 
      name: "Desperate Attack +2", 
      button_name: "Desperate Attack +2",
      skillMod: 2, 
      dmgMod: -2, 
      dmgOverride: "",
      and_selector: [{
          selector_type: "skill", 
          selector_value: "fighting"
        },
        {
          selector_type:"item_type", 
          selector_value: "weapon"
        }],
      group: "Savage Pathfinder"
    }  
  ];
        
  game.brsw.add_actions(BETTER_ROLLS_SWPF);
}); // END HOOKS
```

**Comment by javierriveracastro** [comment]
You are doing it to soon. Actions are initialized in the "ready" Hook that is called after "init".

Even then you should probably do something to be sure that br2 is ready before adding actions.

And please ping me in Discord for help, don't open an issue unless it is something that should be added to the TODO list. I mean if it is a bug, it is probably a documentation one.

**Comment by brunocalado** [comment]
I'll pr an update to the docs. tks

**Comment by brunocalado** [comment]
I can't edit docs anymore.

**Comment by brunocalado** [comment]
I used to have an edit button.

**Comment by javierriveracastro** [comment]
I know. This is why moving to a wiki was bad idea. But moving back is probably a lot of work.

**Comment by javierriveracastro** [comment]
You should be able to change the wiki now editing the files in code/docs (https://github.com/javierriveracastro/betteroll-swade/tree/version_2/docs).
