### ISSUE TITLE
API function to get generic BRSW modifiers

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#519]
As discussed on discord, an exposed function that gets the generic modifiers (above the chat input, not on chat cards) the user has selected in BRWS would be very useful for my purposes and probably those of other devs as well.

**Comment by javierriveracastro** [comment]
Done, exposed get_roll_options on game.brsw.get_roll_options.

Pass an empty dictionary to get the current selection.
