### ISSUE TITLE
Find a way to start different kind of rolls

### ISSUE THREAD

**Issue by javierriveracastro** [javierriveracastro/betteroll-swade#52]
Like extra modifiers, higher rof, or just show a more complex window.

Right or/and long press looks like the most discoverable/expected way. It could also be attached to Atributtes and skill names.

**Comment by SalieriC** [comment]
I think right click would be most intuitive, I'd vote for that. Thank you so much for looking into it.

**Comment by javierriveracastro** [comment]
Right click menus don't work inside scrollables when close to the borders (well they kinda do but not as expected). I have to either find another way or disable the scrollable in the sheet. This have the side effect of making the whole sheet scrollable, which can be a good thing for smaller screen resolutions, but it's another modification to upstream with it associated maintenance cost.

Just keep it here for reference. 

I can't make a decision right now.

**Comment by javierriveracastro** [comment]
Done it, but it changes some css in the general sheet. Most are for the better, IMHO, the sheet is way shorter and it's scrolled as a whole. It should help a lot in smaller screens.

Anyway, It needs more testing, if someone is reading this, please say contact me for a small test.
