### ISSUE TITLE
Pass `shots_used` to item actions in the flags of BRSW cards.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#524]
Actions in the flags of BRSW cards currently do not have a property that informs about the shots used entry. Having this in the flag of each action would be very helpful for developers building on BRSW.

**Comment by javierriveracastro** [comment]
Now that I have read this closely. I don't get it.

There is shot_used field in render_data (that is probably going to be moved), and a flag in the code of each action that modifies then. What are you asking for?

**Comment by javierriveracastro** [comment]
Closing, as it is likely solved. SalieriC if you get time for Foundry again and I have read this wrong, feel free to open it again.

**Comment by SalieriC** [comment]
Yeah no, it's there. I don't know what was wrong back then.
