### ISSUE TITLE
Better Rolls Dual Tab

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#525]
Hi!

Can you create a second chat tab exclusive for BR chat cards?

The normal chat work as usual. But, the br tab will be the place where all rolls a sent.

![Screenshot_1](https://user-images.githubusercontent.com/4999783/199997152-ed05dd99-e6ac-46da-8dc4-5f06af2850b0.png)

This solves
- Sometimes a roll is being resolved, but the players a talking in the chat.
- You are discussing the roll and send a journal with link to chat
- The BR modifiers will who only on BR tab, this cleans the chat.

**Comment by javierriveracastro** [comment]
I'm not really sure about this. This is a somewhat big change of Foundry that will probably merit a full module. Adding this to BR will probably mean lots of maintenance work and side effects.

But it is a neat idea. Maybe something else can be used for a similar effect. Something like a simpler chat card that can be expandeded into a big one?

**Comment by brunocalado** [comment]
> 

Ok. I'm justing trying to find a solution to this case.

**Comment by grendel111111** [comment]
Have to tried tabbed chat? It might not do quite what you want, but keeps the rolls  chats and ooc chats as separate streams.

**Comment by javierriveracastro** [comment]
I'll wait for some more proposals before doing nothing with this issue.

**Comment by brunocalado** [comment]
I still like the dual tab for br2, BUT, the new feature is just great. I'm ok with it.

https://user-images.githubusercontent.com/4999783/200611586-b39ab0d5-7df1-4356-9133-e3f629374c0c.mp4

**Comment by javierriveracastro** [comment]
Then I'll cliose it,
