### ISSUE TITLE
Range Increment Modifiers

### ISSUE THREAD

**Issue by aedgaruk** [javierriveracastro/betteroll-swade#526]
Enhancement

The ability to modify range increments for a character/item would be very useful, notably in the case of the Edge: Brute for example.

![image](https://user-images.githubusercontent.com/111492074/200124836-e4e876dd-614d-4461-b044-3b5e119d0317.png)

... SWADE pg.38

**Comment by javierriveracastro** [comment]
Done.

I made it as an active effect, not at action as it should be always enabled. The downside is that you will have to add the effect to the Brute edge by hand.

The key is 'brsw.thrown-range-modifier' and the value will be the modifer (multiplied by range). So a 1 will do for Brute.

**Comment by aedgaruk** [comment]
Hi,

Sorry but can you lay that out for me please, I think I understand what you're getting at but I'm confused as what goes in each of the AE fields.

Appreciated ... Cheers :)
Andy

**Comment by javierriveracastro** [comment]
Import this item and add it to the actor instead of the current Brute Edege.

The difference are in the effect tab.

```json
{
  "name": "Brute",
  "type": "edge",
  "flags": {
    "core": {
      "sourceId": "Compendium.swade.edges.AQF6xQFtx2OQ2SWW"
    },
    "exportSource": {
      "world": "la-casa-de-la-bestia",
      "system": "swade",
      "coreVersion": "10.288",
      "systemVersion": "2.0.6"
    }
  },
  "img": "systems/swade/assets/icons/edge.svg",
  "system": {
    "description": "<p>See SWADE p.38</p>",
    "notes": "",
    "additionalStats": {},
    "favorite": false,
    "category": "",
    "isArcaneBackground": false,
    "requirements": {
      "value": "Novice, Strength d6+, Vigor d6+"
    },
    "source": ""
  },
  "effects": [
    {
      "label": "Brute",
      "icon": "/icons/svg/mystery-man.svg",
      "transfer": true,
      "_id": "2MULHy3PWzhyBEYv",
      "changes": [
        {
          "key": "brsw.thrown-range-modifier",
          "mode": 2,
          "value": "1",
          "priority": null
        }
      ],
      "disabled": false,
      "duration": {
        "startTime": 5220,
        "seconds": null,
        "combat": null,
        "rounds": null,
        "turns": null,
        "startRound": null,
        "startTurn": null
      },
      "origin": null,
      "tint": null,
      "flags": {
        "swade": {
          "expiration": null,
          "loseTurnOnHold": false
        }
      }
    }
  ],
  "_stats": {
    "systemId": "swade",
    "systemVersion": "2.0.6",
    "coreVersion": "10.288",
    "createdTime": 1667836038413,
    "modifiedTime": 1667836085600,
    "lastModifiedBy": "QH94e0LcdGjKB3tL"
  }
}
```

You can't use the new constructor to add this effect, as it only supports system defined ones.

**Comment by javierriveracastro** [comment]
Or maybe an image is easier.

![imaxe](https://user-images.githubusercontent.com/8113700/200543037-d6b715aa-ae91-4007-b418-d0c01bac85c0.png)

**Comment by aedgaruk** [comment]
You Sir, are a Gentleman and a Scholar ... Thank You!
