### ISSUE TITLE
Global Action: Hindrance - Bad Eyes same mod applied regardless of Min/Maj

### ISSUE THREAD

**Issue by aedgaruk** [javierriveracastro/betteroll-swade#527]
Bug:

BR2 seems to be applying a -1 modifier regardless of whether the Hindrance - Bad Eyes is a Minor (-1) or Major (-2).

Cheers
Andy

**Comment by javierriveracastro** [comment]
It is using the name to identify the Hindrance, so you need one called "Bad Eyes (Major)" to make it apply the -2.

It is possible to check for the hindrance, but I really believe that there are more urgent issues ritght now.
