### ISSUE TITLE
Niche issue with powers and attributes

### ISSUE THREAD

**Issue by Cosmic-Lattee** [javierriveracastro/betteroll-swade#529]
So this is a super niche thing that could very easily just be ignored if you don't want to mess with it. I know this isn't intended to be how spellcasting typically works with savage worlds. :)

So I running a game that uses Spirit as the spellcasting power stat. This means that it will be looking for an attribute instead of a skill when generating the spell card. Not surprisingly this brings up an error:

![image](https://user-images.githubusercontent.com/24766235/200735570-a29f90be-c1d6-47ea-9ed7-048cf440197f.png)

Which points to this code:

![image](https://user-images.githubusercontent.com/24766235/200735617-605a4d27-ce48-4d84-9099-cc34676c647a.png)

Now what makes this interesting is this error only shows up with the electron client. When I use say chrome it works a treat. Here is a gif showing that in practice: 

![Showing](https://user-images.githubusercontent.com/24766235/200736759-0f5893f2-21a9-464e-a764-b979b4317b82.gif)

**Comment by javierriveracastro** [comment]
It looks like you have an old electron client that doesn't support structuredClone.

You should update it (the easiest way is to reinstall Foundry) as it probably lacks support for something else that core Foundry uses.

As a general rule, when updating a full version of Foundry (v9 to v10) in Windows, reinstalling is better.

I'm closing it as it is not an issue, Chromium versions under 98 (Electron 17) are not supported either by Foundry v10 or BR2.
