### ISSUE TITLE
Unfolding the description of a roll unfolds both, roll and damage.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#53]
When damage is not rolled automatically: When a roll is made by a damage inflicting source (Weapons and powers) and damage is rolled using the button in the result and then the description of either is unfold, both unfold.

**Comment by javierriveracastro** [comment]
Quite worse. It unfolded all descriptions. And searched all the page HTML. Nasty and ugly. Solved. Will make a release just for this.
