### ISSUE TITLE
Encumbrance error

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#530]
When you have a character with an encumbrance penalty that rerolls an action it applies the encumbrance penalty an additional time for each reroll you make.

![image](https://user-images.githubusercontent.com/80164119/201236441-01bcd4d0-ef21-41f7-bd5b-067f7f60652f.png)
![image](https://user-images.githubusercontent.com/80164119/201236510-5c8db776-bdb3-40b0-9ab4-465f91806d0e.png)
![image](https://user-images.githubusercontent.com/80164119/201236565-abbed531-d1fa-41c4-abd0-b0e2d1fb83b9.png)
![image](https://user-images.githubusercontent.com/80164119/201236805-4b070da5-933c-4298-b357-098bc0da2a34.png)

**Comment by javierriveracastro** [comment]
Solved
