### ISSUE TITLE
Ranged powers not working when target is targeted

### ISSUE THREAD

**Issue by sroakjp** [javierriveracastro/betteroll-swade#532]
Roll card is unresponsive when attempting to roll for power activation when a token is targeted by the caster.

Console error is:
![image](https://user-images.githubusercontent.com/62338951/201266456-776daa4f-eac2-4492-b2fd-4cdb302bc3da.png)

**Comment by javierriveracastro** [comment]
Solved, I will try to make a bugfix release this afternoon.
