### ISSUE TITLE
Power card does not subtract general PP

### ISSUE THREAD

**Issue by EntreriCansinos** [javierriveracastro/betteroll-swade#534]
During this week there have been several changes, some structural, in the SWADE system. One of them affects the general PP constant. The solution is to replace the string "powerPoints.value" with "powerPoints.general.value" in the item_card.js file.

This is the modified file, just remove the .txt extension

[item_card.js.txt](https://github.com/javierriveracastro/betteroll-swade/files/9996944/item_card.js.txt)

Thank you very much for your work, it makes our life much easier.

**Comment by javierriveracastro** [comment]
Thanks, next time you can upload the file to the code repository and make a pull request ;).

**Comment by javierriveracastro** [comment]
Merged.
