### ISSUE TITLE
Power Point management broken with SWADE version 2.1.0 and above.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#538]
Version 2.1.0 of SWADE introduced a breaking change regarding power points which means that the power point management of BRSW is now non-functional. It doesn't find the power point pool of the power and is thus unable to change it.
Here are the changes detailed: https://gitlab.com/peginc/swade/-/blob/develop/CHANGELOG.md#changed-2

**Comment by javierriveracastro** [comment]
This should already be addressed (not released yet). Have you reproduced the problem with git version?

**Comment by javierriveracastro** [comment]
Seems to be working for me, so I will close this. Feel free to reopen if you find it is not really solved.

**Comment by SalieriC** [comment]
Yeah no, didn't test the git version. Sorry about that.
