### ISSUE TITLE
MDC damage and armor for Rifts

### ISSUE THREAD

**Issue by gravagehulk** [javierriveracastro/betteroll-swade#539]
I was able to get the SWADE developer to add fields in the weapons and armor traits to account for mega damage. This is just a variation of Heavy Weapons and Heavy Armor. 

Is there any way we could get some automation added that checks to see if the weapon damage is MDC when attacking MDC armor? Non-MDC weapons should not do any damage to MDC armor.

<img width="397" alt="Screen Shot 2022-11-22 at 14 10 38 PM" src="https://user-images.githubusercontent.com/69117052/203412337-3b65ad3e-b7ff-401e-b45e-8fde56be0ccf.png">
<img width="392" alt="Screen Shot 2022-11-22 at 14 10 20 PM" src="https://user-images.githubusercontent.com/69117052/203412353-2471cb29-be43-41e8-a2db-2858b9f1d8c8.png">

**Comment by javierriveracastro** [comment]
Sure. What would make more sense, just adding a warning o rolling 0 damage?

Adding a warning will make homerules easier.

**Comment by gravagehulk** [comment]
> Sure. What would make more sense, just adding a warning o rolling 0 damage?
> 
> Adding a warning will make homerules easier.

Ideally, it would do "0" damage and note that it was "immune" or "MDC", but I can understand that may be asking too much and the warning would be almost as effective.

When I requested the addition of the MDC feature on the SWADE github, I requested it as "Heavy Damage/Heavy Weapon", as that is the SWADE mechanic being used. The way they chose to implement it (MDC) makes this specific to the Rifts ruleset, so anything you can do would be great. 

The idea is that when someone shoots a tank with an uzi, it shouldn't damage the tank. So, there should be some kind of notification, if not a block of the wounds entirely. It's a core function of Rifts, but would be problematic in some SWADE campaigns, too. Deadlands,  for example, has a creature called a "Rattler" and it has heavy armor, so regular weapons do not affect it.

**Comment by valdier1** [comment]
I agree that 0 damage and noting that "Target has MDC armor and this is a standard weapons" or similar

**Comment by javierriveracastro** [comment]
I will try to add a limited (torso only) support just now. Location support will need to wait until I somehow rework the called shot code.

**Comment by javierriveracastro** [comment]
Done. Please take care that the armor must be equipped and in torso for this to be applied. Specially as NPCs in core rules (and likely Rifts) don't equip their armor by default.
