### ISSUE TITLE
The Called Shot action does not take armour into account.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#541]
If the target has armour covering the torso, BRSW takes that into account as it should for regular attacks while other armour locations are not (as they don't apply to toughness in the system). So far this is all behaving like it should be.
It gets tricky however with the called shot options (BRSW currently only offers Head but by taking on this issue it might be worthwhile to introduce arms [-2/+0], legs [-2/+0], heart [-4/+4] and hand [-4/+0] for a near complete coverage of the system ([trait penalty/damage bonus])). When a target has armour on the torso, BRSW does take that into account even if the attack is a called shot to the head. If the target has armour on the head and not the torso however, a called shot to the head does not take it into account.
I consider this partly a bug and partly a feature request as the way it is right now is clearly unintentional (and probably requires some more work as each attack needs to process all the targets armour) while the adding of different called shot options is an enhancement.

**Comment by javierriveracastro** [comment]
Done.
