### ISSUE TITLE
Rifts - Ranged Armor

### ISSUE THREAD

**Issue by valdier1** [javierriveracastro/betteroll-swade#542]
Rifts has the concept with Cyberknights, psi-warriors, etc for Ranged Armor, in which a shield adds armor to ranged attacks against the wielder. 

It would be nice if we could add a world effect or better, if core supported properties of "ranged armor" and "melee armor", that added or subtracted from the base armor value. BR2 could then use distance to target (greater than 1 square, the same way as gang up) to see if the ranged armor modifier should be added.

If done as a world effect, then a toggleable option to give the target "extra armor vs this attack based on Spirit, Psionics, or whatever in the macro"

**Comment by javierriveracastro** [comment]
And how is ranged armor idenfied? AFAIK system has no way of telling ranged armor appart from normal.

Note that I don't own any RIFTs module, so maybe it is a stupid question.

**Comment by valdier1** [comment]
In this case, it just notes "_and provides the wielder's Spirit in MDC Armor if an enemy attempts to shoot through it_"

I think for simplicity purposes, if the attack is using shooting or athletics, then it could add the "ranged armor" value?

**Comment by javierriveracastro** [comment]
The problem here is identifying the "ranged" armor. I can't (well, shouldn't) add data or toggles to items. This is out of scope of br. So I need something already existing that identifies the armor. And a text in notes is probably not the best idea.

**Comment by valdier1** [comment]
I think this is honestly too complicated for Foundry to handle easily. This
is more of an issue with shields in general. Shields don't technically make
you miss when the cover value is applied, the shot hits your shield and
then the armor value of the shield is applied to your base armor. The
"ranged" armor in Rifts works similar:

Shield gives Cover -4, and Spirit in Armor. But, much like shields in the
base book, if someone rolls a 7 lets say to hit, you still hit even though
the TN is 8, but you get to apply the shields cover value to your armor.
It's just an artifact of some of the more complex fiddly bits of SWADE that
is likely better off being ignored in the game.

**Comment by javierriveracastro** [comment]
So, I'm closing this a it looks like it is not actionable.
