### ISSUE TITLE
Bleeding out

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#543]
When you are incapacitated it says you are incapacitated, suffered and injury and are bleeding out. As there is now a bleeding out condition in the SUCC conditions, can we get it added when they get incapacitated from combat. (It lets you trigger things off bleeding out).

**Comment by javierriveracastro** [comment]
It is nice but it uses the default dialogs, and this is incosistent and probably confusing.

Anyway it is better than nothing... done.

**Comment by SalieriC** [comment]
Does SUCC not have the feature to turn the dialogue off yet? If so, please 
make an issue there and assign me to it. Can't do it today and by tomorrow 
I've forgotten about it.


Am 30. November 2022 5:29:22 PM schrieb javierriveracastro 
***@***.***>:

**Comment by grendel111111** [comment]
Yes SUCC has the turn off dialog buttons and they work. The chat card says...
![image](https://user-images.githubusercontent.com/80164119/204932218-20d46905-52d6-4bf3-8d20-b9bdf953a4cd.png)
bleeding out.

**Comment by javierriveracastro** [comment]
I mean that the bleeding out roll itself uses the system dialog.

There is no card for that roll and should probably be added. One day.
