### ISSUE TITLE
Global Action selector for flags

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#544]
A global action selector for flags would elevate global actions to another level I think. Currently AEs and text searches seem to be often used and while flags are somewhat more tech-savy to use, they can be much more useful. Especially for creators building with BRSW support in mind.
The challenge would be to cover deep property paths though. I suggest having one selector for the module id (or 'world') that the user enters and one that covers the property path starting after the id.

**Comment by javierriveracastro** [comment]
Do you mean a selector for any value in the character path... I have to think about it, but it could be possible.

**Comment by SalieriC** [comment]
Well, it could be difficult to implement and definitely requires some thought. Let's say we have something like that:
```js
flags: {
        ["some-module"]: {
            singleNumericValue: 2,
            singleStringValue: "some value",
            singleBooleanValue: false,
            moreData: {
                evenMoreData: {
                    yetAnotherNumericValue: 1,
                    yetAnotherStringValue: "some yet other value",
                    yetAnotherBooleanValue: true,
                },
                anotherNumericValue: 3,
                anotherStringValue: "some other value",
                anotherBooleanValue: false,
            }
        }
    }
```

In this case I think it wouldn't be very future-proof to just cover the single values but adding a way to target all possibilities. It's just a matter of how it shall be formatted. Especially if properties have the ['something-else'] stuff that can't be used without the `['']`. One possibility could be something like this maybe?:
```json
{
    "selector_type": "flag",
    "selector_path": "scope.moreData.anotherNumericValue",
    "selector_value": 3
}
```

But then what to do with scopes or paths that require `['']`? At least for the scope this is exceptionally common. To make it easier to parse it would also be interesting to format it in a way that puts the scope individually like so:
```json
{
    "selector_type": "flag",
    "selector_scope": "some-module",
    "selector_property": "moreData.anotherNumericValue",
    "selector_value": 3
}
```

Or going all in and allowing to add full objects? I'm not sure yet what a good solution would be?

Edit: Allowing *any* value of an actor and not just flags would also be interesting. I haven't thought about that but that would make further implementations of selector strings (and existing ones) almost obsolete.

**Comment by javierriveracastro** [comment]
Why flags?. It would be the same code...

You were faster, the code to look for any value would be the same than looking for flags, but much more flexible. Still some values are complex (arrays, objects), checking that would be very difficult.

**Comment by SalieriC** [comment]
Objects would probably be the easiest as long as BRSW requires the complete property path to a value. Arrays on the other hand would make everything pretty complex but equally flexible. I'm not sure how to do that though and if it is worth the effort right now.

**Comment by javierriveracastro** [comment]
IMHO, this issue has been made obsolete by the 'actor_value' selector that let you check for flags (and any value in the actor).
