### ISSUE TITLE
Don't apply encumbrance penalties to NPCs.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#545]
Currently encumbrance penalties are applied to PCs as well as NPCs. I am not sure if anyone even bothers with encumbrance on NPCs but although there is no way to view the current and max encumbrance of NPCs aside from looking at the code (or displaying it as a bar on the token) it does get applied by the system for some reason.
Anyway I think an option to toggle it off would be best although I wouldn't mind deactivating it altogether.

**Comment by javierriveracastro** [comment]
I just don't bother with encumbrance, just max strength.

But rules are rules. It could be added as an optional rule, but default behavior should be the RAW interpretation AFAIK.

**Comment by SalieriC** [comment]
If you say "rules are rules" then what are we talking about here? I don't think that there is any indication in the core rules about Encumbrance applying to allies at all. I also don't think it is intended by PEG that it does. You are not even supposed to track ammo for them. So I think the system did it _wrong_ here. But either way is fine for me. It just doesn't make sense to track their encumbrance IMO and I don't think there is any part in the rules mentioning it.

**Comment by javierriveracastro** [comment]
It applies to "characters", and allies are characters. While I agree that RAI is to ignore encumbrance except in special situations (I have never used it), RAW is (at least to me) quite clear.

So ignoring encumbrance should an optional rule, and now that we talk to it we should probably add an option to ignore it for PCs too.

**Comment by SalieriC** [comment]
I think you're wrong about that. SWADE p.112 distinguishes between characters and allies:
> It doesn’t matter whether or not the _characters_ control the allies, only that the _players_ do.

(Emphasis in original)

SWADE already has the option to not apply encumbrance penalties. That should be enough I think.

**Comment by javierriveracastro** [comment]
I think this quote is just talking about "player's characters" but committing player's as it is clear by the context. 

If you were right NPCs can't be shaken as the rules say:
```

Shaken
Shaken characters...
```

**Comment by javierriveracastro** [comment]
But anyway we need three options:

- Don't apply encumbrance
- Apply encumbrande only to Player Characters
- Apply encumbrance to every one.

The system option is just a on/off toggle, so we will need something else (that could be in addition to system option).

**Comment by javierriveracastro** [comment]
Done, I finally added an optional rule.
