### ISSUE TITLE
Option to not ace.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#546]
When attacking an object The damage dice don't ace. Is it possible to have an option that suppresses acing for damage in world actions. I know this might be too hard to do and if so Can be done with a text warning.

**Comment by javierriveracastro** [comment]
I'm not sure but  it could probably be done.

**Comment by Buuuurce** [comment]
I noticed damage input into the "damage modifier" field won't ace without the x at the end of the die size so it's already possible, just really time consuming. The dice also re-roll properly, unlike any bonus dice added to trait rolls.

**Comment by javierriveracastro** [comment]
Done.
