### ISSUE TITLE
Gang Up Levels Compatibility

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#547]
Hi.

Gang Up detect tokens in other levels when using the module levels.

In this example the red cat got +1 gang up because there is another cat in the lower level.
https://user-images.githubusercontent.com/4999783/206282107-ed11ce75-5c02-4914-9a8e-ec44851372ee.mp4

Is it possible to make BR know about levels?

**Comment by SalieriC** [comment]
It shouldn't be too difficult to do and actually shouldn't be seen as a 
compatibility thing. Levels just uses token elevation so in the gang up 
calculation just exclude tokens that have an elevation that is different 
than the other tokens and everything should be fine I guess. The question 
would just be: how different is different enough? I think an exact match or 
anything more than 1 in elevation difference should rule tokens out of gang up.


Am 7. Dezember 2022 8:54:56 PM schrieb Bruno Calado ***@***.***>:

**Comment by brunocalado** [comment]
> It shouldn't be too difficult to do and actually shouldn't be seen as a compatibility thing. Levels just uses token elevation so in the gang up calculation just exclude tokens that have an elevation that is different than the other tokens and everything should be fine I guess. The question would just be: how different is different enough? I think an exact match or anything more than 1 in elevation difference should rule tokens out of gang up. Am 7. Dezember 2022 8:54:56 PM schrieb Bruno Calado ***@***.***>:
> […](#)
> Hi. Gang Up detect tokens in other levels when using the module levels. In this example the red cat got +1 gang up because there is another cat in the lower level. https://user-images.githubusercontent.com/4999783/206282107-ed11ce75-5c02-4914-9a8e-ec44851372ee.mp4 Is it possible to make BR know about levels? -- Reply to this email directly or view it on GitHub: #547 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

Nice. If this is just a height situation this would be useful to flying enemies too. So, they too don't add gang up.

**Comment by grendel111111** [comment]
I think I would go with a difference in height of 0.8 (or 0.9) or more so that things 1 floor up won't trigger it.

**Comment by SalieriC** [comment]
Yes, exactly. And the more I think about it the more I'm convinced that anything >1" of elevation difference is a perfect solution because that means that airborne tokens one square above or below still add to ganging up while it still allows Levels compatibility since a level height of 1" is a terrible idea anyway.

**Comment by javierriveracastro** [comment]
The problem could be people playing on 5 feet grids...

**Comment by SalieriC** [comment]
But those are playing a different game then. Do templates even work properly there? Since SaWo calls for 1" grid/gridless we don't need to worry about it, do we? Especially since a conversion of maps is so easy.

**Comment by javierriveracastro** [comment]
Done, with 1 as the minimum altitude difference to not count for gangup
