### ISSUE TITLE
Question about questions and log

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#549]
I have 2 questions, the first being where is the best place to ask questions? (This doesn't feel right as it is for issues, and the SWADE Discord feels wrong for clogging up the channel with BRSW content, but I can't find anywhere else). Second question is when you trigger a macro from BRSW it sends a messge to the macro with actor, rolls, etc. is there a way to log that message to the concole so we can see what the data is and the right syntax to use them?

**Comment by javierriveracastro** [comment]
1.- Yes, this is not the best place to ask questions. For now I think that we can keep using the SWADE Discord. Last official word from Flo was that discussing system modules was right and there is not so much traffic in it, less alone BR related. There are not really good options as using module-discussion will mean that we are going to be buried by dnd players.

2.- This should be in the docs. You can get what is passed here (https://github.com/javierriveracastro/betteroll-swade/blob/9ff23911ef4fe81a02e26cc9c50b2f12dcf5635f/betterrolls-swade2/scripts/item_card.js#L628) and you can just log the parameters in the macro itself.
