### ISSUE TITLE
Same roll on free reroll

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#553]
Hi. 

This happened sometimes already. My players started to complain about it.

When you click reroll you get the same dice.

Example:
![image](https://user-images.githubusercontent.com/4999783/211438870-fcabf635-3dd8-4dc6-a67c-9dc26a16967c.png)

**Comment by SalieriC** [comment]
https://www.youtube.com/watch?v=JiSS5xn_0fc

Roll the same roll! - Alright same roll, here we go!

I'm not sure that this really is a bug but just chance.

**Comment by javierriveracastro** [comment]
The next time that it happens, try to modify one roll. That way we can know if it is a duplication bug.

**Comment by javierriveracastro** [comment]
I will close this as there is not enough info to take any action.
