### ISSUE TITLE
Damage rolls always use d4

### ISSUE THREAD

**Issue by lizzard77** [javierriveracastro/betteroll-swade#554]
Foundry 10/v291, SWADE Core Rules and German SWADE Core and character sheet

- Pull an item (i.e. short sword) from the SWADE equipment compendium into the character sheet
- Equip item
- Click on the damage formula in the character sheet

Even though for this item the formula is `@str+d6`, 2d4 are rolled (character has STR d4). I can even enter `1d6` for the formula, and even then d4 is used. Disabling Better Rolls 2 for SWADE solves the issue.

![image](https://user-images.githubusercontent.com/15921685/211740336-2b0a1c47-a4a9-403f-8a43-cf661ad0df75.png)

**Comment by SalieriC** [comment]
The character doesn't meet the strength requirement of that weapon.

**Comment by lizzard77** [comment]
Ooooohhhh! I wasn't aware of that! Sorry for bugging you, so that's a feature, not a bug :-) I love it.

**Comment by SalieriC** [comment]
No harm done. =)
