### ISSUE TITLE
item_description_includes: Can we add the tags 

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#555]
The item_description_includes selector references the discription area of a power/item etc. Can we get it to also check the trappings strip at the top of powers. (Currently if you put fire or magic in the trappings part of the description it doesn't get picked up only in the main body of the description).

**Comment by javierriveracastro** [comment]
Sure, should be easy.

**Comment by javierriveracastro** [comment]
Done in git (devel branch)
