### ISSUE TITLE
New Selector Type: actor_has_item

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#556]
Some items can change the rolls. 

Examples:
Rhino Hide (armor): +4 damage
Laser Sight (gear): +1 shooting

Can you add a way to identify items (armor, gear, consumable, etc) with a new selector? 

tks

**Comment by grendel111111** [comment]
Can I suggest that it checks for if the item is equipped? That way it doesn't trigger for unworn armor or things stored or carried.

**Comment by brunocalado** [comment]
thank you

**Comment by javierriveracastro** [comment]
actor_has_item added. I left the issue open until I add actor_equips_item (name not final).

**Comment by javierriveracastro** [comment]
Done
