### ISSUE TITLE
Bug on Stream Template

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#557]
When I place a stream template in the scene it's just a line. The width is empty.
![image](https://user-images.githubusercontent.com/4999783/214304783-68830b19-234e-44de-aacc-9d522ea05c71.png)

This don't happen on core button
![image](https://user-images.githubusercontent.com/4999783/214304826-24b3b770-7813-461b-a90f-b67069497bc0.png)

**Comment by javierriveracastro** [comment]
Done
