### ISSUE TITLE
New Selector Type: item_from_source

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#559]
Hi

Create a new selector: item_from_source

Use Case
If you have multiple items with the same name from different sources (Savage Pathfinder, Advanced Player Guide, Fantasy Compantion) you can filter to show the correct BR action to each source.

![image](https://user-images.githubusercontent.com/4999783/215290761-b75ad403-849c-4a58-9620-c197c8cb9195.png)

**Comment by javierriveracastro** [comment]
Done
