### ISSUE TITLE
Feature Request: Post to chat.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#56]
Since this is something that isn't really subject of this module, I'm fine if you'd just deny it. But since your chat messages look so nice and are pretty much what I have in mind, I wanted to leave this here. I'm thinking of a way to post the description of items other than weapons and powers to the chat. So for gear that is not something that needs a roll, Hindrances and Edges the icon could be clicked to send a message to the chat without the roll but with the details of the item (e.g. Armour value, protected spots, weight, cost, etc) and an unfoldable description.
Since it is currently not planned to incorporate that into the SWADE system I think would would be great to have that ability here.

**Comment by javierriveracastro** [comment]
Should be done. Like always in version 2
