### ISSUE TITLE
Deleting an Item on an NPC instead activates its chat card.

### ISSUE THREAD

**Issue by Deadlander** [javierriveracastro/betteroll-swade#562]
The title and video covers it all. Able to delete items normally after disabling BR.

https://user-images.githubusercontent.com/13036735/217072156-22ed5735-e18c-4707-88ae-52ff6e05857d.mp4

Thanks!
James from Knights of the Smith Dinner Table

**Comment by javierriveracastro** [comment]
Solved in git. I'm not sure that this merits a release by itself.
