### ISSUE TITLE
Suggestions to Improve Chat Card

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#563]
The br card works great. But, some UI improvements would be nice.

**Replace text with images**
Cover, Multi actions, attack options, situation modifiers could be replace the text with image icons. This would make it takes a single line or two each.

**Image Icons**
To fully replace text with icons the support to image icons is needed. So you can use meaningful images to represent the text.

**Hover text**
All buttons should support hover text. You put the mouse cursor over the button and there a text with information.

![image](https://user-images.githubusercontent.com/4999783/217303720-d379a261-6487-47e1-b667-3fa1ccc7c2ee.png)

**Comment by SalieriC** [comment]
While I do agree that the messages can become pretty big, I have to say that having icons so small that it really matters could be a major accessibility issue. And even for people with good eyesight this could be a problem. The icons would have to be well picked and sized accordingly and this way you could loose what you hope to gain.

**Comment by brunocalado** [comment]
> While I do agree that the messages can become pretty big, I have to say that having icons so small that it really matters could be a major accessibility issue. And even for people with good eyesight this could be a problem. The icons would have to be well picked and sized accordingly and this way you could loose what you hope to gain.

Why the icons would be small? They can have a nice size and save a lot of space. I'll try to make an example.

**Comment by brunocalado** [comment]
This is a simple example. But, you earn free space like this:

![image](https://user-images.githubusercontent.com/4999783/217312324-8626aa7e-ae40-4609-a7c9-eb8bdad74ba5.png)

The icon size could be something 36 up to 48 px.

**Comment by brunocalado** [comment]
To represent the icon is clicked a simple css to add a border or to make the icon smaller or something else

**Comment by javierriveracastro** [comment]
I'm quite sure that this will at the end make the cards bigger. And harder to understand for a novice.

And it will be close to impossible to find icons that are valid for all settings. 

The plus point is that getting rid of translations you get the ability to correctly size the card and layout gets way easier.

I'll post a link to this issue in Discord to try to get more opinions.

**Comment by grendel111111** [comment]
I think a possible solution is to let the groups do most of the heavy lifting and minimize the information in the buttons.
For example: Illunimation is the group name so there is no need to repeat it in the buttons, just use dim, dark,etc.
Same for cover, the buttons can be light, medium, heavy, NT Cover.
Multi action: 2 act, 3 act, run.
1 problem is getting them to appear in a logical order instead of alphabetical order (It wants to put heavy at the start of the list because H).  
![image](https://user-images.githubusercontent.com/80164119/218240970-cca3b383-e181-4447-a617-a28e7edb8b03.png)
Also I think for atarting collapsed there could be an option that if a group name has an astrix in in then that group starts as open. So "Power Modifiers" would start as closed but "Power Modifiers*" would begin expanded.

**Comment by brunocalado** [comment]
> I think a possible solution is to let the groups do most of the heavy lifting and minimize the information in the buttons. For example: Illunimation is the group name so there is no need to repeat it in the buttons, just use dim, dark,etc. Same for cover, the buttons can be light, medium, heavy, NT Cover. Multi action: 2 act, 3 act, run. 1 problem is getting them to appear in a logical order instead of alphabetical order (It wants to put heavy at the start of the list because H). ![image](https://user-images.githubusercontent.com/80164119/218240970-cca3b383-e181-4447-a617-a28e7edb8b03.png) Also I think for atarting collapsed there could be an option that if a group name has an astrix in in then that group starts as open. So "Power Modifiers" would start as closed but "Power Modifiers*" would begin expanded.

Better. But, what about the big text like environmental resistance? Truncate the text would solve that. You could set to the text auto scroll. You could add a tooltip hover feature.

**Comment by grendel111111** [comment]
> Better. But, what about the big text like environmental resistance? Truncate the text would solve that. You could set to the text auto scroll. You could add a tooltip hover feature.

I would put "Target has environmental Resistance" as the group name. 
The buttons would be fire/cold/electricity.

**Comment by brunocalado** [comment]
> > Better. But, what about the big text like environmental resistance? Truncate the text would solve that. You could set to the text auto scroll. You could add a tooltip hover feature.
> 
> I would put "Target has environmental Resistance" as the group name. The buttons would be fire/cold/electricity.

And create another one for Savage pathfinder or whatever? 
![image](https://user-images.githubusercontent.com/4999783/218315633-cd4c68c9-131f-45f7-b288-2e183497004c.png)

The problem is: the button change its size with the text length. 
So, to make the chat card smaller and more clear do something about it is the better solution for lots of situtions.

Things to keep in mind
- Language: you solution for actions and cover is great, but what happens when you translate it?
- Topics limit: create one topic to each case would cost more space and make more confusing to find the button you need.

Solution
Create a button limit size. All buttons can't be bigger than this size. 
The text will roll hover [marquee](https://www.tutorialspoint.com/online_html_editor.php).
They also could have a tooltip on mouse hover.

**Comment by grendel111111** [comment]
environmental resisitance and weakess are consistant between settings I think. Sneak attack on the other hand behaves very differently. DA is in both Pathfinder and fantasy companion. Taranslation is a problem but as I am limited to English I find it hard to compensate for that.

**Comment by javierriveracastro** [comment]
Text rolling over a dozen of labels makes me sick. Literally I mean, even thinking of it makes me dizzy.

Translations are somewhat easy to figure, as no one speaks all the languages. Just don't assume that light is five letters in every language, not that all language split meaning between words like english do. Specially german. I won't be surprised if light cover in german is something like thingyougebehindbutlongertoannoytranslatorandyesligthinthiscase or something like this. 

Just joking, but you get the idea. Also reading order changes. But that's mostly  a problem for translator, and AFAIK most languages currently supported are close related to each other (a couple of latin languages, English and German).

**Comment by brunocalado** [comment]
lol

Then, create a button size limit and use a text hover to show the full button name and a description.

**Comment by brunocalado** [comment]
It's hard problem. I think button limit is the only solution. But, lots of names will not make any sense. It needs someone to know how to limit. 

![image](https://user-images.githubusercontent.com/4999783/218455928-b569e978-9be5-4b29-a636-2554dce93c53.png)
css: https://codepen.io/kazzkiq/pen/qEMjaw/

Maybe, the solution is each user rename their buttons.

But, some improvements to the card css would be nice.
- Remove space betweet buttons.
- Remove buttons margin
- add some ids to the chat card to make easier to customize

**Comment by mrcomac** [comment]
My 2cents as user

We already have icons provided by font awesome, right? I believe it should be as it is. Change it to images can be a mess in near future (that's the reason font awesome exists).

An option that sounds useful is a tiny version of the card.

For instance, remove icons in ilumination and let only text, and multi-action with icons only and the bonuses on it might reduce the size of the card (https://codepen.io/snagov/pen/dyqbwxb)

I think only icons doesn't make sense to BR2 since the idea of this module is allow players/GM to choose options based on the rules without recall if that cover is -2 or -4.

Another solution is buy big screens (larger than 42")

**Comment by javierriveracastro** [comment]
Most of discussions about that are happening in Discord, in this thread (https://discordapp.com/channels/170995199584108546/1125039850161176647/1133072538826707037).

As I don't want to have it duplicated, I'm closing this issue. Thank you everyone for your ideas.
