### ISSUE TITLE
Innate Power Setting Aware

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#564]
Hi.

Can you create a settings option to identify the SWADE setting in game? 

This would let BR2 change its behavior to the selected setting.

**Example**
![image](https://user-images.githubusercontent.com/4999783/218177477-8ec3d1f8-16f2-4d6d-bc4a-2be2d9493fb2.png)
Innate will no cost PP in SWPF. But, in RITFs it works normally.

**Comment by javierriveracastro** [comment]
Done.
