### ISSUE TITLE
Greater Bolt don't show dice

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#566]
This code:
```json
    {
      id:"POWERBOLTMODGREATERBOLT",
      name:"POWERBOLTMODGREATERBOLT",
      button_name:"Greater Bolt (+4)",
      shotsUsed:"+4",
      dmgMod: "+2d6x",
      selector_type:"item_type",
      selector_value:"power",
      group: "Bolt Modifiers"
    }
```

Rolls 4 dice.
![image](https://user-images.githubusercontent.com/4999783/222904023-622a1fdf-1a60-4b61-9bd6-436d4a3f7d83.png)

But, don't display the results in the card. Also, it shows the ID instead of the button name.
![image](https://user-images.githubusercontent.com/4999783/222904034-ee2bd136-cb7d-4aec-a777-5c310c11538a.png)

**Comment by SalieriC** [comment]
Did you try without the x on the dice formula?

**Comment by brunocalado** [comment]
> Did you try without the x on the dice formula?

Yes. 2d6 and 2d6x. Same result.

**Comment by brunocalado** [comment]
![image](https://user-images.githubusercontent.com/4999783/222927486-db4d7eb8-f9b5-4cf2-badf-f1971435e093.png)

**Comment by brunocalado** [comment]
![image](https://user-images.githubusercontent.com/4999783/222927503-1b2a936d-b60d-44ae-b6c9-c62ef121f9d5.png)

**Comment by javierriveracastro** [comment]
The problem, if I understood this correctly, is not that it rolls 4 dice (this is correct), it is that it displays only one die, when that 7 is the result of adding two dice.

Am I right?

**Comment by brunocalado** [comment]
Yes

Em seg, 6 de mar de 2023 05:13, javierriveracastro ***@***.***>
escreveu:

**Comment by grendel111111** [comment]
If the dice explode it adds all them together and displays it in  the one die.

**Comment by javierriveracastro** [comment]
Yes, but there is no explosion there. It had added the extra dice and show it just once.

**Comment by grendel111111** [comment]
Sorry. I meant I ran it and got an explosion. It put everything under the 1 die. I thought it might be useful extra info.

**Comment by javierriveracastro** [comment]
Solved.
