### ISSUE TITLE
Power Damage Reroll Bug

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#567]
After cast a power with multilple targets the player click to spend a benny and reroll for one target. But, br2 rerolls everytrhing.

![image](https://user-images.githubusercontent.com/4999783/222932287-60e564ef-0cdf-49e8-8447-c4dd0ae6841d.png)

![image](https://user-images.githubusercontent.com/4999783/222932299-1448a0dd-4041-48e6-886a-b4a3665f95ef.png)

**Comment by javierriveracastro** [comment]
Done
