### ISSUE TITLE
The power point cost don't sum well

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#568]
Hi.

The sum of modifiers is not working well.

If you mark a couple of modifiers it will not calculate it well.

```
    {
      id:"POWERBOOSTLOWERTRAITMOGREATER",
      name:"POWERBOOSTLOWERTRAITMOGREATER",
      button_name: "Greater Boost/Lower Trait (+2)",
      shotsUsed:"+2",
      and_selector: [
        { selector_type: "item_type", selector_value:"power" }, 
        { selector_type: "item_name", selector_value: "Boost/Lower Trait" }
      ],
      group: "Boost/Lower Trait Modifiers"
    },  

    {
      id:"POWERBARRIERMODDEADLY",
      name:"POWERBARRIERMODDEADLY",
      button_name: starIcon + "Deadly (+2)",
      shotsUsed:"+2",
      dmgOverride: "2d6",
      and_selector: [
        { selector_type: "item_type", selector_value:"power" }, 
        { selector_type: "item_name", selector_value: "Barrier" }
      ],
      group: "Barrier Modifiers"
    },   
```

This would require to remove 6 PP. But, it only take 4 points.
![image](https://user-images.githubusercontent.com/4999783/222999501-87a8d3fa-aba4-4e0e-aa93-e03b1e6774e6.png)

Link: [Link](https://raw.githubusercontent.com/brunocalado/savage-pathfinder-enhanced/main/scripts/init.js)

**Comment by brunocalado** [comment]
another example
![image](https://user-images.githubusercontent.com/4999783/223170144-a42fd8ac-cdde-4414-8f16-27e5db07c05d.png)

**Comment by brunocalado** [comment]
If you override the cost and then add a cost it will fail to sum too.
![image](https://user-images.githubusercontent.com/4999783/223178205-58ee4591-58c4-49f4-81b6-b23c9efd2e03.png)

**Comment by javierriveracastro** [comment]
Done

**Comment by brunocalado** [comment]
It's not working yet
![image](https://user-images.githubusercontent.com/4999783/225717480-04813bb9-435b-46ce-a2c3-be6923ad991c.png)
