### ISSUE TITLE
BR don't trigger NPC actions

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#569]
If you click an NPC action it will not trigger BR card
![image](https://user-images.githubusercontent.com/4999783/223420433-4043b947-275d-428a-9055-121d4994b34d.png)

**Comment by javierriveracastro** [comment]
This has nothing to do with NPCs, it is just that damage actions are not supported.

Trait actions should work.

**Comment by brunocalado** [comment]
Is it possible to make It work for damage?

Em ter, 7 de mar de 2023 12:22, javierriveracastro ***@***.***>
escreveu:

**Comment by javierriveracastro** [comment]
Yes, it is also solved in git (check devel branch).

The problem is what I do when there is no action selected and they try to roll damage. Probably just roll an action?. But witch one?.

**Comment by javierriveracastro** [comment]
Let's go for 1
