### ISSUE TITLE
Damage with raise rerolls base damage

### ISSUE THREAD

**Issue by kristianserrano** [javierriveracastro/betteroll-swade#57]
When reviewing the damage with raise result, it seemed as though it was rerolling the base damage with the additional d6. Instead, it should roll a single d6 and add that result to the regular damage to calculate the total.

This is important because I had several cases in which the roll with raise was actually lower than the regular roll when it should have been the regular roll plus 1d6.

**Comment by javierriveracastro** [comment]
Solved
