### ISSUE TITLE
`system.woundsOrFatigue.ignored` is not respected in rolls.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#570]
Since SWADE v. 2.2 there is another property on actors: `system.woundsOrFatigue.ignored`. This is intended to automate the Relief (Numb) power. BRSW currently doesn't seem to respect it. It should lower the **total penalty of Wounds and Fatigue combined** by the properties value and should stack with wounds.ignored and fatigue.ignored.

**Comment by SalieriC** [comment]
Done in Git.

**Comment by SalieriC** [comment]
Accidentally closed.

**Comment by javierriveracastro** [comment]
Done.
