### ISSUE TITLE
Powers with 0PP don't trigger the cost

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#571]
Hi.

If a power have 0 cost it don't trigger the PP management.

This is required because there is powers where you need to set the cost in the chat card.

Summon Monster has the cost of the selected monters.
![image](https://user-images.githubusercontent.com/4999783/225145971-923f5e78-984f-4aba-9f18-136a03f374b9.png)

**Comment by javierriveracastro** [comment]
You can put a 1 there and use PP override. Free powers can be useful in some settings AFAIK.

**Comment by brunocalado** [comment]
> You can put a 1 there and use PP override. Free powers can be useful in some settings AFAIK.

Yes. But, you would have to edit lots of powers everytime you drag something from an official module.

Is it hard to make override pp work with 0 or text? Some powers have text in the official module (**Special**).

**Comment by javierriveracastro** [comment]
Ok, that's a good point.

I don't know I need to check the source.

**Comment by brunocalado** [comment]
Summon Ally also can use this. 
![image](https://user-images.githubusercontent.com/4999783/225336860-0f8afe4c-988e-458e-9878-98e4c2df760c.png)

**Comment by javierriveracastro** [comment]
Should be done.
