### ISSUE TITLE
Select for rank.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#572]
Not sure if it is detectable, but is it possible to add a select for rank? So you could have a button only turn up if you are rank X

**Comment by brunocalado** [comment]
> Not sure if it is detectable, but is it possible to add a select for rank? So you could have a button only turn up if you are rank X

I was thinking about that. But, there is one special case 

The Summons powers from APG have a list of powers you unlock with rank.
Be able to unlock then with something like: >=Veteran would be nice
![image](https://user-images.githubusercontent.com/4999783/225334970-44e15589-f649-45d3-809a-0805c3d8c8be.png)

**Comment by grendel111111** [comment]
If it can't detect >=, You can do that with just a select for button. Use "not"  at the lower levels and select for at the higher levels. It is at most 1 extra conditional
Novice - no change.
Seasoned - not Novice.
Veteran - Not Novice, Not Seasoned
Heroic - Heroic or Legendary
Legendary - Legendary

**Comment by javierriveracastro** [comment]
Rank is actually a string, so no greater or lesser unless you want it alphabetically ordered.

What we need here is somewhere to check an arbitrary value in the actor data structure.

Maybe something like `selector: 'actor_value', value: 'system.advances.rank=Novice'`

Afterwards we can add support for > and <

**Comment by SalieriC** [comment]
Haven't read everything but maybe that helps: Rank is a string but `system.advances.value` is not, that's a number.

**Comment by javierriveracastro** [comment]
'actor_value' selector added. I'm closing this.
