### ISSUE TITLE
Power Points don't Sum Well

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#574]
It should be 7pp
![image](https://user-images.githubusercontent.com/4999783/225729494-4f60ac84-e5b5-4d24-8b8c-e7157f6979db.png)

This work well
![image](https://user-images.githubusercontent.com/4999783/225729824-76b1a2a7-e5fb-468f-bd1e-1deaadfbd8fe.png)

It should be 6pp
![image](https://user-images.githubusercontent.com/4999783/225730412-73084d69-5381-4ba5-90bf-56d02f2322ef.png)

**Comment by grendel111111** [comment]
If you look at the order the actions are happening it is adding 1 for Adaptable Caster, then it is overriding the PP with Seasoned setting it to 3, and then adding 2 for increased trait for a total of 5. You need to move teh summon Ally Rank higher up in the order so it is choosen first. Or change  Shots used to be: Novice +0, Seasoned +2,  Veteran +4, and Heroic +6. (You don't need to change the buttons they can still say Novice (1)).

**Comment by javierriveracastro** [comment]
Anyway, I should probably add all the modifiers together before updating the last not adding "shoot_override" to make this easier to use

**Comment by brunocalado** [comment]
> Anyway, I should probably add all the modifiers together before updating the last not adding "shoot_override" to make this easier to use

This would let the Power Point management almost perfect. The https://github.com/javierriveracastro/betteroll-swade/issues/565 would let it be perfect.

**Comment by javierriveracastro** [comment]
This should be done
