### ISSUE TITLE
actor_has_effect has got messed up between 3.19 and 3.20.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#575]
![image](https://user-images.githubusercontent.com/80164119/225832752-0d6b79f7-0f2d-474b-b59b-aa77b4d65280.png)

![image](https://user-images.githubusercontent.com/80164119/225833123-e0dde448-034f-4838-b9ef-e9df8e064b49.png)
The first picture is from 3.2/3.21
The second picture is from 3.19 (With no other changes)

In one of the changes from 3.19 to 3.20 the "actor_has_effect" condition seems to have got a bit messed up (target_has_effect is still fine). The actor has the effect Fear and it used to bring up an option to roll to resist the fear effect.

This was done by this action:
{"id":"9ResistingFear",
"name":"Resisting Fear",
"button_name":"Resisting Fear",
"runSkillMacro":"FearResults",
"and_selector":[
{"selector_type":"attribute",
"selector_value":"Spirit"},
{"selector_type":"actor_has_effect",
"selector_value":"Fear"},
{"not_selector":[
{"selector_type":"item_type",
"selector_value":"weapon"}]}],
"group":"Resisting Fear"}

**Comment by javierriveracastro** [comment]
Ummm... nothing was touched there since September.

![imaxe](https://user-images.githubusercontent.com/8113700/225848473-80d1f0b5-4213-497c-b504-9121fb070536.png)

Something else must be going on.

**Comment by javierriveracastro** [comment]
Could it be that you have two actions with the same id?

**Comment by grendel111111** [comment]
Update. After doing a lot of tests it is a problem with Token Action HUD. If you use it to call a roll on an unlinked actor it runs the roll from the actor on the side bar. So if you have an active effect on the token, but not on the actor on the sidebar it doesn't register the effect (It looks at the actor in the side bar to decide what effect etc are on the actor not the token). Like wise if there is an item on the character in the side bar but not the token it treats it as having the effect.

**Comment by javierriveracastro** [comment]
Then this is probably a TAH issue. As it is transitioning from a all system supported architecture to each system is its own module one I'm not sure if it makes sense to look into it or if it's better to just wat for a new release.

**Comment by javierriveracastro** [comment]
I will close this until TAH future is somewhat clear.
