### ISSUE TITLE
Version 3.21 getting target number from target or selected acts like NPC rolled a 1

### ISSUE THREAD

**Issue by TheLaslo** [javierriveracastro/betteroll-swade#577]
![image](https://user-images.githubusercontent.com/74621847/226455109-bafbd270-45a0-4950-bc5b-21743d16c31d.png)
when selecting the "change target number" through the target icon or the select icon BR rolls a six sider and if a 1 comes up it marks a failure.

![image](https://user-images.githubusercontent.com/74621847/226455347-cab9e00e-701a-4c52-a12e-171c7bec7226.png)

**Comment by javierriveracastro** [comment]
I can't reproduce this. Can you give me more context?

**Comment by TheLaslo** [comment]
I attempted to reproduce but couldn't do it consistently.  ( actual consistent example below )
But here is the case:
If a character ( even a wild card) rolls a 1 on either of their dice ( or any in the case of frenzy) if you go to change the target then another d6 will be rolled and the card says "Testing for critical"
![BRSW_error](https://user-images.githubusercontent.com/74621847/230966210-dc813d8c-18f0-4c32-b6f2-fae17ffb9039.png)

**Comment by javierriveracastro** [comment]
Thanks, rolling a one was the key. Solved in git.
