### ISSUE TITLE
Turn Off Actions

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#578]
Hi.

The actions look nice in the default system. I know I can press control to trigger control to use the default system. 

But, is it possible to add an settings option to disable better roll actions? Or maybe provide a clean look like the system

![image](https://user-images.githubusercontent.com/4999783/227562020-d73cec53-78fc-43ac-8768-adf068634a57.png)
 
tks

**Comment by brunocalado** [comment]
Yes. I did more tests with actions. Better Rolls need to rework a lot to deal with them. 

I think a way to disable the better rolls for actions is very important. It's doing more harm then good now. 

After that rethink better rolls and actions

**Comment by javierriveracastro** [comment]
I can't see an easy way to disable actions. They use similar classes to items, so we better start with the rethinking.

**Comment by brunocalado** [comment]
> 

oh... Is not possible to filter the items by type? I thought it would be simple.

**Comment by javierriveracastro** [comment]
Yes, the items itself for sure. I was trying to avoid calling br2 using the classes in the character sheet.

Intercepting it in js should be possible, but uglier (I need to run some stupid code to do nothing).

Let me think about this.

**Comment by brunocalado** [comment]
> 

The 2.3 says something about roll classes. Maybe is better to wait for it.

**Comment by javierriveracastro** [comment]
Doesn't really make sense. I totally ignore system rolls.

**Comment by javierriveracastro** [comment]
I think I can do the same thing that I did for consumables.

**Comment by javierriveracastro** [comment]
Done, it gets so easy when you think about it the right way...
