### ISSUE TITLE
Injuries from becoming Incapacitated are not applied.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#579]
While testing the new hooks which pass the effects from injuries, I noticed that injuries from incapacitation are not applied. This is the hook:
![image](https://user-images.githubusercontent.com/1230041/227813037-79e81691-4cb3-475f-a8f3-b3961ac19fe2.png)
This was for a permanent injury, I don't know how things are for non-permanent ones. Injuries from gritty damage get applied just fine though.

**Comment by SalieriC** [comment]
On further inspection: There seems to be something off with the injury effect for arm and unmentionables results. Those are never applied it seems, neither as permanent nor as gritty damage injury.
There also seems something off with the string defining the type of injury. "gritty" is passed but for permanent injuries (and possibly non-permanent ones) it's currently `undefined`.

**Comment by javierriveracastro** [comment]
Now, that I look at it, there are no active effects for unmentionables or arm.

**Comment by javierriveracastro** [comment]
Both bugs should be solved
