### ISSUE TITLE
The Dice So Nice wild die settings are not being replicated to other players when using BR2

### ISSUE THREAD

**Issue by ddbrown30** [javierriveracastro/betteroll-swade#580]
See Discord discussion here: https://discord.com/channels/170995199584108546/715780900322803753/1089967956357824522

The issue is that wild die customization is not unique and synced for each player. Whatever wild die settings you have locally is how the wild die will appear for every player. In other words, if PlayerA has their wild die yellow and PlayerB has their wild die red, PlayerA will see a yellow wild die for both PlayerA and PlayerB's rolls and vice versa.

If BR2 is disabled, the dice settings are replicated correctly.

**Comment by jseeley150** [comment]
To expand on this issue, if you choose to make your wild die from a die set from The Rollsmith then BR2 just shows a black textured die. The base system had a similar issue for re-rolls (free or benny) and was fixed in the 2.3.0 release that changed the way the roll was cloned.

**Comment by javierriveracastro** [comment]
This should be done.
