### ISSUE TITLE
Add Rapid Shot to SWADE Better Rolls2

### ISSUE THREAD

**Issue by JasonSunday** [javierriveracastro/betteroll-swade#583]
As a GM in a PfSW game,
I (and my players) would like the option to use Rapid Shot in my Better Rolls attack menu
So that I don't have to do it manually.

**Comment by grendel111111** [comment]
You can add this as a world action:
{"id":"6RapidShot",
"name":"RapidShot",
"button_name":"Shoot 2 times",
"rof":"2",
"shotsUsed":"2",
"and_selector":[
{"selector_type":"actor_has_edge",
"selector_value":"Rapid Shot"},
{"selector_type":"skill",
"selector_value":"Shooting"},
{"selector_type":"item_type",
"selector_value":"weapon"}]},
"group":"Rapid Shot"}

It only applies for pathfinder. fantasy companion has a slightly different edge called double shot.

**Comment by javierriveracastro** [comment]
Right now, I believe that the best place for actions that are related to settings (like SWPF) are their own module (like Bruno's PF one). Otherwise we are going to have clashes, as it happens here.

So I going to close this. If you have some reason against these decision, please state them here.
