### ISSUE TITLE
There are two "Ran" options in the Global Actions list?

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#584]
There are two "Ran" options in the Global Actions list?

![image](https://user-images.githubusercontent.com/64320/232090982-f477b981-cb49-4911-a22d-44d0e8d79461.png)

**Comment by javierriveracastro** [comment]
Yes, one is for people with the steady hands edge, another for all the rest.

The one for Steady Hands should read "Ran(-1)". Next version should have it corrected.
