### ISSUE TITLE
Applying damage when shaking, doesn't apply shaken status

### ISSUE THREAD

**Issue by basic-element** [javierriveracastro/betteroll-swade#586]
After targeting and applying damage, it just says "Actor has been shaken" in a new chat card. But, the shaken status is not applied to the actor.

**Comment by valdier1** [comment]
I'm not sure this is limited only to shaken, I was seeing similar with Wild Swings as well not applying the condition.

**Comment by javierriveracastro** [comment]
I haven't been able to look at this, but I'm wondering if this could be related to this item in the SWADE changelog:

` Added the ability for certain status effects to add related status effects when they are created.`

**Comment by javierriveracastro** [comment]
No, it was our own, original bug. Should be solved and I will make an emergency update now, as this is a showstopping bug.
