### ISSUE TITLE
Removing automatic opening of item card after right click on the gear icon 

### ISSUE THREAD

**Issue by HOND0123** [javierriveracastro/betteroll-swade#587]
With the new reload features i would like to recommend an option to disable the automatic opening of the "item card" after right click on the icon. It's overlapping with the reload menu. If you close it, the menu will close too....Workaround: you can drag the item card elsewhere and after "re-clicking" you access the reload menu but you have to close the item card every time after you reloaded. 
![image](https://user-images.githubusercontent.com/100947962/233956223-bd83efce-062d-41a8-9967-0eb4a9c7a592.png)

**Comment by javierriveracastro** [comment]
Done.
