### ISSUE TITLE
Problem with reloading magazines or batteries. 

### ISSUE THREAD

**Issue by CarWashMeNot** [javierriveracastro/betteroll-swade#588]
So, I got my weapon set up like this 
![pistol](https://user-images.githubusercontent.com/79021008/234604589-2829c250-c5be-4e9e-a1fc-6cf3047e8639.png)

and my ammunition like this
![battery](https://user-images.githubusercontent.com/79021008/234604613-b7ad263f-529e-4ae9-8941-6b2b8ef2c0e2.png)

but it wont work. What am I doing wrong? When I toggle to reload type  FULL it is working, but using the batteries as single bullets, which is not what I want. It always says, that I don't have any consumabled marked as ammunition.

**Comment by CarWashMeNot** [comment]
Okay, I used Foundry in German and the error message was not clear enough. In english it totally made sense, since I did not create my ammunition as "consumable".

**Comment by javierriveracastro** [comment]
AFAIK reloading is now using system code. So there should be not related at all to BR2.

This is likely a system bug. Try it again with BR2 disabled to be sure. If it somewhat works then reopen this issue and please write exactly what are you doing (which reload button are you clicking) and what you expect to happen (to tell the truth I have no idea at all as how batteries are supposed to work).

I'm closing it now as it looks quite difficult that this is BR2 related to me. Again feel free to open it again if you think I'm wrong.

**Comment by javierriveracastro** [comment]
Also get sure that you are using the last version (2.32) of BR2. Now that I think about it what you are describing makes sense with prior versions, where BR still used its own code to manage ammo.
