### ISSUE TITLE
Shield items have a chat message with a reroll button.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#59]
So, intentionally or not, Shields can be pinned to the chat (which is awesome btw, should be available for everything, see #56), but it is treated as a roll as it seems. It gives a message that seems to be a roll, only there is nothing rolled, but there still is a reroll button.
![image](https://user-images.githubusercontent.com/1230041/92599192-307bc000-f2aa-11ea-8c27-7a5fe09bf093.png)
It could also be made (instead of a pin to the chat) as a roll for shield bash as per SWADE p. 71. It would then need to roll Fighting and @str+d4 damage.

**Comment by javierriveracastro** [comment]
Depends on #55

**Comment by SalieriC** [comment]
Same is true for Armour as it seems.

**Comment by javierriveracastro** [comment]
This is also solved in betterrolls 2.
