### ISSUE TITLE
Character icon disappears from card when buttons clicked

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#591]
The initial card shows the character icon ...

![br2-player-icon-1-initial](https://github.com/javierriveracastro/betteroll-swade/assets/64320/c4a492d5-9a84-4c75-8e37-b0add8dc74d4)

But when I click any of the button on the BR2 card, the icon disappears ...

![br2-player-icon-2-after-click](https://github.com/javierriveracastro/betteroll-swade/assets/64320/3441277d-9cf7-470d-a67b-51d2984fdb90)

BR2 v3.25
SWADE v2.3.6
Foundry v10.291

**Comment by javierriveracastro** [comment]
Bugfix released.
