### ISSUE TITLE
Attack Inanimate Object aces damage on melee weapons

### ISSUE THREAD

**Issue by ddbrown30** [javierriveracastro/betteroll-swade#593]
1. Make an attack with a melee weapon
2. Select the Attack Inanimate Object option
3. Click roll damage until a roll comes up with one or more dice that roll their max value
4. The die aces

I checked the code and it is handling it but it looks like the rolls for melee and ranged are handled differently. Melee attacks don't see to require the x at the end in order to ace.

**Comment by javierriveracastro** [comment]
The problem is in @str expansion. It is happening after removing the x, so it is not affected by it. That's why you are only seeing the problem is melee damage rolls.

**Comment by javierriveracastro** [comment]
Solved.
