### ISSUE TITLE
If a character does not have the associated trait for an item, the card does not render correctly

### ISSUE THREAD

**Issue by ddbrown30** [javierriveracastro/betteroll-swade#594]
1. Add a ranged weapon that uses shooting to a character
2. Ensure that character does not have the shooting skill
3. Attack with the weapon
4. The item card will be empty

If a character does not have the associated skill, it should fall back to unskilled. The fix for this could maybe just be limited to fighting and shooting since powers can't be used unskilled.

**Comment by javierriveracastro** [comment]
It seems to work on my side.

A couple of questions:

- Does the actor has an unskilled skill. The module fall backs to a skill in ["untrained", "untrainiert", "desentrenada",
    "non entraine", "non entrainé", "unskilled", "unskilled attempt"] to roll unskilled attempts. System is supposed to add it automatically to all actors.

- How is the weapon configured? Has it a string assigning it a skill or is BR2 guessing it?

**Comment by ddbrown30** [comment]
- Yes. It is named `(Unskilled)`
- It has the skill Shooting assigned to it.

If you have the pathfinder module, you can do the exact same test as me by dragging the long or short bow from the gear compendium. If you have the SWADE module, the bow from there has the same problem.

Actually, I just tested renaming (Unskilled) to be just Unskilled and that fixed it. Probably just a bug with your regex or string compare logic. FYI, that seems to be the what unskilled is named when importing characters from savaged.us.

**Comment by javierriveracastro** [comment]
Ahhhhhh.... I'll add (Unskilled) to the array.
