### ISSUE TITLE
Rerolling Powers that you have a success with then get a fail. PP correct?

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#599]
If you use a power and it fails (but not crit fail) it uses 1PP. If you reroll it changes the PP to the full amount as expected.
If you get a success and decide to reroll either to get a raise or a higher number to set a target number for a test, then it takes the full PP.
But if you reroll and get a fail on the reroll it will change the PP to 1 because you failed, but you would use the previous roll and get at least a success, so should the PP then be the full amount as yo u have already passed the tast and will choose the better result (I can't think of any reason you would choose to take the fail in that situation (Unles it is a crit fail). So should the PP check look to see if you have at least a success on any of your previous rolls on that card?

**Comment by SalieriC** [comment]
Yes, I think this is a bug.

**Comment by javierriveracastro** [comment]
Now selecting and old roll triggers a recalculation of the expended power points. This should solve this issue.
