### ISSUE TITLE
Right click menu opens and immediately closes after something on the sheet was edited.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#60]
For example after editing a hindrance or edge.

**Comment by javierriveracastro** [comment]
I can't make it happen. It does happen when editing a skill in a NPC sheet (right clicking on it), and it is a bug, but I can't make it happen on edge editing, adding or removal.

**Comment by SalieriC** [comment]
Try opening a PC and make a new Edge/Hindrance by clicking the +. Then try again to right click the skill. Does this reproduce it? It does for me. Also tested it w/o other modules.

**Comment by javierriveracastro** [comment]
Sorry. I was expecting that the menu was opening when I was making a new edge. I will try this afternoon.

**Comment by javierriveracastro** [comment]
Now I can reproduce it. Not that I understand why.

**Comment by javierriveracastro** [comment]
Solved.
