### ISSUE TITLE
Martial Artist/Warrior are adding an extra damage die

### ISSUE THREAD

**Issue by ddbrown30** [javierriveracastro/betteroll-swade#601]
The Martial Artist edge should give the character a d4 damage die or upgrade it if they already have it from something like Claws or Brawler. The Martial Warrior edge then upgrades that die another type.

What BR2 is doing is assuming that MA is always giving a d4 and MW is always giving a d6, which is incorrect and just makes everything more complicated to deal with if you're using anything other than the simplest case.

The additional dice should be removed and should be instead manually implemented in item actions like other similar edges.

**Comment by javierriveracastro** [comment]
I'm not sure about that. It makes sense but it can also broke some people setup. Let me think a little more about it.

**Comment by ddbrown30** [comment]
Yeah, fair enough. Always tough to make a change like this since you can't please everyone.

**Comment by javierriveracastro** [comment]
I have asked a bit around. Everybody believes this is a good change. They also believe that it will break some people games and that sucks.

I have really no idea of what to do about this. Probably accept it as I believe not a lot of people are relaying on it.

**Comment by ddbrown30** [comment]
Yeah, my vote should be obvious but I would just make the change. It's an easy fix for anyone who was relying on it vs an unsolvable problem for people who aren't.
