### ISSUE TITLE
Bullet consumption issue

### ISSUE THREAD

**Issue by WyntherKnight** [javierriveracastro/betteroll-swade#604]
Toggling the "Subtract ammo" causes the weapon to consume a number of shots equal to what is written on the ROF of the weapon (if ROF is 4, then 4 shots are used). Toggling it off actually consumes a number of ammo as written in the rules (if ROF is 4, then 20 shots are used). Shouldn't this be the other way around?

![image](https://github.com/javierriveracastro/betteroll-swade/assets/66346903/886d4735-6237-41a6-a39c-a8ee4d0b39d1)

**Comment by javierriveracastro** [comment]
Ummm... are you using SWIM ammo management?

**Comment by WyntherKnight** [comment]
Yes, I use SWIMM, but I don't see any ammo mangement in for PCs (only for NPC) so I disabled SWIMM. Now when "subtract ammo" is toggled, It still only consumes 4 shots (for an ROF of 4) and disabling it does not consume any shots.

**Comment by WyntherKnight** [comment]
I see, looks like SWIMM is able to use the rules of ammo consumption correctly, but BRSW doesn't.

**Comment by javierriveracastro** [comment]
The truth is that BRSW doesn't do ammo management. It delegates it either to the system or SWIM. But let me check if I'm passing something incorrectly to system.

**Comment by WyntherKnight** [comment]
Thanks. We could have sworn that BRSW was the one handling the ammo consumption.

**Comment by javierriveracastro** [comment]
At the end it was my fault. I was passing the incorrect number of shots to system.
