### ISSUE TITLE
Alphabetically sort action card section entries

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#605]
Alphabetically sort action card section entries.

e.g. in the attached screen shot, the Attack options section, the various Called Shots should be together, after the Attack Inanimate Object, and before the Desperate Attacks ...
![image](https://github.com/javierriveracastro/betteroll-swade/assets/64320/4b75be33-7ffb-4d92-b5a2-211935fdd2bf)

Unfortunately this won't work so well in the Cover section, as they are better as they are, ie. sorted in increasing cover level.

Maybe sort by just the first word? 
Or an override for each section?

Better yet, a user defined sort, maybe a hidden field element of the global action?

**Comment by javierriveracastro** [comment]
Sorting by ID makes the most sense to me. It is hidden an already there.

**Comment by steveculshaw** [comment]
That sounds great

**Comment by javierriveracastro** [comment]
Done, now ids should be changed to get proper ordering, but that is another bug.

**Comment by steveculshaw** [comment]
Nice one
