### ISSUE TITLE
Option to use the "Wild Die Preset" from SWADE Dice Settings

### ISSUE THREAD

**Issue by jseeley150** [javierriveracastro/betteroll-swade#606]
It's different than Theme and supports "The Rollsmith" dice, which are not configurable as a theme.

There are a couple of free Rollsmith dice sets available, including a free set in the module installer "Foundry VTT Anniversary Dice Set by The Rollsmith", and Rainbow from The Rollsmith website.

Without this setting, the only way to use the Wild Die Preset is to bypass BR2SW.

**Comment by javierriveracastro** [comment]
Done.
