### ISSUE TITLE
Effects that stay

### ISSUE THREAD

**Issue by WyntherKnight** [javierriveracastro/betteroll-swade#608]
Making multiple effects that modifies the same skill roll will leave the effect on future rolls even if some of the effects are turned off. They also stay even if the effects are removed. 
![image](https://github.com/javierriveracastro/betteroll-swade/assets/66346903/a893217b-5eed-471b-94f8-a5e01faa646d)

![image](https://github.com/javierriveracastro/betteroll-swade/assets/66346903/f3c5aa64-ff33-4fe4-9cb2-eddfb50a3491)

**Comment by javierriveracastro** [comment]
Well, you are going to find this quite amusing. I'm quite sure it is a system bug. Yeah, I know they send you here.

I will talk with Chaos, if they don't solve it I will work around it. But for now I'd wait, as solving it in system is the better solution, AFAIK.

**Comment by javierriveracastro** [comment]
Chaos confirmed that this will be solver in version 3.1 of the system. So it makes no sense to work around it in BR. Thanks for reporting, but I'm closing it.
