### ISSUE TITLE
The value storen in the flaf render_data.trait_rolls is not propagated to other users.

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#610]
If the GM tries to delete a modifiers from a PC roll there is an error.

![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/0868a726-5ce5-4e51-bb10-460319e5b824)

![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/69e67f5e-4b0e-450f-aef7-3ad072dda1d7)

**Comment by javierriveracastro** [comment]
And it should be solved.
