### ISSUE TITLE
Error Message when Reroll with benny

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#611]
If the player click reroll with a benny there is an error on the console

![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/7b4e4e04-fc6f-4cc7-9664-910e57af7cd2)
![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/f6078289-6478-490b-83d8-ef35d84efd21)

**Comment by brunocalado** [comment]
Sometimes this prevents the reroll

**Comment by javierriveracastro** [comment]
This is a file not found error. Foundry is failing to find /modules/succ/icons/holding.svg. Maybe the player has changed the bennie image to one that doesn't exists?

Anyway, closing it. Thank you, but there is nothing BR can do about this.
