### ISSUE TITLE
After add a modifier the roll disappear from the chat, the br card remain.

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#612]
After add a modifier the roll disappear from the chat, the br card remain.

![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/761193ed-fcf7-445c-b54e-69ed8aac8d01)
![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/400cfb66-a90d-4703-99f0-1aa569ecee02)

**Comment by javierriveracastro** [comment]
I can't get this to happen. But testing has shown another bug, when clicking in a modifier after a roll the benny reroll button disappears.

**Comment by javierriveracastro** [comment]
Ummm... I think I got this. Dupplicate of #610
