### ISSUE TITLE
Soak check not adding +2 for Unarmoured Hero setting

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#614]
The Soak check is not adding the +2 bonus for the Unarmoured Hero setting.

<img width="175" alt="image" src="https://github.com/javierriveracastro/betteroll-swade/assets/64320/3fe5db75-feea-43f3-9b93-a99ad5ecdf97">

The existing `brsw.soak-modifier add 2` works fine in an Active Effect to handle the setting ...
<img width="375" alt="image" src="https://github.com/javierriveracastro/betteroll-swade/assets/64320/6c135c80-e8ae-4516-b84d-11186feed14a">

giving ...
<img width="175" alt="image" src="https://github.com/javierriveracastro/betteroll-swade/assets/64320/6ce305f1-c9bf-45c9-8f96-1d0b494731ef">

**Comment by javierriveracastro** [comment]
Done
