### ISSUE TITLE
Unable to Remove Called Shots

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#617]
I'm trying to replace Called shot. But, I can't remove it. I'm using the ID from [](https://github.com/javierriveracastro/betteroll-swade/blob/version_2/betterrolls-swade2/scripts/actions/combat_options.js)

![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/31af3fc2-c349-403c-adbb-5cfe47b4492f)

I'm currently experiencing difficulties with removing called shots using the provided code below:

```json
  {
    id: "CS-HEAD",
    name: "Called Shot: Head",
    button_name: "Head",
    skillMod: -4,
    dmgMod: +4,
    dmgOverride: "",
    selector_type: "item_type",
    selector_value: "weapon",
    group: "Called Shot",
    change_location: "head"
  }, {
    id: "CS-ARM",
    name: "Called Shot: Arm",
    button_name: "Arm",
    skillMod: -2,
    selector_type: "item_type",
    selector_value: "weapon",
    group: "Called Shot",
    change_location: "arm"
  }, {
    id: "CS-LEG",
    name: "Called Shot: Leg",
    button_name: "Leg",
    skillMod: -2,
    selector_type: "item_type",
    selector_value: "weapon",
    group: "Called Shot",
    change_location: "leg"
  }
```

**Comment by javierriveracastro** [comment]
And again this is working for me. Maybe you have an old version of BR2?

![imaxe](https://github.com/javierriveracastro/betteroll-swade/assets/8113700/37ca19b6-9825-411f-8e87-33e410980556)

**Comment by brunocalado** [comment]
It's working well on 342
Thank you.
