### ISSUE TITLE
Add the minus values for cover to action buttons

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#621]
Foundry v11.308
BR2 v3.44

The new style action buttons for "cover" are missing the negatives; -2, -4, etc.

<img width="337" alt="image" src="https://github.com/javierriveracastro/betteroll-swade/assets/64320/16ba61cc-0600-4f5d-9406-2468fe043629">

**Comment by javierriveracastro** [comment]
Already done.

**Comment by steveculshaw** [comment]
@javierriveracastro Wow ... that's a pretty quick response :-)

**Comment by javierriveracastro** [comment]
Yes, I saw it in discord while I was working on another thing and it was a quick fix.
