### ISSUE TITLE
Soaking with Ignore wounds

### ISSUE THREAD

**Issue by Alekboldlin** [javierriveracastro/betteroll-swade#622]
When Actor with 2 wounds and 2 Ingore wounds is soaking, new wounds modifiers  are not calculated correctly.

Before:
![image](https://github.com/javierriveracastro/betteroll-swade/assets/143077587/213f08b9-946c-4028-a80f-cc97d03f915a)

After:
![image](https://github.com/javierriveracastro/betteroll-swade/assets/143077587/0006019b-9329-4def-8cbb-a8b1c97df6be)

**Comment by javierriveracastro** [comment]
I believe it is working right now.
