### ISSUE TITLE
Bonus to Trait Rolls on Weapons No Longer Working

### ISSUE THREAD

**Issue by LeBonkerson** [javierriveracastro/betteroll-swade#625]
I'm not sure if it was from the most recent update or before that, but the Trait Modifier on the weapons for my characters are not applying in Better Rolls 2 anymore.

We have a few characters with bonuses like Martial Artist and Martial Warrior that we manually added a +2 to their fist weapons (since they are named differently from Unarmed and Natural Claws, which I see the Edge gives an effect to change). Before, Better Rolls automatically added the +2 to the attack rolls when creating the card, but that is not shown or calculated in anymore.

It may just be user error on my end that I'm doing incorrectly, so please let me know if so. Thanks!

<img width="448" alt="image" src="https://github.com/javierriveracastro/betteroll-swade/assets/94027196/969a50e4-3d9d-4da5-a83b-f9556732434f">
<img width="214" alt="image" src="https://github.com/javierriveracastro/betteroll-swade/assets/94027196/3625fd3e-afc5-46cc-b3ea-40b999e25fc5">

**Comment by javierriveracastro** [comment]
Not an error, this is likely caused by some update to system. There are other people seeing it, and has also been a recent problem to SWADE Tools.

**Comment by javierriveracastro** [comment]
Done.
