### ISSUE TITLE
Damage Actions not working

### ISSUE THREAD

**Issue by Balekin** [javierriveracastro/betteroll-swade#627]
Items can now have Actions that modify how their damage works. For example spells that do 2d6 damage by default but can be upgraded to 3d6 or 4d6. When the action is selected the damage roll still only does the default damage and seems to ignore the Action. So if you have 3d6 damage selected and roll for damage it still only rolls 2 dice.

**Comment by javierriveracastro** [comment]
It is working for me. Are you sure that you are in the last version?. It was added in version 3.48.

If you are in 3.48 or newer and still see it, please reopen the issue and try to give some more data to find what is going on.
