### ISSUE TITLE
MATT is causing the damage to roll twice

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#630]
Hi.

If you enable the MATT module the damage is rolled twice.

![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/7d42a7f7-46b9-466b-96c6-2b7e8a06652b)

**Comment by javierriveracastro** [comment]
I have installed MATT and it is not happening.

There must be something else. Or some configuration of MATT, or maybe MATT plus some other module plus BetterRolls.

**Comment by brunocalado** [comment]
Warp Gate Module
