### ISSUE TITLE
Minimize right UI missing

### ISSUE THREAD

**Issue by BolieRide** [javierriveracastro/betteroll-swade#635]
When the module is active, the ability to minimize the right hand menu is gone.
Thanks!

**Comment by javierriveracastro** [comment]
That's an incompatibility with tailwindcss (the css framework that I'm using). It could be tricky to solve.

**Comment by javierriveracastro** [comment]
Or not. Solved.

**Comment by BolieRide** [comment]
Awesome!  Thanks!!
