### ISSUE TITLE
Improve handling of powers with 0 PP base cost

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#642]
Working on the Shape Change power modifiers.
If I set the actual power to a non-zero PP cost, after the cast roll, the chat card with PP cost is displayed and the extra points correctly added.
But if it's a 0 PP power, even with extra costs from power modifiers, the PP cost chat card isn't displayed, nor are the PP's subtracted from the players PP pool

If something has 0 PP base cost the power point counting code is not executed at all. Maybe we need a better heuristic.

_From discussion starting around in_ ...
* [Discord](https://discord.com/channels/170995199584108546/1052222686463537272/1159761807221719143)
* [Discord](https://discord.com/channels/170995199584108546/1052222686463537272/1159763066020433981)

**Comment by javierriveracastro** [comment]
Ummm... maybe activating it for powers or things that have PPs?

**Comment by javierriveracastro** [comment]
Done.
