### ISSUE TITLE
Add "radio button" functionality for action options

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#643]
Add "radio button" functionality for action options to link together a set of options and only allow one to be chosen from the group.

e.g. in the power Shape Change, there are five possible values for the Size power modifier, e.g., "Size -4 to Size -1", "Size 0", etc.
However the choice of Size is mutually exclusive.

Another example is the generic power modifier "Armour Piercing" with three possible values

**Comment by javierriveracastro** [comment]
Done. I mean, now groups can be single choice, but actions is still multiple choice as run is there and you can run and do two actions.

**Comment by steveculshaw** [comment]
@javierriveracastro Wow, that's really great ... I was thinking it'd be a major re-write so only something long term
