### ISSUE TITLE
Can cast power even if don't have enough power points

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#644]
It's possible to cast a power even if the character don't have enough power points.

Can the Roll button be deactivated and/or a warning shown if the token doesn't have the requisite power points for the select power and power modifiers

**Comment by javierriveracastro** [comment]
That was by design. I feel that GMs should be allowed to do that.

But a warning is indeed a good idea.

**Comment by javierriveracastro** [comment]
Umm... a warning is posted to chat. I will make it also post a foundry warning.

**Comment by javierriveracastro** [comment]
Done
