### ISSUE TITLE
Environmental Protection power has a Cone template option

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#647]
The Environmental Protection power has a Cone template option ...

<img width="220" alt="image" src="https://github.com/javierriveracastro/betteroll-swade/assets/64320/37c1bc55-fc11-4105-bb7a-3ce0513ee8b8">

But it doesn't have any templates selected in its Properties ...

![image](https://github.com/javierriveracastro/betteroll-swade/assets/64320/c381ea6c-1061-4dd0-a892-6702fa3c6e5f)

Export of the power attached _(as a .txt file)_ ...
[fvtt-Item-environmental-protection-a2NuH1HyWizuqLfC.json.txt](https://github.com/javierriveracastro/betteroll-swade/files/12841390/fvtt-Item-environmental-protection-a2NuH1HyWizuqLfC.json.txt)

<img width="164" alt="image" src="https://github.com/javierriveracastro/betteroll-swade/assets/64320/27596e62-fb7d-4e26-b4cb-f3bcf0ce8892">

**Comment by javierriveracastro** [comment]
The description, it also tries to get templates from the description, and enviromental protection has this:

"""
within the cone of a volcano
"""

There is no real solution for this except disabling detecting templates in descriptions. And I'm not sure that this is a good idea yet.

**Comment by steveculshaw** [comment]
Added a note to documentation.
