### ISSUE TITLE
Chat Modifiers Name don't work with other languages

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#648]
If you change the language the modifier name don't change

![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/c0408f6e-aca3-4c06-af7a-07987752c68c)

**Comment by javierriveracastro** [comment]
I can't reproduce it:

![imaxe](https://github.com/javierriveracastro/betteroll-swade/assets/8113700/d8c5ddaf-03f5-4076-bf24-ad759e1962f0)

Something else must be going on. Did you reload? Are any errors in the console? Maybe some other module?

**Comment by brunocalado** [comment]
Sometimes it happen I can't find out when. Tks
