### ISSUE TITLE
Handle core system global mod for Wild Attacks

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#651]
Wild Attack implemented by the core system ... the +2 to attack isn't handled, whereas the +2 to damage is

_This is system way of handling wild attack.
It's a new addition.
Global mod to attack is not supported. I should probably add it._

See [Discord](https://discord.com/channels/170995199584108546/1052222686463537272/1167150827736158299)

![image](https://github.com/javierriveracastro/betteroll-swade/assets/64320/c37ffb33-890a-4564-b65b-fad04dbd6547)

**Comment by javierriveracastro** [comment]
Done.
