### ISSUE TITLE
The size modifier for attack rolls doesn't seem to work

### ISSUE THREAD

**Issue by florian-denizot** [javierriveracastro/betteroll-swade#660]
An image is worth a 1000 words.  

![Screenshot 2023-12-01 182856](https://github.com/javierriveracastro/betteroll-swade/assets/1583894/1c4257df-fcd3-4f61-a318-944184ab3460)

Am I missing something?

**Comment by grendel111111** [comment]
0 and 3 are in the same scale band. (-1 to 3. Try changing the size to 4 and then they will be in different scale bands.

**Comment by florian-denizot** [comment]
My bad you are absolutely right.
Thanks for taking the time to answer me.
