### ISSUE TITLE
Float support for trait modifiers

### ISSUE THREAD

**Issue by florian-denizot** [javierriveracastro/betteroll-swade#662]
I am trying to create a module to implement the No Power Points optional rule.

"Instead of using Power Points, characters with Arcane Backgrounds simply choose the power they want to activate and make an arcane skill roll. The penalty to the roll is the power’s total cost in Power Points (base cost plus all Modifiers), divided by 2. Round up. "

I was planning on using the global action API and replacing the power modifiers, switching the power point cost for trait roll penalties. 
The thing is, since I need to divide the PP cost to get my modifiers I end up with floating numbers and those aren't supported at the moment as modifier values are casted as integers.

My question is, would you be open to the idea of providing floating number support for trait modifiers? 
I can come up with the code.

**Comment by javierriveracastro** [comment]
I don't think that SWADE rules support decimal modifiers, but as long as it is optional, go along.

**Comment by florian-denizot** [comment]
SWADE rules don't really support decimal modifiers, but if we want to keep the ability to plug and play power modifiers the way Better Roll allows it with the No PP rule, I dont really see a way around it.

I added a pull request to show what I have in mind.  #663
