### ISSUE TITLE
Can "tnOverride" get an option added for "Parry"

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#665]
The current tnOverride will let you change the target number by setting it to x amount. is it possible to add the option of a 
"tnOverride":"Parry", That will take the parry of the first target and use that as the target number. 
It would cut down on steps of having to ask the target for their parry then entering it for things like missile deflection where ranged weapons go against the targets parry instead of NT:4.

**Comment by javierriveracastro** [comment]
Sure.

**Comment by javierriveracastro** [comment]
Done.

**Comment by grendel111111** [comment]
Thank you.
