### ISSUE TITLE
Adjusting the roll after a die roll  macro.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#666]
When you click on a die to change its value  manually after rolling it changes the results and now shows the new success or failure / roll total. But it doesn't refire any runSkillMacro triggers. It would be helpful to send the updated die rolls and success states again by running the macros again.

**Comment by javierriveracastro** [comment]
I was not sure about this, as I fear that it could broke some macro. But as die editing is probably quite unusual I did it.
