### ISSUE TITLE
Suggestion: Show ammo on attack cards 

### ISSUE THREAD

**Issue by majoralucas** [javierriveracastro/betteroll-swade#667]
It's really annoying not knowing how much ammo is left on the gun. I think it would be a great QoL to have a line on the attack card showing the gun's ammo capacity (linked to the Shots detail in the guns config).

**Comment by javierriveracastro** [comment]
Sure, I will discuss this on the design channel of the Discord server. It would have to wait until result information redesign is done.

**Comment by javierriveracastro** [comment]
As I'm still not convinced about making cards higher, I tried to add this data to the tooltip that appears when you hover the card title:

![Screenshot_20240117_155951](https://github.com/javierriveracastro/betteroll-swade/assets/8113700/b743ecdc-1ffd-4b9a-8127-c018aa481849)

What do you think?

**Comment by javierriveracastro** [comment]
Mark as solved, as there is no further feedback.

**Comment by majoralucas** [comment]
The tooltip helps, but I think it would be better to have it somewhere on the card, as it would be faster to check just by looking at it without having to put the mouse on the weapon name.

**Comment by javierriveracastro** [comment]
Yes, but where?. Note that keeping the card as small as possible is now a priority.
