### ISSUE TITLE
Chat card CSS issue

### ISSUE THREAD

**Issue by ian612** [javierriveracastro/betteroll-swade#669]
I have an issue where the chat card has scroll bars due to the arrow icon moving to the next line. When I mouse over the text, the scroll bars go away, but when I mouse away from the text, the bars appear again. This causes the chat card text below it to bounce around in a distracting manner.

It shows up in both Chrome and Firefox, though in Chrome it's less noticeable. Images below are of Firefox.

Mouse not over chat card
![image](https://github.com/javierriveracastro/betteroll-swade/assets/34078802/551bf93b-ed26-4cac-9694-803be1fff418)

Mouse over chat card text
![image](https://github.com/javierriveracastro/betteroll-swade/assets/34078802/315185eb-f2b7-47f3-baac-4bbcc5e2f0ea)

**Comment by javierriveracastro** [comment]
I can't see it.

![image](https://github.com/javierriveracastro/betteroll-swade/assets/8113700/9b4319ed-994d-4289-a10b-5150aaf1554a)

¿Are you using some specific resolution, or window or font size?. Any other module?

The font looks different for sure.

**Comment by javierriveracastro** [comment]
Someone has posted an screenshot in Discord with this same problem.

**Comment by ian612** [comment]
Hey sorry for not responding earlier. I can see this issue without any modules enabled other than Better Rolls, and no special font sizing (at least that I know of).
I was able to fix it by using CustomCSS and adding the following rules:

```
/* Custom CSS */
.overflow-scroll {
  overflow:visible;
}
```

**Comment by javierriveracastro** [comment]
I have to make some tests, but (without any testing) I'm afraid that this can cause big skill or item names to break the card layout.

**Comment by ian612** [comment]
Yeah I’m not sure it’s a good solution to the issue, but it’s a quick hack that patched it for me for now at least. There’s probably a better way to fix it that’s less hacky

**Comment by javierriveracastro** [comment]
Ok, are you sure that you are updated and that no other module is interfering?

Because that is how the CSS looks on my machine:

![imaxe](https://github.com/javierriveracastro/betteroll-swade/assets/8113700/28ecb0de-3215-413d-9713-bcf9719d5042)

As you see it is the same as your hack.

**Comment by javierriveracastro** [comment]
Waiiitttttt... this is only on hover...

Sorry. I really hate CSS sometimes.

Can you check if this solves your issue:

```
.overflow-scroll {
  overflow:clip;
}
```

**Comment by javierriveracastro** [comment]
As there are no comments I will close it, hopefully solved.

**Comment by ian612** [comment]
Hi, apologies for not responding earlier. This css solves the issue for me. Thanks!
