### ISSUE TITLE
Add AP to Action Damage

### ISSUE THREAD

**Issue by JasonSunday** [javierriveracastro/betteroll-swade#672]
As a GM/Player,
I want to be able to add Armor Piercing to Actions,
So that I can automate attack actions more effectively.

![action-ap](https://github.com/javierriveracastro/betteroll-swade/assets/10623958/65fb6997-d42f-4b1c-b6c6-c9a30fc5dce4)

**Comment by javierriveracastro** [comment]
You will need to use world actions to add AP to an attack (see the wiki).

That window is from the system, not better rolls, and chaging it is totally out of scope. If you want it changed, you will need to add a ticket for the system (https://gitlab.com/peginc/swade).

Sorry, but I'm closing this.
