### ISSUE TITLE
Item Description includes could look at the notes section of an item so we don't have to duplicate into description.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#675]
When using item_description_includes the details of a weapon used to be in the description. In the modules it now appears in the notes section of an item, for things like two handed, ignores shield etc. Can item_description_includes check the item notes as well so that we don't have to copy them over to the description each time.
![image](https://github.com/javierriveracastro/betteroll-swade/assets/80164119/20eea25a-d7e9-48a4-aba2-fe13fc6f8f73)

**Comment by javierriveracastro** [comment]
Sure, that should be easy and makes a lot of sense.

**Comment by javierriveracastro** [comment]
Done. Well kinda, I made it look into both notes and category.

**Comment by grendel111111** [comment]
That's great thanks.
