### ISSUE TITLE
Messy swarm attack chat card

### ISSUE THREAD

**Issue by Gorka-de-Ituroitz** [javierriveracastro/betteroll-swade#679]
The chat card for the "swarm" creature attack (no attack roll, just damage) from the SWADE Core Rules is a bit messy.
![image](https://github.com/javierriveracastro/betteroll-swade/assets/137724382/98aad70c-5bd8-462f-a101-0bcfa07aa1ae)

**Comment by javierriveracastro** [comment]
Very likely a issue with the creature itself (probably some missformed HTML in the attack description). Try to editing the attack description (just change anything, even a space should do) and saving it again.

If the problems is solved, then it is likely a Core Rules error.

**Comment by Gorka-de-Ituroitz** [comment]
Right its the description of the attack. Trere's a link in it that messes up the chat card, if corrected it looks OK again. I'll put an issue to metamorphic.
Thanks.
