### ISSUE TITLE
Not Enough Power points Showing on Self Roll

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#683]
I'm on Self Roll, but the players can see I don't have enough PP.

![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/6b4dc83a-67fe-4897-84c9-aca0716f2ce8)

**Comment by brunocalado** [comment]
This happens whe whatever option I pick:
![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/ba616b40-5336-4896-8b2f-89bc82416a20)

**Comment by javierriveracastro** [comment]
Master only seems to work for me. I found a bug in "Master and GM", but not in master only.

Note that here "Master" are the owners of the card. I will change the name to make it clearer.

If you are asking for that message to inherit the hidden permission of the originating card... that could be done.

**Comment by brunocalado** [comment]
> Master only seems to work for me. I found a bug in "Master and GM", but not in master only.
> 
> Note that here "Master" are the owners of the card. I will change the name to make it clearer.
> 
> If you are asking for that message to inherit the hidden permission of the originating card... that could be done.

I just want the players to not be able to see this "Not enough PP" message when I set rolls to private.

**Comment by javierriveracastro** [comment]
Yes, but will having the setting "GM and Owner" work is enough or you want to keep the setting "All" and have a different behavior for messages that are private.

If it is the first I'll close the issue as that should work in next version.

If it is the former I need to think about it.

**Comment by brunocalado** [comment]
> Yes, but will having the setting "GM and Owner" work is enough or you want to keep the setting "All" and have a different behavior for messages that are private.
> 
> If it is the first I'll close the issue as that should work in next version.
> 
> If it is the former I need to think about it.

I think It could work.
