### ISSUE TITLE
Hard to Read Text

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#685]
Hi. It's hard to read with this red color. Maybe change to a color to improve reading. Thank you.
![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/6f44ea59-3889-4056-abd2-e5882b3dd50e)

**Comment by brunocalado** [comment]
I would suggest white text with red underline for negative values

**Comment by javierriveracastro** [comment]
I have tried it, but the red underline is barely visible :(

I'll go with a white underline for modifiers.
