### ISSUE TITLE
Request for Tooltip Removal Option on Chat Cards

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#699]
When tooltips appear, it's not possible to click on the chat card buttons. You have to move the mouse to remove the tooltip before being able to use the card. During the last combat, it was annoying every time I went to the card, the tooltip appeared, and I had to wait for it to disappear. Is it possible to add an option to remove the tooltip? Instead could you make the options clickable? They only appear if you click on them.

https://github.com/javierriveracastro/betteroll-swade/assets/4999783/5609a6b3-6252-4207-949a-fd359160f6f4

**Comment by javierriveracastro** [comment]
You can set the maximum characters in the tool-tip in settings. Setting it to 0 should disable them.

But anyway I'll see if I can make the waiting time before showing longer to avoid accidentally triggering it.

**Comment by brunocalado** [comment]
> You can set the maximum characters in the tool-tip in settings. Setting it to 0 should disable them.
> 
> But anyway I'll see if I can make the waiting time before showing longer to avoid accidentally triggering it.

It's small, but still showing up.
![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/a7a9f368-f72b-4a3a-a543-9fe396556685)

**Comment by javierriveracastro** [comment]
I shouldn't. At least it is not showing any tooltip to me when I set that to 0. Have you hit Apply?.

Also note that it only works for cards created from the change, cards that were created before you changed the settings keep they tooltips. In reality the settings prevents the creation of tooltips, not if they are show or not.

**Comment by brunocalado** [comment]
> I shouldn't. At least it is not showing any tooltip to me when I set that to 0. Have you hit Apply?.
> 
> Also note that it only works for cards created from the change, cards that were created before you changed the settings keep they tooltips. In reality the settings prevents the creation of tooltips, not if they are show or not.

Yes. Newly created cards don't show anything.

**Comment by brunocalado** [comment]
tks

**Comment by javierriveracastro** [comment]
Waiting time extended to one second.
