### ISSUE TITLE
Suggestion: Use tokens resources instead of actor resources.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#70]
If you create a token and populate it with a weapon, it can roll the weapons skill but not its damage. This seems to be because Better Rolls uses what is present on the actor, not the token, making it impossible to use it for Tokens which have different stuff than the actor usually would.

**Comment by javierriveracastro** [comment]
Will look into it.

**Comment by javierriveracastro** [comment]
Version 1.9 (pre-2) is already using token data when available (if I get it right it should be always but when the sheet is opened from the actor tab).
