### ISSUE TITLE
Proposal for Popout Button in Chat Cards

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#700]
I'd like to suggest creating a button for performing the popout action. Currently, you have to right-click and then click on 'pop out'. I'd prefer a button directly on the chat card for easy popout.

![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/92ed697d-f545-4d7e-b6f3-d48f1865853f)

**Comment by javierriveracastro** [comment]
Makes sense, but I don't really like that big button there. There must be some other way to make it. Let me think about it a little more.

**Comment by javierriveracastro** [comment]
Done in git.
