### ISSUE TITLE
Issue with Modifier Deletion in Chat Cards

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#701]
After a player deletes a modifier in the chat card, they lose the ability to reroll. To reproduce the bug, simply send a roll to the chat while connected as a player, delete a modifier, and then attempt to reroll.

https://github.com/javierriveracastro/betteroll-swade/assets/4999783/92a60bdc-f39d-4257-aafd-2954cf14a001

**Comment by javierriveracastro** [comment]
Should be solved on git.
