### ISSUE TITLE
Resist actions trait modifiers does not apply.

### ISSUE THREAD

**Issue by Gorka-de-Ituroitz** [javierriveracastro/betteroll-swade#705]
The actions whit the "resist" type may apply a trait modifier to the roll, but it is not taken in account in BR2.
![image](https://github.com/javierriveracastro/betteroll-swade/assets/137724382/623e1e07-7e90-4c93-9e93-969256a874d0)

May not be related to this, but also the TN for resist is the attack result, not the default value of '4'. If you change the action type from "Resist" to "Trait" the action is not shown in the BR2 chat card.

**Comment by javierriveracastro** [comment]
Should be there on next version.

**Comment by Gorka-de-Ituroitz** [comment]
Many thanks!
