### ISSUE TITLE
Issue with Saving Cards and Module Actions

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#709]
Improvement: The process of saving cards encounters difficulties when dealing with actions created by a module. 

Description: When attempting to save a card containing actions generated by a module (such as Savage Pathfinder Enhanced), although the macro is saved, the selected options are not retained.

![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/afd5ef72-6fbf-4606-8015-1ea36fb9fe08)

1. Activate the module savage pathfinder enhanced
2. roll bolt
3. use actions from the module
4. save the card
5. you will see the actions you saved will not show

**Comment by ddbrown30** [comment]
Thanks for the issue. Made it easy to figure out the bug.
