### ISSUE TITLE
Suggestion: Free Reroll Button

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#71]
Certain Edges like Charismatic allow a free reroll (without spending a Benny). Currently this can only be done by a regular roll from the character sheet. A button on the roll in the chat would make this easier. The button should be smaller than the one which uses a Benny to prevent accidental pressing of the wrong button. It could be like this:
![image](https://user-images.githubusercontent.com/1230041/98345998-b0f23f00-2015-11eb-8772-d9747cb92ac0.png)

**Comment by javierriveracastro** [comment]
A nice and easy to implement idea. I'll add it to the next update.

**Comment by javierriveracastro** [comment]
Done, just four lines of code.

![image](https://i.imgur.com/4VCEH2N.png)
