### ISSUE TITLE
Gang Up adding bonus without being adjacent

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#711]
1. BR is adding bonus without being adjacent. In this case the gang up should be 1, not 3.
![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/440bc12c-0ab4-4009-95ec-48f0ee6c6ca7)

**Comment by javierriveracastro** [comment]
Can you try to play with the Melee Distance setting and see if it helps?

**Comment by brunocalado** [comment]
> Can you try to play with the Melee Distance setting and see if it helps?
Change this?
![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/4d264911-97ee-4f6e-adbb-37b9a52b08aa)

**Comment by javierriveracastro** [comment]
Yes. Make it something like 1.3 (never go as far as 2) and make some test. Note that solving the big token issue can break the normal size token calculations.

**Comment by brunocalado** [comment]
> Yes. Make it something like 1.3 (never go as far as 2) and make some test. Note that solving the big token issue can break the normal size token calculations.

I set to 1,7 and no change. +3 Gang Up
![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/a4094aff-6dee-47d9-8688-ea8262a54350)

**Comment by javierriveracastro** [comment]
Try the other way around (0.7), please.

**Comment by brunocalado** [comment]
> Try the other way around (0.7), please.

0,1 and 0,3 dropped to +2
![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/353eab86-ad05-4c2e-b670-969b892bd0bc)

**Comment by javierriveracastro** [comment]
Ufff... that's too low. Thanks, I'll take a look.

**Comment by javierriveracastro** [comment]
Should be solved (too many edge cases to test all) on git.

**Comment by brunocalado** [comment]
Thank you.
