### ISSUE TITLE
There are some translation gaps

### ISSUE THREAD

**Issue by peterprokurist** [javierriveracastro/betteroll-swade#713]
The module is translated very well into different languages, which in my opinion contributes a lot to a good immersion.
However, the language.json apparently cannot change all text passages. I noticed the following:

The text "No actions selected" is always in English, regardless of which language was set. Likewise the text “Trait Die”. 
Here is a screenshot from the German core:
![image](https://github.com/javierriveracastro/betteroll-swade/assets/115837717/62a2281d-f732-41d0-98c2-b5df70dcb1c2)

Furthermore, the text “Single Choice” for the selectable actions is also always in English:
![image](https://github.com/javierriveracastro/betteroll-swade/assets/115837717/3eec1b79-3aa0-424c-b282-d9200466278c)

I would like to emphasize that these are really small things and I can live with them very, very well. But maybe you can find the time to fix it. It could increase the immersion a bit :-)

**Comment by javierriveracastro** [comment]
I have added "No action selected" to the translatable strings, should appear on next version.

But Trait Die is just lacking German translations, it is already in the file as "BRSW.TraitDie". I can't help you with that, but you can help with translation here (https://hosted.weblate.org/projects/betterrolls-2-for-swade/main/)
