### ISSUE TITLE
UNARMORED HERO - pg141

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#714]
I would like to suggest adding an option to enable the UNARMORED HERO rule.

```
Unarmored Hero
Pulp action tales often feature heroes with
little or no armor defeating far more heavily
armored adversaries.
In these settings, if a Wild Card chooses not
to wear any armor (ignoring shields), he adds
+2 bonus to his Soak rolls!
```

**Comment by javierriveracastro** [comment]
This is supported since 3.39 AFAIK.

But it is no more visible in settings. Probably it get lost in the rework of the setting menu.

**Comment by javierriveracastro** [comment]
Actually no. It had been reworked to use the setting in the system. It should work if you enable "unarmored hero" in the rules tab of the system.
