### ISSUE TITLE
Modifier for hindrances is calculated twice

### ISSUE THREAD

**Issue by peterprokurist** [javierriveracastro/betteroll-swade#717]
If a Hindrance has an automatic effect, this will be shown (and calculated) twice.
Here is the example of “Mean”, which gives -1 to “Persuasion”:

![image](https://github.com/javierriveracastro/betteroll-swade/assets/115837717/e1dc0827-3c3a-4fe8-bb93-81cf41483c65)

![image](https://github.com/javierriveracastro/betteroll-swade/assets/115837717/b4a00aa1-943d-4d62-a291-b187a0d9eb04)

![image](https://github.com/javierriveracastro/betteroll-swade/assets/115837717/ec53c4fd-543e-491c-b0ba-402c9cc536a1)

**Comment by ddbrown30** [comment]
You need to disable the effect on the actor.

**Comment by peterprokurist** [comment]
thaaaaank you!  :-)

**Comment by ddbrown30** [comment]
No prob. :)

**Comment by javierriveracastro** [comment]
Or disable the action in BR configuration.

I'll try to see if we can auto-disable it.

**Comment by javierriveracastro** [comment]
Added a check to disable the action if the core rules are enabled. It is not perfect, as the active effect can be there and the core rules disabled, but it should avoid this problem 90% of the time.

It can also be extended to other problematic items in the future.
