### ISSUE TITLE
[Bug] Item actions with the 'trait' set to an attribute are not found

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#719]
When an item action is set to trait and an attribute is entered (i.e. 'Spirit'), the action can't be applied or rolled on and instead creates an error in the console:
![image](https://github.com/javierriveracastro/betteroll-swade/assets/1230041/68ce3e74-6d5f-44e3-ad9e-7d5d6e83ad5c)
(The first is from clicking 'Set', the second from clicking 'Roll' in the selection menu.)

Tested on BRSW v. 3.77; SWADE v. 3.3.11 and FVTT v. 11.315.

**Comment by javierriveracastro** [comment]
Done.
