### ISSUE TITLE
Wounds calc issue

### ISSUE THREAD

**Issue by superseva** [javierriveracastro/betteroll-swade#72]
I think there is a small bug coming out of wounds calculations
it looks it ignores second raise. this should say 2 wounds.
![brolls](https://user-images.githubusercontent.com/4093045/98537340-67118f00-2289-11eb-8605-983b9a8e914b.jpg)

I guess it is related to line 164
```let wounds = raises - 1```

**Comment by javierriveracastro** [comment]
Solved. Or at least, I hope that it's solved.
