### ISSUE TITLE
Integration with Offical SWADE Module and Pathfinder Bestiary.

### ISSUE THREAD

**Issue by ennerre25** [javierriveracastro/betteroll-swade#721]
Good afternoon, I´m running  Foundry v11 Patch 13 (Build 315) with Better Rolls 2 version 3.77

The following issue happens when using Better Rolls 2 with the skills from the Official SWADE Module or from the premade creatures within the Official Pathfinder Bestiary.

When making a roll like an attack if I choose the option to Display Better Rolls chat card plus Opening the Dialog Box. When you select different modifiers like Wild Attack, Unarmed Defender etc, whatever I select doesn´t get taken into account when I press the roll button, it all disappears from the chat card and from the end result.
I need to do Set and then Roll from the chat card directly, rolling from the Dialog Box removes all the preselected modifiers.
This happens for Fighting, Faith, Spellcasting and Stealth (maybe others).

When I do the same using skills from the base system it works correctly.

I created a different world, actors and scenes and got the same results. 

Thank you for whatever help you can provide and for this amazing module!

**Comment by javierriveracastro** [comment]
You are the second one to report this, but we have been not able to reproduce it. I'll try again.

It is probably some race condition, and those are hard to debug.

**Comment by javierriveracastro** [comment]
Should be solved in last version. If it isn't feel free to reopen this issue.
