### ISSUE TITLE
Change the way the 'Ranged Weapons in Melee' rule is handled in gridless scenes.

### ISSUE THREAD

**Issue by JosephA1997** [javierriveracastro/betteroll-swade#723]
this issue only affects people trying to do freeform movement with a gridless scene (which may or may not be many), so it is understandable if this is a low priority or not worth the effort.

when the module is determining whether or not to use the 'Ranged Weapons in Melee' rule (pg. 104 and 105) it seems to always round the distance between the two tokens down to the nearest integer. this works fine on a gridded scene, however on a gridless scene it has the effect of applying this rule even when the tokens are more than 1-inch apart and technically should not be in melee with each other. it leads to situations like in the screenshot below where two tokens are a fair distance away from each other, but the module still considers them to be in melee.

Neither of these actors have weapons that alter the reach of their melee attacks if that matters.
(all other modules disabled)

![Screenshot 2024-07-09 005420](https://github.com/javierriveracastro/betteroll-swade/assets/63314272/c70012c8-8ec5-4cf7-b8fe-82395f847db3)

**Comment by javierriveracastro** [comment]
The truth is that it just check if the distance in grid units is less than 2.

And the problem is that there is no really good definition of melee distance in a gridless map. There is a config that is used for flanking, I will try to check if I can reuse it for this.

**Comment by javierriveracastro** [comment]
Done, now you should be able to configure it in settings. Not that by default the behavior is the same.
