### ISSUE TITLE
Enhancement: consider showing the 'current/max' shots for ranged weapons next to ammo management button

### ISSUE THREAD

**Issue by JosephA1997** [javierriveracastro/betteroll-swade#724]
I know the tooltip displays this already, but having this info on the card itself would be super helpful.

Squeezing it next to the ammo management button as shown below would not add any vertical size to the card and makes logical sense to have it next to the buttons relating to ammo.

![Screenshot 2024-07-16 214102](https://github.com/user-attachments/assets/1feb6ed1-7d7c-4d49-8db7-7246b4f72b07)

 some things to consider:

- may add too much visual clutter to the card for some people's taste so it should probably be a world setting.
- account for the fact that a weapon may have ammo counts that are 3+ digits long and how that would be displayed on the card
- Perhaps remove the 'Shots:' part and just show 'current/max' (shown below), as it is next to a bullet icon it might be safe to assume that users will associate it with ammo anyway.

![Screenshot 2024-07-16 214058](https://github.com/user-attachments/assets/b891b781-ec21-4448-959d-000352e0ab09)

**Comment by javierriveracastro** [comment]
I'm probably more inclined to remove things from the card than to add them. But let's here what other people think.

Can you bring this to the official Discord channel?

**Comment by JosephA1997** [comment]
Just posted it

**Comment by javierriveracastro** [comment]
Done in git.
