### ISSUE TITLE
Enhancement: Journal enrichers to request rolls 

### ISSUE THREAD

**Issue by peterprokurist** [javierriveracastro/betteroll-swade#725]
How about journal enrichers that allow you to request certain dice rolls in chat?

**Comment by javierriveracastro** [comment]
First we probably need to support requesting rolls from chat. 

And after that, I'm not really sure how useful this could be. This probably needs a discussion, please, bring it to discord. I'll be closing it now as it is a little out of scope. If something comes out from Discord, we should open a couple of issues with a clear roadmap.
