### ISSUE TITLE
Players can save macros from NPC rolls

### ISSUE THREAD

**Issue by peterprokurist** [javierriveracastro/betteroll-swade#731]
If the GM rolls for an NPC, a player can use the floppy disk icon in the chat to save the roll as a macro and then re-roll it in the NPC's name.
Players should not be allowed to save other people's rolls as macros in order to roll in their name.

**Comment by ddbrown30** [comment]
@javierriveracastro I could set up the save button visibility to be based on user permission (or maybe player vs trusted player) but this does raise the fact that the API the macro uses is itself insecure.

**Comment by javierriveracastro** [comment]
I agree on changing visibility (should be as easy a wrapping the icon in the form class). 

But I disagree about the API. This is not an API problems, it is a Foundry server issue. There is nothing we can do at client level to prevent it. The code that is run in a player browser is totally controlled by the player.

**Comment by javierriveracastro** [comment]
Solved by @ddbrown30
