### ISSUE TITLE
Can't place templates from chat card

### ISSUE THREAD

**Issue by Felian2** [javierriveracastro/betteroll-swade#732]
Hi there, 

when I'm trying to place templates from chat cards (for example: from granades), it does not work. The template isn't showing up to be placed. 

I'm using Froundry 12.331, SWADE 4.1.1 and the latest Version of Better Rolls installed. 

Already tried a fresh world with only the Game System, Better Rolls and it's dependencies activated and still does not wirk.

Had no problem with placing templates while using Foundry v11. 

Does anyone have an idea what the problem could be? Anyone else having this issue?

Thanks for the help. 

Best regads.

**Comment by javierriveracastro** [comment]
Confirmed. I will take a look.

**Comment by javierriveracastro** [comment]
Solved, I hope to release an updated version tomorrow if I can get some time to properly test it.
