### ISSUE TITLE
Respect Conviction.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#74]
Currently Better Rolls does not add the +d6 to rolls if Conviction is turned on.

**Comment by javierriveracastro** [comment]
That's a thing. Version 1 will probably never support it, I'm not really into adding new features to it, just bugfixes. 

Version 2 should automatically support it as it relies in system rolls. But just now version 2 only does attributes, and system doesn't look like is supporting conviction in attribute rolls.

I'll keep this bug report here until at least version 2 supports skills and then I will see.

**Comment by javierriveracastro** [comment]
Working, in version 2, of course. Or at least I believe it does, never used conviction. If you can, please, review the video.

https://natilla.comunidadumbria.com/ficheros/get/11161/peek_2020-12-11_16-12.webm

**Comment by SalieriC** [comment]
It looks like it does. Doesn't look good of course, because of the crappy sheet. :-P
Also the skill icons are gone. Oh boy, the future is pretty dark indeed. :-S Thank you for the heads up nevertheless.

**Comment by javierriveracastro** [comment]
Yes, icons are out. Adding them to all the sheets is a little bit crazy.
