### ISSUE TITLE
Ammo count to weapon chatcard

### ISSUE THREAD

**Issue by Alis-72** [javierriveracastro/betteroll-swade#75]
Currently weapon chatcard lists some weapon stats on bottom (range, damage, ap...) 
It would be nice addition to show current and max ammo ro the weapon used. 
Format could be something like
Ammo x/y   /where x=current ammo count and y=full clip)

Would also be really usefull if better rolls would automaticly reduce ammo count by each time weapon-icon is clicked.
(There are lot of special options that might not be possible to automate, like RoF, Doubletap, Fanning-the-hammer which might be better left manual)

**Comment by javierriveracastro** [comment]
First part done, I will keep the bug open until I do (or decide on not doing) the second part.

**Comment by javierriveracastro** [comment]
Ammo is now reduced on version 2.
