### ISSUE TITLE
not working with new official swade 0.15.0 character sheet

### ISSUE THREAD

**Issue by Alis-72** [javierriveracastro/betteroll-swade#76]
Icons infront skills is missing and clicking  quick access icons does nothing (nothing appears in console).

When switching to community  character sheet, Betterrolls work just fine thoug warning "You are using the Die#rolls attribute which is deprecated in favor of Die#results." appears in console.

Founfry version 0.7.8
SWADE version 0.15.0

**Comment by JWambaugh** [comment]
I am also seeing this issue in the new SWADE available here: https://gitlab.com/peginc/savage-worlds-adventure-edition/-/releases

**Comment by javierriveracastro** [comment]
I'm aware of it and thinking about what to do.
Currentrly most likely plan is to move version 1 to his own module so that people who want to use it with the old sheet can, and trying to make version 2 work with both sheets.

The main problem is that version 2 lacks lots of features.

**Comment by Yalnin** [comment]
As the maker of the "official" SWADE module is cooperating with PegInc, I would expect that the old sheet will be dropped anytime soon. That being said, I highly value the work you have done with Better Rolls for SWADE, so my humble suggestion would be to focus on the new sheet to match the new releases, announced to be expanded soon.

**Comment by javierriveracastro** [comment]
It was easier than expected. Working on both versions.
