### ISSUE TITLE
Take Shaken status into calculations

### ISSUE THREAD

**Issue by Alis-72** [javierriveracastro/betteroll-swade#78]
Currently Better Rolls ignores Shaken status from wound calculation. 
Would be nice if it could take that to wound level calculation.
There are couple exceptions (Hardy edge etc) that mess this up abit but those are minority (hopefully)

i.e. 
unshaken target: damage 0-3 points over Toughness -> Shaken  
Shaken target: Damage 0-7 points over toughness -> Shaken + 1 wound

**Comment by javierriveracastro** [comment]
This should be solved in version 2 when applying damage.
