### ISSUE TITLE
Feature Request: Optional Gritty Damage support

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#84]
Please consider to add an option to the settings to use Gritty Damage and a field to apply the name or ID of the Injury Table in this world.
Then, whenever damage is rolled, add a button to the chat message called "Gritty Damage" which will roll on the table defined in the settings.

**Comment by javierriveracastro** [comment]
That could be done, but probably after damage cards are finished.

**Comment by javierriveracastro** [comment]
Sorry, wrong button.

**Comment by SalieriC** [comment]
I've done that in [SWIM](https://github.com/SalieriC/SWADE-Immersive-Macros) already, I think I can do this.

**Comment by javierriveracastro** [comment]
As you wish. I'm slowly working on this. Where slowly means: first do incapacitation card, after that add wounds rolls that add active effects with the roll and finally add gritty damage.

But It's going to take a while, so I'm all in for a quick fix, even if we remove it at the end.

**Comment by SalieriC** [comment]
Maybe we remove it, maybe we can use it again after you did all that. In case of the latter I saved you some time, in case of the former it might be useful in the meantime. =)

**Comment by javierriveracastro** [comment]
This is getting closer, I have an injury card ready that adds most of the injuries as ActiveEffects.

The problems is the Injuries that give you a Hindrance. How should it be done?. Add the hindrance to the actor, bringing the description from the compemdiun if possible and adding something like "(from injuries)" in the name?

Any other idea?

**Comment by SalieriC** [comment]
A compendium the user could choose for Hindrances would be cool. Maybe adding some prefix like `!Injury: <Hindrance Name>` I think a prefix would be much easier to spot than a suffix.

**Comment by javierriveracastro** [comment]
I have finally added the remaining injuries as active effects (with name but no effect), as putting then in different places was confusing to me.

**Comment by javierriveracastro** [comment]
At last... in just two months.... DONE!!!
