### ISSUE TITLE
Shooting attacks in melee combat

### ISSUE THREAD

**Issue by D20Chemist** [javierriveracastro/betteroll-swade#85]
When using targeting have a toggle? or some method of comparing to parry instead of 4 if using a ranged weapon in melee combat.

**Comment by javierriveracastro** [comment]
No need for a toggle, just check distance. Added to the todo list

**Comment by javierriveracastro** [comment]
This should be done for shooting skills in the development version.

Still pending, make it work with thrown weapons, try to get some more use of the code and try to make automatic distance modifiers.

**Comment by javierriveracastro** [comment]
Done, now Better Rolls do range penalties.
