### ISSUE TITLE
Feature Request: Auto-Roll on executing Skill macro (BR2)

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#87]
Since Skills and such cannot be made a floating window (anymore?), it makes little sense that macros created from Skills don't roll automatically but show a button to roll. This only leads to more clicking which is contrary to the intention of the module. I'd suggest making the Skill macros automatically roll instead, similar to Weapon Rolls..

**Comment by javierriveracastro** [comment]
The plan was to create different macros depending on the key pushed while dragging. So you can drag the chat card, a direct roll, or even roll and damage.

But meanwhile, you are right, will change it asap.

**Comment by javierriveracastro** [comment]
Done.
