### ISSUE TITLE
Feature Request: Allow creating BR Macros for Powers dragged from the Powers Menu on all Sheets (BR2)

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#88]
Currently BR Macros for Powers can only be created from Quick Access & Effects on the summary tab. It should be possible (for all sheets, including the community and NPC sheets) to drag-create BR macros from the powers tab as well. Especially since it currently is impossible to drag-create BR macros for NPCs as those have no way of linking powers to the summary.

**Comment by javierriveracastro** [comment]
Done.
