### ISSUE TITLE
Optional results (BR2)

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#89]
Currently BR2 always shows results of rolls (a checkmark, a blood drop, etc.). Please make these optional. Not all users might like the automation of interpreting the results.

**Comment by javierriveracastro** [comment]
You know that they can be set to master only, do you?

**Comment by SalieriC** [comment]
Yes. And I'd like to have the option to never show it to anyone. =)

**Comment by javierriveracastro** [comment]
Damage roll results now respect the settings and yes, it was a bug. Thank you for spotting it.

I'm not very sure what to do about this issue. It is probably too much work just to hide the results from the master who can quite easily ignore them and who already has all the info so no leaking problem. I'm on the edge of closing it, but I will give it some time.

You can give some examples where it could be useful. May I'm seeing thins clearly.

**Comment by SalieriC** [comment]
Ignoring something is tough. Kids are very bad at this but adults are not that much better. Especially when something is colourful. So it will almost always distract from the roll itself. This is fine if you want it to interpret the result for you but otherwise it's not. Especially on BR2 where the results are already so easy to miss.
Also it would further reduce the size of the message making it more clear, less bulky and better suitable for the Combat focus Module for example. 
Options are always good unless you're doing something for yourself only.

**Comment by javierriveracastro** [comment]
Using it with combat focus is something that I'd like to do someday. Maybe have an option for a condesed card or something. But someday.

**Comment by javierriveracastro** [comment]
Well, some small steps of condensation has been made. Also a bigger redesign is in another branch, just as an idea playground.

Anyway, I'm closing the bug.
