### ISSUE TITLE
Support Wild card entries for bennies

### ISSUE THREAD

**Issue by D20Chemist** [javierriveracastro/betteroll-swade#90]
Have file directory or use wildcards to allow for multiple benny images to be used/randomized for the animation

**Comment by javierriveracastro** [comment]
I'm sure of how to do this, but I'll try.

This could be easily done from node, but from the broswer... looks challenging.

**Comment by javierriveracastro** [comment]
Challeging and if some day I made it, it will be in Spices, closing as Won't Fix.

**Comment by javierriveracastro** [comment]
Reopening as Spices is somewhat in flux.

**Comment by SalieriC** [comment]
Yeah, definitely other things to focus on there. But Code doesn't go anywhere so maybe able to port it later. Anyway, it seems that changing the benny image will come to the system eventually, maybe they'll also cover that. We'll see.

**Comment by javierriveracastro** [comment]
Ok, I will close this as Won't Fix. Custom bennies are totally out of scope for better rolls. As soon as Spices supports then in 0,8 I'll remove them from here, as they make much more sense there.
