### ISSUE TITLE
Draw ammo from inventory

### ISSUE THREAD

**Issue by D20Chemist** [javierriveracastro/betteroll-swade#91]
With the new feature of pulling ammunition from the inventory automatically as it is placed in a gun, get the reload on betterrolls to hook into this.

**Comment by javierriveracastro** [comment]
I must be stupid but I can't see the ammo field in the weapon. I just see a check "Doesn't need reload action".

**Comment by javierriveracastro** [comment]
Find it, after enable and disabling a couple of settings.

**Comment by javierriveracastro** [comment]
Done.
