### ISSUE TITLE
Pre-defined "global action" buttons for the weapon cards

### ISSUE THREAD

**Issue by Yalnin** [javierriveracastro/betteroll-swade#92]
It would be great to have pre-defined action buttons for the weapon cards like "double shot", "recoil", "snapshot", "headshot", etc. with preset skill/damage modificators, and/or extra ammo consumption? Maybe even in a configurable listing in the settings? Seems kinda crazy to include those actions manually into every single weapon to be able to have them in the weapon cards...

**Comment by javierriveracastro** [comment]
That makes a lot of sense and it is probably a quite powerful idea.
I make no promise, but would like to talk about its details.

BTW, I like the name "Global Actions".

A global action for me should be made by a "selector" or something that tells the system when it applies and som effects (like ammo and modifiers).

The module should provide a couple pre-made, but the user should be able to add to them.

The actions should appear on the card when the selector applies to it.

That's the rough idea. A couple of problems:
- ¿Won't this make the card too big?. ¿How many "global actions" should appear on it?.
- Should the actions be stored in settings?, should the user be able to disable system ones?
- What kind of GUI will be needed to create them
- What selectors do we need?

I'd like an open discussion about this, no idea is set not even mine. Anyone is welcome to join, more, I'll be thankful of any input, even the ones that in the end I'll disregard. Of course PRs will be better.

Get in mind that we are talking about an ideal here, real implementation is doomed to be worse.

**Comment by jvir** [comment]
I will write just a little in case what I say is not interesting.

I think that in swade you currently have to configure in the weapons many actions that can be inferred. For example if a weapon has a rate of fire 3 you know it can fire with rate of fire 2 or 1.

Taking this into account I think that we could make an approximation to the global actions starting with the most used which are the weapons. Very basic approach.

Melee weapons:
    - range: show target selection icon (if there is one selected icon in red, if not in grey, on hover show highlighted possible targets, drag over target select, click open dialog to select target).

Ranged weapons:
   - range: same as above, but on hover show the different targets with different color according to the distance and in the selection you can select as many targets as cdf (you can select the CoF for each one).

**Comment by javierriveracastro** [comment]
ROF is not really needed IMHO, because BR supports it quite well with the "chat window" modifiers. You only need to create actions when the ammunition consumed is not "standard", but this is likely different for each weapon and can't be solved with "global actions".

A target icon could be a good idea, but probably a totally different issue.

**Comment by Yalnin** [comment]
> A global action for me should be made by a "selector" or something that tells the system when it applies and som effects (like ammo and modifiers).
> The module should provide a couple pre-made, but the user should be able to add to them.

My suggestiom would be a configurable table listing in the config section of the module, with rows that merge the two possible action types "skill" and "damage" like e.g.:

`Action Name; Button Name; RoF; Skill Modifier; Alternative Skill; Shots Used; Damage Override; Damage Modifier`

> The actions should appear on the card when the selector applies to it.
> That's the rough idea. A couple of problems:
> * ¿Won't this make the card too big?. ¿How many "global actions" should appear on it?.

No, since the listing would be configured by the user manually, he would decide how many global actions he wants to use. You can put in some presets, but the user decides if he wants to modify or delete them at all. By using separate fields "action name" and "button name" you could make the actual button smaller, e.g. by calling the action "Aimed Headshot" but the actual button name in the weapon card "AimHead" or just "Head".

> * Should the actions be stored in settings?, should the user be able to disable system ones?

Yep, see above.

> * What kind of GUI will be needed to create them

Just a table list would be fine.

> * What selectors do we need?

Adding selectors is a good idea, however I am not sure how to trigger them provided the weapon sheet does not really offer the definition of "marks" or "properties" like checkboxes to mark if a weapon is subject to special properties. I suppose this would be a matter of enhancing the swade module in general.

Another alternative may be to place special coded trigger words in the description or notes field that would mark a weapon as eligible for showing up the marked global action on the weapon card. (e.g. [snapshot]). Then of course you would have to include an additional row in the definition listing mentioned above called "trigger" or "selector".

Maybe the easiest way to implement global actions in the beginning would be to just implement them without any selector at all, just whatever action is on the list is showes up on every weapon card. After all, the point of an action to be "global" would be that it shows up on every weapon card, you do not have to add them to every card manually.

**Comment by javierriveracastro** [comment]
About selectors... that's what I can think of:
- Every item
- Item type (weapon, spell, ...)
- Linked skill (fighting, shooting, magic skill x)
- Part of the name (things with "shotgun" or "sword" or "psionic" on its name)

Anyway, there is zero probability that this going to be implemented (at least by me, PR accepted) in one shot. It will likely go small, the first interaction will be probably actions without selector and not user editable, and the rest will be improved step by step, adding features each version.

**Comment by Yalnin** [comment]
Good idea with the selectors. Just consider the mechanics need to be translation-proof.

Maybe the "global actions" would be a thing for the general SWADE game system. After all, the item actions were also implemented by FloRad and you use them in the BR2 module, correct?

**Comment by javierriveracastro** [comment]
Sure, it will be much better for it to be in system.

You can try to open a ticket in github, but Flo philosophy is that automatization belongs to modules. I bet he is not going to accept it. But if you open it I'd love to support it.

**Comment by Yalnin** [comment]
Done. Would love to help you implement it, but I am no coder...

**Comment by javierriveracastro** [comment]
Ok, today commit has the very start of all this.

There is one (and only one) global action: "Wild Attack". There is no GUI and it is always on. But it is a start.

There is one selector (skill name) and the ability to do skill mods, damage mods and damage overrides.

You can check details here: https://github.com/javierriveracastro/betteroll-swade/blob/version_2/betterrolls-swade2/scripts/global_actions.js

**Comment by javierriveracastro** [comment]
Added abilty to set a state to the roller to global actions. Now Wild Attacking will auto-make you vulnerable.

A basic GUI should be the next step.

**Comment by Yalnin** [comment]
Maybe you noticed yourself - the "wild attack" seems to be triggered by the skill definition of the weapon, correct? We use German skill "Kämpfen" for "Fighting" and wild attack did not show up until I added a skill with the english name to the actor and changed the weapon to the english skill name. May be worth considering in future global action development?

**Comment by SalieriC** [comment]
@Yalnin: You're free to make a translation for it. The Fighting skill uses localisation. Creating localisations is the least complicated thing imaginable.
I could also tell you how to do it (auch in deutsch) if you like. Although I despise my native language. XD

**Comment by javierriveracastro** [comment]
Not really it uses both localization and a couple of guessing. And kampfen should work (sse line 7 of skill_cards.js) as it is a "white list". Something else is going on here. This probaby needs its own issue.

**Comment by Yalnin** [comment]
@SalieriC As Javier said, I do not have the impression this is a translation problem, since "Kämpfen" worked fine before in the BR2 environment. Anyways, I am actually trinlingual with German playing environment, English too but my native language is Spanish. If this is of any help for the project (although I am no coder) I would be glad to contribute.

**Comment by javierriveracastro** [comment]
Opened #125 https://github.com/javierriveracastro/betteroll-swade/issues/125

**Comment by javierriveracastro** [comment]
Update: Next version can disable and enable system global actions in settings.

For now it came with two global actions: "Wild Attack" enabled on items that use fighting, and "The Drop" enabled on all weapon items.

If someone has some idea for a "system" global action now is a good time to tell.

**Comment by SalieriC** [comment]
Illumination (penalty on everything that requires sight, bonus on Stealth).

**Comment by Yalnin** [comment]
Besides the different illumination levels (dim -2, dark -4, pitch dark -6) that SalieriC mentioned, there could be the -2 for "unstable platform" for fights on moving vehicles, then for fights the +1 drm and +1 ammo expend for "double attack", and any kind of called shots (head -4 drm +4 dmg, hand -4 drm, limbs -2 drm).

Problem is that some will find many selectable effects just fine, others will find the section too cluttered with selectable options, that's why at some point the possibility to modify, add and remove global effects would be the best solution imho. If doable of course. For example, for my setting in zombie apocalypse "head called shots" are an important global effect, in some other setting I can imagine it to be never used. Or e.g. if I play modern setting with many machineguns, global FR2, FR3, FR4 active effects would save you from having to modify all the auto weapons individually, but on medieval settings this would be futile.

**Comment by javierriveracastro** [comment]
For now, system global actions are selectable one by one. 

I don't think that ilumination is a good canditate as it affects all rolls, but for sure all the other are.

User defined actions is comming, but step by step, I have very limited time.

**Comment by javierriveracastro** [comment]
And now world (user created) global actions are working. They are still very limited, but new rules will be added as they are needed to implement new things.

I'm closing this bug, if anyone wants some rule, please open a new bug.
