### ISSUE TITLE
Links break on Weapon cards (BR2).

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#95]
On weapon cards Links in the Notes and Description sections break and show the code instead:
![image](https://user-images.githubusercontent.com/1230041/105994318-c83a4900-60a7-11eb-8bea-0b5aa6ffbe26.png)
It should be noted that, when the weapon does not auto roll (only the card is shown), the links work fine but once they roll (either by clicking or having auto roll activated (doesn't matter if damage or Trait) the links break.
![image](https://user-images.githubusercontent.com/1230041/105994479-f586f700-60a7-11eb-83aa-5e6ab6c402dd.png)

**Comment by javierriveracastro** [comment]
This one looks funny.

**Comment by SalieriC** [comment]
It's "inconsistent and can confuse users." :-P

**Comment by javierriveracastro** [comment]
I know, by funny I mean a hell to solve.

I have not idea of what is going on here. Likely it has some to do with storing it in flag, but then skill descriptions in items should work.

**Comment by javierriveracastro** [comment]
Not so hard. Right now I hate Artropos, but done.
