### ISSUE TITLE
possibility to play sounds when clicking roll button

### ISSUE THREAD

**Issue by Harfang** [javierriveracastro/betteroll-swade#96]
Hi, first i would like to thank you for your amazing work.
Second, i would like to now if it is possible de make BR2 compatible with other modules like Maestro to play sounds when clicking on the BR2 card.

A french fan.

**Comment by javierriveracastro** [comment]
Yes, quite likely. Probably no just sound, but an arbitrary macro. But not anytime soon.

**Comment by javierriveracastro** [comment]
After next release there are two ways of plating souds, the global actions "runSkillMacro" and "runDamageMacro" and Deadlands gun improvement module (https://foundryvtt.com/packages/deadlands-gun-enchantments).

So I feel this issue is done.
