### ISSUE TITLE
Strange error with ammo quantities not adjusting right

### ISSUE THREAD

**Issue by RandyLyne** [javierriveracastro/betteroll-swade#97]
I was testing the reload mechanics and when trying to reload a 30 shot gun with more ammo then needed, it swaps my ammo count and my shot count numbers.
![before reload](https://user-images.githubusercontent.com/77080531/106626582-7711d580-653d-11eb-8bf3-6beb9be9abd2.PNG)
![reload](https://user-images.githubusercontent.com/77080531/106626590-78db9900-653d-11eb-863d-64ae41dd33a5.PNG)
![after reload](https://user-images.githubusercontent.com/77080531/106626591-79742f80-653d-11eb-83a3-972240e3aff2.PNG)

**Comment by javierriveracastro** [comment]
Could it be just that it recharge 5 shots?

**Comment by RandyLyne** [comment]
No, because if i reload again, the numbers swap back.

**Comment by javierriveracastro** [comment]
Found it. I will push an update as soon as I can.

**Comment by RandyLyne** [comment]
Awesome. Thanks.
