### ISSUE TITLE
Pressing enter while editing reload/shooting causes page to refresh.

### ISSUE THREAD

**Issue by RandyLyne** [javierriveracastro/betteroll-swade#98]
While trying to reload i typed the quantity and pressed enter by habit. Doing this forces the page to refresh.

I tried to watch for errors on the console but didnt see any red before the refresh.

**Comment by javierriveracastro** [comment]
Solved.

@SalieriC, you can be interested in this. This bug was in the integration of your reloading/spend pp code and was caused because no default button was specified. It can also affect your macros.
